# Generated by Django 5.2.17 on 2026-09-21 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_normalize_index_names'),
        ('scheduling', '0006_barber_lifecycle'),
        ('tenants', '0004_normalize_index_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingdelivery',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingdelivery',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingdelivery',
            name='tracking_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('queued', 'Na fila'), ('sent', 'Enviada'), ('failed', 'Falhou'), ('cancelled', 'Cancelada'), ('skipped', 'Ignorada')], db_index=True, default='queued', max_length=16),
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wa_id', models.CharField(max_length=32)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('bot', 'Bot'), ('waiting_human', 'Aguardando humano'), ('human', 'Humano'), ('closed', 'Fechada')], db_index=True, default='bot', max_length=20)),
                ('bot_state', models.CharField(default='welcome', max_length=60)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('last_message_at', models.DateTimeField()),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='scheduling.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_conversations', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(blank=True, max_length=190, null=True, unique=True)),
                ('direction', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída')], max_length=4)),
                ('sender_type', models.CharField(choices=[('customer', 'Cliente'), ('bot', 'Bot'), ('user', 'Usuário'), ('system', 'Sistema')], max_length=12)),
                ('message_type', models.CharField(default='text', max_length=30)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Recebida'), ('queued', 'Na fila'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou')], max_length=16)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.whatsappconversation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['tenant', 'status', 'last_message_at'], name='comm_wa_inbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappconversation',
            constraint=models.UniqueConstraint(fields=('tenant', 'wa_id'), name='uq_wa_conversation'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['conversation', 'id'], name='comm_wa_message_idx'),
        ),
    ]
