# Generated by Django 5.2.17 on 2026-09-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_masterwhatsappconversation_masterwhatsappmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterWhatsAppFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('greeting', models.CharField(default='Olá! Como podemos ajudar sua empresa?', max_length=1000)),
                ('fallback', models.CharField(default='Não entendi. Conte com outras palavras ou escreva atendimento.', max_length=1000)),
                ('handoff', models.CharField(default='Vou encaminhar você para nosso atendimento humano.', max_length=1000)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='masterwhatsappconversation',
            name='flow_state',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='masterwhatsappconversation',
            name='human_handoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterwhatsappmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterwhatsappmessage',
            name='delivery_status',
            field=models.CharField(choices=[('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida')], default='sent', max_length=12),
        ),
        migrations.AddField(
            model_name='masterwhatsappmessage',
            name='flow_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterwhatsappmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterwhatsappmessage',
            name='recipient_jid',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='MasterWhatsAppDeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(max_length=190)),
                ('recipient_jid', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider_message_id', 'recipient_jid', 'status'), name='master_wa_receipt_unique')],
            },
        ),
    ]
