# Generated by Django 5.2.17 on 2026-09-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_masterwhatsappflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterwhatsappmessage',
            name='attachment',
            field=models.FileField(blank=True, upload_to='master-whatsapp/'),
        ),
        migrations.AddField(
            model_name='masterwhatsappmessage',
            name='attachment_mime',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='masterwhatsappmessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
