# Generated by Django 5.2.17 on 2026-09-29 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_masterwhatsappmessage_attachment_and_more'),
        ('scheduling', '0008_appointment_vehicle'),
        ('tenants', '0008_tenantonboarding_email_verification_waived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconversation',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='scheduling.appointment'),
        ),
        migrations.CreateModel(
            name='TenantWhatsAppConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_qr_connection', to='tenants.tenant')),
            ],
        ),
    ]
