# Generated by Django 5.2.17 on 2026-10-05 15:23

import operations.telemetry
import uuid

def fill_trace_ids(apps,schema_editor):
    Notification=apps.get_model("communications","Notification")
    alias=schema_editor.connection.alias
    while True:
        rows=list(Notification.objects.using(alias).filter(trace_id__isnull=True)[:500])
        if not rows: break
        for row in rows: row.trace_id=uuid.uuid4()
        Notification.objects.using(alias).bulk_update(rows,["trace_id"])

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_whatsappconversation_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_manual_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='manual_retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='trace_id',
            field=models.UUIDField(db_index=True,null=True),
        ),
        migrations.RunPython(fill_trace_ids,migrations.RunPython.noop),
        migrations.AlterField(model_name='notification',name='trace_id',field=models.UUIDField(db_index=True,default=operations.telemetry.trace_id)),
    ]
