# Generated by Django 5.2.18 on 2026-10-07 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_notification_last_manual_retry_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterwhatsappconversation',
            name='flow_context_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='masterwhatsappconversation',
            name='flow_last_error',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='masterwhatsappconversation',
            name='flow_revision',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='masterwhatsappconversation',
            name='flow_wait_kind',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='masterwhatsappconversation',
            name='flow_wake_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterwhatsappflow',
            name='ai_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterwhatsappflow',
            name='ai_key_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='masterwhatsappflow',
            name='ai_model',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='masterwhatsappflow',
            name='graph',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='masterwhatsappflow',
            name='integrations_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MasterFlowDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=120, unique=True)),
                ('body', models.CharField(max_length=4096)),
                ('status', models.CharField(db_index=True, default='queued', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_deliveries', to='communications.masterwhatsappconversation')),
            ],
        ),
    ]
