# Generated by Django 5.2.18 on 2026-10-07 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_lead_attribution_referral'),
        ('communications', '0011_masterwhatsappconversation_flow_context_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterwhatsappconversation',
            name='sales_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='commercial.lead'),
        ),
    ]
