<?php $e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');?>
<div class="section-heading"><div><div class="eyebrow">Prospecção e indicações</div><h1>E-mail marketing</h1><p class="text-secondary mb-0">Campanhas, contatos e origem das conversões em um só lugar.</p></div><a class="btn btn-light" href="/master/email-marketing/exportar">Exportar CSV</a></div>
<?php $campaignAction=(string)($_GET['campaign_action']??'');$campaignMessages=['updated'=>'Campanha atualizada. Os e-mails ainda na fila receberam os novos dados.','referrer'=>'Indicador alterado. Os e-mails ainda na fila foram atualizados.','inactive'=>'Campanha inativada e envios pendentes cancelados.','reactivated'=>'Campanha reativada. Os envios cancelados anteriormente não foram reenviados.','deleted'=>'Campanha removida da gestão.'];?>
<?php if(isset($_GET['smtp'])||isset($_GET['smtp_test'])||isset($_GET['leads'])||isset($_GET['campaign'])||isset($campaignMessages[$campaignAction])):?><div class="alert alert-success"><?=isset($campaignMessages[$campaignAction])?$campaignMessages[$campaignAction]:(isset($_GET['campaign'])?'Campanha adicionada à fila.':(isset($_GET['smtp_test'])?'E-mail de teste enviado.':(isset($_GET['smtp'])?'SMTP salvo com segurança.':(int)$_GET['leads'].' contato(s) processado(s).')))?></div><?php endif;?>
<?php if(isset($_GET['smtp_error'])):?><div class="alert alert-danger"><strong>O teste SMTP não foi enviado.</strong><br><?=htmlspecialchars(mb_substr((string)$_GET['smtp_error'],0,220),ENT_QUOTES,'UTF-8')?></div><?php endif;?>
<div class="row g-3 mb-4"><?php foreach([['Contatos ativos',$stats['active']],['Descadastrados',$stats['unsubscribed']],['E-mails enviados',$stats['sent']],['Falhas',$stats['failed']]] as $m):?><div class="col-6 col-xl-3"><div class="card metric-card h-100"><div class="card-body"><div class="metric-label"><?=$m[0]?></div><div class="metric-value"><?=(int)$m[1]?></div></div></div></div><?php endforeach;?></div>

<div class="card mb-4"><div class="card-header"><strong>Desempenho das indicações</strong><small class="d-block text-secondary">O clique é atribuído por 30 dias; a conversão ocorre quando o estabelecimento conclui o cadastro.</small></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Indicador</th><th>Perfil</th><th>Código</th><th>Cliques</th><th>Cadastros</th><th>Conversão</th></tr></thead><tbody><?php foreach($staff as $person):$rate=(int)$person['clicks']>0?((int)$person['conversions']/(int)$person['clicks']*100):0;?><tr><td><strong><?=$e($person['name'])?></strong><small class="d-block text-secondary"><?=$e($person['email'])?></small></td><td><?=$person['role_slug']==='master'?'Master':'Suporte'?></td><td><code><?=$e($person['referral_code'])?></code></td><td><?=(int)$person['clicks']?></td><td><?=(int)$person['conversions']?></td><td><?=number_format($rate,1,',','.')?>%</td></tr><?php endforeach;?><?php if(!$staff):?><tr><td colspan="6"><div class="empty-state">Nenhum indicador disponível.</div></td></tr><?php endif;?></tbody></table></div></div>

<div class="card mb-4"><div class="card-header d-flex justify-content-between"><div><strong>SMTP exclusivo para marketing</strong><small class="d-block text-secondary">Não altera o SMTP transacional.</small></div><span class="badge <?=$smtpConfigured?'text-bg-success':'text-bg-warning'?>"><?=$smtpConfigured?'Configurado':'Pendente'?></span></div><div class="card-body"><form method="post" action="/master/email-marketing/smtp" class="row g-3"><?=\App\Core\CSRF::field()?><div class="col-md-4"><label class="form-label">Nome do remetente</label><input class="form-control" name="from_name" required value="<?=$e($smtp['from_name']??'ApPlanner')?>"></div><div class="col-md-4"><label class="form-label">E-mail remetente</label><input class="form-control" type="email" name="from_email" required value="<?=$e($smtp['from_email']??'')?>"></div><div class="col-md-4"><label class="form-label">Responder para</label><input class="form-control" type="email" name="reply_to" value="<?=$e($smtp['reply_to']??'')?>"></div><div class="col-md-4"><label class="form-label">Servidor SMTP</label><input class="form-control" name="host" required value="<?=$e($smtp['host']??'')?>" placeholder="mail.applanner.com.br"></div><div class="col-md-2"><label class="form-label">Porta</label><input class="form-control" type="number" name="port" min="1" max="65535" value="<?=(int)($smtp['port']??587)?>"></div><div class="col-md-2"><label class="form-label">Segurança</label><select class="form-select" name="encryption"><?php foreach(['tls'=>'TLS','ssl'=>'SSL','none'=>'Nenhuma'] as $v=>$l):?><option value="<?=$v?>" <?=($smtp['encryption']??'tls')===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Usuário</label><input class="form-control" name="username" value="<?=$e($smtp['username']??'')?>"></div><div class="col-md-4"><label class="form-label">Senha</label><input class="form-control" type="password" name="password" autocomplete="new-password"><small class="text-secondary"><?=$smtpConfigured?'Em branco mantém a senha atual.':'Informe a senha SMTP.'?></small></div><div class="col-12"><button class="btn btn-primary">Salvar SMTP</button></div></form><?php if($smtpConfigured):?><hr><form method="post" action="/master/email-marketing/smtp/testar" class="row g-2 align-items-end"><?=\App\Core\CSRF::field()?><div class="col-md-5"><label class="form-label">Enviar teste para</label><input class="form-control" type="email" name="test_email" required></div><div class="col-md-3"><button class="btn btn-outline-primary w-100">Testar SMTP</button></div></form><?php endif;?></div></div>

<div class="row g-4 mb-4"><div class="col-xl-7"><div class="card h-100"><div class="card-header"><strong>Nova campanha</strong></div><div class="card-body"><form method="post" enctype="multipart/form-data" action="/master/email-marketing/enviar" data-warn-unsaved id="marketingCampaignForm"><?=\App\Core\CSRF::field()?><label class="form-label">Responsável pela indicação</label><select class="form-select mb-3" name="referrer_user_id" required><option value="">Selecione Master ou Suporte</option><?php foreach($staff as $person):?><option value="<?=(int)$person['id']?>"><?=$e($person['name'])?> · <?=$person['role_slug']==='master'?'Master':'Suporte'?></option><?php endforeach;?></select><div class="form-text mb-3">O link individual desta pessoa será inserido automaticamente em cada e-mail.</div><label class="form-label">Assunto</label><input class="form-control mb-3" name="subject" maxlength="190" required><label class="form-label">Mensagem</label><textarea class="form-control" name="body" rows="8" placeholder="Olá {nome},&#10;&#10;Conheça o ApPlanner..."></textarea><div class="form-text mb-3">Variáveis: <code>{nome}</code>, <code>{email}</code> e <code>{link_indicacao}</code>. A mensagem pode ser curta quando houver um card.</div>
<div class="border rounded-3 p-3 mb-3"><div class="d-flex align-items-center justify-content-between gap-2 mb-2"><strong>Card / imagem da campanha</strong><span class="badge text-bg-secondary">Opcional</span></div>
<label class="form-label">Imagem</label><input class="form-control" type="file" name="card_image" id="marketingCardImage" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp">
<div class="form-text">JPG, PNG ou WebP, até 5 MB. Recomendado: 1200×628 px ou 1080×1080 px. No e-mail: largura máxima de 640 px.</div>
<div class="row g-2 mt-1"><div class="col-md-6"><label class="form-label">Texto alternativo</label><input class="form-control" name="image_alt" maxlength="190" placeholder="Ex.: Conheça o ApPlanner"></div>
<div class="col-md-6"><label class="form-label">Link ao clicar no card</label><input class="form-control" type="url" name="card_link_url" placeholder="https://..."><div class="form-text">Vazio = usa o link individual de indicação.</div></div></div>
<div id="marketingCardPreviewWrap" class="mt-3 d-none"><div class="small text-secondary mb-2">Pré-visualização</div><img id="marketingCardPreview" alt="Prévia do card" style="display:block;max-width:100%;max-height:420px;border-radius:12px;border:1px solid var(--bs-border-color);"></div></div>
<div class="alert alert-info"><strong>Entrega:</strong> HTML responsivo + versão em texto como fallback para clientes que bloqueiam imagens.</div><div class="alert alert-warning mt-3">Será enviado para <?=(int)$stats['active']?> contatos ativos. Utilize somente uma base legal válida.</div><button class="btn btn-primary" <?=$smtpConfigured&&$stats['active']>0&&$staff?'':'disabled'?>>Colocar campanha na fila</button></form></div></div></div>
<div class="col-xl-5"><div class="card h-100"><div class="card-header"><strong>Adicionar contatos</strong></div><div class="card-body"><form method="post" action="/master/email-marketing/contatos" class="row g-2 mb-4"><?=\App\Core\CSRF::field()?><div class="col-sm-5"><input class="form-control" name="name" placeholder="Nome" required></div><div class="col-sm-5"><input class="form-control" type="email" name="email" placeholder="E-mail" required></div><div class="col-sm-2"><button class="btn btn-primary w-100">+</button></div></form><form method="post" action="/master/email-marketing/lista" class="mb-4"><?=\App\Core\CSRF::field()?><label class="form-label">Colar lista</label><textarea class="form-control" name="list" rows="6" placeholder="Maria,maria@empresa.com&#10;João;joao@empresa.com"></textarea><button class="btn btn-outline-primary mt-2">Cadastrar lista</button></form><form method="post" enctype="multipart/form-data" action="/master/email-marketing/importar"><?=\App\Core\CSRF::field()?><label class="form-label">Importar CSV</label><input class="form-control" type="file" name="csv" accept=".csv,text/csv" required><div class="form-text">Formato nome,email ou nome;email. Até 5 MB/5.000 linhas.</div><button class="btn btn-outline-primary mt-2">Importar CSV</button></form></div></div></div></div>

<?php if(!empty($editCampaign)):?>
<div class="card mb-4" id="campaign-edit"><div class="card-header d-flex justify-content-between align-items-center"><div><strong>Editar campanha #<?=(int)$editCampaign['id']?></strong><small class="d-block text-secondary">Alterações afetam somente e-mails ainda na fila.</small></div><a class="btn btn-sm btn-outline-secondary" href="/master/email-marketing">Fechar</a></div><div class="card-body"><form method="post" enctype="multipart/form-data" action="/master/email-marketing/campanhas/<?=(int)$editCampaign['id']?>/editar" class="row g-3" data-warn-unsaved><?=\App\Core\CSRF::field()?>
<div class="col-md-5"><label class="form-label">Indicador</label><select class="form-select" name="referrer_user_id" required><?php foreach($staff as $person):?><option value="<?=(int)$person['id']?>" <?=((int)$editCampaign['referrer_user_id']===(int)$person['id'])?'selected':''?>><?=$e($person['name'])?></option><?php endforeach;?></select></div>
<div class="col-md-7"><label class="form-label">Assunto</label><input class="form-control" name="subject" maxlength="190" required value="<?=$e($editCampaign['subject'])?>"></div>
<div class="col-12"><label class="form-label">Mensagem</label><textarea class="form-control" name="body" rows="8"><?=$e($editCampaign['body'])?></textarea></div>
<div class="col-md-5"><label class="form-label">Novo card</label><input class="form-control" type="file" name="card_image" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp"><div class="form-text">Opcional. Substitui o card atual.</div></div>
<div class="col-md-3"><label class="form-label">Texto alternativo</label><input class="form-control" name="image_alt" maxlength="190" value="<?=$e($editCampaign['image_alt']??'')?>"></div>
<div class="col-md-4"><label class="form-label">Link do card</label><input class="form-control" type="url" name="card_link_url" value="<?=$e($editCampaign['card_link_url']??'')?>"></div>
<?php if(!empty($editCampaign['image_url'])):?><div class="col-12"><div class="d-flex gap-3 align-items-start flex-wrap"><img src="<?=$e($editCampaign['image_url'])?>" alt="" style="max-width:260px;max-height:180px;border-radius:10px;border:1px solid var(--bs-border-color)"><label class="form-check mt-2"><input class="form-check-input" type="checkbox" name="remove_card" value="1"><span class="form-check-label">Remover card atual</span></label></div></div><?php endif;?>
<div class="col-12"><button class="btn btn-primary">Salvar alterações</button></div></form></div></div>
<?php endif;?>
<div class="card mb-4"><div class="card-header"><strong>Campanhas</strong><small class="d-block text-secondary">Edite, troque o indicador, inative ou exclua campanhas. E-mails já enviados são preservados.</small></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Campanha</th><th style="min-width:220px">Indicador</th><th>Status</th><th>Total</th><th>Enviados</th><th>Falhas</th><th style="min-width:240px">Ações</th></tr></thead><tbody>
<?php foreach($campaigns as $c):?><tr class="<?=!(int)$c['active']?'opacity-75':''?>"><td><strong><?=$e($c['subject'])?></strong><?php if(!empty($c['image_url'])):?><span class="badge text-bg-info ms-1">Card</span><?php endif;?><small class="d-block text-secondary">#<?=(int)$c['id']?> · <?=$e($c['created_at'])?><?php if((int)$c['visit_count']>0):?> · <?=(int)$c['visit_count']?> clique(s)<?php endif;?></small></td>
<td><form method="post" action="/master/email-marketing/campanhas/<?=(int)$c['id']?>/indicador" class="d-flex gap-2"><?=\App\Core\CSRF::field()?><select class="form-select form-select-sm" name="referrer_user_id" <?=!(int)$c['active']?'disabled':''?>><?php foreach($staff as $person):?><option value="<?=(int)$person['id']?>" <?=((int)$c['referrer_user_id']===(int)$person['id'])?'selected':''?>><?=$e($person['name'])?></option><?php endforeach;?></select><button class="btn btn-sm btn-outline-primary" <?=!(int)$c['active']?'disabled':''?>>Alterar</button></form></td>
<td><?php if(!(int)$c['active']):?><span class="badge text-bg-secondary">Inativa</span><?php else:?><span class="badge <?=($c['status']==='completed'?'text-bg-success':($c['status']==='sending'?'text-bg-primary':'text-bg-warning'))?>"><?=$e(['queued'=>'Na fila','sending'=>'Enviando','completed'=>'Concluída','cancelled'=>'Cancelada'][$c['status']]??$c['status'])?></span><?php endif;?></td><td><?=(int)$c['total_count']?></td><td><?=(int)$c['sent_count']?></td><td><?=(int)$c['failed_count']?></td>
<td><div class="d-flex flex-wrap gap-2"><a class="btn btn-sm btn-outline-primary" href="/master/email-marketing?edit_campaign=<?=(int)$c['id']?>#campaign-edit">Editar</a><form method="post" action="/master/email-marketing/campanhas/<?=(int)$c['id']?>/status"><?=\App\Core\CSRF::field()?><input type="hidden" name="active" value="<?=!(int)$c['active']?'1':'0'?>"><button class="btn btn-sm <?=!(int)$c['active']?'btn-outline-success':'btn-outline-warning'?>"><?=!(int)$c['active']?'Reativar':'Inativar'?></button></form><form method="post" action="/master/email-marketing/campanhas/<?=(int)$c['id']?>/excluir" onsubmit="return confirm('Excluir esta campanha da gestão? Envios já realizados permanecerão preservados para auditoria quando necessário.')"><?=\App\Core\CSRF::field()?><button class="btn btn-sm btn-outline-danger">Excluir</button></form></div></td></tr><?php endforeach;?><?php if(!$campaigns):?><tr><td colspan="7"><div class="empty-state">Nenhuma campanha.</div></td></tr><?php endif;?></tbody></table></div></div>

<div class="card"><div class="card-header"><strong>Base de contatos</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Nome</th><th>E-mail</th><th>Origem</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($leads as $lead):?><tr><td><?=$e($lead['name'])?></td><td><?=$e($lead['email'])?></td><td><?=$e($lead['source'])?></td><td><?=$e(['active'=>'Ativo','unsubscribed'=>'Descadastrado','bounced'=>'Rejeitado'][$lead['status']]??$lead['status'])?></td><td><form method="post" action="/master/email-marketing/contatos/<?=(int)$lead['id']?>"><?=\App\Core\CSRF::field()?><select class="form-select form-select-sm" name="status" onchange="this.form.submit()"><option value="active" <?=$lead['status']==='active'?'selected':''?>>Ativo</option><option value="unsubscribed" <?=$lead['status']==='unsubscribed'?'selected':''?>>Descadastrado</option><option value="bounced" <?=$lead['status']==='bounced'?'selected':''?>>Rejeitado</option></select></form></td></tr><?php endforeach;?><?php if(!$leads):?><tr><td colspan="5"><div class="empty-state">Nenhum contato.</div></td></tr><?php endif;?></tbody></table></div></div>

<script>
document.addEventListener('DOMContentLoaded',function(){
  const input=document.getElementById('marketingCardImage'),wrap=document.getElementById('marketingCardPreviewWrap'),img=document.getElementById('marketingCardPreview');
  if(!input||!wrap||!img)return;
  input.addEventListener('change',function(){
    const file=this.files&&this.files[0];
    if(!file){wrap.classList.add('d-none');img.removeAttribute('src');return;}
    if(file.size>5*1024*1024){alert('O card deve ter no máximo 5 MB.');this.value='';wrap.classList.add('d-none');return;}
    const reader=new FileReader();reader.onload=e=>{img.src=e.target.result;wrap.classList.remove('d-none');};reader.readAsDataURL(file);
  });
});
</script>
