<?php $e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$money=fn($v)=>'R$ '.number_format((float)$v,2,',','.');?>
<div class="master-focus">
 <section class="master-focus-hero"><span class="eyebrow text-white-50">Central ApPlanner</span><h1>O que precisa da sua atenção, sem ruído.</h1><p class="mb-4">Clientes, receita, suporte e crescimento reunidos numa visão operacional.</p><div class="master-focus-actions"><a class="btn btn-light" href="/master/tenants">Gerenciar clientes</a><a class="btn btn-outline-light" href="/master/conversion-settings">Melhorar aquisição</a><a class="btn btn-outline-light" href="/master/homologacao">Ver homologação</a></div></section>
 <section class="master-signal-grid">
  <article class="master-signal"><small>Empresas ativas</small><strong><?=(int)$stats['active']?></strong><a href="/master/tenants">Abrir carteira</a></article>
  <article class="master-signal"><small>Em teste</small><strong><?=(int)$stats['trials']?></strong><a href="/master/tenants">Acompanhar conversão</a></article>
  <article class="master-signal"><small>Recebido no mês</small><strong><?=$money($stats['payments_month'])?></strong><a href="/master/financeiro">Ver financeiro</a></article>
  <article class="master-signal"><small>Ações pendentes</small><strong><?=((int)$stats['support_open']+(int)$stats['payments_pending']+(int)$stats['subscriptions_due'])?></strong><span class="text-secondary">suporte, pagamentos e vencimentos</span></article>
 </section>
 <div class="master-work-grid">
  <section class="master-work-card"><div class="d-flex justify-content-between align-items-center"><div><span class="eyebrow">Prioridades</span><h2 class="h4 mb-0">Fila de trabalho</h2></div><a href="/master/homologacao">Central completa</a></div>
   <?php $priorities=[[(int)$stats['support_open'],'Chamados aguardando atendimento','/master/support'],[(int)$stats['payments_pending'],'Pagamentos pendentes','/master/payments'],[(int)$stats['subscriptions_due'],'Assinaturas vencendo em 7 dias','/master/financeiro'],[count($moduleRequests),'Solicitações de módulos','/master/solicitacoes-modulos']];foreach($priorities as [$count,$label,$href]):?><div class="master-row"><div><strong><?=$e($label)?></strong><p><?=$count?$count.' item(ns) para revisar':'Nenhuma pendência agora'?></p></div><a class="btn btn-sm <?=$count?'btn-primary':'btn-light'?>" href="<?=$href?>">Abrir</a></div><?php endforeach;?>
  </section>
  <aside class="master-work-card"><span class="eyebrow">Acesso rápido</span><h2 class="h4">Ferramentas</h2><div class="master-shortcuts"><a class="btn btn-light" href="/master/plans">Planos</a><a class="btn btn-light" href="/master/modulos">Módulos</a><a class="btn btn-light" href="/master/email-marketing">Campanhas</a><a class="btn btn-light" href="/master/blog">Blog</a><a class="btn btn-light" href="/master/backups">Backups</a><a class="btn btn-light" href="/master/system-health">Saúde</a><a class="btn btn-light" href="/master/mercadopago">Mercado Pago</a><a class="btn btn-light" href="/master/integrations">Integrações</a></div></aside>
 </div>
 <section class="master-work-card"><div class="d-flex justify-content-between align-items-center mb-2"><div><span class="eyebrow">Carteira</span><h2 class="h4 mb-0">Clientes recentes</h2></div><a href="/master/tenants">Ver todos</a></div><?php if(!$tenants):?><div class="empty-state">Nenhuma empresa cadastrada.</div><?php else:?><?php foreach(array_slice($tenants,0,6) as $tenant):?><div class="master-row"><div><strong><?=$e($tenant['name'])?></strong><p><?=$e($tenant['plan_name']??'Sem plano')?> · <?=$e($tenant['subscription_status']??$tenant['status'])?></p></div><a class="btn btn-sm btn-light" href="/master/tenants/<?=(int)$tenant['id']?>">Gerenciar</a></div><?php endforeach;?><?php endif;?></section>
</div>
