# Generated by Django 5.2.17 on 2026-09-21 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_normalize_index_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFinanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa'), ('both', 'Ambos')], default='both', max_length=12)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=120)),
                ('bank_code', models.CharField(max_length=10)),
                ('ispb', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(choices=[('checking', 'Corrente'), ('savings', 'Poupança'), ('payment', 'Pagamento'), ('business', 'Empresarial')], max_length=16)),
                ('agency_encrypted', models.TextField()),
                ('agency_digit', models.CharField(blank=True, max_length=3)),
                ('account_encrypted', models.TextField()),
                ('account_digit', models.CharField(blank=True, max_length=3)),
                ('holder_name', models.CharField(max_length=150)),
                ('holder_document_encrypted', models.TextField()),
                ('person_type', models.CharField(choices=[('individual', 'Pessoa física'), ('company', 'Pessoa jurídica')], max_length=16)),
                ('pix_key_encrypted', models.TextField(blank=True)),
                ('pix_key_type', models.CharField(blank=True, max_length=12)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('notes_encrypted', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('inactive', 'Inativa')], db_index=True, default='active', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'is_default'], name='platform_bank_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True), ('status', 'active')), fields=('is_default',), name='uq_platform_default_bank')],
            },
        ),
        migrations.CreateModel(
            name='PlatformFinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=12)),
                ('description', models.CharField(max_length=190)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=16)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.platformfinancecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_finance_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'status', 'due_at'], name='platform_finance_status_idx')],
            },
        ),
    ]
