<?php
namespace App\Services;

use App\Core\Database;

final class ArenaMaintenanceService
{
    public function runTenant(int $tenantId): array
    {
        $result=['expired'=>0,'membership_generated'=>0,'membership_conflicts'=>0,'waitlist_offers'=>0,'reminders'=>0,'class_billing'=>0,'crm_returns'=>0,'idle_alerts'=>0];
        $result['expired']=$this->expireReservations($tenantId);
        $memberships=(new ArenaMembershipService())->generateDue($tenantId);
        $result['membership_generated']=(int)$memberships['generated'];$result['membership_conflicts']=(int)$memberships['conflicts'];
        $result['waitlist_offers']=$this->matchWaitlist($tenantId);
        $result['reminders']=$this->reservationReminders($tenantId);
        $result['class_billing']=$this->classBilling($tenantId);
        $result['crm_returns']=$this->crmReturn($tenantId);
        $result['idle_alerts']=$this->idleSlotAlerts($tenantId);
        (new ArenaReservationService())->recalculateCustomerMetrics($tenantId);
        return $result;
    }

    private function config(int $tenantId): array
    {
        $q=Database::connection()->prepare('SELECT * FROM sports_arena_settings WHERE tenant_id=:tenant');$q->execute(['tenant'=>$tenantId]);
        return $q->fetch()?:[];
    }

    private function expireReservations(int $tenantId): int
    {
        $pdo=Database::connection();$q=$pdo->prepare("SELECT f.reservation_id FROM sports_reservation_finance f JOIN sports_reservations r ON r.id=f.reservation_id AND r.tenant_id=f.tenant_id WHERE f.tenant_id=:tenant AND f.payment_state='pending' AND f.expires_at IS NOT NULL AND f.expires_at<NOW() AND r.status='pending_payment' ORDER BY f.expires_at LIMIT 200");$q->execute(['tenant'=>$tenantId]);$count=0;
        foreach($q->fetchAll(\PDO::FETCH_COLUMN) as $reservationId){$pdo->beginTransaction();try{$lock=$pdo->prepare("SELECT status FROM sports_reservations WHERE id=:id AND tenant_id=:tenant FOR UPDATE");$lock->execute(['id'=>(int)$reservationId,'tenant'=>$tenantId]);if($lock->fetchColumn()!=='pending_payment'){$pdo->rollBack();continue;}$pdo->prepare("UPDATE sports_reservations SET status='cancelled',payment_status='cancelled',cancelled_at=NOW(),updated_at=NOW() WHERE id=:id AND tenant_id=:tenant")->execute(['id'=>(int)$reservationId,'tenant'=>$tenantId]);$pdo->prepare("UPDATE sports_reservation_finance SET payment_state='expired',updated_at=NOW() WHERE reservation_id=:id AND tenant_id=:tenant")->execute(['id'=>(int)$reservationId,'tenant'=>$tenantId]);$pdo->prepare("UPDATE tenant_payment_transactions SET status='expired',updated_at=NOW() WHERE tenant_id=:tenant AND reference_type='reservation' AND reference_id=:id AND status IN('created','pending')")->execute(['tenant'=>$tenantId,'id'=>(int)$reservationId]);$pdo->prepare("INSERT INTO sports_reservation_history(reservation_id,action,old_status,new_status,notes,created_at) VALUES(:id,'payment_expired','pending_payment','cancelled','Prazo do sinal expirado; horário liberado',NOW())")->execute(['id'=>(int)$reservationId]);$pdo->commit();$count++;}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('[ApPlanner Arena] Expiração reserva #'.(int)$reservationId.': '.$e->getMessage());}}
        return $count;
    }

    private function matchWaitlist(int $tenantId): int
    {
        $pdo=Database::connection();$cfg=$this->config($tenantId)+['waitlist_offer_minutes'=>10,'allow_waitlist'=>1,'waitlist_email_enabled'=>1,'waitlist_whatsapp_enabled'=>0];if(empty($cfg['allow_waitlist']))return 0;
        $pdo->prepare("UPDATE sports_waitlist SET status='waiting',offer_expires_at=NULL,offered_at=NULL,offered_starts_at=NULL,offered_total=NULL,notification_queued_at=NULL,updated_at=NOW() WHERE tenant_id=:tenant AND status='offered' AND offer_expires_at<NOW()")->execute(['tenant'=>$tenantId]);
        $q=$pdo->prepare("SELECT * FROM sports_waitlist WHERE tenant_id=:tenant AND status='waiting' AND preferred_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 30 DAY) ORDER BY preferred_date,id LIMIT 100");$q->execute(['tenant'=>$tenantId]);$availability=new SportsAvailabilityService();$offered=0;
        $tenantQ=$pdo->prepare('SELECT name,public_slug,public_short_code FROM tenants WHERE id=:tenant');$tenantQ->execute(['tenant'=>$tenantId]);$tenant=$tenantQ->fetch()?:[];$app=require dirname(__DIR__,2).'/config/app.php';
        $emailCfg=PlatformSetting::secret('platform.marketing_email');$waCfg=PlatformSetting::secret('platform.whatsapp');
        foreach($q->fetchAll() as $entry){$courtIds=[];if(!empty($entry['court_id']))$courtIds=[(int)$entry['court_id']];else{$courts=$pdo->prepare('SELECT id FROM sports_courts WHERE tenant_id=:tenant AND active=1 ORDER BY sort_order,id');$courts->execute(['tenant'=>$tenantId]);$courtIds=array_map('intval',$courts->fetchAll(\PDO::FETCH_COLUMN));}
            foreach($courtIds as $courtId){$modalityId=(int)($entry['modality_id']??0);if($modalityId<=0){$m=$pdo->prepare('SELECT modality_id FROM sports_court_modalities WHERE court_id=:court ORDER BY modality_id LIMIT 1');$m->execute(['court'=>$courtId]);$modalityId=(int)$m->fetchColumn();}if($modalityId<=0)continue;try{$slots=$availability->slots($tenantId,$courtId,$modalityId,$entry['preferred_date'],(int)$entry['duration_minutes']);}catch(\Throwable){$slots=[];}if(!$slots)continue;
                $preferred=$entry['preferred_start']?strtotime($entry['preferred_date'].' '.$entry['preferred_start']):null;$flex=(int)$entry['flexibility_minutes']*60;$match=null;foreach($slots as $slot){$time=strtotime($slot['value']);if($preferred===null||abs($time-$preferred)<=$flex){$match=$slot;break;}}if(!$match)continue;
                $expires=(new \DateTimeImmutable('+'.max(1,(int)$cfg['waitlist_offer_minutes']).' minutes'))->format('Y-m-d H:i:s');$update=$pdo->prepare("UPDATE sports_waitlist SET status='offered',court_id=:court,modality_id=:modality,offered_at=NOW(),offered_starts_at=:starts,offered_total=:total,offer_expires_at=:expires,updated_at=NOW() WHERE id=:id AND tenant_id=:tenant AND status='waiting'");$update->execute(['court'=>$courtId,'modality'=>$modalityId,'starts'=>$match['value'],'total'=>$match['total'],'expires'=>$expires,'id'=>$entry['id'],'tenant'=>$tenantId]);if(!$update->rowCount())break;
                $slug=(string)($tenant['public_slug']?:$tenant['public_short_code']??'');$link=rtrim((string)($app['url']??''),'/').'/arena/'.rawurlencode($slug).'?waitlist_offer='.rawurlencode((string)$entry['public_token']).'#reservar';$message='Olá '.$entry['customer_name'].', surgiu uma vaga na '.$tenant['name'].' em '.date('d/m H:i',strtotime($match['value'])).'. Ela ficará reservada temporariamente para você. Reserve aqui: '.$link;$queued=[];
                if(!empty($entry['notify_whatsapp'])&&!empty($cfg['waitlist_whatsapp_enabled'])&&!empty($waCfg['phone_number_id'])&&!empty($waCfg['access_token'])){$phone=preg_replace('/\D/','',(string)$entry['customer_phone']);if(preg_match('/^\d{10,15}$/',$phone)){NotificationService::queueExternal($tenantId,'whatsapp',$phone,'Vaga liberada',$message,['sports_waitlist_id'=>$entry['id']]);$queued[]='whatsapp';}}
                if(!empty($entry['notify_email'])&&!empty($cfg['waitlist_email_enabled'])&&!empty($emailCfg['host'])&&filter_var($entry['customer_email']??'',FILTER_VALIDATE_EMAIL)){NotificationService::queueExternal($tenantId,'email',(string)$entry['customer_email'],'Sua vaga na Arena foi liberada',$message,['sports_waitlist_id'=>$entry['id']]);$queued[]='email';}
                NotificationService::tenantOwners($tenantId,'arena.waitlist','Vaga oferecida pela lista de espera',$entry['customer_name'].' recebeu prioridade para '.date('d/m H:i',strtotime($match['value'])),'/sports/waitlist','info');
                $pdo->prepare("UPDATE sports_waitlist SET notification_queued_at=:queued,last_notification_at=IF(:has=1,NOW(),last_notification_at),updated_at=NOW() WHERE id=:id AND tenant_id=:tenant")->execute(['queued'=>$queued?date('Y-m-d H:i:s'):null,'has'=>$queued?1:0,'id'=>$entry['id'],'tenant'=>$tenantId]);
                $pdo->prepare("INSERT INTO sports_automation_logs(tenant_id,automation_key,entity_type,entity_id,channel,status,detail,created_at) VALUES(:tenant,'waitlist.match','sports_waitlist',:id,:channel,:status,:detail,NOW())")->execute(['tenant'=>$tenantId,'id'=>$entry['id'],'channel'=>$queued?implode(',',$queued):null,'status'=>$queued?'queued':'skipped','detail'=>'Vaga em '.$match['value'].'; prioridade até '.$expires]);$offered++;break;
            }
        }
        return $offered;
    }

    private function reservationReminders(int $tenantId): int
    {
        $cfg=$this->config($tenantId)+['reservation_reminder_enabled'=>1,'reservation_reminder_hours'=>24];if(empty($cfg['reservation_reminder_enabled']))return 0;$hours=max(1,(int)$cfg['reservation_reminder_hours']);$pdo=Database::connection();$q=$pdo->prepare("SELECT r.id,r.customer_id,r.customer_name,r.customer_phone,r.customer_email,r.starts_at,c.name court_name FROM sports_reservations r JOIN sports_courts c ON c.id=r.court_id WHERE r.tenant_id=:tenant AND r.status='confirmed' AND r.customer_id IS NOT NULL AND (SELECT cc.granted FROM customer_consents cc WHERE cc.tenant_id=r.tenant_id AND cc.customer_id=r.customer_id AND cc.type='operational_reminders' ORDER BY cc.id DESC LIMIT 1)=1 AND r.starts_at BETWEEN DATE_ADD(NOW(),INTERVAL :h1 HOUR) AND DATE_ADD(NOW(),INTERVAL :h2 HOUR) AND NOT EXISTS(SELECT 1 FROM sports_automation_logs l WHERE l.tenant_id=r.tenant_id AND l.automation_key='reservation.reminder' AND l.entity_id=r.id)");$q->execute(['tenant'=>$tenantId,'h1'=>max(0,$hours-1),'h2'=>$hours]);$emailCfg=PlatformSetting::secret('platform.marketing_email');$waCfg=PlatformSetting::secret('platform.whatsapp');$count=0;
        foreach($q->fetchAll() as $r){$text='Lembrete: sua reserva da quadra '.$r['court_name'].' é em '.date('d/m/Y H:i',strtotime($r['starts_at'])).'.';$queued=[];if(!empty($waCfg['phone_number_id'])&&!empty($waCfg['access_token'])){$phone=preg_replace('/\D/','',(string)$r['customer_phone']);if(preg_match('/^\d{10,15}$/',$phone)){NotificationService::queueExternal($tenantId,'whatsapp',$phone,'Lembrete da reserva',$text,['reservation_id'=>$r['id']]);$queued[]='whatsapp';}}if(!$queued&&!empty($emailCfg['host'])&&filter_var($r['customer_email']??'',FILTER_VALIDATE_EMAIL)){NotificationService::queueExternal($tenantId,'email',(string)$r['customer_email'],'Lembrete da sua reserva',$text,['reservation_id'=>$r['id']]);$queued[]='email';}$pdo->prepare("INSERT INTO sports_automation_logs(tenant_id,automation_key,entity_type,entity_id,channel,status,detail,created_at) VALUES(:tenant,'reservation.reminder','sports_reservation',:id,:channel,:status,:detail,NOW())")->execute(['tenant'=>$tenantId,'id'=>$r['id'],'channel'=>$queued?implode(',',$queued):null,'status'=>$queued?'queued':'skipped','detail'=>$queued?'Lembrete enfileirado':'Nenhum canal global configurado']);$count++;}
        return $count;
    }

    private function classBilling(int $tenantId): int
    {
        try{if(!ModuleService::has('finance',$tenantId))return 0;}catch(\Throwable){return 0;}$pdo=Database::connection();$month=date('Y-m');$day=(int)date('j');$q=$pdo->prepare("SELECT s.id student_id,s.customer_id,COALESCE(s.monthly_amount_override,c.monthly_amount) amount,COALESCE(s.billing_day,1) billing_day,c.name class_name,cu.name customer_name FROM sports_class_students s JOIN sports_classes c ON c.id=s.class_id AND c.tenant_id=s.tenant_id JOIN customers cu ON cu.id=s.customer_id AND cu.tenant_id=s.tenant_id WHERE s.tenant_id=:tenant AND s.status='active' AND c.status='active' AND COALESCE(s.monthly_amount_override,c.monthly_amount)>0 AND COALESCE(s.billing_day,1)<=:day");$q->execute(['tenant'=>$tenantId,'day'=>$day]);$count=0;
        foreach($q->fetchAll() as $row){$key='arena-class-'.$row['student_id'].'-'.$month;$amount=round((float)$row['amount'],2);try{$pdo->beginTransaction();$pdo->prepare("INSERT IGNORE INTO financial_transactions(tenant_id,source_type,source_id,type,description,amount,payment_method,status,idempotency_key,due_at,created_at,updated_at) VALUES(:tenant,'arena_class_student',:source,'income',:description,:amount,'other','pending',:key,:due,NOW(),NOW())")->execute(['tenant'=>$tenantId,'source'=>$row['student_id'],'description'=>'Mensalidade '.$row['class_name'].' · '.$row['customer_name'].' · '.$month,'amount'=>$amount,'key'=>$key,'due'=>date('Y-m-').str_pad((string)min(28,max(1,(int)$row['billing_day'])),2,'0',STR_PAD_LEFT)]);$fq=$pdo->prepare('SELECT id FROM financial_transactions WHERE tenant_id=:tenant AND idempotency_key=:key');$fq->execute(['tenant'=>$tenantId,'key'=>$key]);$fid=(int)$fq->fetchColumn();$ins=$pdo->prepare("INSERT IGNORE INTO sports_class_billing_log(tenant_id,student_id,competence_month,amount,financial_transaction_id,status,created_at) VALUES(:tenant,:student,:month,:amount,:finance,'generated',NOW())");$ins->execute(['tenant'=>$tenantId,'student'=>$row['student_id'],'month'=>$month,'amount'=>$amount,'finance'=>$fid?:null]);if($ins->rowCount())$count++;$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('[ApPlanner Arena Class Billing] '.$e->getMessage());}}
        return $count;
    }

    private function crmReturn(int $tenantId): int
    {
        $cfg=$this->config($tenantId)+['crm_return_enabled'=>0,'crm_return_days'=>30];if(empty($cfg['crm_return_enabled']))return 0;$days=max(7,(int)$cfg['crm_return_days']);$pdo=Database::connection();$emailCfg=PlatformSetting::secret('platform.marketing_email');$waCfg=PlatformSetting::secret('platform.whatsapp');if(!$emailCfg&&!$waCfg)return 0;
        $q=$pdo->prepare("SELECT m.customer_id,c.name,c.email,c.phone,m.last_reservation_at,(SELECT cc.granted FROM customer_consents cc WHERE cc.tenant_id=m.tenant_id AND cc.customer_id=m.customer_id AND cc.type='marketing_whatsapp' ORDER BY cc.id DESC LIMIT 1) consent_whatsapp,(SELECT cc.granted FROM customer_consents cc WHERE cc.tenant_id=m.tenant_id AND cc.customer_id=m.customer_id AND cc.type='marketing_email' ORDER BY cc.id DESC LIMIT 1) consent_email FROM sports_customer_metrics m JOIN customers c ON c.id=m.customer_id AND c.tenant_id=m.tenant_id WHERE m.tenant_id=:tenant AND m.last_reservation_at<DATE_SUB(NOW(),INTERVAL :days DAY) AND NOT EXISTS(SELECT 1 FROM sports_automation_logs l WHERE l.tenant_id=m.tenant_id AND l.automation_key='crm.return' AND l.entity_id=m.customer_id AND l.created_at>DATE_SUB(NOW(),INTERVAL :days2 DAY)) LIMIT 50");$q->execute(['tenant'=>$tenantId,'days'=>$days,'days2'=>$days]);$count=0;
        foreach($q->fetchAll() as $c){$msg='Olá '.$c['name'].', sentimos sua falta na Arena. Consulte os horários disponíveis e volte a jogar!';$queued=[];$phone=preg_replace('/\D/','',(string)$c['phone']);if(!empty($c['consent_whatsapp'])&&!empty($waCfg['phone_number_id'])&&!empty($waCfg['access_token'])&&preg_match('/^\d{10,15}$/',$phone)){NotificationService::queueExternal($tenantId,'whatsapp',$phone,'Volte a jogar',$msg,['customer_id'=>$c['customer_id']]);$queued[]='whatsapp';}elseif(!empty($c['consent_email'])&&!empty($emailCfg['host'])&&filter_var($c['email']??'',FILTER_VALIDATE_EMAIL)){NotificationService::queueExternal($tenantId,'email',(string)$c['email'],'A Arena sente sua falta',$msg,['customer_id'=>$c['customer_id']]);$queued[]='email';}$pdo->prepare("INSERT INTO sports_automation_logs(tenant_id,automation_key,entity_type,entity_id,channel,status,detail,created_at) VALUES(:tenant,'crm.return','customer',:id,:channel,:status,:detail,NOW())")->execute(['tenant'=>$tenantId,'id'=>$c['customer_id'],'channel'=>$queued?implode(',',$queued):null,'status'=>$queued?'queued':'skipped','detail'=>'Cliente sem reserva há '.$days.' dias']);$count++;}
        return $count;
    }

    private function idleSlotAlerts(int $tenantId): int
    {
        $cfg=$this->config($tenantId)+['idle_slot_campaign_enabled'=>0,'idle_slot_hours_before'=>24];if(empty($cfg['idle_slot_campaign_enabled']))return 0;$hours=max(1,(int)$cfg['idle_slot_hours_before']);$pdo=Database::connection();$target=(new \DateTimeImmutable('+'.$hours.' hours'))->format('Y-m-d');$q=$pdo->prepare("SELECT COUNT(*) FROM sports_courts WHERE tenant_id=:tenant AND active=1");$q->execute(['tenant'=>$tenantId]);$courts=(int)$q->fetchColumn();if(!$courts)return 0;$q=$pdo->prepare("SELECT COUNT(DISTINCT court_id) FROM sports_reservations WHERE tenant_id=:tenant AND DATE(starts_at)=:date AND status IN('pending_payment','confirmed','completed')");$q->execute(['tenant'=>$tenantId,'date'=>$target]);$occupied=(int)$q->fetchColumn();if($occupied>=$courts)return 0;$key='idle.'.$target;$check=$pdo->prepare("SELECT 1 FROM sports_automation_logs WHERE tenant_id=:tenant AND automation_key=:key LIMIT 1");$check->execute(['tenant'=>$tenantId,'key'=>$key]);if($check->fetchColumn())return 0;NotificationService::tenantOwners($tenantId,'arena.idle','Há quadras ociosas próximas',($courts-$occupied).' quadra(s) ainda sem reserva para '.$target,'/sports/agenda','warning');$pdo->prepare("INSERT INTO sports_automation_logs(tenant_id,automation_key,entity_type,channel,status,detail,created_at) VALUES(:tenant,:key,'arena','internal','sent',:detail,NOW())")->execute(['tenant'=>$tenantId,'key'=>$key,'detail'=>($courts-$occupied).' quadras ociosas']);return 1;
    }
}
