<?php
namespace App\Services;

use App\Core\{Database,Encryption};

final class PremiumAutomationService
{
    public function dispatch(bool $manual=false,?int $tenantFilter=null):array
    {
        $pdo=Database::connection();$cfg=PlatformSetting::json('platform.automation');
        if(!$manual&&empty($cfg['enabled']))return ['queued'=>0,'customers'=>0,'skipped'=>0];
        $global=max(1,min(10000,(int)($cfg['daily_limit']??500)));$used=(int)$pdo->query("SELECT COUNT(*) FROM platform_automation_log WHERE created_at>=CURDATE() AND status IN('queued','sent')")->fetchColumn();$remaining=max(0,$global-$used);if(!$remaining)return ['queued'=>0,'customers'=>0,'skipped'=>0];
        $days=max(0,min(15,(int)($cfg['days_before']??2)));$sql="SELECT t.id tenant_id,t.name tenant_name,t.public_slug,t.public_short_code,c.id customer_id,c.name customer_name,c.email,c.phone,c.birth_date,bp.next_expected_date,p.features_json FROM customers c JOIN tenants t ON t.id=c.tenant_id LEFT JOIN behavior_profiles bp ON bp.customer_id=c.id AND bp.tenant_id=c.tenant_id JOIN subscriptions s ON s.id=(SELECT MAX(s2.id) FROM subscriptions s2 WHERE s2.tenant_id=t.id) JOIN plans p ON p.id=s.plan_id WHERE t.status IN('trial','active') AND t.deleted_at IS NULL AND COALESCE(t.is_demo,0)=0 AND c.status='active' AND c.consent_marketing=1 AND s.status IN('trial','active') AND ((bp.next_expected_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL :days DAY)) OR (c.birth_date IS NOT NULL AND DATE_FORMAT(c.birth_date,'%m-%d')=DATE_FORMAT(CURDATE(),'%m-%d')))";$params=['days'=>$days];if($tenantFilter){$sql.=' AND t.id=:tenant';$params['tenant']=$tenantFilter;}$sql.=' ORDER BY c.id LIMIT 1500';$q=$pdo->prepare($sql);$q->execute($params);$queued=0;$customers=[];$skipped=0;
        foreach($q->fetchAll() as $r){if($queued>=$remaining)break;$features=json_decode((string)($r['features_json']??'{}'),true)?:[];$birthday=!empty($r['birth_date'])&&date('m-d',strtotime((string)$r['birth_date']))===date('m-d');$event=$birthday?'BIRTHDAY':'RETURN_DUE';$allowed=$birthday?($features['automation_birthday']??false):($features['automation_return']??false);if(!$allowed||($manual&&!($features['automation_manual']??false))){$skipped++;continue;}$tenantLimit=max(1,(int)($features['automation_daily_limit']??50));$count=$pdo->prepare("SELECT COUNT(*) FROM platform_automation_log WHERE tenant_id=:t AND created_at>=CURDATE() AND status IN('queued','sent')");$count->execute(['t'=>$r['tenant_id']]);if((int)$count->fetchColumn()>=$tenantLimit){$skipped++;continue;}
            $options=$this->availability((int)$r['tenant_id'],(int)$r['customer_id']);$slug=$r['public_slug']?:$r['public_short_code'];$app=require dirname(__DIR__,2).'/config/app.php';$link=rtrim((string)($app['url']??''),'/').'/a/'.$slug;$availability=$options?implode(' • ',$options):'Consulte a agenda online para ver os próximos horários';$subject=$birthday?(string)($cfg['birthday_subject']??'Um presente especial no seu aniversário 🎉'):(string)($cfg['subject']??'Está chegando a hora de voltar');$template=$birthday?(string)($cfg['birthday_message']??'Parabéns, {cliente}! A equipe {empresa} deseja um dia incrível. Preparamos um convite especial para você: {disponibilidade}. Agende aqui: {link}'):(string)($cfg['message']??'Olá {cliente}, sentimos sua falta na {empresa}. Próximos horários: {disponibilidade}. Agende: {link}');$message=strtr($template,['{cliente}'=>$r['customer_name'],'{empresa}'=>$r['tenant_name'],'{link}'=>$link,'{disponibilidade}'=>$availability]);
            foreach(['email','whatsapp'] as $channel){if($queued>=$remaining)break 2;if(empty($cfg[$channel.'_enabled'])||empty($features['automation_'.$channel]))continue;$dest=$channel==='email'?$r['email']:preg_replace('/\D/','',(string)$r['phone']);if(($channel==='email'&&!filter_var($dest,FILTER_VALIDATE_EMAIL))||($channel==='whatsapp'&&!preg_match('/^\d{10,15}$/',(string)$dest)))continue;$cool=$birthday?350:max(1,(int)($cfg['cooldown_days']??14));$recent=$pdo->prepare("SELECT 1 FROM platform_automation_log WHERE tenant_id=:t AND customer_id=:c AND event_type=:event AND channel=:ch AND status IN('queued','sent') AND created_at>=DATE_SUB(NOW(),INTERVAL :cool DAY) LIMIT 1");$recent->execute(['t'=>$r['tenant_id'],'c'=>$r['customer_id'],'event'=>$event,'ch'=>$channel,'cool'=>$cool]);if($recent->fetchColumn())continue;
                $pdo->beginTransaction();try{$pdo->prepare("INSERT INTO platform_automation_log(tenant_id,customer_id,event_type,channel,scheduled_for,status,created_at)VALUES(:t,:c,:event,:ch,CURDATE(),'queued',NOW())")->execute(['t'=>$r['tenant_id'],'c'=>$r['customer_id'],'event'=>$event,'ch'=>$channel]);$log=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO notifications(tenant_id,customer_id,channel,template_key,destination,payload_json,status,scheduled_at,created_at)VALUES(:t,:c,:ch,:event,:dest,:payload,'queued',NOW(),NOW())")->execute(['t'=>$r['tenant_id'],'c'=>$r['customer_id'],'ch'=>$channel,'event'=>$event,'dest'=>$dest,'payload'=>json_encode(['subject'=>$subject,'link'=>$link,'availability'=>$options,'manual'=>$manual],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR)]);$notification=(int)$pdo->lastInsertId();$payload=Encryption::encrypt(['automation_log_id'=>$log,'notification_id'=>$notification,'channel'=>$channel,'destination'=>$dest,'subject'=>$subject,'message'=>$message]);$pdo->prepare("INSERT INTO jobs(tenant_id,type,payload_encrypted,status,attempts,available_at,created_at,updated_at)VALUES(:t,'campaign.send',:p,'queued',0,NOW(),NOW(),NOW())")->execute(['t'=>$r['tenant_id'],'p'=>$payload]);$pdo->commit();$queued++;$customers[(int)$r['customer_id']]=true;}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('[ApPlanner PremiumAutomation] '.mb_substr($e->getMessage(),0,250));$skipped++;}
            }
        }
        return ['queued'=>$queued,'customers'=>count($customers),'skipped'=>$skipped];
    }

    private function availability(int $tenantId,int $customerId):array
    {
        $pdo=Database::connection();$last=$pdo->prepare("SELECT service_id,professional_id FROM appointments WHERE tenant_id=:t AND customer_id=:c AND status='completed' ORDER BY starts_at DESC LIMIT 1");$last->execute(['t'=>$tenantId,'c'=>$customerId]);$history=$last->fetch();if(!$history)return [];$service=(int)$history['service_id'];$preferred=$pdo->prepare("SELECT professional_id,COUNT(*) total FROM appointments WHERE tenant_id=:t AND customer_id=:c AND service_id=:s AND status='completed' GROUP BY professional_id ORDER BY total DESC LIMIT 1");$preferred->execute(['t'=>$tenantId,'c'=>$customerId,'s'=>$service]);$preferredId=(int)$preferred->fetchColumn();$pros=$pdo->prepare("SELECT p.id,p.name FROM professionals p WHERE p.tenant_id=:t AND p.active=1 AND (:preferred=0 OR p.id=:preferred2) AND (NOT EXISTS(SELECT 1 FROM professional_services x WHERE x.professional_id=p.id) OR EXISTS(SELECT 1 FROM professional_services x2 WHERE x2.professional_id=p.id AND x2.service_id=:s)) ORDER BY p.name LIMIT 20");$pros->execute(['t'=>$tenantId,'preferred'=>$preferredId,'preferred2'=>$preferredId,'s'=>$service]);$pros=$pros->fetchAll();$availability=new AvailabilityService();$found=[];
        for($offset=0;$offset<14&&count($found)<3;$offset++){$day=(new \DateTimeImmutable('today'))->modify('+'.$offset.' days');foreach($pros as $pro){$slots=$availability->slots($tenantId,$service,(int)$pro['id'],$day,true);if($slots){$found[]=$day->format('d/m').' '.$slots[0]['label'].' · '.$pro['name'];if(count($found)>=3)break;}}}return $found;
    }
}
