from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies=[
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("arena","0002_operations"),
        ("finance","0002_normalize_index_names"),
        ("scheduling","0006_barber_lifecycle"),
    ]
    operations=[
        migrations.AlterField(
            model_name="reservation",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("not_required","Não exigido"),("pending","Pendente"),
                    ("partial","Parcial"),("paid","Pago"),
                    ("refunded","Estornado"),("cancelled","Cancelado"),
                ],
                default="not_required",max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="champion_team",
            field=models.ForeignKey(
                blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,
                related_name="championships",to="arena.tournamentteam",
            ),
        ),
        migrations.CreateModel(
            name="ClassMakeup",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("original_date",models.DateField()),
                ("replacement_date",models.DateField(blank=True,null=True)),
                ("status",models.CharField(
                    choices=[
                        ("credit","Crédito"),("scheduled","Agendada"),
                        ("used","Utilizada"),("cancelled","Cancelada"),
                    ],
                    db_index=True,default="credit",max_length=16,
                )),
                ("notes",models.CharField(blank=True,max_length=300)),
                ("created_by",models.ForeignKey(
                    blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,
                    related_name="sports_makeups_created",to=settings.AUTH_USER_MODEL,
                )),
                ("original_class",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="makeups_origin",to="arena.sportsclass",
                )),
                ("replacement_class",models.ForeignKey(
                    blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,
                    related_name="makeups_replacement",to="arena.sportsclass",
                )),
                ("student",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="makeups",to="arena.classstudent",
                )),
                ("tenant",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="sports_class_makeups",to="tenants.tenant",
                )),
            ],
        ),
        migrations.CreateModel(
            name="ClassBillingLog",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("competence_month",models.CharField(max_length=7)),
                ("amount",models.DecimalField(decimal_places=2,max_digits=12)),
                ("status",models.CharField(
                    choices=[
                        ("generated","Gerada"),("skipped","Ignorada"),("cancelled","Cancelada"),
                    ],
                    default="generated",max_length=16,
                )),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("financial_transaction",models.ForeignKey(
                    blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,
                    related_name="sports_class_billing_logs",to="finance.financialtransaction",
                )),
                ("student",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="billing_logs",to="arena.classstudent",
                )),
                ("tenant",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="sports_class_billing_logs",to="tenants.tenant",
                )),
            ],
        ),
        migrations.CreateModel(
            name="DynamicPricingAudit",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("base_total",models.DecimalField(decimal_places=2,max_digits=12)),
                ("final_total",models.DecimalField(decimal_places=2,max_digits=12)),
                ("multiplier",models.DecimalField(decimal_places=4,max_digits=8)),
                ("details",models.JSONField(blank=True,default=dict)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("reservation",models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="dynamic_pricing_audit",to="arena.reservation",
                )),
                ("tenant",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="sports_dynamic_pricing_audits",to="tenants.tenant",
                )),
            ],
        ),
        migrations.CreateModel(
            name="TournamentTeamPlayer",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("jersey_number",models.PositiveSmallIntegerField(blank=True,null=True)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("customer",models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="tournament_teams",to="scheduling.customer",
                )),
                ("team",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="players",to="arena.tournamentteam",
                )),
                ("tenant",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="sports_tournament_players",to="tenants.tenant",
                )),
            ],
        ),
        migrations.CreateModel(
            name="TournamentEvent",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("event_type",models.CharField(max_length=50)),
                ("detail",models.CharField(blank=True,max_length=500)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("created_by",models.ForeignKey(
                    blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,
                    related_name="sports_tournament_events",to=settings.AUTH_USER_MODEL,
                )),
                ("tenant",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="sports_tournament_events",to="tenants.tenant",
                )),
                ("tournament",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="events",to="arena.tournament",
                )),
            ],
        ),
        migrations.CreateModel(
            name="CustomerMetric",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("last_reservation_at",models.DateTimeField(blank=True,null=True)),
                ("reservation_count",models.PositiveIntegerField(default=0)),
                ("cancellation_count",models.PositiveIntegerField(default=0)),
                ("no_show_count",models.PositiveIntegerField(default=0)),
                ("total_spent",models.DecimalField(decimal_places=2,default=0,max_digits=14)),
                ("average_ticket",models.DecimalField(decimal_places=2,default=0,max_digits=12)),
                ("is_membership",models.BooleanField(default=False)),
                ("game_count",models.PositiveIntegerField(default=0)),
                ("segment",models.CharField(
                    choices=[
                        ("new","Novo"),("recurring","Recorrente"),("vip","VIP"),
                        ("inactive","Inativo"),("churn_risk","Risco de churn"),
                    ],
                    db_index=True,default="new",max_length=16,
                )),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("customer",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="sports_metrics",to="scheduling.customer",
                )),
                ("favorite_court",models.ForeignKey(
                    blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,
                    related_name="+",to="arena.court",
                )),
                ("favorite_modality",models.ForeignKey(
                    blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,
                    related_name="+",to="arena.modality",
                )),
                ("tenant",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="sports_customer_metrics",to="tenants.tenant",
                )),
            ],
        ),
        migrations.CreateModel(
            name="AutomationLog",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("automation_key",models.CharField(max_length=80)),
                ("entity_type",models.CharField(blank=True,max_length=60)),
                ("entity_id",models.BigIntegerField(blank=True,null=True)),
                ("channel",models.CharField(blank=True,max_length=20)),
                ("status",models.CharField(
                    choices=[
                        ("skipped","Ignorado"),("queued","Na fila"),
                        ("sent","Enviado"),("failed","Falhou"),
                    ],
                    max_length=16,
                )),
                ("detail",models.CharField(blank=True,max_length=500)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("tenant",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="sports_automation_logs",to="tenants.tenant",
                )),
            ],
        ),
        migrations.CreateModel(
            name="ArenaCommand",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("public_id",models.CharField(max_length=32,unique=True)),
                ("status",models.CharField(
                    choices=[("open","Aberta"),("closed","Fechada"),("cancelled","Cancelada")],
                    db_index=True,default="open",max_length=16,
                )),
                ("subtotal",models.DecimalField(decimal_places=2,default=0,max_digits=12)),
                ("discount",models.DecimalField(decimal_places=2,default=0,max_digits=12)),
                ("surcharge",models.DecimalField(decimal_places=2,default=0,max_digits=12)),
                ("total",models.DecimalField(decimal_places=2,default=0,max_digits=12)),
                ("payment_method",models.CharField(blank=True,max_length=40)),
                ("payment_status",models.CharField(
                    choices=[
                        ("pending","Pendente"),("paid","Pago"),
                        ("partial","Parcial"),("cancelled","Cancelado"),
                    ],
                    default="pending",max_length=16,
                )),
                ("notes",models.CharField(blank=True,max_length=500)),
                ("opened_at",models.DateTimeField()),
                ("closed_at",models.DateTimeField(blank=True,null=True)),
                ("closed_by",models.ForeignKey(
                    blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,
                    related_name="sports_commands_closed",to=settings.AUTH_USER_MODEL,
                )),
                ("customer",models.ForeignKey(
                    blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,
                    related_name="sports_commands",to="scheduling.customer",
                )),
                ("opened_by",models.ForeignKey(
                    blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,
                    related_name="sports_commands_opened",to=settings.AUTH_USER_MODEL,
                )),
                ("reservation",models.ForeignKey(
                    blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,
                    related_name="commands",to="arena.reservation",
                )),
                ("tenant",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="sports_commands",to="tenants.tenant",
                )),
            ],
        ),
        migrations.CreateModel(
            name="ArenaCommandItem",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("description",models.CharField(max_length=190)),
                ("quantity",models.DecimalField(decimal_places=3,max_digits=12)),
                ("unit_price",models.DecimalField(decimal_places=2,max_digits=12)),
                ("cost_snapshot",models.DecimalField(decimal_places=2,default=0,max_digits=12)),
                ("total",models.DecimalField(decimal_places=2,max_digits=12)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("command",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="items",to="arena.arenacommand",
                )),
                ("product",models.ForeignKey(
                    blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,
                    related_name="sports_command_items",to="finance.product",
                )),
                ("tenant",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="sports_command_items",to="tenants.tenant",
                )),
            ],
        ),
        migrations.CreateModel(
            name="ArenaCommandStockMovement",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("quantity",models.DecimalField(decimal_places=3,max_digits=12)),
                ("balance_after",models.DecimalField(decimal_places=3,max_digits=12)),
                ("movement_type",models.CharField(
                    choices=[
                        ("command_close","Fechamento de comanda"),
                        ("command_reversal","Estorno de comanda"),
                    ],
                    max_length=24,
                )),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("command",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="stock_movements",to="arena.arenacommand",
                )),
                ("product",models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="sports_command_stock_movements",to="finance.product",
                )),
                ("tenant",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="sports_command_stock_movements",to="tenants.tenant",
                )),
            ],
        ),
        migrations.AddIndex(
            model_name="classmakeup",
            index=models.Index(
                fields=["tenant","student","status","original_date"],
                name="arena_makeup_student_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="classbillinglog",
            constraint=models.UniqueConstraint(
                fields=("student","competence_month"),
                name="uq_class_billing_month",
            ),
        ),
        migrations.AddIndex(
            model_name="classbillinglog",
            index=models.Index(
                fields=["tenant","competence_month","status"],
                name="arena_class_billing_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dynamicpricingaudit",
            index=models.Index(
                fields=["tenant","created_at"],name="arena_dynamic_audit_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentteamplayer",
            constraint=models.UniqueConstraint(
                fields=("team","customer"),name="uq_tournament_team_player"
            ),
        ),
        migrations.AddIndex(
            model_name="tournamentevent",
            index=models.Index(
                fields=["tournament","created_at"],name="arena_tournament_event_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customermetric",
            constraint=models.UniqueConstraint(
                fields=("tenant","customer"),name="uq_arena_customer_metric"
            ),
        ),
        migrations.AddIndex(
            model_name="customermetric",
            index=models.Index(
                fields=["tenant","segment","last_reservation_at"],
                name="arena_customer_segment_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationlog",
            index=models.Index(
                fields=["tenant","automation_key","created_at"],
                name="arena_automation_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="arenacommand",
            index=models.Index(
                fields=["tenant","status","opened_at"],name="arena_command_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arenacommanditem",
            index=models.Index(fields=["command"],name="arena_command_item_idx"),
        ),
        migrations.AddConstraint(
            model_name="arenacommandstockmovement",
            constraint=models.UniqueConstraint(
                fields=("command","product","movement_type"),
                name="uq_arena_command_stock",
            ),
        ),
    ]
