# Generated by Django 5.2.17 on 2026-09-21 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_normalize_index_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaConversionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('event_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Na fila'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], db_index=True, default='queued', max_length=12)),
                ('http_status', models.SmallIntegerField(blank=True, null=True)),
                ('response_excerpt', models.CharField(blank=True, max_length=500)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcquisitionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('event_id', models.UUIDField(unique=True)),
                ('event_name', models.CharField(db_index=True, max_length=50)),
                ('segment', models.CharField(blank=True, max_length=40)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('medium', models.CharField(blank=True, max_length=100)),
                ('campaign', models.CharField(blank=True, max_length=120)),
                ('content', models.CharField(blank=True, max_length=120)),
                ('term', models.CharField(blank=True, max_length=120)),
                ('event_url', models.CharField(blank=True, max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('client_ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('value_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisition_events', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisition_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event_name', 'created_at'], name='growth_funnel_idx'), models.Index(fields=['campaign', 'created_at'], name='growth_campaign_idx'), models.Index(fields=['session_key', 'created_at'], name='growth_session_idx')],
            },
        ),
        migrations.CreateModel(
            name='PublicContentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=10)),
                ('content_key', models.CharField(max_length=80)),
                ('content_value', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_translations', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'locale', 'content_key'), name='uq_public_translation')],
            },
        ),
    ]
