# Generated by Django 5.2.17 on 2026-09-21 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0003_marketingdelivery_clicked_at_and_more'),
        ('scheduling', '0006_barber_lifecycle'),
        ('tenants', '0004_normalize_index_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLoyaltySettings',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='loyalty_settings', serialize=False, to='tenants.tenant')),
                ('enabled', models.BooleanField(default=False)),
                ('points_per_currency', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('reward_points', models.PositiveIntegerField(default=100)),
                ('reward_value', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('referral_points', models.PositiveIntegerField(default=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchased_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('exhausted', 'Esgotado'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], db_index=True, default='active', max_length=16)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('external_reference', models.CharField(blank=True, max_length=190)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='scheduling.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_packages', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPackageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_used', models.PositiveSmallIntegerField(default=1)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_usages', to='scheduling.appointment')),
                ('customer_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='engagement.customerpackage')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scheduling.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_usages', to='tenants.tenant')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_usages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_code', models.CharField(max_length=32, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('validity_days', models.PositiveSmallIntegerField(default=30)),
                ('active', models.BooleanField(default=True)),
                ('recurring', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_packages', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customerpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_packages', to='engagement.servicepackage'),
        ),
        migrations.CreateModel(
            name='CustomerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral')], default='monthly', max_length=16)),
                ('recurring_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], db_index=True, default='active', max_length=16)),
                ('started_at', models.DateField()),
                ('next_due_at', models.DateField(db_index=True)),
                ('last_billed_at', models.DateField(blank=True, null=True)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=190)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='scheduling.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_memberships', to='tenants.tenant')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='engagement.servicepackage')),
            ],
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=190, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('verified', 'Verificado'), ('failed', 'Falhou'), ('disabled', 'Desabilitado')], db_index=True, default='pending', max_length=16)),
                ('verification_token', models.CharField(max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('period', models.CharField(choices=[('any', 'Qualquer'), ('morning', 'Manhã'), ('afternoon', 'Tarde'), ('evening', 'Noite')], default='any', max_length=16)),
                ('status', models.CharField(choices=[('waiting', 'Aguardando'), ('matched', 'Encontrado'), ('booked', 'Agendado'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], db_index=True, default='waiting', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='scheduling.customer')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='scheduling.professional')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='scheduling.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to='scheduling.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'customer'), name='uq_loyalty_account')],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=16)),
                ('reward_points', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_origin', to='scheduling.customer')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='scheduling.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_referrals', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'referred'), name='uq_referral_referred')],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField()),
                ('reward_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('redeemed', 'Resgatado'), ('cancelled', 'Cancelado')], db_index=True, default='available', max_length=16)),
                ('issued_at', models.DateTimeField()),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_rewards', to='scheduling.customer')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_rewards_redeemed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_rewards', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'customer', 'status'], name='eng_loyalty_reward_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('earn', 'Ganho'), ('redeem', 'Resgate'), ('adjust', 'Ajuste'), ('reverse', 'Estorno')], max_length=12)),
                ('points', models.IntegerField()),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='scheduling.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'customer', 'created_at'], name='eng_loyalty_tx_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_id__isnull', False), ('source_type__gt', '')), fields=('tenant', 'customer', 'type', 'source_type', 'source_id'), name='uq_loyalty_source')],
            },
        ),
        migrations.CreateModel(
            name='ReferralVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_token_hash', models.CharField(max_length=64, unique=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('clicked_at', models.DateTimeField()),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_conversions', to='tenants.tenant')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_visits', to='communications.marketinglead')),
                ('referrer_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['referrer_user', 'clicked_at'], name='eng_referral_owner_idx')],
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveSmallIntegerField(default=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_items', to='scheduling.service')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='engagement.servicepackage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('package', 'service'), name='uq_package_service')],
            },
        ),
        migrations.AddIndex(
            model_name='customerpackage',
            index=models.Index(fields=['tenant', 'customer', 'status'], name='eng_pkg_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='customermembership',
            index=models.Index(fields=['tenant', 'status', 'next_due_at'], name='eng_membership_due_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantdomain',
            index=models.Index(fields=['tenant', 'status'], name='eng_domain_status_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['tenant', 'status', 'service', 'professional', 'preferred_date'], name='eng_waitlist_match_idx'),
        ),
    ]
