from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies=[
        ("engagement","0001_initial"),
        ("scheduling","0007_waiting_status"),
        ("tenants","0005_onboarding_status_history"),
    ]
    operations=[
        migrations.CreateModel(
            name="BehaviorProfile",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("avg_interval_days",models.DecimalField(blank=True,decimal_places=2,max_digits=8,null=True)),
                ("median_interval_days",models.DecimalField(blank=True,decimal_places=2,max_digits=8,null=True)),
                ("std_deviation_days",models.DecimalField(blank=True,decimal_places=2,max_digits=8,null=True)),
                ("last_visit_at",models.DateTimeField(blank=True,null=True)),
                ("next_expected_date",models.DateField(blank=True,db_index=True,null=True)),
                ("confidence_score",models.PositiveSmallIntegerField(default=0)),
                ("visits_count",models.PositiveIntegerField(default=0)),
                ("intervals",models.JSONField(blank=True,default=list)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("customer",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="behavior_profiles",to="scheduling.customer")),
                ("tenant",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="behavior_profiles",to="tenants.tenant")),
            ],
        ),
        migrations.AddConstraint(model_name="behaviorprofile",constraint=models.UniqueConstraint(fields=("tenant","customer"),name="uq_behavior_customer")),
        migrations.AddIndex(model_name="behaviorprofile",index=models.Index(fields=["tenant","next_expected_date"],name="behavior_next_idx")),
        migrations.CreateModel(
            name="BehaviorServiceProfile",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("avg_interval_days",models.DecimalField(blank=True,decimal_places=2,max_digits=8,null=True)),
                ("median_interval_days",models.DecimalField(blank=True,decimal_places=2,max_digits=8,null=True)),
                ("std_deviation_days",models.DecimalField(blank=True,decimal_places=2,max_digits=8,null=True)),
                ("last_visit_at",models.DateTimeField(blank=True,null=True)),
                ("next_expected_date",models.DateField(blank=True,null=True)),
                ("confidence_score",models.PositiveSmallIntegerField(default=0)),
                ("visits_count",models.PositiveIntegerField(default=0)),
                ("intervals",models.JSONField(blank=True,default=list)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("customer",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="behavior_service_profiles",to="scheduling.customer")),
                ("service",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="behavior_profiles",to="scheduling.service")),
                ("tenant",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="behavior_service_profiles",to="tenants.tenant")),
            ],
        ),
        migrations.AddConstraint(model_name="behaviorserviceprofile",constraint=models.UniqueConstraint(fields=("tenant","customer","service"),name="uq_behavior_service")),
        migrations.AddIndex(model_name="behaviorserviceprofile",index=models.Index(fields=["tenant","next_expected_date","confidence_score"],name="behavior_service_next_idx")),
        migrations.CreateModel(
            name="BehaviorEvent",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("event_type",models.CharField(max_length=60)),
                ("score",models.DecimalField(blank=True,decimal_places=2,max_digits=8,null=True)),
                ("payload",models.JSONField(blank=True,default=dict)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("customer",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="behavior_events",to="scheduling.customer")),
                ("tenant",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="behavior_events",to="tenants.tenant")),
            ],
        ),
        migrations.AddIndex(model_name="behaviorevent",index=models.Index(fields=["tenant","event_type","created_at"],name="behavior_event_type_idx")),
        migrations.CreateModel(
            name="PlatformAutomationLog",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("event_type",models.CharField(max_length=60)),
                ("channel",models.CharField(choices=[("email","E-mail"),("whatsapp","WhatsApp")],max_length=16)),
                ("scheduled_for",models.DateField()),
                ("status",models.CharField(choices=[("queued","Na fila"),("sent","Enviado"),("failed","Falhou"),("skipped","Ignorado")],default="queued",max_length=16)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("customer",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="automation_logs",to="scheduling.customer")),
                ("tenant",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="automation_logs",to="tenants.tenant")),
            ],
        ),
        migrations.AddConstraint(model_name="platformautomationlog",constraint=models.UniqueConstraint(fields=("tenant","customer","event_type","channel","scheduled_for"),name="uq_platform_automation")),
        migrations.AddIndex(model_name="platformautomationlog",index=models.Index(fields=["tenant","scheduled_for","status"],name="platform_automation_idx")),
    ]
