# Generated by Django 5.2.17 on 2026-09-23 15:29

from django.db import migrations, models


def restore_provider_memberships(apps,schema_editor):
    Membership=apps.get_model('engagement','CustomerMembership')
    Recurring=apps.get_model('billing','TenantRecurringSubscription')
    db=schema_editor.connection.alias
    for membership in Membership.objects.using(db).all().iterator():
        recurring=Recurring.objects.using(db).filter(
            tenant_id=membership.tenant_id,reference_type='customer_membership',
            reference_id=membership.pk,
        ).order_by('-pk').first()
        if recurring or membership.provider_subscription_id:
            Membership.objects.using(db).filter(pk=membership.pk).update(
                billing_mode='provider',
                provider_status=recurring.status if recurring else '',
                provider_checkout_url=recurring.checkout_url if recurring else '',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_referral_campaign'),
        ('billing', '0009_connection_auth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermembership',
            name='billing_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('provider', 'Automática')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='customermembership',
            name='provider_checkout_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='customermembership',
            name='provider_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.RunPython(restore_provider_memberships,migrations.RunPython.noop),
    ]
