# Generated by Django 5.2.17 on 2026-09-30 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0005_customermembership_billing_mode_and_more'),
        ('scheduling', '0010_alter_appointment_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entry', to='scheduling.appointment'),
        ),
    ]
