# Generated by Django 5.2.18 on 2026-10-07 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0008_waitlist_unit'),
        ('tenants', '0011_tenant_archive_snapshot_tenant_archived_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnMessagingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('daily_limit', models.PositiveSmallIntegerField(default=30)),
                ('cooldown_days', models.PositiveSmallIntegerField(default=7)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_messaging', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
