"""Rótulos visíveis dos portais, sem alterar nomes de colunas do legado."""

from django.core.exceptions import FieldDoesNotExist


FIELD_LABELS = {
    "action": "Ação",
    "active": "Ativo", "address": "Endereço", "address_number": "Número",
    "addon_monthly_price": "Valor mensal adicional", "addon_sellable": "Adicional comercializável",
    "alert_key": "Identificador do alerta", "allow_games": "Permitir jogos",
    "allow_waitlist": "Permitir lista de espera", "amount": "Valor",
    "allow_full_payment": "Permitir pagamento total por Pix no agendamento",
    "allow_partial_payment": "Permitir sinal por Pix no agendamento",
    "allow_pay_on_site": "Permitir pagamento na unidade",
    "appointment": "Agendamento", "approval_status": "Situação da aprovação",
    "assigned_professional": "Profissional responsável", "assigned_to": "Atribuído a",
    "attempts": "Tentativas", "available_at": "Disponível em", "avg_interval_days": "Intervalo médio em dias",
    "backup": "Backup", "backup_before_update": "Backup antes da atualização",
    "backup_encrypt": "Criptografar backup", "backup_include_uploads": "Incluir arquivos no backup",
    "backup_retention_days": "Retenção do backup em dias", "base_amount": "Valor base",
    "batch": "Lote", "bay": "Box", "bay_type": "Tipo de box", "billing_cycle": "Ciclo de cobrança",
    "billing_day": "Dia da cobrança", "birth_date": "Data de nascimento", "blocked_at": "Bloqueado em",
    "body": "Conteúdo", "brand": "Marca", "branding_done": "Identidade visual concluída",
    "buffer_minutes": "Intervalo entre horários (minutos)", "business_type": "Tipo de negócio",
    "campaign": "Campanha", "cancel_notice_minutes": "Antecedência para cancelar (minutos)",
    "cancellation_policy": "Política de cancelamento", "capacity": "Capacidade",
    "category": "Categoria", "changed_by": "Alterado por", "channel": "Canal",
    "city": "Cidade", "clicked_at": "Clicado em", "closed_at": "Encerrado em",
    "code": "Código", "color": "Cor", "comment": "Comentário",
    "commercial_user": "Responsável comercial", "commission_amount": "Valor da comissão",
    "commission_percent": "Comissão (%)", "commission_type": "Tipo de comissão",
    "commission_value": "Valor da comissão", "company_done": "Dados da empresa concluídos",
    "competence_at": "Competência", "completed_at": "Concluído em",
    "confidence_score": "Grau de confiança", "consent_marketing": "Consentimento para marketing",
    "contact_name": "Nome do contato", "content": "Conteúdo", "contracted_price": "Valor contratado",
    "cost_price": "Preço de custo", "court": "Quadra", "cover": "Foto de capa",
    "created_at": "Criado em", "critical_alert_email": "E-mail para alertas críticos",
    "critical_alerts_enabled": "Alertas críticos ativos", "crm_default_return_days": "Prazo padrão de retorno (dias)",
    "crm_return_days": "Prazo de retorno (dias)", "crm_return_enabled": "Retorno automático ativo",
    "cron_key": "Identificador da tarefa", "cron_stale_minutes": "Tolerância da tarefa (minutos)",
    "cta_label": "Texto do botão", "cta_url": "Link do botão", "customer": "Cliente",
    "customer_can_cancel": "Cliente pode cancelar", "customer_can_reschedule": "Cliente pode reagendar",
    "customer_email": "E-mail do cliente", "customer_name": "Nome do cliente",
    "customer_package": "Pacote do cliente", "customer_phone": "Telefone do cliente",
    "cycle": "Ciclo", "cycle_months": "Ciclo em meses", "daily_rent": "Diária",
    "day_of_month": "Dia do mês", "default_buffer_minutes": "Intervalo padrão (minutos)",
    "deposit_percent": "Percentual do sinal", "description": "Descrição",
    "destination": "Destino", "details": "Detalhes",
    "disk_min_free_mb": "Espaço livre mínimo (MB)", "display_name": "Nome de exibição",
    "district": "Bairro", "domain": "Domínio", "due_at": "Vencimento",
    "duration_minutes": "Duração (minutos)", "duration_ms": "Duração (ms)",
    "dynamic_max_multiplier": "Multiplicador máximo de preço",
    "dynamic_min_multiplier": "Multiplicador mínimo de preço",
    "dynamic_pricing_enabled": "Preço dinâmico ativo", "email": "E-mail",
    "email_attempted": "E-mail informado", "email_verification_waived_at": "Confirmação de e-mail dispensada em",
    "end_date": "Data final", "end_time": "Hora final", "ended_at": "Encerrado em",
    "ends_at": "Termina em", "ends_on": "Termina no dia",
    "environment": "Ambiente", "event_name": "Nome do evento", "event_type": "Tipo do evento",
    "excerpt": "Resumo", "executed_at": "Executado em", "executed_by": "Executado por",
    "exemption_type": "Tipo de isenção", "expires_at": "Expira em",
    "expected_minutes": "Duração prevista (minutos)", "expected_ready_at": "Entrega prevista em",
    "external_reference": "Referência externa", "failed_at": "Falhou em",
    "failed_count": "Falhas", "featured": "Em destaque", "final_price": "Preço final",
    "finished_at": "Finalizado em", "flexibility_minutes": "Flexibilidade (minutos)",
    "format": "Formato", "frequency": "Frequência", "from_plan": "Plano anterior",
    "from_status": "Situação anterior", "fuel_level": "Nível de combustível",
    "generate_days_ahead": "Gerar com antecedência (dias)", "gross_amount": "Valor bruto",
    "headline": "Chamada principal", "host_name": "Servidor", "id": "ID",
    "idle_slot_campaign_enabled": "Campanha para horários vagos ativa",
    "idle_slot_hours_before": "Antecedência de horário vago (horas)", "indoor": "Coberta",
    "internal_notes": "Observações internas", "interval_minutes": "Intervalo (minutos)",
    "ip_address": "Endereço IP", "is_active": "Ativo", "is_custom": "Plano personalizado",
    "is_primary": "Principal", "is_secret": "Sigiloso", "is_staff": "Acesso administrativo",
    "job": "Ordem de serviço", "joined_at": "Entrou em", "key": "Chave",
    "keys_received": "Chaves recebidas", "label": "Rótulo", "last_message_at": "Última mensagem em",
    "last_payment_at": "Último pagamento em", "last_seen_at": "Última ocorrência em",
    "last_sync_at": "Última sincronização em", "last_tested_at": "Último teste em",
    "last_visit_at": "Última visita em", "lead": "Lead", "lead_retention_days": "Retenção de leads (dias)",
    "level": "Nível", "lighting": "Iluminação", "locale": "Idioma",
    "logo": "Logo", "master_user": "Usuário Master", "max_discount_percent": "Desconto máximo (%)",
    "max_players": "Máximo de jogadores", "max_uses": "Máximo de usos",
    "maximum_days_ahead": "Antecedência máxima (dias)",
    "maximum_duration_minutes": "Duração máxima (minutos)",
    "maximum_minutes": "Máximo de minutos", "medium": "Meio",
    "membership": "Mensalidade", "message": "Mensagem", "meta_description": "Descrição para buscas",
    "meta_title": "Título para buscas", "method": "Método", "migration": "Migração",
    "minimum_duration_minutes": "Duração mínima (minutos)",
    "minimum_minutes": "Mínimo de minutos", "minimum_notice_minutes": "Antecedência mínima (minutos)",
    "minimum_stock": "Estoque mínimo", "modality": "Modalidade", "model": "Modelo",
    "module": "Módulo", "month": "Mês", "monthly_amount": "Valor mensal",
    "monthly_amount_override": "Valor mensal ajustado", "monthly_price": "Valor mensal",
    "monthly_rent": "Aluguel mensal", "name": "Nome", "net_amount": "Valor líquido",
    "new_amount": "Novo valor", "next_billing_at": "Próxima cobrança",
    "next_contact_at": "Próximo contato", "next_due_at": "Próximo vencimento",
    "next_expected_date": "Próxima data prevista", "next_generation_date": "Próxima geração em",
    "notes": "Observações", "notified_at": "Notificado em", "notify_email": "Avisar por e-mail",
    "notify_whatsapp": "Avisar pelo WhatsApp", "number": "Número",
    "occurrence_count": "Ocorrências", "odometer_in": "Quilometragem na entrada",
    "offer_expires_at": "Oferta expira em", "opened_at": "Aberto em",
    "opening_amount": "Valor inicial", "original_class": "Turma original",
    "original_date": "Data original", "original_name": "Nome original",
    "package": "Pacote", "paid_at": "Pago em", "payment_deadline_minutes": "Prazo para pagamento (minutos)",
    "payment_method": "Forma de pagamento", "payment_status": "Situação do pagamento",
    "performed_at": "Realizado em", "period": "Período", "phone": "Telefone",
    "photo": "Foto", "plan": "Plano", "plate": "Placa", "points": "Pontos",
    "postal_code": "CEP", "preferred_date": "Data desejada",
    "preferred_end": "Término desejado", "preferred_professional": "Profissional preferido",
    "preferred_start": "Início desejado", "previous_amount": "Valor anterior",
    "price": "Preço", "price_per_hour": "Preço por hora", "priority": "Prioridade",
    "product": "Produto", "products_target": "Meta de produtos", "professional": "Profissional",
    "professional_done": "Profissional cadastrado", "protocol": "Protocolo",
    "processed_at": "Processado em", "provider": "Provedor", "provider_customer_id": "ID do cliente no provedor",
    "provider_subscription_id": "ID da assinatura no provedor", "provider_environment": "Ambiente da assinatura no Mercado Pago", "public_enabled": "Página pública ativa",
    "public_id": "Identificador público", "public_notes": "Observações públicas",
    "public_rules": "Regras públicas", "public_slug": "Link público",
    "published_at": "Publicado em", "purchase_amount": "Valor da compra",
    "purpose": "Finalidade", "quantity": "Quantidade", "quoted_monthly_price": "Valor mensal proposto",
    "rating": "Nota", "read_at": "Lido em", "reason": "Motivo",
    "reason_code": "Código do motivo", "reason_text": "Descrição do motivo",
    "received_at": "Recebido em", "record_type": "Tipo de registro",
    "recurring": "Recorrente", "recurring_amount": "Valor recorrente",
    "reference_type": "Tipo de referência", "registration_amount": "Valor da matrícula",
    "reminder_24h_enabled": "Lembrete de 24 horas ativo",
    "reminder_2h_enabled": "Lembrete de 2 horas ativo",
    "rent_due_day": "Dia do vencimento", "replacement_class": "Turma de reposição",
    "replacement_date": "Data de reposição", "request_type": "Tipo de solicitação",
    "require_checkin_photos": "Exigir fotos na entrada",
    "require_delivery_acceptance": "Exigir aceite na entrega",
    "reservation_reminder_enabled": "Lembrete da reserva ativo",
    "reservation_reminder_hours": "Antecedência do lembrete (horas)",
    "responsible_name": "Nome do responsável", "responsible_phone": "Telefone do responsável",
    "result": "Resultado", "revenue_target": "Meta de receita", "role": "Papel",
    "rule_type": "Tipo de regra", "sale_price": "Preço de venda",
    "schedule_done": "Agenda configurada", "scope": "Escopo", "score": "Pontuação",
    "segment": "Segmento", "sent_at": "Enviado em", "sent_count": "Enviados",
    "seo_description": "Descrição para buscas", "seo_title": "Título para buscas",
    "service": "Serviço", "service_commission_percent": "Comissão de serviço (%)",
    "service_done": "Serviço cadastrado", "services_target": "Meta de serviços",
    "severity": "Gravidade", "size_bytes": "Tamanho (bytes)",
    "sku": "Código do produto", "slot_interval_minutes": "Intervalo entre horários (minutos)",
    "slug": "Identificador", "sort_order": "Ordem de exibição", "source": "Origem",
    "source_job": "Ordem de origem", "specialty": "Especialidade",
    "specific_date": "Data específica", "sports_class": "Turma",
    "start_date": "Data inicial", "start_time": "Hora inicial", "started_at": "Iniciado em",
    "starts_at": "Começa em", "starts_on": "Começa no dia", "state": "Estado",
    "status": "Situação", "step_type": "Tipo de etapa", "stock": "Estoque",
    "subheadline": "Chamada secundária",
    "student": "Aluno", "subject": "Assunto", "subscription": "Assinatura",
    "support_enabled": "Acesso ao suporte ativo", "surface": "Piso",
    "teacher_name": "Nome do professor", "tenant": "Empresa", "terms_text": "Texto dos termos",
    "ticket": "Chamado", "ticket_target": "Meta de tíquete médio", "timezone": "Fuso horário",
    "title": "Título", "to_plan": "Novo plano", "to_status": "Nova situação",
    "total": "Total", "total_amount": "Valor total", "total_count": "Total de registros",
    "trial_ends_at": "Fim do teste", "type": "Tipo", "unblocked_at": "Desbloqueado em",
    "unit": "Unidade", "unit_done": "Unidade cadastrada", "unit_label": "Identificação da unidade",
    "updated_at": "Atualizado em", "user": "Usuário", "uses_count": "Usos",
    "valid_from": "Válido desde", "valid_to": "Válido até", "valid_until": "Válido até",
    "validity_days": "Validade em dias", "value": "Valor", "value_amount": "Valor",
    "vehicle": "Veículo", "verification_type": "Tipo de verificação",
    "verified_at": "Verificado em", "version": "Versão", "visits_count": "Número de visitas",
    "wa_id": "ID do WhatsApp", "waitlist_offer_minutes": "Tempo da oferta (minutos)",
    "warranty_until": "Garantia até", "weekday": "Dia da semana",
    "whatsapp": "WhatsApp", "year": "Ano",
    "annual_price": "Valor anual", "quarterly_price": "Valor trimestral",
    "semiannual_price": "Valor semestral", "trial_days": "Dias de teste grátis",
    "trial_without_card": "Teste sem cartão", "public_visible": "Visível na página de planos",
    "public_booking_enabled": "Agendamento público ativo",
}


def field_label(model, name):
    if name in FIELD_LABELS:
        return FIELD_LABELS[name]
    try:
        return str(model._meta.get_field(name).verbose_name).capitalize()
    except FieldDoesNotExist:
        return name.replace("_", " ").capitalize()
