<?php
$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$masterMode=!empty($masterMode);$money=fn($v)=>'R$ '.number_format((float)$v,2,',','.');
$total=(int)($leadStats['total']??0);$converted=(int)($leadStats['converted']??0);$conversion=$total?round($converted/$total*100,1):0;$pipeline=(float)($leadStats['pipeline']??0);
$appUrl=rtrim((string)((require __DIR__.'/../../../config/app.php')['url']??''),'/');
?>
<section class="commercial-hero"><div><span class="eyebrow">Central de vendas</span><h1><?=$masterMode?'Comercial da plataforma':'Olá, '.$e(\App\Core\Auth::user()['name']??'Comercial')?></h1><p>Priorize oportunidades, acompanhe retornos e transforme propostas em assinaturas.</p></div><div class="commercial-hero-actions"><a class="btn btn-light" href="/comercial/oportunidades">Abrir oportunidades<?php if(!empty($leadStats['overdue'])):?><span class="badge text-bg-danger ms-1"><?=(int)$leadStats['overdue']?></span><?php endif;?></a><button class="btn btn-warning" type="button" data-open-proposal>+ Nova proposta</button></div></section>
<?php if(isset($_GET['proposta'])):?><div class="alert alert-success">Proposta criada. O link está pronto para compartilhar na lista de propostas.</div><?php endif;?>
<div class="commercial-kpis">
<?php foreach([['Pipeline',$money($pipeline),'Oportunidades abertas','primary'],['Conversão',$conversion.'%',$converted.' de '.$total.' oportunidades','success'],['Em atendimento',(int)($leadStats['in_service']??0),'Contatos em andamento','info'],['SLA vencido',(int)($leadStats['overdue']??0),'Precisam de ação agora',!empty($leadStats['overdue'])?'danger':'success'],['Comissão projetada',$money($stats['projected']??0),'Aguardando validação','warning'],['Comissão validada',$money($stats['approved']??0),'Aprovada ou paga','success']] as $m):?><article class="commercial-kpi"><span><?=$e($m[0])?></span><strong><?=$e($m[1])?></strong><small><?=$e($m[2])?></small><i class="bg-<?=$e($m[3])?>"></i></article><?php endforeach;?>
</div>
<div class="row g-4 mb-4"><div class="col-xl-7"><section class="card h-100"><div class="card-header d-flex justify-content-between align-items-center"><div><strong>Próximas ações</strong><small class="d-block text-secondary">O que merece sua atenção primeiro.</small></div><a href="/comercial/oportunidades">Ver CRM</a></div><div class="list-group list-group-flush">
<?php foreach($nextLeads as $l):$late=!empty($l['contact_deadline_at'])&&strtotime($l['contact_deadline_at'])<time()&&in_array($l['status'],['new','in_service'],true);?><article class="list-group-item commercial-next"><div class="lead-avatar"><?=mb_strtoupper(mb_substr((string)$l['name'],0,1))?></div><div><strong><?=$e($l['name'])?></strong><small><?=$e($l['business_type'])?><?php if(!empty($l['assigned_name'])):?> · <?=$e($l['assigned_name'])?><?php endif;?></small><span><?=$late?'SLA vencido':(!empty($l['next_contact_at'])?'Retorno '.date('d/m H:i',strtotime($l['next_contact_at'])):'Aguardando ação')?></span></div><div class="commercial-next-actions"><a class="btn btn-sm btn-success" target="_blank" rel="noopener" href="https://wa.me/55<?=preg_replace('/\D/','',(string)$l['phone'])?>">WhatsApp</a><a class="btn btn-sm btn-outline-primary" href="/comercial/oportunidades#lead-<?=(int)$l['id']?>">Abrir</a></div></article><?php endforeach;?>
<?php if(!$nextLeads):?><div class="empty-state">Nenhuma oportunidade pendente. Excelente trabalho.</div><?php endif;?></div></section></div>
<div class="col-xl-5"><section class="card h-100"><div class="card-header"><strong>Funil comercial</strong><small class="d-block text-secondary">Distribuição atual das oportunidades.</small></div><div class="card-body commercial-funnel"><?php foreach([['Novos','new_count'],['Em atendimento','in_service'],['Contatados','contacted'],['Qualificados','qualified'],['Convertidos','converted']] as $f):$n=(int)($leadStats[$f[1]]??0);$pct=$total?max(3,round($n/$total*100)):0;?><div><span><?=$e($f[0])?><b><?=$n?></b></span><div><i style="width:<?=$pct?>%"></i></div></div><?php endforeach;?></div></section></div></div>
<?php if(!$masterMode):?><section class="card mb-4 referral-card"><div class="card-body"><div><strong>Seu link de indicação</strong><small>Comissão: <?=number_format((float)$profile['commission_percent'],2,',','.')?>% · desconto permitido: <?=number_format((float)$profile['max_discount_percent'],2,',','.')?>%</small></div><div class="input-group"><input class="form-control" value="<?=$e($referralUrl)?>" readonly id="referral-link"><button class="btn btn-outline-primary" type="button" data-copy="#referral-link">Copiar</button><button class="btn btn-success" type="button" data-share-link="#referral-link">Compartilhar</button></div></div></section><?php endif;?>
<section class="card mb-4" id="proposal-builder"><div class="card-header d-flex justify-content-between"><div><strong>Montar proposta personalizada</strong><small class="d-block text-secondary">Preço, módulos e benefícios em um único fluxo.</small></div><span class="badge text-bg-light">Oferta privada</span></div><div class="card-body"><form method="post" action="<?=$masterMode?'/master/comercial/propostas':'/comercial/propostas'?>" class="row g-3" data-proposal-form><?=\App\Core\CSRF::field()?>
<div class="col-md-4"><label class="form-label">Nome da proposta</label><input class="form-control" name="title" required placeholder="Proposta Studio Aurora"></div><div class="col-md-4"><label class="form-label">Cliente</label><input class="form-control" name="customer_name" placeholder="Nome do responsável"></div><div class="col-md-4"><label class="form-label">E-mail</label><input class="form-control" type="email" name="customer_email" placeholder="cliente@empresa.com.br"></div>
<div class="col-md-4"><label class="form-label">Plano base <span class="text-secondary">(opcional)</span></label><select class="form-select" name="plan_id" data-plan-base><option value="" data-price="" data-trial="14">Criar plano do zero</option><?php foreach($plans as $p):?><option value="<?=(int)$p['id']?>" data-price="<?=$e($p['monthly_price'])?>" data-trial="<?=(int)$p['trial_days']?>"><?=$e($p['name'])?> · <?=$money($p['monthly_price'])?></option><?php endforeach;?></select><div class="form-text">Use um plano existente como referência ou deixe sem plano base.</div></div><div class="col-md-4"><label class="form-label">Nome do plano privado</label><input class="form-control" name="custom_plan_name" required placeholder="Premium Personalizado"></div><div class="col-md-2"><label class="form-label">Valor mensal</label><div class="input-group"><span class="input-group-text">R$</span><input class="form-control" name="custom_price" inputmode="decimal" required data-custom-price></div><div class="form-text" data-discount-preview></div></div><div class="col-md-2"><label class="form-label">Teste grátis</label><input class="form-control" type="number" min="0" max="90" name="trial_days" value="14" data-trial-days></div>
<div class="col-12"><div class="d-flex justify-content-between"><label class="form-label">Módulos liberados</label><button class="btn btn-sm btn-link" type="button" data-toggle-modules>Selecionar todos</button></div><div class="module-selector"><?php foreach($modules as $m):?><label><input class="form-check-input" type="checkbox" name="modules[]" value="<?=(int)$m['id']?>"><span><strong><?=$e($m['name'])?></strong><small><?=$e($m['description'])?></small></span></label><?php endforeach;?></div></div>
<div class="col-md-7"><label class="form-label">Benefícios exibidos</label><textarea class="form-control" rows="4" name="included_features[]" placeholder="Um benefício por linha"></textarea></div><div class="col-md-5"><label class="form-label">Observações comerciais</label><textarea class="form-control" rows="4" name="notes" placeholder="Condições combinadas com o cliente"></textarea></div><div class="col-12 d-flex justify-content-between align-items-center"><small class="text-secondary">A proposta expira automaticamente em 30 dias.</small><button class="btn btn-primary btn-lg">Gerar proposta e link privado</button></div></form></div></section>
<div class="row g-4"><div class="col-xl-8"><section class="card h-100"><div class="card-header"><strong>Propostas recentes</strong></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Proposta</th><?php if($masterMode):?><th>Responsável</th><?php endif;?><th>Preço</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($proposals as $p):?><tr><td><strong><?=$e($p['title'])?></strong><small class="d-block text-secondary"><?=$e($p['customer_name']?:$p['plan_name'])?></small></td><?php if($masterMode):?><td><?=$e($p['commercial_name']??'Master')?></td><?php endif;?><td><?=$money($p['final_price'])?></td><td><span class="badge commercial-status status-<?=$e($p['status'])?>"><?=$e(['draft'=>'Rascunho','sent'=>'Enviada','viewed'=>'Visualizada','converted'=>'Convertida','expired'=>'Expirada','cancelled'=>'Cancelada'][$p['status']]??$p['status'])?></span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" target="_blank" href="/proposta/<?=$e($p['public_token'])?>">Abrir</a><button class="btn btn-sm btn-light" type="button" data-copy-value="<?=$e($appUrl.'/proposta/'.$p['public_token'])?>">Copiar link</button></td></tr><?php endforeach;?><?php if(!$proposals):?><tr><td colspan="6"><div class="empty-state">Nenhuma proposta criada.</div></td></tr><?php endif;?></tbody></table></div></section></div>
<div class="col-xl-4"><section class="card h-100"><div class="card-header"><strong>Comissões recentes</strong></div><div class="list-group list-group-flush"><?php foreach(array_slice($commissions,0,8) as $c):?><div class="list-group-item d-flex justify-content-between"><span><strong><?=$e($c['tenant_name'])?></strong><small class="d-block text-secondary"><?=$e(['projected'=>'Projetada','approved'=>'Validada','reversed'=>'Estornada','paid'=>'Paga'][$c['status']]??$c['status'])?></small></span><strong><?=$money($c['commission_amount'])?></strong></div><?php endforeach;?><?php if(!$commissions):?><div class="empty-state">Nenhuma comissão registrada.</div><?php endif;?></div></section></div></div>
<script src="/public/assets/js/commercial-experience.js?v=20260813"></script>
