<?php
$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$labels=['new'=>'Novo','in_service'=>'Em atendimento','contacted'=>'Contatado','qualified'=>'Qualificado','converted'=>'Convertido','lost'=>'Perdido'];$userId=(int)(\App\Core\Auth::user()['id']??0);
$filters=['all'=>count($leads)];foreach(array_keys($labels) as $s)$filters[$s]=count(array_filter($leads,fn($l)=>$l['status']===$s));
?>
<div class="section-heading"><div><div class="eyebrow">CRM comercial</div><h1>Oportunidades</h1><p class="text-secondary mb-0">Atenda primeiro quem está mais perto de comprar.</p></div><a class="btn btn-light" href="<?=$masterMode?'/master/comercial':'/comercial'?>">← Painel comercial</a></div>
<?php if(isset($_GET['salvo'])):?><div class="alert alert-success">Oportunidade atualizada com sucesso.</div><?php endif;?>
<div class="lead-toolbar"><div class="lead-filters"><?php foreach(['all'=>'Todos']+$labels as $key=>$label):?><button type="button" class="<?=$key==='all'?'active':''?>" data-lead-filter="<?=$e($key)?>"><?=$e($label)?> <b><?=(int)$filters[$key]?></b></button><?php endforeach;?></div><div class="lead-search"><span>⌕</span><input type="search" placeholder="Buscar nome, segmento, telefone ou e-mail" data-lead-search></div></div>
<div class="lead-board"><?php foreach($leads as $l):$mine=(int)($l['assigned_to']??0)===$userId;$canEdit=$masterMode||$mine;$overdue=!empty($l['contact_deadline_at'])&&strtotime($l['contact_deadline_at'])<time()&&in_array($l['status'],['new','in_service'],true);?><article class="lead-card <?=$overdue?'is-overdue':''?>" id="lead-<?=(int)$l['id']?>" data-lead-card data-status="<?=$e($l['status'])?>" data-search="<?=$e(mb_strtolower($l['name'].' '.$l['business_type'].' '.$l['phone'].' '.$l['email']))?>"><header><div class="lead-avatar"><?=mb_strtoupper(mb_substr((string)$l['name'],0,1))?></div><div><h2><?=$e($l['name'])?></h2><span><?=$e($l['business_type'])?></span></div><span class="badge text-bg-<?=$overdue?'danger':($l['status']==='new'?'warning':($l['status']==='converted'?'success':'primary'))?>"><?=$overdue?'SLA vencido':$e($labels[$l['status']]??$l['status'])?></span></header>
<div class="lead-meta"><span>Recebido <b><?=date('d/m H:i',strtotime($l['created_at']))?></b></span><span>Potencial <b><?=$l['estimated_value']!==null?'R$ '.number_format((float)$l['estimated_value'],2,',','.'):'A definir'?></b></span><?php if($l['next_contact_at']):?><span>Retorno <b><?=date('d/m H:i',strtotime($l['next_contact_at']))?></b></span><?php endif;?></div>
<div class="lead-contact-actions"><a class="btn btn-success" href="https://wa.me/55<?=preg_replace('/\D/','',(string)$l['phone'])?>" target="_blank" rel="noopener">WhatsApp</a><a class="btn btn-outline-primary" href="mailto:<?=$e($l['email'])?>">E-mail</a><button class="btn btn-light" type="button" data-copy-value="<?=$e($l['phone'])?>">Copiar número</button></div>
<?php if(empty($l['assigned_to'])):?><form method="post" action="/comercial/oportunidades/<?=(int)$l['id']?>/atender"><?=\App\Core\CSRF::field()?><button class="btn btn-primary w-100">Assumir atendimento</button></form><?php else:?><div class="lead-owner">Responsável: <strong><?=$e($l['assigned_name'])?></strong></div><?php if($canEdit):?><details class="lead-editor"><summary>Atualizar oportunidade</summary><form method="post" action="/comercial/oportunidades/<?=(int)$l['id']?>/status" class="row g-2 mt-2"><?=\App\Core\CSRF::field()?><div class="col-md-4"><label class="form-label">Etapa</label><select class="form-select" name="status"><?php foreach(['in_service','contacted','qualified','converted','lost'] as $s):?><option value="<?=$s?>" <?=$l['status']===$s?'selected':''?>><?=$e($labels[$s])?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Próximo contato</label><input class="form-control" type="datetime-local" name="next_contact_at" value="<?=$l['next_contact_at']?date('Y-m-d\TH:i',strtotime($l['next_contact_at'])):''?>"></div><div class="col-md-4"><label class="form-label">Valor estimado</label><input class="form-control" name="estimated_value" inputmode="decimal" value="<?=$e($l['estimated_value'])?>"></div><div class="col-md-6"><label class="form-label">Anotação</label><textarea class="form-control" rows="2" name="notes"><?=$e($l['notes'])?></textarea></div><div class="col-md-6"><label class="form-label">Motivo da perda</label><input class="form-control" name="loss_reason" value="<?=$e($l['loss_reason'])?>"></div><div class="col-12 text-end"><button class="btn btn-primary">Salvar acompanhamento</button></div></form>
<form method="post" action="/comercial/oportunidades/<?=(int)$l['id']?>/transferir" class="input-group mt-2"><?=\App\Core\CSRF::field()?><select class="form-select" name="target_user_id" required><option value="">Transferir atendimento...</option><?php foreach($targets as $t):if((int)$t['id']===(int)$l['assigned_to'])continue;?><option value="<?=(int)$t['id']?>"><?=$e($t['name'])?> · <?=$t['role_slug']==='master'?'Master':'Comercial'?></option><?php endforeach;?></select><button class="btn btn-outline-secondary">Transferir</button></form></details><?php endif;?><?php endif;?></article><?php endforeach;?></div>
<div class="empty-state" data-lead-empty <?=$leads?'hidden':''?>>Nenhuma oportunidade encontrada neste filtro.</div>
<script src="/public/assets/js/commercial-experience.js?v=20260813"></script>
