<div class="section-heading"><div><div class="eyebrow">Administração da plataforma</div><h1>Painel da plataforma</h1><p class="text-secondary mb-0">Clientes, assinaturas, previsão de receita, suporte e operação do negócio em um só lugar.</p></div><div class="d-flex gap-2 flex-wrap"><a class="btn btn-outline-primary" href="/master/tenants/create">+ Nova empresa</a><a class="btn btn-primary" href="/master/plans/create">+ Novo plano</a></div></div>
<div class="row g-3 mb-4">
<?php foreach([
['Clientes da plataforma',$metrics['tenants'], $metrics['active_subscriptions'].' assinatura(s) ativa(s)'],
['Clientes finais cadastrados',$metrics['end_customers'], $metrics['new_30d'].' nova(s) empresa(s) em 30 dias'],
['Receita recorrente mensal','R$ '.number_format((float)$metrics['mrr'],2,',','.'),'Planos + módulos adicionais'],
['Projeção anual','R$ '.number_format((float)$metrics['arr'],2,',','.'),'Com base na receita recorrente atual'],
['Previsão em 30 dias','R$ '.number_format((float)$metrics['forecast_30d'],2,',','.'),'Cobranças previstas nas assinaturas atuais'],
['Valor médio por cliente','R$ '.number_format((float)$metrics['arpa'],2,',','.'),'Receita mensal média por assinatura ativa'],
['Recebido no mês','R$ '.number_format((float)$metrics['received_month'],2,',','.'),'Somente produção e receitas manuais'],
['Potencial dos testes grátis','R$ '.number_format((float)$metrics['trial_potential_mrr'],2,',','.'),$metrics['trials'].' empresa(s) em teste']
] as $card):?><div class="col-6 col-xl-3"><div class="card metric-card h-100"><div class="card-body"><div class="metric-label"><?=htmlspecialchars($card[0])?></div><div class="metric-value"><?=is_numeric($card[1])?number_format((float)$card[1],0,',','.'):$card[1]?></div><small><?=htmlspecialchars($card[2])?></small></div></div></div><?php endforeach;?>
</div>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="card"><div class="card-body"><div class="metric-label">Módulos adicionais</div><div class="metric-value">R$ <?=number_format((float)$metrics['addon_mrr'],2,',','.')?></div><small>Receita mensal recorrente adicional</small></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><div class="metric-label">A receber</div><div class="metric-value">R$ <?=number_format((float)$metrics['receivable'],2,',','.')?></div><small>Faturas pendentes ou vencidas</small></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><div class="metric-label">Cancelamento em 30 dias</div><div class="metric-value"><?=number_format((float)$metrics['churn_30d'],1,',','.')?>%</div><small>Indicador aproximado de perda de assinaturas</small></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><div class="metric-label">Solicitações de módulos</div><div class="metric-value"><?=(int)$metrics['module_requests_pending']?></div><small>Aguardando análise comercial</small></div></div></div></div>
<div class="row g-4 mb-4"><div class="col-lg-7"><div class="card h-100"><div class="card-header d-flex justify-content-between"><strong>Clientes recentes</strong><a href="/master/tenants">Ver todos</a></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Empresa</th><th>Plano</th><th>Assinatura</th><th>Próximo evento</th><th></th></tr></thead><tbody><?php foreach($tenants as $t):?><tr><td><strong><?=htmlspecialchars($t['name'])?></strong><div class="small text-secondary">/a/<?=htmlspecialchars($t['public_short_code']?:$t['public_slug'])?></div></td><td><?=htmlspecialchars($t['plan_name']??'—')?></td><td><?=htmlspecialchars(['trial'=>'Teste grátis','active'=>'Ativa','past_due'=>'Em atraso','suspended'=>'Suspensa','cancelled'=>'Cancelada'][$t['subscription_status']??'']??($t['subscription_status']??$t['status']))?></td><td><?=!empty($t['trial_ends_at'])?date('d/m/Y',strtotime($t['trial_ends_at'])):(!empty($t['next_billing_at'])?date('d/m/Y',strtotime($t['next_billing_at'])):'—')?></td><td><a class="btn btn-sm btn-outline-primary" href="/master/tenants/<?=(int)$t['id']?>">Abrir</a></td></tr><?php endforeach;?></tbody></table></div></div></div><div class="col-lg-5"><div class="card h-100"><div class="card-header d-flex justify-content-between"><strong>Chamados que precisam de atenção</strong><a href="/master/support">Central de suporte</a></div><div class="list-group list-group-flush"><?php foreach($tickets as $t):?><a class="list-group-item list-group-item-action" href="/support/<?=(int)$t['id']?>"><div class="d-flex justify-content-between"><strong><?=htmlspecialchars($t['tenant_name'])?></strong><span class="badge <?=$t['remote_access_allowed']?'text-bg-success':'text-bg-light'?>"><?=$t['remote_access_allowed']?'Acesso autorizado':'Sem acesso'?></span></div><div><?=htmlspecialchars($t['subject'])?></div><small class="text-secondary"><?=htmlspecialchars($t['protocol'])?> · <?=htmlspecialchars($t['priority'])?></small></a><?php endforeach;?><?php if(!$tickets):?><div class="empty-state">Nenhum chamado pendente.</div><?php endif;?></div></div></div></div>
<div class="row g-4"><div class="col-lg-6"><div class="card h-100"><div class="card-header d-flex justify-content-between"><strong>Solicitações de módulos</strong><a href="/master/solicitacoes-modulos">Ver todas</a></div><div class="list-group list-group-flush"><?php foreach($moduleRequests as $r):?><a class="list-group-item list-group-item-action" href="/master/solicitacoes-modulos"><div class="d-flex justify-content-between"><strong><?=htmlspecialchars($r['tenant_name'])?></strong><span>R$ <?=number_format((float)$r['quoted_monthly_price'],2,',','.')?>/mês</span></div><div><?=htmlspecialchars($r['module_name'])?></div><small class="text-secondary"><?=date('d/m/Y H:i',strtotime($r['created_at']))?></small></a><?php endforeach;?><?php if(!$moduleRequests):?><div class="empty-state">Nenhuma solicitação pendente.</div><?php endif;?></div></div></div><div class="col-lg-6"><div class="card h-100"><div class="card-header"><strong>Indicadores financeiros</strong></div><div class="card-body"><div class="d-flex justify-content-between py-2 border-bottom"><span>Receita recorrente dos planos</span><strong>R$ <?=number_format((float)$metrics['plan_mrr'],2,',','.')?></strong></div><div class="d-flex justify-content-between py-2 border-bottom"><span>Receita recorrente de módulos</span><strong>R$ <?=number_format((float)$metrics['addon_mrr'],2,',','.')?></strong></div><div class="d-flex justify-content-between py-2 border-bottom"><span>Despesas pagas no mês</span><strong>R$ <?=number_format((float)$metrics['expenses_month'],2,',','.')?></strong></div><div class="d-flex justify-content-between py-2"><span>Resultado realizado no mês</span><strong>R$ <?=number_format((float)$metrics['net_month'],2,',','.')?></strong></div><a class="btn btn-outline-primary w-100 mt-3" href="/master/financeiro">Abrir financeiro da plataforma</a></div></div></div></div>
