# Generated by Django 5.2.17 on 2026-09-21 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_normalize_index_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('database', 'Banco'), ('files', 'Arquivos'), ('full', 'Completo')], max_length=16)),
                ('scope', models.CharField(default='database', max_length=24)),
                ('status', models.CharField(choices=[('running', 'Executando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('expired', 'Expirado')], max_length=16)),
                ('destination', models.CharField(max_length=190)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('encrypted', models.BooleanField(default=False)),
                ('encryption_method', models.CharField(blank=True, max_length=60)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CronAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_key', models.CharField(max_length=190)),
                ('channel', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=12)),
                ('message', models.CharField(max_length=500)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackupVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(default='integrity', max_length=16)),
                ('status', models.CharField(max_length=12)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('restored_database', models.CharField(blank=True, max_length=190)),
                ('verified_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='operations.backup')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backup_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CronHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_key', models.CharField(max_length=80)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=12)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('host_name', models.CharField(blank=True, max_length=190)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cron_key', 'status', 'finished_at'], name='ops_cron_health_idx')],
                'constraints': [models.UniqueConstraint(fields=('cron_key', 'started_at'), name='uq_cron_heartbeat')],
            },
        ),
        migrations.CreateModel(
            name='HomologationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('passed', 'Aprovado'), ('warning', 'Aviso'), ('blocked', 'Bloqueado')], max_length=12)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('results', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homologation_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformOperationSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('backup_retention_days', models.PositiveSmallIntegerField(default=30)),
                ('backup_include_uploads', models.BooleanField(default=True)),
                ('backup_encrypt', models.BooleanField(default=True)),
                ('backup_before_update', models.BooleanField(default=True)),
                ('lead_retention_days', models.PositiveSmallIntegerField(default=730)),
                ('critical_alert_email', models.EmailField(blank=True, max_length=254)),
                ('critical_alerts_enabled', models.BooleanField(default=False)),
                ('cron_stale_minutes', models.PositiveSmallIntegerField(default=15)),
                ('disk_min_free_mb', models.PositiveIntegerField(default=1024)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protocol', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=190)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=12)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('in_progress', 'Em andamento'), ('waiting_user', 'Aguardando usuário'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], db_index=True, default='open', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_assignments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to='support/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='operations.supportticket')),
            ],
        ),
        migrations.CreateModel(
            name='SupportAccessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_access_sessions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_access_sessions', to='tenants.tenant')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_sessions', to='operations.supportticket')),
            ],
        ),
        migrations.CreateModel(
            name='OperationalIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Aviso'), ('critical', 'Crítico')], max_length=12)),
                ('title', models.CharField(max_length=190)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('acknowledged', 'Reconhecido'), ('resolved', 'Resolvido')], db_index=True, default='open', max_length=16)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'severity', 'last_seen_at'], name='ops_incident_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['tenant', 'status'], name='ops_ticket_tenant_idx'),
        ),
    ]
