from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies=[
        ("operations","0003_billing_support_platform_setting"),
        ("tenants","0006_merge_onboarding_demo"),
    ]
    operations=[
        migrations.CreateModel(
            name="LegacyRuntimeJob",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("type",models.CharField(max_length=100)),
                ("payload_encrypted",models.TextField()),
                ("status",models.CharField(db_index=True,max_length=16)),
                ("attempts",models.PositiveSmallIntegerField(default=0)),
                ("available_at",models.DateTimeField(db_index=True)),
                ("locked_at",models.DateTimeField(blank=True,null=True)),
                ("failed_at",models.DateTimeField(blank=True,null=True)),
                ("last_error",models.CharField(blank=True,max_length=500)),
                ("created_at",models.DateTimeField()),
                ("updated_at",models.DateTimeField()),
                ("tenant",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="legacy_runtime_jobs",to="tenants.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="LegacyFailedJobArchive",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("type",models.CharField(max_length=100)),
                ("payload_encrypted",models.TextField()),
                ("status",models.CharField(db_index=True,max_length=16)),
                ("attempts",models.PositiveSmallIntegerField(default=0)),
                ("available_at",models.DateTimeField()),
                ("locked_at",models.DateTimeField(blank=True,null=True)),
                ("failed_at",models.DateTimeField(blank=True,null=True)),
                ("created_at",models.DateTimeField()),
                ("updated_at",models.DateTimeField()),
                ("tenant",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="legacy_failed_jobs",to="tenants.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="LegacyMigrationRecord",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("migration",models.CharField(db_index=True,max_length=190)),
                ("batch",models.PositiveIntegerField()),
                ("executed_at",models.DateTimeField()),
            ],
            options={"ordering":["id"]},
        ),
        migrations.AddIndex(
            model_name="legacyruntimejob",
            index=models.Index(fields=["status","available_at"],name="ops_legacy_job_status_idx"),
        ),
        migrations.AddIndex(
            model_name="legacyruntimejob",
            index=models.Index(fields=["type","created_at"],name="ops_legacy_job_type_idx"),
        ),
        migrations.AddIndex(
            model_name="legacyfailedjobarchive",
            index=models.Index(fields=["status","failed_at"],name="ops_legacy_fail_status_idx"),
        ),
    ]
