# Generated by Django 5.2.17 on 2026-09-23 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_legacy_runtime_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportaccesssession',
            name='impersonated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonated_support_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='app_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='browser_context',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='error_id',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='remote_access_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='remote_access_allowed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='remote_access_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='source_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
