# Generated by Django 5.2.17 on 2026-10-05 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_smtp_dkim_selector'),
        ('tenants', '0011_tenant_archive_snapshot_tenant_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TenantActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_active_at', models.DateTimeField()),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operation_activity', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RuntimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True)),
                ('component', models.CharField(max_length=30)),
                ('operation', models.CharField(max_length=120)),
                ('status_code', models.PositiveIntegerField(default=200)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['component', 'created_at'], name='ops_runtime_component_idx')],
            },
        ),
    ]
