<h1 class="h3 mb-4">Segurança da conta</h1><?php if($message):?><div class="alert alert-info"><?=htmlspecialchars($message,ENT_QUOTES,'UTF-8')?></div><?php endif;?><?php if(!empty($security['must_change_password'])||isset($_GET['password_required'])):?><div class="alert alert-warning"><strong>Troca de senha obrigatória.</strong> Você entrou com uma senha temporária. Crie sua senha definitiva antes de continuar.</div><?php endif;?><?php if($password_error):?><div class="alert alert-danger"><?=htmlspecialchars($password_error,ENT_QUOTES,'UTF-8')?></div><?php endif;?>
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><h2 class="h5">Alterar minha senha</h2><p class="text-secondary">Disponível para empresa, profissional, Master, Suporte e Comercial.</p><form method="post" action="/security/password" class="row g-3"><?php echo \App\Core\CSRF::field();?><div class="col-md-4"><label class="form-label">Senha atual</label><input class="form-control" type="password" name="current_password" autocomplete="current-password" required></div><div class="col-md-4"><label class="form-label">Nova senha</label><input class="form-control" type="password" name="new_password" minlength="12" autocomplete="new-password" required><small class="text-secondary">12+ caracteres, maiúscula, minúscula, número e símbolo.</small></div><div class="col-md-4"><label class="form-label">Confirmar nova senha</label><input class="form-control" type="password" name="new_password_confirmation" minlength="12" autocomplete="new-password" required></div><div class="col-12"><button class="btn btn-primary">Alterar senha</button></div></form></div></div>
<div class="row g-4"><div class="col-lg-6"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Confirmação de e-mail</h2><p>Status: <span class="badge text-bg-<?=$security['email_verified_at']?'success':'warning'?>"><?=$security['email_verified_at']?'Confirmado':'Pendente'?></span></p><?php if(!$security['email_verified_at']):?><form method="post" action="/security/email/send"><?=\App\Core\CSRF::field()?><button class="btn btn-outline-primary">Enviar confirmação</button></form><?php endif;?></div></div></div>
<div class="col-lg-6"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Autenticação em duas etapas</h2><p>Status: <span class="badge text-bg-<?=$security['two_factor_enabled_at']?'success':'secondary'?>"><?=$security['two_factor_enabled_at']?'Ativa':'Desativada'?></span></p><?php if(!$security['two_factor_enabled_at']&&!$setup_secret):?><form method="post" action="/security/2fa/start"><?=\App\Core\CSRF::field()?><button class="btn btn-primary">Configurar 2FA</button></form><?php elseif($setup_secret):?><p>Adicione manualmente no autenticador:</p><code class="user-select-all"><?=htmlspecialchars($setup_secret,ENT_QUOTES,'UTF-8')?></code><form method="post" action="/security/2fa/confirm" class="mt-3"><?=\App\Core\CSRF::field()?><input class="form-control" name="code" placeholder="Código de 6 dígitos" required><button class="btn btn-success mt-2">Confirmar ativação</button></form><?php endif;?></div></div></div></div>

<?php if(!empty($security['two_factor_enabled_at'])):?>
<div class="card border-0 shadow-sm mt-4"><div class="card-body"><div class="d-flex justify-content-between align-items-start gap-3 flex-wrap"><div><h2 class="h5 mb-1">Dispositivos confiáveis</h2><p class="text-secondary mb-0">Após validar o 2FA, este navegador pode ser lembrado por até <?= (int)($trusted_days??30) ?> dias. A senha continua sendo exigida normalmente.</p></div><?php if(!empty($trusted_devices)):?><form method="post" action="/security/2fa/trusted-devices/revoke-all"><?php echo \App\Core\CSRF::field();?><button class="btn btn-outline-danger btn-sm">Revogar todos</button></form><?php endif;?></div>
<?php if(empty($trusted_devices)):?><div class="alert alert-light border mt-3 mb-0">Nenhum dispositivo confiável ativo. No próximo desafio 2FA, mantenha marcada a opção <strong>Confiar neste dispositivo por 30 dias</strong>.</div><?php else:?><div class="table-responsive mt-3"><table class="table align-middle mb-0"><thead><tr><th>Dispositivo</th><th>Último uso</th><th>Válido até</th><th></th></tr></thead><tbody><?php foreach($trusted_devices as $device):?><tr><td><strong><?=htmlspecialchars((string)($device['device_label']??'Dispositivo'),ENT_QUOTES,'UTF-8')?></strong><?php if(!empty($device['is_current'])):?><span class="badge text-bg-success ms-2">Este dispositivo</span><?php endif;?><div class="small text-secondary"><?=htmlspecialchars((string)($device['ip_address']??''),ENT_QUOTES,'UTF-8')?></div></td><td><?=!empty($device['last_used_at'])?htmlspecialchars(date('d/m/Y H:i',strtotime($device['last_used_at'])),ENT_QUOTES,'UTF-8'):'Ainda não reutilizado'?></td><td><?=htmlspecialchars(date('d/m/Y H:i',strtotime($device['expires_at'])),ENT_QUOTES,'UTF-8')?></td><td class="text-end"><form method="post" action="/security/2fa/trusted-devices/revoke"><?php echo \App\Core\CSRF::field();?><input type="hidden" name="device_id" value="<?= (int)$device['id'] ?>"><button class="btn btn-outline-secondary btn-sm">Revogar</button></form></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
</div></div>
<?php endif;?>
<?php if($recovery_codes):?><div class="alert alert-warning mt-4"><strong>Salve estes códigos agora. Eles serão exibidos uma única vez.</strong><div class="row mt-2"><?php foreach($recovery_codes as $code):?><div class="col-sm-6"><code><?=htmlspecialchars($code,ENT_QUOTES,'UTF-8')?></code></div><?php endforeach;?></div></div><?php endif;?>
