<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){fwrite(STDERR,"CLI only\n");exit(2);}
$dsn=getenv('E2E_MYSQL_DSN')?:'';$user=getenv('E2E_MYSQL_USER')?:'';$pass=getenv('E2E_MYSQL_PASS')?:'';
if($dsn===''){fwrite(STDERR,"BLOCKED: defina E2E_MYSQL_DSN/E2E_MYSQL_USER/E2E_MYSQL_PASS para um banco de homologação.\n");exit(3);}
if(!preg_match('/dbname=([^;]+)/i',$dsn,$m)||!preg_match('/(test|teste|homolog|staging)/i',$m[1])){fwrite(STDERR,"ABORTADO: o banco E2E deve conter test/teste/homolog/staging no nome. Nunca rode este smoke em produção.\n");exit(4);}
try{$pdo=new PDO($dsn,$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);}catch(Throwable $e){fwrite(STDERR,"FAIL database connection: ".$e->getMessage()."\n");exit(1);}
$required=['tenants','users','customers','professionals','professional_availability','services','appointments','products','sales','financial_transactions','support_tickets','login_audit','tenant_schedule_settings','professional_time_off','professional_breaks','customer_packages','customer_memberships','tenant_domains'];$missing=[];foreach($required as $table){$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=:t');$q->execute(['t'=>$table]);if(!(int)$q->fetchColumn())$missing[]=$table;}
if($missing){fwrite(STDERR,"FAIL missing tables: ".implode(', ',$missing)."\n");exit(1);}echo "PASS database connection\nPASS required tables\n";
$columns=['appointments'=>['customer_manage_token_hash','reminder_24h_sent_at','vehicle_id'],'support_tickets'=>['source_url','browser_context','error_id'],'customer_packages'=>['membership_id','financial_transaction_id']];foreach($columns as $table=>$cols){foreach($cols as $col){$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=:t AND column_name=:c');$q->execute(['t'=>$table,'c'=>$col]);if(!(int)$q->fetchColumn()){fwrite(STDERR,"FAIL missing column {$table}.{$col}\n");exit(1);}}}echo "PASS V3 columns\n";
try{$pdo->beginTransaction();$pdo->query('SELECT id,status FROM tenants ORDER BY id DESC LIMIT 1 FOR UPDATE')->fetch();$pdo->rollBack();echo "PASS transaction/row-lock capability\n";}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();fwrite(STDERR,"FAIL transaction/locking: ".$e->getMessage()."\n");exit(1);}exit(0);
