<?php
declare(strict_types=1);
$root=dirname(__DIR__);$errors=[];$ok=[];
$check=static function(bool $cond,string $msg)use(&$errors,&$ok):void{if($cond){$ok[]=$msg;echo "[OK] {$msg}\n";}else{$errors[]=$msg;echo "[ERRO] {$msg}\n";}};
$required=[
'app/Controllers/AutoOperationsController.php','app/Controllers/PublicAutoController.php','app/Controllers/VehicleController.php','app/Services/AutoTenantService.php','app/Services/AutoAvailabilityService.php','app/Views/auto/dashboard.php','app/Views/auto/bays.php','app/Views/auto/jobs.php','app/Views/auto/job.php','app/Views/auto/commands.php','app/Views/auto/command.php','app/Views/auto/crm.php','app/Views/auto/reports.php','app/Views/auto/settings.php','app/Views/public/auto.php','app/Views/public/auto-manage.php','app/Views/public/auto-estimate.php','app/Views/public/auto-delivery.php','app/Views/vehicles/show.php','cron/auto.php','database/migrations/041_applanner_auto_v1.sql'
];foreach($required as $rel)$check(is_file($root.'/'.$rel),'Arquivo presente: '.$rel);
$index=(string)@file_get_contents($root.'/index.php');foreach(['/auto/bays','/auto/bookings/create','/auto/jobs/{id}/checkin','/auto/jobs/{id}/inspection','/auto/jobs/{id}/materials','/auto/jobs/{id}/estimates','/auto/commands/{id}/adjust','/auto/crm','/auto/{slug}','/auto/orcamento/{token}','/auto/entrega/{token}'] as $route)$check(str_contains($index,$route),'Rota presente: '.$route);
$migration=(string)@file_get_contents($root.'/database/migrations/041_applanner_auto_v1.sql');foreach(['auto_service_bays','auto_jobs','auto_job_inspection_items','auto_job_photos','auto_job_material_usage','auto_job_technical_details','auto_estimates','auto_commands','auto_vehicle_maintenance','auto_crm_events','auto_vehicle_package_links'] as $table)$check(str_contains($migration,$table),'Schema Auto contém '.$table);$check(!preg_match('/\b(DROP\s+(?:DATABASE|TABLE)|TRUNCATE\s+TABLE)\b/i',$migration),'Migration Auto sem DROP/TRUNCATE');
$ops=(string)@file_get_contents($root.'/app/Controllers/AutoOperationsController.php');foreach(['PackageService::consumeForAppointment','LoyaltyService::earn','product_stock_movements','financial_transactions','auto_job_material_usage','auto_job_technical_details','auto_delivery_terms'] as $needle)$check(str_contains($ops,$needle),'Operação integrada: '.$needle);
$pub=(string)@file_get_contents($root.'/app/Controllers/PublicAutoController.php');$check(str_contains($pub,'professional_id,service_id')&&str_contains($pub,"NULL,:s"),'Reserva pública Auto não exige profissional');$check(str_contains($pub,'GET_LOCK')&&str_contains($pub,'bayAvailable'),'Reserva pública usa lock + revalidação');$check(str_contains($pub,'customer_can_cancel')&&str_contains($pub,'customer_can_reschedule'),'Auto respeita autoatendimento de cancelamento/remarcação');
$availability=(string)@file_get_contents($root.'/app/Services/AutoAvailabilityService.php');$check(str_contains($availability,'auto_service_bays')&&str_contains($availability,'auto_bay_hours'),'Agenda usa boxes e horários próprios');$check(str_contains($availability,'minimum_notice_minutes')&&str_contains($availability,'maximum_days_ahead'),'Agenda Auto respeita antecedência mínima/máxima');
$vehicles=(string)@file_get_contents($root.'/app/Controllers/VehicleController.php');$check(str_contains($vehicles,'auto_vehicle_profiles')&&str_contains($vehicles,'auto_vehicle_maintenance'),'Histórico técnico é vinculado ao veículo');
$package=(string)@file_get_contents($root.'/app/Services/PackageService.php');$check(str_contains($package,'auto_vehicle_package_links'),'Pacotes podem ser vinculados ao veículo');
$cron=(string)@file_get_contents($root.'/cron/auto.php');$check(str_contains($cron,'auto_crm_events')&&str_contains($cron,'auto_estimates'),'Cron Auto cobre CRM e expiração de orçamentos');
if($errors){echo "\nauto v1 smoke: FALHOU (".count($errors).")\n";exit(1);}echo "\nauto v1 smoke: OK (".count($ok)." verificações)\n";
