<?php use App\Core\Authorization;$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$slug=$tenant['public_slug']?:$tenant['public_short_code'];?>
<div class="sports-head"><div><span class="sports-kicker">APPLANNER ARENA</span><h1>Gestão da Arena</h1><p>Quadras, agenda, reservas, rachas, mensalistas, comandas e operação esportiva em um só lugar.</p></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-primary" href="/arena/<?=$e($slug)?>" target="_blank" rel="noopener">Abrir página pública ↗</a><?php if(Authorization::allows('sports.reservations.manage')):?><a class="btn btn-primary" href="/sports/reservations">+ Nova reserva</a><?php endif;?></div></div>
<div class="sports-stats"><article><span>Quadras/Espaços ativos</span><strong><?=(int)$stats['courts']?></strong></article><article><span>Reservas hoje</span><strong><?=(int)$stats['today']?></strong></article><article><span>Aguardando pagamento</span><strong><?=(int)$stats['pending']?></strong></article><article><span>Reservado no mês</span><strong>R$ <?=number_format((float)$stats['month'],2,',','.')?></strong></article></div>
<div class="sports-actions">
<a href="/sports/agenda">▦ <span><strong>Agenda visual</strong><small>Dia/semana por quadra, com ocupação e horários livres</small></span></a>
<a href="/sports/courts">◫ <span><strong>Quadras/Espaços</strong><small>Disponibilidade, intervalos, modalidades, preços e bloqueios</small></span></a>
<a href="/sports/reservations">📅 <span><strong>Reservas</strong><small>Clientes, sinal e recebimentos sem vínculo com profissional</small></span></a>
<?php if(Authorization::allows('sports.games.manage')):?><a href="/sports/games">⚽ <span><strong>Rachas</strong><small>Jogadores, vagas e divisão de pagamento</small></span></a><?php endif;?>
<?php if(Authorization::allows('sports.memberships.manage')):?><a href="/sports/memberships">↻ <span><strong>Mensalistas</strong><small>Horários fixos e recorrência com tratamento de conflitos</small></span></a><?php endif;?>
<?php if(Authorization::allows('sports.commands.manage')):?><a href="/sports/commands">▤ <span><strong>Comandas</strong><small>Consumo, produtos, estoque e fechamento</small></span></a><?php endif;?>
<?php if(Authorization::allows('sports.reports.view')):?><a href="/sports/reports">↗ <span><strong>Relatórios e CRM</strong><small>Ocupação, receita, ticket e recorrência de clientes</small></span></a><?php endif;?>
<?php if(Authorization::allows('sports.manage')):?><a href="/sports/arena-settings">⚙ <span><strong>Configurações da Arena</strong><small>Comodidades, regras públicas e política de cancelamento</small></span></a><?php endif;?>
</div>
<section class="card border-0 shadow-sm"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Próximas reservas</h2><a href="/sports/agenda">Ver agenda</a></div><?php if(!$upcoming):?><div class="sports-empty">Nenhuma reserva futura. Compartilhe a página pública da Arena para começar.</div><?php else:?><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Data</th><th>Quadra/Espaço</th><th>Cliente</th><th>Valor</th><th>Status</th></tr></thead><tbody><?php foreach($upcoming as $r):?><tr><td><strong><?=date('d/m/Y',strtotime($r['starts_at']))?></strong><br><small><?=date('H:i',strtotime($r['starts_at']))?>–<?=date('H:i',strtotime($r['ends_at']))?></small></td><td><?=$e($r['court_name'])?><br><small><?=$e($r['modality_name']??'')?></small></td><td><?=$e($r['customer_name'])?></td><td>R$ <?=number_format((float)$r['total_amount'],2,',','.')?></td><td><span class="sports-status status-<?=$e($r['status'])?>"><?=$e(str_replace('_',' ',$r['status']))?></span></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div></section>
