<?php
use App\Core\{CSRF,Authorization};
$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$status=['pending_payment'=>'Aguardando pagamento','confirmed'=>'Confirmada','completed'=>'Finalizada','cancelled'=>'Cancelada','no_show'=>'Não compareceu'];
$payments=['not_required'=>'Não exigido','pending'=>'Pendente','signal_paid'=>'Sinal pago','paid'=>'Pago integral','refunded'=>'Reembolsado','cancelled'=>'Cancelado'];
$finance=['not_required'=>'Não exigido','pending'=>'Pendente','partial'=>'Sinal pago','paid'=>'Pago','expired'=>'Expirado','cancelled'=>'Cancelado','refunded'=>'Reembolsado','partially_refunded'=>'Reembolso parcial','failed'=>'Falhou'];
$canManage=Authorization::allows('sports.reservations.manage');
?>
<div class="sports-head"><div><span class="sports-kicker">APPLANNER ARENA</span><h1>Reservas</h1><p>A reserva pertence diretamente à quadra/espaço. Nenhum profissional é exigido.</p></div><div class="d-flex flex-wrap gap-2"><a href="/sports/agenda" class="btn btn-outline-primary">Agenda visual</a><a href="/sports/courts" class="btn btn-outline-secondary">Quadras/Espaços</a></div></div>
<?php if(isset($_GET['created'])):?><div class="alert alert-success">Reserva criada com sucesso.</div><?php endif;?>
<?php if(isset($_GET['updated'])):?><div class="alert alert-success">Reserva atualizada.</div><?php endif;?><?php if(isset($_GET['rescheduled'])):?><div class="alert alert-success">Reserva remarcada com revalidação de disponibilidade.</div><?php endif;?>
<div class="row g-4">
<?php if($canManage):?><div class="col-xl-4"><form class="card border-0 shadow-sm sports-sticky" method="post" action="/sports/reservations"><div class="card-body"><?=CSRF::field()?><h2 class="h5">Nova reserva</h2><p class="small text-secondary">Para horários fixos recorrentes, prefira <a href="/sports/memberships">Mensalistas</a>.</p>
<?php if(!$courts):?><div class="alert alert-warning mb-0">Cadastre uma quadra/espaço antes de criar reservas.</div><?php else:?>
<label class="form-label">Quadra/Espaço</label><select class="form-select mb-2" name="court_id" id="arenaReservationCourt" required><?php foreach($courts as $c):?><option value="<?=(int)$c['id']?>" data-min="<?=(int)$c['minimum_minutes']?>" data-max="<?=(int)$c['maximum_minutes']?>"><?=$e($c['name'])?></option><?php endforeach;?></select>
<label class="form-label">Modalidade</label><select class="form-select mb-2" name="modality_id" id="arenaReservationModality" required><?php foreach($modalities as $m):?><option value="<?=(int)$m['id']?>" data-court="<?=(int)$m['court_id']?>"><?=$e($m['name'])?></option><?php endforeach;?></select>
<label class="form-label">Data e horário</label><input class="form-control mb-2" type="datetime-local" name="starts_at" required>
<div class="row g-2"><div class="col-6"><label class="form-label">Duração</label><input class="form-control" type="number" name="duration_minutes" value="60" min="15" step="15"></div><div class="col-6"><label class="form-label">Repetir</label><div class="input-group"><input class="form-control" type="number" name="repeat_weeks" value="1" min="1" max="52"><span class="input-group-text">sem.</span></div></div></div>
<label class="form-label mt-2">Cliente/Jogador responsável</label><input class="form-control mb-2" name="customer_name" maxlength="150" required placeholder="Nome"><input class="form-control mb-2" name="customer_phone" maxlength="32" inputmode="tel" placeholder="Telefone"><input class="form-control mb-2" type="email" name="customer_email" maxlength="190" placeholder="E-mail">
<label class="form-label">Forma prevista</label><select class="form-select mb-2" name="payment_method"><option value="onsite">Pagar no local</option><option value="pix">Pix</option></select><textarea class="form-control mb-3" name="notes" maxlength="1000" placeholder="Observações"></textarea><button class="btn btn-primary w-100">Criar reserva</button>
<?php endif;?></div></form></div><?php endif;?>
<div class="<?=$canManage?'col-xl-8':'col-12'?>"><form class="d-flex flex-wrap gap-2 mb-3" method="get"><input class="form-control" style="max-width:220px" type="date" name="from" value="<?=$e($from)?>"><input class="form-control" style="max-width:220px" type="date" name="to" value="<?=$e($to)?>"><button class="btn btn-outline-primary">Filtrar</button></form>
<?php foreach($reservations as $r):$detailed=$r['detailed_payment_state']??null;?><article class="card border-0 shadow-sm mb-3"><div class="card-body"><div class="d-flex flex-wrap justify-content-between gap-3"><div><div class="d-flex flex-wrap gap-2"><span class="sports-status status-<?=$e($r['status'])?>"><?=$e($status[$r['status']]??$r['status'])?></span><?php if($detailed):?><span class="badge text-bg-light border"><?=$e($finance[$detailed]??$detailed)?></span><?php endif;?></div><h2 class="h5 mt-2 mb-1"><?=$e($r['court_name'])?><?php if(!empty($r['modality_name'])):?> · <?=$e($r['modality_name'])?><?php endif;?></h2><strong><?=date('d/m/Y H:i',strtotime($r['starts_at']))?>–<?=date('H:i',strtotime($r['ends_at']))?></strong><p class="mb-0"><?=$e($r['customer_name'])?><?php if(!empty($r['customer_phone'])):?> · <?=$e($r['customer_phone'])?><?php endif;?></p></div><div class="text-end"><strong class="fs-5">R$ <?=number_format((float)$r['total_amount'],2,',','.')?></strong><br><small>Sinal: R$ <?=number_format((float)$r['deposit_amount'],2,',','.')?></small><?php if(isset($r['amount_paid'])&&(float)$r['amount_paid']>0):?><br><small>Recebido: R$ <?=number_format((float)$r['amount_paid'],2,',','.')?></small><?php endif;?></div></div>
<?php if($canManage):$selectedPayment=$detailed==='partial'?'signal_paid':$r['payment_status'];?><form method="post" action="/sports/reservations/<?=(int)$r['id']?>/update" class="row g-2 mt-2"><?=CSRF::field()?><div class="col-md-5"><select class="form-select" name="status"><?php foreach($status as $key=>$label):?><option value="<?=$key?>" <?=$r['status']===$key?'selected':''?>><?=$label?></option><?php endforeach;?></select></div><div class="col-md-5"><select class="form-select" name="payment_status"><?php foreach($payments as $key=>$label):?><option value="<?=$key?>" <?=$selectedPayment===$key?'selected':''?>><?=$label?></option><?php endforeach;?></select></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Salvar</button></div></form><?php if(in_array($r['status'],['pending_payment','confirmed'],true)):?><details class="mt-2"><summary class="small text-primary" style="cursor:pointer">Remarcar</summary><form method="post" action="/sports/reservations/<?=(int)$r['id']?>/reschedule" class="row g-2 mt-2"><?=CSRF::field()?><div class="col-md-6"><input class="form-control" type="datetime-local" name="starts_at" required></div><div class="col-md-3"><input class="form-control" type="number" name="duration_minutes" value="<?=(int)$r['duration_minutes']?>" min="15" step="15"></div><div class="col-md-3"><button class="btn btn-outline-secondary w-100">Remarcar</button></div></form></details><?php endif;?><?php endif;?>
</div></article><?php endforeach;?><?php if(!$reservations):?><div class="sports-empty">Nenhuma reserva no período.</div><?php endif;?></div></div>
<script>
(function(){const court=document.getElementById('arenaReservationCourt'),mod=document.getElementById('arenaReservationModality');if(!court||!mod)return;function sync(){let first=null;for(const o of mod.options){const ok=o.dataset.court===court.value;o.hidden=!ok;o.disabled=!ok;if(ok&&!first)first=o;}if(mod.selectedOptions[0]?.disabled&&first)mod.value=first.value;}court.addEventListener('change',sync);sync();})();
</script>
