<?php
namespace App\Controllers;
use App\Core\{Auth,Audit,Authorization,CSRF,Database,HttpException,TenantContext,View};
use App\Services\{ModuleService,SportsAvailabilityService};
final class SportsController
{
 private function access(string $permission='sports.view'):array{ModuleService::require('sports_courts');Authorization::require($permission);return[Database::connection(),TenantContext::id()];}
 public function index():void
 {
  [$pdo,$t]=$this->access();$stats=[];foreach(['courts'=>"SELECT COUNT(*) FROM sports_courts WHERE tenant_id=:t AND active=1",'today'=>"SELECT COUNT(*) FROM sports_reservations WHERE tenant_id=:t AND DATE(starts_at)=CURDATE() AND status IN('pending_payment','confirmed','completed')",'pending'=>"SELECT COUNT(*) FROM sports_reservations WHERE tenant_id=:t AND status='pending_payment'",'month'=>"SELECT COALESCE(SUM(total_amount),0) FROM sports_reservations WHERE tenant_id=:t AND status IN('confirmed','completed') AND starts_at>=DATE_FORMAT(CURDATE(),'%Y-%m-01')"] as $k=>$sql){$q=$pdo->prepare($sql);$q->execute(['t'=>$t]);$stats[$k]=$q->fetchColumn();}$q=$pdo->prepare("SELECT r.*,c.name court_name,m.name modality_name FROM sports_reservations r JOIN sports_courts c ON c.id=r.court_id LEFT JOIN sports_modalities m ON m.id=r.modality_id WHERE r.tenant_id=:t AND r.ends_at>=NOW() AND r.status IN('pending_payment','confirmed') ORDER BY r.starts_at LIMIT 12");$q->execute(['t'=>$t]);$tenant=$pdo->prepare('SELECT name,public_short_code,public_slug FROM tenants WHERE id=:t');$tenant->execute(['t'=>$t]);View::render('sports/index',['title'=>'ApPlanner Arena','stats'=>$stats,'upcoming'=>$q->fetchAll(),'tenant'=>$tenant->fetch()]);
 }
 public function courts():void{[$pdo,$t]=$this->access();$q=$pdo->prepare("SELECT c.*,u.name unit_name,GROUP_CONCAT(DISTINCT m.name ORDER BY m.name SEPARATOR ', ') modalities FROM sports_courts c LEFT JOIN units u ON u.id=c.unit_id LEFT JOIN sports_court_modalities cm ON cm.court_id=c.id LEFT JOIN sports_modalities m ON m.id=cm.modality_id WHERE c.tenant_id=:t GROUP BY c.id,u.name ORDER BY c.active DESC,c.sort_order,c.name");$q->execute(['t'=>$t]);View::render('sports/courts',['title'=>'Quadras/Espaços','courts'=>$q->fetchAll()]);}
 public function createCourt():void{[$pdo,$t]=$this->access('sports.manage');View::render('sports/court-form',['title'=>'Nova quadra','court'=>null]+$this->formData($pdo,$t));}
 public function editCourt(string $id):void{[$pdo,$t]=$this->access('sports.manage');$q=$pdo->prepare('SELECT * FROM sports_courts WHERE id=:id AND tenant_id=:t');$q->execute(['id'=>(int)$id,'t'=>$t]);$court=$q->fetch();if(!$court)HttpException::abort(404,'Quadra não encontrada.');$data=$this->formData($pdo,$t,(int)$id);View::render('sports/court-form',['title'=>'Editar quadra','court'=>$court]+$data);}
 public function storeCourt():void{$this->saveCourt(null);}public function updateCourt(string $id):void{$this->saveCourt((int)$id);}
 private function saveCourt(?int $id):void
 {
  [$pdo,$t]=$this->access('sports.manage');CSRF::enforce();$name=trim((string)($_POST['name']??''));if(mb_strlen($name)<2)HttpException::abort(422,'Informe o nome da quadra.');$currentCourt=$id?$this->court($pdo,$t,$id):null;$min=max(15,min(720,(int)($_POST['minimum_minutes']??60)));$max=max($min,min(1440,(int)($_POST['maximum_minutes']??180)));$slug=$currentCourt?(string)$currentCourt['slug']:$this->slug($name);$unit=(int)($_POST['unit_id']??0)?:null;$modalities=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['modalities']??[])))));if(!$modalities)HttpException::abort(422,'Selecione ao menos uma modalidade.');$pdo->beginTransaction();try{if($id){$q=$pdo->prepare('UPDATE sports_courts SET unit_id=:u,name=:n,slug=:slug,description=:d,photo_path=:photo,surface=:surface,indoor=:indoor,lighting=:lighting,capacity=:capacity,minimum_minutes=:min,maximum_minutes=:max,interval_minutes=:buffer,active=:active,updated_at=NOW() WHERE id=:id AND tenant_id=:t');$q->execute($this->courtParams($t,$unit,$name,$slug,$min,$max)+['id'=>$id]);if(!$q->rowCount()){$check=$pdo->prepare('SELECT 1 FROM sports_courts WHERE id=:id AND tenant_id=:t');$check->execute(['id'=>$id,'t'=>$t]);if(!$check->fetchColumn())throw new \DomainException('Quadra não encontrada.');}}else{$q=$pdo->prepare('INSERT INTO sports_courts(tenant_id,unit_id,name,slug,description,photo_path,surface,indoor,lighting,capacity,minimum_minutes,maximum_minutes,interval_minutes,active,created_at,updated_at)VALUES(:t,:u,:n,:slug,:d,:photo,:surface,:indoor,:lighting,:capacity,:min,:max,:buffer,:active,NOW(),NOW())');$q->execute($this->courtParams($t,$unit,$name,$slug,$min,$max));$id=(int)$pdo->lastInsertId();}$valid=$pdo->prepare('SELECT id FROM sports_modalities WHERE tenant_id=? AND active=1 AND id IN('.implode(',',array_fill(0,count($modalities),'?')).')');$valid->execute(array_merge([$t],$modalities));$mods=array_map('intval',$valid->fetchAll(\PDO::FETCH_COLUMN));if(count($mods)!==count($modalities))throw new \DomainException('Modalidade inválida.');$pdo->prepare('DELETE FROM sports_court_modalities WHERE court_id=:c')->execute(['c'=>$id]);$ins=$pdo->prepare('INSERT INTO sports_court_modalities(court_id,modality_id)VALUES(:c,:m)');foreach($mods as $m)$ins->execute(['c'=>$id,'m'=>$m]);$pdo->commit();Audit::log($id?'SPORTS_COURT_SAVED':'SPORTS_COURT_CREATED','sports_courts',$id);}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}header('Location: /sports/courts/'.$id.'/edit?saved=1');exit;
 }
 private function courtParams(int $t,?int $unit,string $name,string $slug,int $min,int $max):array{return['t'=>$t,'u'=>$unit,'n'=>$name,'slug'=>$slug,'d'=>trim((string)($_POST['description']??''))?:null,'photo'=>trim((string)($_POST['photo_path']??''))?:null,'surface'=>trim((string)($_POST['surface']??''))?:null,'indoor'=>isset($_POST['indoor'])?1:0,'lighting'=>isset($_POST['lighting'])?1:0,'capacity'=>(int)($_POST['capacity']??0)?:null,'min'=>$min,'max'=>$max,'buffer'=>max(0,min(120,(int)($_POST['interval_minutes']??0))),'active'=>isset($_POST['active'])?1:0];}
 public function saveHours(string $id):void
 {
  [$pdo,$t]=$this->access('sports.manage');CSRF::enforce();$court=(int)$id;$this->court($pdo,$t,$court);$pdo->beginTransaction();try{$pdo->prepare('DELETE FROM sports_court_hours WHERE court_id=:c AND tenant_id=:t')->execute(['c'=>$court,'t'=>$t]);$ins=$pdo->prepare('INSERT INTO sports_court_hours(tenant_id,court_id,weekday,start_time,end_time,active,created_at,updated_at)VALUES(:t,:c,:d,:s,:e,1,NOW(),NOW())');foreach(range(1,7) as $d){$s=(string)($_POST['start'][$d]??'');$e=(string)($_POST['end'][$d]??'');if($s===''&&$e==='')continue;if(!preg_match('/^\d{2}:\d{2}$/',$s)||!preg_match('/^\d{2}:\d{2}$/',$e)||$s>=$e)throw new \DomainException('Horário inválido no dia '.$d.'.');$ins->execute(['t'=>$t,'c'=>$court,'d'=>$d,'s'=>$s.':00','e'=>$e.':00']);}$pdo->commit();Audit::log('SPORTS_HOURS_UPDATED','sports_courts',$court);}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}header('Location: /sports/courts/'.$court.'/edit?hours=1');exit;
 }
 public function addPrice(string $id):void
 {
  [$pdo,$t]=$this->access('sports.manage');CSRF::enforce();$court=(int)$id;$this->court($pdo,$t,$court);
  $price=$this->money($_POST['price_per_hour']??'');$weekday=(int)($_POST['weekday']??0)?:null;$modality=(int)($_POST['modality_id']??0)?:null;$start=trim((string)($_POST['start_time']??''))?:null;$end=trim((string)($_POST['end_time']??''))?:null;
  $ruleType=in_array((string)($_POST['rule_type']??'standard'),['standard','holiday','special'],true)?(string)$_POST['rule_type']:'standard';$specificDate=$this->validDate((string)($_POST['specific_date']??''));$validFrom=$this->validDate((string)($_POST['valid_from']??''));$validTo=$this->validDate((string)($_POST['valid_to']??''));$minDuration=(int)($_POST['minimum_duration_minutes']??0)?:null;$maxDuration=(int)($_POST['maximum_duration_minutes']??0)?:null;
  if($price<=0||($weekday!==null&&($weekday<1||$weekday>7))||(($start||$end)&&(!$start||!$end||$start>=$end))||($validFrom&&$validTo&&$validTo<$validFrom)||($minDuration!==null&&$minDuration<15)||($maxDuration!==null&&$maxDuration<15)||($minDuration!==null&&$maxDuration!==null&&$maxDuration<$minDuration))HttpException::abort(422,'Regra de preço inválida.');
  if($ruleType==='holiday'&&!$specificDate)HttpException::abort(422,'Para feriado/data específica, informe a data.');
  if($ruleType==='special'&&!$specificDate&&!$validFrom&&!$validTo)HttpException::abort(422,'Para período especial, informe uma data ou período.');
  if($modality!==null){$mq=$pdo->prepare('SELECT 1 FROM sports_modalities m JOIN sports_court_modalities cm ON cm.modality_id=m.id WHERE m.id=:m AND m.tenant_id=:t AND m.active=1 AND cm.court_id=:c');$mq->execute(['m'=>$modality,'t'=>$t,'c'=>$court]);if(!$mq->fetchColumn())HttpException::abort(422,'Modalidade inválida para esta quadra.');}
  $pdo->beginTransaction();try{
   $pdo->prepare('INSERT INTO sports_price_rules(tenant_id,court_id,modality_id,weekday,start_time,end_time,price_per_hour,priority,active,created_at,updated_at)VALUES(:t,:c,:m,:d,:s,:e,:p,:priority,1,NOW(),NOW())')->execute(['t'=>$t,'c'=>$court,'m'=>$modality,'d'=>$weekday,'s'=>$start?$start.':00':null,'e'=>$end?$end.':00':null,'p'=>$price,'priority'=>(int)($_POST['priority']??0)]);$ruleId=(int)$pdo->lastInsertId();
   if($ruleType!=='standard'||$specificDate||$validFrom||$validTo||$minDuration||$maxDuration){$pdo->prepare('INSERT INTO sports_price_rule_extensions(price_rule_id,tenant_id,rule_type,specific_date,valid_from,valid_to,minimum_duration_minutes,maximum_duration_minutes,label,created_at,updated_at)VALUES(:rule,:tenant,:type,:specific,:from,:to,:min,:max,:label,NOW(),NOW())')->execute(['rule'=>$ruleId,'tenant'=>$t,'type'=>$ruleType,'specific'=>$specificDate,'from'=>$validFrom,'to'=>$validTo,'min'=>$minDuration,'max'=>$maxDuration,'label'=>trim((string)($_POST['label']??''))?:null]);}
   $pdo->commit();
  }catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
  header('Location: /sports/courts/'.$court.'/edit?price=1');exit;
 }
 public function deletePrice(string $id):void{[$pdo,$t]=$this->access('sports.manage');CSRF::enforce();$q=$pdo->prepare('DELETE FROM sports_price_rules WHERE id=:id AND tenant_id=:t');$q->execute(['id'=>(int)$id,'t'=>$t]);header('Location: '.($_SERVER['HTTP_REFERER']??'/sports/courts'));exit;}
 public function addBlock():void{[$pdo,$t]=$this->access('sports.manage');CSRF::enforce();$court=(int)($_POST['court_id']??0);$this->court($pdo,$t,$court);try{$s=new \DateTimeImmutable((string)($_POST['starts_at']??''));$e=new \DateTimeImmutable((string)($_POST['ends_at']??''));}catch(\Throwable){HttpException::abort(422,'Período inválido.');}if($e<=$s)HttpException::abort(422,'Período inválido.');$pdo->prepare("INSERT INTO sports_court_blocks(tenant_id,court_id,starts_at,ends_at,reason,status,created_by,created_at,updated_at)VALUES(:t,:c,:s,:e,:r,'active',:u,NOW(),NOW())")->execute(['t'=>$t,'c'=>$court,'s'=>$s->format('Y-m-d H:i:s'),'e'=>$e->format('Y-m-d H:i:s'),'r'=>trim((string)($_POST['reason']??''))?:null,'u'=>Auth::user()['id']]);header('Location: /sports/courts/'.$court.'/edit?block=1');exit;}
 public function cancelBlock(string $id):void{[$pdo,$t]=$this->access('sports.manage');CSRF::enforce();$pdo->prepare("UPDATE sports_court_blocks SET status='cancelled',updated_at=NOW() WHERE id=:id AND tenant_id=:t")->execute(['id'=>(int)$id,'t'=>$t]);header('Location: '.($_SERVER['HTTP_REFERER']??'/sports/courts'));exit;}
 public function settings():void{[$pdo,$t]=$this->access('sports.manage');$q=$pdo->prepare('SELECT * FROM sports_settings WHERE tenant_id=:t');$q->execute(['t'=>$t]);$settings=$q->fetch()?:[];$q=$pdo->prepare('SELECT * FROM sports_modalities WHERE tenant_id=:t ORDER BY active DESC,sort_order,name');$q->execute(['t'=>$t]);View::render('sports/settings',['title'=>'Configurações da Arena','settings'=>$settings,'modalities'=>$q->fetchAll()]);}
 public function saveSettings():void{[$pdo,$t]=$this->access('sports.manage');CSRF::enforce();$type=in_array($_POST['deposit_type']??'percent',['fixed','percent'],true)?$_POST['deposit_type']:'percent';$pdo->prepare('INSERT INTO sports_settings(tenant_id,public_enabled,default_slot_minutes,minimum_notice_minutes,maximum_days_ahead,cancellation_notice_minutes,require_deposit,deposit_type,deposit_value,pix_key,pix_holder,booking_terms,updated_at)VALUES(:t,:public,:slot,:notice,:ahead,:cancel,:require,:type,:value,:pix,:holder,:terms,NOW()) ON DUPLICATE KEY UPDATE public_enabled=VALUES(public_enabled),default_slot_minutes=VALUES(default_slot_minutes),minimum_notice_minutes=VALUES(minimum_notice_minutes),maximum_days_ahead=VALUES(maximum_days_ahead),cancellation_notice_minutes=VALUES(cancellation_notice_minutes),require_deposit=VALUES(require_deposit),deposit_type=VALUES(deposit_type),deposit_value=VALUES(deposit_value),pix_key=VALUES(pix_key),pix_holder=VALUES(pix_holder),booking_terms=VALUES(booking_terms),updated_at=NOW()')->execute(['t'=>$t,'public'=>isset($_POST['public_enabled'])?1:0,'slot'=>max(5,min(120,(int)($_POST['default_slot_minutes']??60))),'notice'=>max(0,min(10080,(int)($_POST['minimum_notice_minutes']??60))),'ahead'=>max(1,min(365,(int)($_POST['maximum_days_ahead']??90))),'cancel'=>max(0,min(10080,(int)($_POST['cancellation_notice_minutes']??720))),'require'=>isset($_POST['require_deposit'])?1:0,'type'=>$type,'value'=>$this->money($_POST['deposit_value']??0),'pix'=>trim((string)($_POST['pix_key']??''))?:null,'holder'=>trim((string)($_POST['pix_holder']??''))?:null,'terms'=>trim((string)($_POST['booking_terms']??''))?:null]);header('Location: /sports/settings?saved=1');exit;}
 public function addModality():void{[$pdo,$t]=$this->access('sports.manage');CSRF::enforce();$name=trim((string)($_POST['name']??''));if(mb_strlen($name)<2)HttpException::abort(422,'Nome inválido.');$pdo->prepare('INSERT INTO sports_modalities(tenant_id,name,description,active,created_at,updated_at)VALUES(:t,:n,:d,1,NOW(),NOW()) ON DUPLICATE KEY UPDATE description=VALUES(description),active=1,updated_at=NOW()')->execute(['t'=>$t,'n'=>$name,'d'=>trim((string)($_POST['description']??''))?:null]);header('Location: /sports/settings?modality=1');exit;}
 public function reservations():void{[$pdo,$t]=$this->access('sports.reservations.manage');$from=(string)($_GET['from']??date('Y-m-d'));$to=(string)($_GET['to']??date('Y-m-d',strtotime('+30 days')));$q=$pdo->prepare("SELECT r.*,c.name court_name,m.name modality_name FROM sports_reservations r JOIN sports_courts c ON c.id=r.court_id LEFT JOIN sports_modalities m ON m.id=r.modality_id WHERE r.tenant_id=:t AND DATE(r.starts_at) BETWEEN :f AND :to ORDER BY r.starts_at");$q->execute(['t'=>$t,'f'=>$from,'to'=>$to]);$courts=$pdo->prepare('SELECT id,name FROM sports_courts WHERE tenant_id=:t AND active=1 ORDER BY name');$courts->execute(['t'=>$t]);$mods=$pdo->prepare('SELECT id,name FROM sports_modalities WHERE tenant_id=:t AND active=1 ORDER BY name');$mods->execute(['t'=>$t]);View::render('sports/reservations',['title'=>'Reservas de quadras','reservations'=>$q->fetchAll(),'courts'=>$courts->fetchAll(),'modalities'=>$mods->fetchAll(),'from'=>$from,'to'=>$to]);}
 public function storeReservation():void
 {
  [$pdo,$t]=$this->access('sports.reservations.manage');CSRF::enforce();$court=(int)($_POST['court_id']??0);$mod=(int)($_POST['modality_id']??0);$duration=max(15,min(1440,(int)($_POST['duration_minutes']??60)));$weeks=max(1,min(52,(int)($_POST['repeat_weeks']??1)));try{$first=new \DateTimeImmutable((string)($_POST['starts_at']??''));}catch(\Throwable){HttpException::abort(422,'Data inválida.');}$c=$this->court($pdo,$t,$court);$service=new SportsAvailabilityService();$group=$weeks>1?bin2hex(random_bytes(16)):null;$pdo->beginTransaction();try{for($i=0;$i<$weeks;$i++){$start=$first->modify('+'.$i.' weeks');$end=$start->modify('+'.$duration.' minutes');if(!$service->free($t,$court,$start,$end,(int)$c['interval_minutes']))throw new \DomainException('A quadra não está livre em '.$start->format('d/m/Y H:i').'.');$quote=$service->quote($t,$court,$mod,$start,$duration);if(!$quote)throw new \DomainException('Não existe preço para o horário selecionado.');$token=bin2hex(random_bytes(32));$pdo->prepare("INSERT INTO sports_reservations(public_id,tenant_id,court_id,modality_id,customer_name,customer_phone,customer_email,starts_at,ends_at,duration_minutes,price_per_hour,total_amount,deposit_amount,status,payment_method,payment_status,manage_token_hash,recurrence_group,source,notes,confirmed_at,created_by,created_at,updated_at)VALUES(:public,:t,:c,:m,:name,:phone,:email,:s,:e,:duration,:hour,:total,0,'confirmed',:method,'not_required',:token,:group,:source,:notes,NOW(),:u,NOW(),NOW())")->execute(['public'=>bin2hex(random_bytes(16)),'t'=>$t,'c'=>$court,'m'=>$mod?:null,'name'=>trim((string)($_POST['customer_name']??''))?:'Reserva interna','phone'=>preg_replace('/\D/','',(string)($_POST['customer_phone']??'')),'email'=>mb_strtolower(trim((string)($_POST['customer_email']??'')))?:null,'s'=>$start->format('Y-m-d H:i:s'),'e'=>$end->format('Y-m-d H:i:s'),'duration'=>$duration,'hour'=>$quote['price_per_hour'],'total'=>$quote['total'],'method'=>($_POST['payment_method']??'onsite')==='pix'?'pix':'onsite','token'=>hash('sha256',$token),'group'=>$group,'source'=>$weeks>1?'recurring':'internal','notes'=>trim((string)($_POST['notes']??''))?:null,'u'=>Auth::user()['id']]);}$pdo->commit();Audit::log('SPORTS_RESERVATION_CREATED','sports_reservations',null,null,['court_id'=>$court,'repeat_weeks'=>$weeks]);}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}header('Location: /sports/reservations?created=1');exit;
 }
 public function updateReservation(string $id):void{[$pdo,$t]=$this->access('sports.reservations.manage');CSRF::enforce();$status=(string)($_POST['status']??'');if(!in_array($status,['pending_payment','confirmed','completed','cancelled','no_show'],true))HttpException::abort(422,'Status inválido.');$payment=(string)($_POST['payment_status']??'');if(!in_array($payment,['not_required','pending','paid','refunded','cancelled'],true))HttpException::abort(422,'Pagamento inválido.');$q=$pdo->prepare("UPDATE sports_reservations SET status=:s,payment_status=:p,confirmed_at=IF(:s2='confirmed' AND confirmed_at IS NULL,NOW(),confirmed_at),cancelled_at=IF(:s3='cancelled',NOW(),cancelled_at),updated_at=NOW() WHERE id=:id AND tenant_id=:t");$q->execute(['s'=>$status,'p'=>$payment,'s2'=>$status,'s3'=>$status,'id'=>(int)$id,'t'=>$t]);Audit::log('SPORTS_RESERVATION_UPDATED','sports_reservations',(int)$id,null,['status'=>$status,'payment_status'=>$payment]);header('Location: /sports/reservations?updated=1');exit;}
 private function formData(\PDO $pdo,int $t,?int $court=null):array{$u=$pdo->prepare('SELECT id,name FROM units WHERE tenant_id=:t AND active=1 ORDER BY name');$u->execute(['t'=>$t]);$m=$pdo->prepare('SELECT id,name,description FROM sports_modalities WHERE tenant_id=:t AND active=1 ORDER BY name');$m->execute(['t'=>$t]);$enabled=[];$hours=[];$prices=[];$blocks=[];if($court){$q=$pdo->prepare('SELECT modality_id FROM sports_court_modalities WHERE court_id=:c');$q->execute(['c'=>$court]);$enabled=array_map('intval',$q->fetchAll(\PDO::FETCH_COLUMN));$q=$pdo->prepare('SELECT * FROM sports_court_hours WHERE court_id=:c AND active=1 ORDER BY weekday,start_time');$q->execute(['c'=>$court]);foreach($q->fetchAll() as $h)$hours[(int)$h['weekday']]=$h;$q=$pdo->prepare('SELECT pr.*,m.name modality_name,x.rule_type,x.specific_date,x.valid_from,x.valid_to,x.minimum_duration_minutes,x.maximum_duration_minutes,x.label rule_label FROM sports_price_rules pr LEFT JOIN sports_modalities m ON m.id=pr.modality_id LEFT JOIN sports_price_rule_extensions x ON x.price_rule_id=pr.id WHERE pr.court_id=:c AND pr.active=1 ORDER BY pr.priority DESC,pr.id DESC');$q->execute(['c'=>$court]);$prices=$q->fetchAll();$q=$pdo->prepare("SELECT * FROM sports_court_blocks WHERE court_id=:c AND status='active' AND ends_at>=NOW() ORDER BY starts_at");$q->execute(['c'=>$court]);$blocks=$q->fetchAll();}return['units'=>$u->fetchAll(),'modalities'=>$m->fetchAll(),'enabledModalities'=>$enabled,'hours'=>$hours,'prices'=>$prices,'blocks'=>$blocks];}
 private function court(\PDO $pdo,int $t,int $court):array{$q=$pdo->prepare('SELECT * FROM sports_courts WHERE id=:c AND tenant_id=:t');$q->execute(['c'=>$court,'t'=>$t]);$c=$q->fetch();if(!$c)HttpException::abort(404,'Quadra não encontrada.');return$c;}
 private function slug(string $name):string{$s=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$name)?:$name;return trim(preg_replace('/[^a-z0-9]+/','-',mb_strtolower($s)),'-').'-'.substr(bin2hex(random_bytes(3)),0,6);}
 private function validDate(string $v):?string{if($v==='')return null;if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))return null;$d=\DateTimeImmutable::createFromFormat('!Y-m-d',$v);return $d&&$d->format('Y-m-d')===$v?$v:null;}
 private function money(mixed $v):float{$x=str_replace(['R$',' ','.'],['','',''],trim((string)$v));$x=str_replace(',','.',$x);return is_numeric($x)?round((float)$x,2):0.0;}
}
