# Generated by Django 5.2.17 on 2026-10-05 14:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_audit_hash_chain'),
        ('tenants', '0011_tenant_archive_snapshot_tenant_archived_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingFunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey', models.UUIDField()),
                ('stage', models.CharField(choices=[('visit', 'Visita'), ('resource', 'Serviço ou quadra'), ('slot', 'Horário'), ('confirmed', 'Reserva registrada')], max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.unit')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'unit', 'created_at'], name='booking_funnel_period_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'unit', 'journey', 'stage'), name='booking_funnel_unique_stage')],
            },
        ),
    ]
