<?php
namespace App\Controllers;

use App\Core\{Auth,Authorization,Database,View,CSRF,Audit,Encryption,HttpException};
use App\Services\{PlatformSetting,ErrorLogService,PlatformMetricsService};

final class MasterController
{
    private function master():void{Auth::requireRole('master');}

    public function index(): void
    {
        $this->master();$pdo=Database::connection();$metrics=PlatformMetricsService::calculate();
        $stats=[
            'tenants'=>(int)$metrics['tenants'],
            'active'=>(int)$metrics['active_subscriptions'],
            'trials'=>(int)$metrics['trials'],
            'subscriptions_due'=>(int)$pdo->query("SELECT COUNT(*) FROM subscriptions WHERE status IN('trial','active') AND next_billing_at BETWEEN NOW() AND DATE_ADD(NOW(),INTERVAL 7 DAY)")->fetchColumn(),
            'payments_pending'=>(int)$pdo->query("SELECT COUNT(*) FROM payments WHERE status='pending'")->fetchColumn(),
            'payments_month'=>(float)$metrics['received_month'],
            'support_open'=>(int)$pdo->query("SELECT COUNT(*) FROM support_tickets WHERE status IN('open','in_progress','waiting_user')")->fetchColumn(),
            'blocked'=>(int)$pdo->query("SELECT COUNT(*) FROM users WHERE status='blocked'")->fetchColumn(),
        ];
        $tenants=$pdo->query("SELECT t.id,t.name,t.public_slug,t.public_short_code,t.status,t.created_at,p.name plan_name,s.status subscription_status,s.trial_ends_at,s.next_billing_at,s.contracted_price,s.billing_cycle FROM tenants t LEFT JOIN subscriptions s ON s.id=(SELECT MAX(s2.id) FROM subscriptions s2 WHERE s2.tenant_id=t.id) LEFT JOIN plans p ON p.id=s.plan_id WHERE t.deleted_at IS NULL ORDER BY t.created_at DESC LIMIT 10")->fetchAll();
        $tickets=$pdo->query("SELECT st.id,st.protocol,st.subject,st.priority,st.status,st.remote_access_allowed,t.name tenant_name FROM support_tickets st JOIN tenants t ON t.id=st.tenant_id WHERE st.status IN('open','in_progress','waiting_user') ORDER BY FIELD(st.priority,'urgent','high','normal','low'),st.updated_at DESC LIMIT 8")->fetchAll();
        $moduleRequests=$pdo->query("SELECT mr.id,t.name tenant_name,m.name module_name,mr.quoted_monthly_price,mr.created_at FROM module_requests mr JOIN tenants t ON t.id=mr.tenant_id JOIN modules m ON m.id=mr.module_id WHERE mr.status='pending' ORDER BY mr.created_at DESC LIMIT 6")->fetchAll();
        View::render('master/index',['title'=>'Painel da plataforma','stats'=>$stats,'metrics'=>$metrics,'tenants'=>$tenants,'tickets'=>$tickets,'moduleRequests'=>$moduleRequests]);
    }

    public function conversionSettings():void
    {
        $this->master();
        $keys=['growth.hero_title','growth.hero_subtitle','growth.cta_label','growth.meta_pixel_id','growth.whatsapp','growth.instagram','growth.default_utm_campaign'];$settings=[];
        foreach($keys as $key)$settings[$key]=PlatformSetting::get($key,'');
        View::render('master/conversion-settings',['title'=>'Aquisição e conversão','settings'=>$settings,'success'=>$_SESSION['growth_success']??null]);unset($_SESSION['growth_success']);
    }

    public function saveConversionSettings():void
    {
        $this->master();CSRF::enforce();
        $values=[
            'growth.hero_title'=>mb_substr(trim((string)($_POST['hero_title']??'')),0,120),
            'growth.hero_subtitle'=>mb_substr(trim((string)($_POST['hero_subtitle']??'')),0,320),
            'growth.cta_label'=>mb_substr(trim((string)($_POST['cta_label']??'')),0,50),
            'growth.whatsapp'=>preg_replace('/\D/','',(string)($_POST['whatsapp']??'')),
            'growth.instagram'=>mb_substr(trim((string)($_POST['instagram']??'')),0,120),
            'growth.default_utm_campaign'=>preg_replace('/[^a-zA-Z0-9_-]/','',mb_substr((string)($_POST['default_utm_campaign']??''),0,80)),
        ];
        $pixel=trim((string)($_POST['meta_pixel_id']??''));if($pixel!==''&&!preg_match('/^\d{5,30}$/',$pixel))HttpException::abort(422,'ID do Pixel da Meta inválido.');$values['growth.meta_pixel_id']=$pixel;
        foreach($values as $key=>$value)PlatformSetting::set($key,$value,false);
        Audit::log('MASTER_GROWTH_SETTINGS_UPDATED','settings',null,null,['keys'=>array_keys($values)]);$_SESSION['growth_success']='Configurações de aquisição atualizadas.';header('Location: /master/conversion-settings');exit;
    }

    public function tenants(): void
    {
        $this->master();$tenants=Database::connection()->query("SELECT t.*,p.id plan_id,p.name plan_name,s.status subscription_status,s.trial_ends_at,s.next_billing_at FROM tenants t LEFT JOIN subscriptions s ON s.id=(SELECT MAX(s2.id) FROM subscriptions s2 WHERE s2.tenant_id=t.id) LEFT JOIN plans p ON p.id=s.plan_id WHERE t.deleted_at IS NULL ORDER BY t.id DESC")->fetchAll();View::render('master/tenants',['title'=>'Empresas','tenants'=>$tenants]);
    }

    public function tenantDetail(string $id):void
    {
        $this->master();$tenantId=(int)$id;$pdo=Database::connection();$q=$pdo->prepare("SELECT t.*,s.id subscription_id,s.status subscription_status,s.plan_id,s.trial_ends_at,s.next_billing_at,s.contracted_price,p.name plan_name FROM tenants t LEFT JOIN subscriptions s ON s.id=(SELECT MAX(s2.id) FROM subscriptions s2 WHERE s2.tenant_id=t.id) LEFT JOIN plans p ON p.id=s.plan_id WHERE t.id=:id AND t.deleted_at IS NULL");$q->execute(['id'=>$tenantId]);$tenant=$q->fetch();if(!$tenant)HttpException::abort(404,'Empresa não encontrada.');
        $u=$pdo->prepare("SELECT u.id,u.name,u.email,u.status,u.last_login_at,r.name role_name,r.slug role_slug,(SELECT ub.reason_text FROM user_blocks ub WHERE ub.user_id=u.id AND ub.unblocked_at IS NULL ORDER BY ub.id DESC LIMIT 1) block_reason FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id WHERE u.tenant_id=:t ORDER BY u.name");$u->execute(['t'=>$tenantId]);
        $p=$pdo->prepare('SELECT id,name,email,specialty,active FROM professionals WHERE tenant_id=:t ORDER BY active DESC,name');$p->execute(['t'=>$tenantId]);
        $tickets=$pdo->prepare('SELECT id,protocol,subject,status,priority,remote_access_allowed,updated_at FROM support_tickets WHERE tenant_id=:t ORDER BY updated_at DESC LIMIT 20');$tickets->execute(['t'=>$tenantId]);
        $payments=$pdo->prepare('SELECT * FROM payments WHERE tenant_id=:t ORDER BY created_at DESC LIMIT 20');$payments->execute(['t'=>$tenantId]);
        $plans=$pdo->query("SELECT id,name,monthly_price FROM plans WHERE active=1 OR id=".(int)($tenant['plan_id']??0)." ORDER BY monthly_price,sort_order")->fetchAll();
        View::render('master/tenant-detail',['title'=>$tenant['name'],'tenant'=>$tenant,'users'=>$u->fetchAll(),'professionals'=>$p->fetchAll(),'tickets'=>$tickets->fetchAll(),'payments'=>$payments->fetchAll(),'plans'=>$plans]);
    }

    public function createTenant(): void{$this->master();$plans=Database::connection()->query("SELECT id,name FROM plans WHERE active=1 ORDER BY monthly_price")->fetchAll();View::render('master/tenant-form',['title'=>'Nova empresa','plans'=>$plans]);}

    public function storeTenant(): void
    {
        $this->master();CSRF::enforce();$name=trim((string)($_POST['name']??''));$slug=$this->slug((string)($_POST['slug']??$name));$email=mb_strtolower(trim((string)($_POST['owner_email']??'')));$owner=trim((string)($_POST['owner_name']??''));$password=(string)($_POST['owner_password']??'');$planId=filter_var($_POST['plan_id']??null,FILTER_VALIDATE_INT);$category=trim((string)($_POST['category']??''));
        if(strlen($name)<2||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($owner)<2||strlen($password)<12||!$planId){http_response_code(422);exit('Dados inválidos.');}
        $pdo=Database::connection();$plan=$pdo->prepare('SELECT * FROM plans WHERE id=:id AND active=1');$plan->execute(['id'=>$planId]);$plan=$plan->fetch();if(!$plan)HttpException::abort(422,'Plano inválido.');
        $exists=$pdo->prepare('SELECT 1 FROM tenants WHERE slug=:s OR public_slug=:s2');$exists->execute(['s'=>$slug,'s2'=>$slug]);if($exists->fetchColumn())HttpException::abort(422,'Este slug já está em uso.');
        $pdo->beginTransaction();try{$pdo->prepare("INSERT INTO tenants(name,slug,public_slug,email,category,status,public_enabled,public_booking_enabled,onboarding_step,created_at,updated_at)VALUES(:name,:slug,:public,:email,:category,'trial',1,1,1,NOW(),NOW())")->execute(['name'=>$name,'slug'=>$slug,'public'=>$slug,'email'=>$email,'category'=>$category?:null]);$tenantId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO users(tenant_id,name,email,password_hash,status,created_at,updated_at)VALUES(:tenant,:name,:email,:hash,'active',NOW(),NOW())")->execute(['tenant'=>$tenantId,'name'=>$owner,'email'=>$email,'hash'=>password_hash($password,PASSWORD_DEFAULT)]);$userId=(int)$pdo->lastInsertId();$role=(int)$pdo->query("SELECT id FROM roles WHERE slug='owner'")->fetchColumn();$pdo->prepare('INSERT INTO user_roles(user_id,role_id)VALUES(:user,:role)')->execute(['user'=>$userId,'role'=>$role]);$days=(int)$plan['trial_days'];$pdo->prepare("INSERT INTO subscriptions(tenant_id,plan_id,billing_cycle,contracted_price,status,started_at,trial_ends_at,next_billing_at,created_at,updated_at)VALUES(:tenant,:plan,'monthly',:price,'trial',NOW(),DATE_ADD(NOW(),INTERVAL :days DAY),DATE_ADD(NOW(),INTERVAL :days2 DAY),NOW(),NOW())")->execute(['tenant'=>$tenantId,'plan'=>$planId,'price'=>$plan['monthly_price'],'days'=>$days,'days2'=>$days]);$pdo->prepare('INSERT INTO tenant_onboarding(tenant_id,updated_at)VALUES(:t,NOW())')->execute(['t'=>$tenantId]);$pdo->commit();Audit::log('master.tenant.create','tenants',$tenantId,null,['name'=>$name,'plan_id'=>$planId,'trial_days'=>$days]);}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}header('Location: /master/tenants/'.$tenantId);exit;
    }

    public function updateTenant(): void
    {
        $this->master();CSRF::enforce();$id=filter_var($_POST['id']??null,FILTER_VALIDATE_INT);$status=(string)($_POST['status']??'');$plan=filter_var($_POST['plan_id']??null,FILTER_VALIDATE_INT);$reason=trim((string)($_POST['reason']??'Alteração administrativa'));
        if(!$id||!$plan||!in_array($status,['trial','active','suspended','cancelled'],true)){http_response_code(422);exit('Dados inválidos.');}$pdo=Database::connection();$old=$pdo->prepare('SELECT status FROM tenants WHERE id=:id AND deleted_at IS NULL');$old->execute(['id'=>$id]);$before=$old->fetch();if(!$before)HttpException::abort(404,'Empresa não encontrada.');
        $pdo->beginTransaction();try{$pdo->prepare('UPDATE tenants SET status=:status,updated_at=NOW() WHERE id=:id')->execute(['status'=>$status,'id'=>$id]);$pdo->prepare("UPDATE subscriptions SET plan_id=:plan,status=CASE WHEN :cancel='cancelled' THEN 'cancelled' WHEN :suspend='suspended' THEN 'suspended' WHEN status IN('suspended','past_due') AND :active='active' THEN 'active' ELSE status END,updated_at=NOW() WHERE tenant_id=:id ORDER BY id DESC LIMIT 1")->execute(['plan'=>$plan,'cancel'=>$status,'suspend'=>$status,'active'=>$status,'id'=>$id]);if($before['status']!==$status)$pdo->prepare('INSERT INTO tenant_status_history(tenant_id,from_status,to_status,reason,changed_by,created_at)VALUES(:t,:f,:to,:r,:u,NOW())')->execute(['t'=>$id,'f'=>$before['status'],'to'=>$status,'r'=>$reason?:'Alteração administrativa','u'=>Auth::user()['id']]);$pdo->commit();Audit::log('master.tenant.update','tenants',(int)$id,$before,['status'=>$status,'plan_id'=>$plan,'reason'=>$reason]);}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}header('Location: /master/tenants/'.$id);exit;
    }

    public function plans(): void
    {
        $this->master();$pdo=Database::connection();$plans=$pdo->query('SELECT * FROM plans ORDER BY active DESC,sort_order,monthly_price')->fetchAll();foreach($plans as &$p){$q=$pdo->prepare('SELECT m.name FROM plan_modules pm JOIN modules m ON m.id=pm.module_id WHERE pm.plan_id=:p AND pm.enabled=1 AND m.active=1 ORDER BY m.name');$q->execute(['p'=>$p['id']]);$p['modules']=$q->fetchAll(\PDO::FETCH_COLUMN);$features=json_decode($p['features_json']??'{}',true)?:[];$p['included_features']=array_values(array_filter((array)($features['included_features']??[]),'is_string'));} $default=PlatformSetting::get('platform.trial_days_default');View::render('master/plans',['title'=>'Planos','plans'=>$plans,'trialDefault'=>$default!==false?(int)$default:14]);
    }
    public function createPlan():void{$this->master();$modules=Database::connection()->query('SELECT * FROM modules ORDER BY active DESC,sort_order,name')->fetchAll();View::render('master/plan-form',['title'=>'Novo plano','plan'=>null,'modules'=>$modules,'enabledModules'=>[]]);}
    public function editPlan(string $id):void{$this->master();$pdo=Database::connection();$q=$pdo->prepare('SELECT * FROM plans WHERE id=:id');$q->execute(['id'=>(int)$id]);$plan=$q->fetch();if(!$plan)HttpException::abort(404,'Plano não encontrado.');$modules=$pdo->query('SELECT * FROM modules ORDER BY active DESC,sort_order,name')->fetchAll();$e=$pdo->prepare('SELECT module_id FROM plan_modules WHERE plan_id=:p AND enabled=1');$e->execute(['p'=>$plan['id']]);View::render('master/plan-form',['title'=>'Editar plano','plan'=>$plan,'modules'=>$modules,'enabledModules'=>array_map('intval',$e->fetchAll(\PDO::FETCH_COLUMN))]);}
    public function storePlan():void{$this->master();CSRF::enforce();$id=$this->savePlan(null);header('Location: /master/plans/'.$id.'/edit');exit;}
    public function updatePlan(string $id):void{$this->master();CSRF::enforce();$this->savePlan((int)$id);header('Location: /master/plans/'.$id.'/edit');exit;}
    public function updateTrialDefault():void{$this->master();CSRF::enforce();$days=filter_var($_POST['trial_days']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>0,'max_range'=>90]]);if($days===false)HttpException::abort(422,'Prazo de teste inválido.');$pdo=Database::connection();PlatformSetting::set('platform.trial_days_default',(string)$days,false);if(isset($_POST['apply_all']))$pdo->prepare('UPDATE plans SET trial_days=:d,updated_at=NOW() WHERE active=1')->execute(['d'=>$days]);Audit::log('MASTER_TRIAL_DEFAULT_UPDATED','settings',null,null,['days'=>$days,'apply_all'=>isset($_POST['apply_all'])]);header('Location: /master/plans');exit;}

    private function savePlan(?int $id):int
    {
        $creating=$id===null;$pdo=Database::connection();$name=trim((string)($_POST['name']??''));$slug=$this->slug((string)($_POST['slug']??$name));$monthly=$this->money($_POST['monthly_price']??null);$trial=filter_var($_POST['trial_days']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>0,'max_range'=>90]]);if(strlen($name)<2||$monthly===null||$trial===false)HttpException::abort(422,'Dados do plano inválidos.');
        $prices=['quarterly_price'=>$this->money($_POST['quarterly_price']??null),'semiannual_price'=>$this->money($_POST['semiannual_price']??null),'annual_price'=>$this->money($_POST['annual_price']??null)];$included=[];foreach((array)($_POST['included_features']??[]) as $item){$item=trim(strip_tags((string)$item));if($item!==''&&mb_strlen($item)<=120&&!in_array($item,$included,true))$included[]=$item;if(count($included)>=30)break;}$features=['professionals'=>max(1,(int)($_POST['professionals_limit']??1)),'units'=>max(1,(int)($_POST['units_limit']??1)),'included_features'=>$included];$visible=isset($_POST['public_visible'])?1:0;$pdo->beginTransaction();try{if($id){$q=$pdo->prepare('UPDATE plans SET name=:n,slug=:s,description=:d,monthly_price=:m,quarterly_price=:q,semiannual_price=:sa,annual_price=:a,trial_days=:trial,trial_without_card=1,active=:active,public_visible=:visible,featured=:featured,sort_order=:sort,features_json=:features,updated_at=NOW() WHERE id=:id');$q->execute(['n'=>$name,'s'=>$slug,'d'=>trim((string)($_POST['description']??'')),'m'=>$monthly,'q'=>$prices['quarterly_price'],'sa'=>$prices['semiannual_price'],'a'=>$prices['annual_price'],'trial'=>$trial,'active'=>isset($_POST['active'])?1:0,'visible'=>$visible,'featured'=>isset($_POST['featured'])?1:0,'sort'=>(int)($_POST['sort_order']??0),'features'=>json_encode($features,JSON_UNESCAPED_UNICODE),'id'=>$id]);}else{$q=$pdo->prepare('INSERT INTO plans(name,slug,description,monthly_price,quarterly_price,semiannual_price,annual_price,trial_days,trial_without_card,active,public_visible,featured,sort_order,features_json,created_at,updated_at)VALUES(:n,:s,:d,:m,:q,:sa,:a,:trial,1,:active,:visible,:featured,:sort,:features,NOW(),NOW())');$q->execute(['n'=>$name,'s'=>$slug,'d'=>trim((string)($_POST['description']??'')),'m'=>$monthly,'q'=>$prices['quarterly_price'],'sa'=>$prices['semiannual_price'],'a'=>$prices['annual_price'],'trial'=>$trial,'active'=>isset($_POST['active'])?1:0,'visible'=>$visible,'featured'=>isset($_POST['featured'])?1:0,'sort'=>(int)($_POST['sort_order']??0),'features'=>json_encode($features,JSON_UNESCAPED_UNICODE)]);$id=(int)$pdo->lastInsertId();}
            $pdo->prepare('DELETE FROM plan_modules WHERE plan_id=:p')->execute(['p'=>$id]);$mods=array_unique(array_map('intval',(array)($_POST['modules']??[])));$valid=$pdo->prepare('SELECT 1 FROM modules WHERE id=:m AND active=1');$ins=$pdo->prepare('INSERT INTO plan_modules(plan_id,module_id,enabled)VALUES(:p,:m,1)');foreach($mods as $m){$valid->execute(['m'=>$m]);if($valid->fetchColumn())$ins->execute(['p'=>$id,'m'=>$m]);}$pdo->commit();Audit::log($creating?'MASTER_PLAN_CREATED':'MASTER_PLAN_SAVED','plans',$id,null,['name'=>$name,'modules'=>$mods,'included_features'=>$included]);return $id;}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }

    public function users():void
    {
        $this->master();$pdo=Database::connection();$platform=$pdo->query("SELECT u.id,u.name,u.email,u.status,u.last_login_at,r.name role_name,r.slug role_slug,cp.commission_percent,cp.max_discount_percent FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id LEFT JOIN commercial_profiles cp ON cp.user_id=u.id WHERE u.tenant_id IS NULL ORDER BY u.name")->fetchAll();$tenant=$pdo->query("SELECT u.id,u.name,u.email,u.status,u.last_login_at,t.name tenant_name,r.name role_name,r.slug role_slug FROM users u JOIN tenants t ON t.id=u.tenant_id LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id ORDER BY u.id DESC LIMIT 300")->fetchAll();View::render('master/users',['title'=>'Usuários','platformUsers'=>$platform,'tenantUsers'=>$tenant]);
    }
    public function storePlatformUser():void
    {
        $this->master();CSRF::enforce();$name=trim((string)($_POST['name']??''));$email=mb_strtolower(trim((string)($_POST['email']??'')));$role=(string)($_POST['role']??'support');if(mb_strlen($name)<2||!filter_var($email,FILTER_VALIDATE_EMAIL)||!in_array($role,['support','master','commercial'],true))HttpException::abort(422,'Revise nome, e-mail e perfil.');$pdo=Database::connection();$e=$pdo->prepare('SELECT 1 FROM users WHERE email=:e');$e->execute(['e'=>$email]);if($e->fetchColumn())HttpException::abort(422,'Já existe usuário com este e-mail.');$r=$pdo->prepare('SELECT id FROM roles WHERE slug=:r LIMIT 1');$r->execute(['r'=>$role]);$rid=(int)$r->fetchColumn();if(!$rid)HttpException::abort(503,'O perfil selecionado ainda não foi instalado. Aguarde a migração 022 ou atualize a página.');$token=bin2hex(random_bytes(32));$uid=0;
        $pdo->beginTransaction();try{$pdo->prepare("INSERT INTO users(tenant_id,name,email,password_hash,status,created_at,updated_at)VALUES(NULL,:n,:e,:h,'pending',NOW(),NOW())")->execute(['n'=>$name,'e'=>$email,'h'=>password_hash(bin2hex(random_bytes(32)),PASSWORD_DEFAULT)]);$uid=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO user_roles(user_id,role_id)VALUES(:u,:r)')->execute(['u'=>$uid,'r'=>$rid]);$pdo->prepare('DELETE FROM password_reset_tokens WHERE user_id=:u AND used_at IS NULL')->execute(['u'=>$uid]);$pdo->prepare('INSERT INTO password_reset_tokens(user_id,token_hash,expires_at,created_at)VALUES(:u,:h,DATE_ADD(NOW(),INTERVAL 24 HOUR),NOW())')->execute(['u'=>$uid,'h'=>hash('sha256',$token)]);$app=require __DIR__.'/../../config/app.php';$payload=Encryption::encrypt(['to'=>$email,'template'=>'password_reset','url'=>rtrim((string)$app['url'],'/').'/reset-password?token='.$token]);$pdo->prepare("INSERT INTO jobs(tenant_id,type,payload_encrypted,status,attempts,available_at,created_at,updated_at)VALUES(NULL,'mail.send',:p,'queued',0,NOW(),NOW(),NOW())")->execute(['p'=>$payload]);$pdo->commit();}catch(\PDOException $e){if($pdo->inTransaction())$pdo->rollBack();error_log('[ApPlanner MasterUser] '.$e->getCode().' '.mb_substr($e->getMessage(),0,300));if($e->getCode()==='23000')HttpException::abort(422,'Não foi possível criar: e-mail ou vínculo de perfil já existente.');HttpException::abort(500,'Não foi possível criar o usuário. Confirme que todas as migrações foram executadas e consulte storage/logs/app.log.');}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('[ApPlanner MasterUser] '.mb_substr($e->getMessage(),0,300));HttpException::abort(500,'Não foi possível preparar o convite do usuário. Consulte storage/logs/app.log.');}try{Audit::log('MASTER_USER_CREATED','users',$uid,null,['role'=>$role]);}catch(\Throwable $auditError){error_log('[ApPlanner MasterUser Audit] '.mb_substr($auditError->getMessage(),0,200));}header('Location: /master/users?created=1');exit;
    }
    public function editUser(string $id):void
    {
        $this->master();$uid=(int)$id;$pdo=Database::connection();$q=$pdo->prepare("SELECT u.id,u.tenant_id,u.name,u.email,u.status,r.slug role_slug,t.name tenant_name,cp.commission_percent,cp.max_discount_percent,cp.support_enabled FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id LEFT JOIN tenants t ON t.id=u.tenant_id LEFT JOIN commercial_profiles cp ON cp.user_id=u.id WHERE u.id=:id LIMIT 1");$q->execute(['id'=>$uid]);$account=$q->fetch();if(!$account)HttpException::abort(404,'Usuário não encontrado.');$roles=$account['tenant_id']===null?['support'=>'Suporte','commercial'=>'Comercial','master'=>'Master']:['owner'=>'Proprietário','manager'=>'Gerente','reception'=>'Recepção','professional'=>'Profissional'];View::render('master/user-form-v2',['title'=>'Editar usuário','account'=>$account,'roles'=>$roles]);
    }

    public function updateUser(string $id):void
    {
        $this->master();CSRF::enforce();$uid=(int)$id;$pdo=Database::connection();$q=$pdo->prepare("SELECT u.id,u.tenant_id,u.status,r.slug role_slug FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id WHERE u.id=:id LIMIT 1");$q->execute(['id'=>$uid]);$old=$q->fetch();if(!$old)HttpException::abort(404,'Usuário não encontrado.');$name=trim((string)($_POST['name']??''));$email=mb_strtolower(trim((string)($_POST['email']??'')));$role=(string)($_POST['role']??'');$status=(string)($_POST['status']??'active');$allowedRoles=$old['tenant_id']===null?['support','master','commercial']:['owner','manager','reception','professional'];if(strlen($name)<2||!filter_var($email,FILTER_VALIDATE_EMAIL)||!in_array($role,$allowedRoles,true)||!in_array($status,['active','pending','inactive'],true))HttpException::abort(422,'Dados de usuário inválidos.');if($uid===(int)Auth::user()['id']&&($role!=='master'||$status!=='active'))HttpException::abort(422,'Você não pode remover seu próprio acesso Master.');$dup=$pdo->prepare('SELECT 1 FROM users WHERE email=:e AND id<>:id');$dup->execute(['e'=>$email,'id'=>$uid]);if($dup->fetchColumn())HttpException::abort(422,'Este e-mail já está em uso.');$r=$pdo->prepare('SELECT id FROM roles WHERE slug=:r');$r->execute(['r'=>$role]);$rid=(int)$r->fetchColumn();if(!$rid)HttpException::abort(422,'Perfil inválido.');$pdo->beginTransaction();try{$pdo->prepare('UPDATE users SET name=:n,email=:e,status=:s,session_version=session_version+1,updated_at=NOW() WHERE id=:id')->execute(['n'=>$name,'e'=>$email,'s'=>$status,'id'=>$uid]);$pdo->prepare('DELETE FROM user_roles WHERE user_id=:u')->execute(['u'=>$uid]);$pdo->prepare('INSERT INTO user_roles(user_id,role_id)VALUES(:u,:r)')->execute(['u'=>$uid,'r'=>$rid]);$pdo->commit();Audit::log('MASTER_USER_UPDATED','users',$uid,$old,['name'=>$name,'role'=>$role,'status'=>$status]);}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}header('Location: /master/users');exit;
    }

    public function saveCommercialProfile(string $id):void
    {
        $this->master();CSRF::enforce();$uid=(int)$id;$commission=(float)str_replace(',','.',(string)($_POST['commission_percent']??0));$discount=(float)str_replace(',','.',(string)($_POST['max_discount_percent']??0));$support=isset($_POST['support_enabled'])?1:0;if($commission<0||$commission>100||$discount<0||$discount>100)HttpException::abort(422,'Percentuais inválidos.');$pdo=Database::connection();$q=$pdo->prepare("SELECT 1 FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE u.id=:u AND u.tenant_id IS NULL AND r.slug='commercial'");$q->execute(['u'=>$uid]);if(!$q->fetchColumn())HttpException::abort(422,'O usuário precisa ter o perfil Comercial.');$pdo->beginTransaction();try{$pdo->prepare('INSERT INTO commercial_profiles(user_id,commission_percent,max_discount_percent,active,support_enabled,created_at,updated_at)VALUES(:u,:c,:d,1,:support,NOW(),NOW()) ON DUPLICATE KEY UPDATE commission_percent=VALUES(commission_percent),max_discount_percent=VALUES(max_discount_percent),active=1,support_enabled=VALUES(support_enabled),updated_at=NOW()')->execute(['u'=>$uid,'c'=>$commission,'d'=>$discount,'support'=>$support]);$pdo->prepare('INSERT IGNORE INTO marketing_referral_profiles(user_id,referral_code,active,created_at,updated_at)VALUES(:u,:code,1,NOW(),NOW())')->execute(['u'=>$uid,'code'=>bin2hex(random_bytes(8))]);$pdo->commit();Audit::log('COMMERCIAL_PROFILE_UPDATED','users',$uid,null,['commission_percent'=>$commission,'max_discount_percent'=>$discount,'support_enabled'=>(bool)$support]);}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}header('Location: /master/users');exit;
    }

    public function saveCommercialSupport(string $id):void{$this->master();CSRF::enforce();$uid=(int)$id;$enabled=isset($_POST['support_enabled'])?1:0;$pdo=Database::connection();$q=$pdo->prepare("SELECT 1 FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE u.id=:u AND u.tenant_id IS NULL AND r.slug='commercial'");$q->execute(['u'=>$uid]);if(!$q->fetchColumn())HttpException::abort(422,'Usuário comercial não encontrado.');$pdo->prepare('INSERT INTO commercial_profiles(user_id,commission_percent,max_discount_percent,active,support_enabled,created_at,updated_at)VALUES(:u,0,0,1,:enabled,NOW(),NOW()) ON DUPLICATE KEY UPDATE support_enabled=VALUES(support_enabled),updated_at=NOW()')->execute(['u'=>$uid,'enabled'=>$enabled]);if(!$enabled)$pdo->prepare("UPDATE support_tickets SET assigned_to=NULL,status=IF(status='in_progress','open',status),updated_at=NOW() WHERE assigned_to=:u AND status NOT IN('resolved','closed')")->execute(['u'=>$uid]);Audit::log('COMMERCIAL_SUPPORT_PERMISSION_UPDATED','users',$uid,null,['enabled'=>(bool)$enabled]);header('Location: /master/users/'.$uid.'/edit?support_saved=1');exit;}
    public function blockUser(string $id):void{$this->master();CSRF::enforce();$uid=(int)$id;if($uid===Auth::user()['id'])HttpException::abort(422,'Você não pode bloquear sua própria conta por esta tela.');$reason=trim((string)($_POST['reason']??''));if(strlen($reason)<3)HttpException::abort(422,'Informe o motivo.');$pdo=Database::connection();$q=$pdo->prepare('SELECT tenant_id,status FROM users WHERE id=:id');$q->execute(['id'=>$uid]);$u=$q->fetch();if(!$u)HttpException::abort(404,'Usuário não encontrado.');$pdo->beginTransaction();try{$pdo->prepare("UPDATE users SET status='blocked',session_version=session_version+1,updated_at=NOW() WHERE id=:id")->execute(['id'=>$uid]);$pdo->prepare("INSERT INTO user_blocks(user_id,tenant_id,reason_code,reason_text,blocked_by,blocked_at)VALUES(:u,:t,'MANUAL',:r,:b,NOW())")->execute(['u'=>$uid,'t'=>$u['tenant_id'],'r'=>$reason,'b'=>Auth::user()['id']]);$pdo->commit();Audit::log('USER_BLOCKED','users',$uid,$u,['reason'=>$reason]);}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}header('Location: /master/blocked');exit;}
    public function unblockUser(string $id):void{$this->master();CSRF::enforce();$uid=(int)$id;$pdo=Database::connection();$pdo->beginTransaction();try{$pdo->prepare("UPDATE users SET status='active',session_version=session_version+1,updated_at=NOW() WHERE id=:id")->execute(['id'=>$uid]);$pdo->prepare('UPDATE user_blocks SET unblocked_by=:b,unblocked_at=NOW() WHERE user_id=:u AND unblocked_at IS NULL')->execute(['b'=>Auth::user()['id'],'u'=>$uid]);$pdo->commit();Audit::log('USER_UNBLOCKED','users',$uid);}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}header('Location: /master/blocked');exit;}
    public function blocked():void{$this->master();$rows=Database::connection()->query("SELECT u.id,u.name,u.email,u.status,t.name tenant_name,ub.reason_code,ub.reason_text,ub.blocked_at,ub.expires_at,bu.name blocked_by_name FROM users u LEFT JOIN tenants t ON t.id=u.tenant_id LEFT JOIN user_blocks ub ON ub.id=(SELECT MAX(ub2.id) FROM user_blocks ub2 WHERE ub2.user_id=u.id AND ub2.unblocked_at IS NULL) LEFT JOIN users bu ON bu.id=ub.blocked_by WHERE u.status='blocked' ORDER BY ub.blocked_at DESC")->fetchAll();View::render('master/blocked',['title'=>'Usuários bloqueados','rows'=>$rows]);}
    public function loginAudit():void{Auth::requireLogin();Authorization::require('master.login_audit.view');$result=(string)($_GET['result']??'');$email=trim((string)($_GET['email']??''));$sql='SELECT la.*,t.name tenant_name,u.name user_name FROM login_audit la LEFT JOIN tenants t ON t.id=la.tenant_id LEFT JOIN users u ON u.id=la.user_id WHERE 1=1';$params=[];if(in_array($result,['success','failure'],true)){$sql.=' AND la.result=:r';$params['r']=$result;}if($email!==''){$sql.=' AND la.email_attempted LIKE :email';$params['email']='%'.$email.'%';}$sql.=' ORDER BY la.created_at DESC LIMIT 500';$q=Database::connection()->prepare($sql);$q->execute($params);View::render('master/login-audit',['title'=>'Auditoria de login','rows'=>$q->fetchAll(),'result'=>$result,'email'=>$email]);}
    public function payments():void{$this->master();$rows=Database::connection()->query("SELECT pay.*,t.name tenant_name,p.name plan_name FROM payments pay JOIN tenants t ON t.id=pay.tenant_id LEFT JOIN subscriptions s ON s.id=pay.subscription_id LEFT JOIN plans p ON p.id=s.plan_id ORDER BY pay.created_at DESC LIMIT 500")->fetchAll();View::render('master/payments',['title'=>'Pagamentos','payments'=>$rows]);}

    public function systemHealth(): void
    {
        $this->master();$pdo=Database::connection();$checks=[];
        try{$pdo->query('SELECT 1')->fetchColumn();$checks['Banco']=['ok','Conectado'];}catch(\Throwable){$checks['Banco']=['error','Indisponível'];}
        $storage=realpath(__DIR__.'/../../storage')?:__DIR__.'/../../storage';$writable=is_writable($storage);$checks['Armazenamento']=[$writable?'ok':'error',$writable?'Gravável':'Sem permissão de escrita'];
        $free=@disk_free_space($storage);$checks['Disco']=[$free!==false&&$free>536870912?'ok':'warning',$free!==false?number_format($free/1073741824,1,',','.').' GB livres':'Não detectado'];
        $checks['PHP']=[version_compare(PHP_VERSION,'8.2.0','>=')?'ok':'error',PHP_VERSION];foreach(['curl','openssl','mbstring','pdo_mysql','fileinfo'] as $ext)$checks['PHP '.$ext]=[extension_loaded($ext)?'ok':'error',extension_loaded($ext)?'Ativo':'Ausente'];
        try{$cron=$pdo->query("SELECT setting_value FROM settings WHERE tenant_id IS NULL AND setting_key='cron.last_run_at' ORDER BY id DESC LIMIT 1")->fetchColumn();$fresh=$cron&&strtotime((string)$cron)>time()-900;$checks['Cron']=[$fresh?'ok':'warning',$cron?'Última execução: '.$cron:'Nunca registrado'];}catch(\Throwable){$checks['Cron']=['warning','Ainda não configurado'];}
        try{$queued=(int)$pdo->query("SELECT COUNT(*) FROM jobs WHERE status='queued' AND available_at<=NOW()")->fetchColumn();$failed=(int)$pdo->query("SELECT COUNT(*) FROM jobs WHERE status='failed'")->fetchColumn();$checks['Fila']=[$failed>0?'error':($queued<100?'ok':'warning'),$queued.' pendente(s), '.$failed.' falho(s)'];}catch(\Throwable){$checks['Fila']=['warning','Não disponível'];}
        try{$backup=$pdo->query("SELECT status,completed_at,size_bytes FROM backups ORDER BY id DESC LIMIT 1")->fetch();if(!$backup){$checks['Backup']=['warning','Nenhum backup executado'];}else{$backupFresh=$backup['status']==='completed'&&!empty($backup['completed_at'])&&strtotime((string)$backup['completed_at'])>time()-93600;$bStatus=$backup['status']==='failed'?'error':($backupFresh?'ok':'warning');$bText=$backup['status']==='completed'?'Último: '.$backup['completed_at'].' • '.number_format(((int)$backup['size_bytes'])/1048576,1,',','.').' MB':('Situação: '.$backup['status']);$checks['Backup']=[$bStatus,$bText];}}catch(\Throwable){$checks['Backup']=['warning','Estrutura ainda não inicializada'];}
        $https=!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off';$checks['HTTPS']=[$https?'ok':'warning',$https?'Ativo':'Não detectado'];$app=require __DIR__.'/../../config/app.php';$checks['Depuração']=[empty($app['debug'])?'ok':'error',empty($app['debug'])?'Desativada':'ATIVA'];
        try{$mp=$pdo->query("SELECT environment,last_test_status,active,last_tested_at FROM payment_gateways WHERE provider='mercadopago' ORDER BY (environment='production') DESC,last_tested_at DESC LIMIT 1")->fetch();if(!$mp){$checks['Mercado Pago']=['warning','Não configurado'];}else{$checks['Mercado Pago']=[($mp['last_test_status']==='validated'&&$mp['active'])?'ok':'warning',($mp['environment']==='production'?'Produção':'Teste').' · '.($mp['last_test_status']==='validated'?'validado':'não validado')];}}catch(\Throwable){$checks['Mercado Pago']=['warning','Execute as migrations da versão atual'];}
        try{$email=PlatformSetting::secret('platform.marketing_email');$checks['E-mail']=[!empty($email['host'])&&!empty($email['from_email'])?'ok':'warning',!empty($email['host'])?'Configurado':'Não configurado'];$wa=PlatformSetting::secret('platform.whatsapp');$checks['WhatsApp']=[!empty($wa['phone_number_id'])&&!empty($wa['access_token'])?'ok':'warning',!empty($wa['phone_number_id'])?'Configurado':'Não configurado'];}catch(\Throwable){$checks['E-mail']=['warning','Não configurado'];$checks['WhatsApp']=['warning','Não configurado'];}
        try{$legalOk=(string)PlatformSetting::get('legal.legal_name','')!==''&&(string)PlatformSetting::get('legal.document','')!==''&&(string)PlatformSetting::get('legal.support_email','')!=='';$terms=(int)$pdo->query("SELECT COUNT(*) FROM legal_documents WHERE type='terms' AND status='published'")->fetchColumn();$privacy=(int)$pdo->query("SELECT COUNT(*) FROM legal_documents WHERE type='privacy' AND status='published'")->fetchColumn();$checks['Documentos legais']=[($legalOk&&$terms&&$privacy)?'ok':'warning',($legalOk&&$terms&&$privacy)?'Publicados e identificados':'Complete a identificação e publique Termos/Privacidade'];}catch(\Throwable){$checks['Documentos legais']=['warning','Execute a migration 016 e configure a identificação jurídica'];}
        $app=require __DIR__.'/../../config/app.php';View::render('master/system-health',['title'=>'Saúde do sistema','checks'=>$checks,'appVersion'=>$app['version']??'4.0.0 RC']);
    }


    public function analytics():void
    {
        $this->master();$pdo=Database::connection();
        $rows=$pdo->query("SELECT t.id,t.name,t.status,t.onboarding_step,t.created_at,MAX(u.last_login_at) last_login_at,COUNT(DISTINCT a.id) appointments_30d,COUNT(DISTINCT p.id) professionals_count,COUNT(DISTINCT c.id) customers_count,pl.name plan_name,s.status subscription_status,s.trial_ends_at,s.next_billing_at FROM tenants t LEFT JOIN users u ON u.tenant_id=t.id LEFT JOIN appointments a ON a.tenant_id=t.id AND a.starts_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) LEFT JOIN professionals p ON p.tenant_id=t.id AND p.active=1 LEFT JOIN customers c ON c.tenant_id=t.id AND c.status='active' LEFT JOIN subscriptions s ON s.id=(SELECT MAX(s2.id) FROM subscriptions s2 WHERE s2.tenant_id=t.id) LEFT JOIN plans pl ON pl.id=s.plan_id WHERE t.deleted_at IS NULL GROUP BY t.id,pl.name,s.status,s.trial_ends_at,s.next_billing_at ORDER BY t.id DESC")->fetchAll();
        foreach($rows as &$r){$risk=0;$reasons=[];if(!$r['last_login_at']||strtotime($r['last_login_at'])<strtotime('-14 days')){$risk+=40;$reasons[]='sem login recente';}if((int)$r['appointments_30d']===0){$risk+=35;$reasons[]='sem agendamentos em 30 dias';}if((int)$r['onboarding_step']<8){$risk+=20;$reasons[]='onboarding incompleto';}if($r['subscription_status']==='past_due'){$risk+=50;$reasons[]='inadimplente';}$r['risk_score']=min(100,$risk);$r['risk_reasons']=implode(', ',$reasons)?:'uso saudável';}
        $events=$pdo->query("SELECT event_type,status,COUNT(*) total FROM platform_automation_log WHERE created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY) GROUP BY event_type,status ORDER BY event_type,status")->fetchAll();
        View::render('master/analytics',['title'=>'Operação comercial','tenants'=>$rows,'automationStats'=>$events]);
    }

    public function errors():void
    {
        $this->master();$search=trim((string)($_GET['q']??''));$rows=ErrorLogService::recent(120,$search?:null);View::render('master/errors',['title'=>'Central de erros','rows'=>$rows,'search'=>$search]);
    }

    public function automationLogs():void
    {
        $this->master();$pdo=Database::connection();$rows=$pdo->query("SELECT pal.*,t.name tenant_name,c.name customer_name FROM platform_automation_log pal JOIN tenants t ON t.id=pal.tenant_id JOIN customers c ON c.id=pal.customer_id ORDER BY pal.id DESC LIMIT 500")->fetchAll();$notifications=$pdo->query("SELECT n.*,t.name tenant_name,c.name customer_name FROM notifications n JOIN tenants t ON t.id=n.tenant_id LEFT JOIN customers c ON c.id=n.customer_id ORDER BY n.id DESC LIMIT 500")->fetchAll();View::render('master/automation-logs',['title'=>'Logs de automação','rows'=>$rows,'notifications'=>$notifications]);
    }

    public function savePlanAutomation(string $id):void
    {
        $this->master();CSRF::enforce();$planId=(int)$id;$pdo=Database::connection();$q=$pdo->prepare('SELECT features_json FROM plans WHERE id=:id');$q->execute(['id'=>$planId]);$raw=$q->fetchColumn();if($raw===false)HttpException::abort(404,'Plano não encontrado.');$features=json_decode((string)$raw,true)?:[];$features['automation_return']=isset($_POST['automation_return']);$features['automation_birthday']=isset($_POST['automation_birthday']);$features['automation_manual']=isset($_POST['automation_manual']);$features['automation_email']=isset($_POST['automation_email']);$features['automation_whatsapp']=isset($_POST['automation_whatsapp']);$features['automation_daily_limit']=max(1,min(5000,(int)($_POST['automation_daily_limit']??50)));$pdo->prepare('UPDATE plans SET features_json=:features,updated_at=NOW() WHERE id=:id')->execute(['features'=>json_encode($features,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),'id'=>$planId]);Audit::log('MASTER_PLAN_AUTOMATION_SAVED','plans',$planId,null,$features);header('Location: /master/plans/'.$planId.'/edit?automation_saved=1');exit;
    }

    private function slug(string $v):string{$v=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$v)?:$v;return trim(preg_replace('/[^a-z0-9]+/','-',strtolower($v)),'-')?:'plano';}
    private function money(mixed $v):?float{if($v===''||$v===null)return null;$n=filter_var(str_replace(',','.',(string)$v),FILTER_VALIDATE_FLOAT);return $n===false||$n<0?null:(float)$n;}
}
