<?php
$total=(float)($services['revenue']??0)+(float)($sales['revenue']??0);$serviceQty=(int)($services['qty']??0);$avg=$serviceQty>0?(float)($services['avg_ticket']??0):0;$target=(float)($goal['revenue_target']??0);$progress=$target>0?min(100,round($total/$target*100,1)):0;
$modelLabels=['commission'=>'Comissão','chair_rent'=>'Aluguel mensal de cadeira','daily_rent'=>'Diária de cadeira','hybrid'=>'Híbrido'];$model=$compensation['model']??'commission';
?>
<div class="section-heading"><div><div class="eyebrow">Produção</div><h1>Meu desempenho</h1><p class="text-secondary mb-0">Indicadores do mês atual, produção, comissão e metas.</p></div><?php if(!empty($barberMode)):?><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="/barber/commands">Comandas</a><a class="btn btn-outline-primary" href="/barber/goals">Metas</a></div><?php endif;?></div>
<div class="row g-3 mb-4">
<div class="col-md-4 col-xl-2"><div class="card metric-card h-100"><div class="card-body"><div class="metric-label">Serviços</div><div class="metric-value"><?=$serviceQty?></div><small>R$ <?=number_format((float)$services['revenue'],2,',','.')?></small></div></div></div>
<div class="col-md-4 col-xl-2"><div class="card metric-card h-100"><div class="card-body"><div class="metric-label">Produtos</div><div class="metric-value"><?=(int)($sales['qty']??0)?></div><small>R$ <?=number_format((float)$sales['revenue'],2,',','.')?></small></div></div></div>
<div class="col-md-4 col-xl-2"><div class="card metric-card h-100"><div class="card-body"><div class="metric-label">Produção total</div><div class="metric-value">R$ <?=number_format($total,2,',','.')?></div><small>Serviços + produtos</small></div></div></div>
<div class="col-md-4 col-xl-2"><div class="card metric-card h-100"><div class="card-body"><div class="metric-label">Ticket médio</div><div class="metric-value">R$ <?=number_format($avg,2,',','.')?></div><small>Por atendimento concluído</small></div></div></div>
<div class="col-md-4 col-xl-2"><div class="card metric-card h-100"><div class="card-body"><div class="metric-label">Comissão pendente</div><div class="metric-value">R$ <?=number_format((float)($commissions['pending']??0),2,',','.')?></div><small>Pago no mês: R$ <?=number_format((float)($commissions['paid']??0),2,',','.')?></small></div></div></div>
<div class="col-md-4 col-xl-2"><div class="card metric-card h-100"><div class="card-body"><div class="metric-label">No-show</div><div class="metric-value"><?=(int)$noShow?></div><small>Ausências no mês</small></div></div></div>
</div>
<?php if(!empty($barberMode)):?>
<div class="row g-3">
<div class="col-lg-7"><div class="card h-100"><div class="card-body"><h2 class="h5">Meta mensal</h2><?php if($goal):?><div class="d-flex justify-content-between mb-2"><span>Meta de produção</span><strong>R$ <?=number_format($target,2,',','.')?></strong></div><div class="progress mb-2" role="progressbar" aria-valuenow="<?=$progress?>" aria-valuemin="0" aria-valuemax="100"><div class="progress-bar" style="width:<?=$progress?>%"><?=$progress?>%</div></div><small class="text-secondary">Produção atual: R$ <?=number_format($total,2,',','.')?> · Meta de serviços: <?=(int)($goal['services_target']??0)?> · Meta de produtos: R$ <?=number_format((float)($goal['products_target']??0),2,',','.')?></small><?php else:?><div class="empty-state">Nenhuma meta foi configurada para este mês.</div><?php endif;?></div></div></div>
<div class="col-lg-5"><div class="card h-100"><div class="card-body"><h2 class="h5">Modelo de trabalho</h2><div class="h4 mb-2"><?=htmlspecialchars($modelLabels[$model]??$model,ENT_QUOTES,'UTF-8')?></div><?php if($model==='commission'):?><p class="mb-0 text-secondary">Comissão padrão de serviços: <?=number_format($commission,2,',','.')?>%. Regras específicas por serviço podem substituir esse percentual.</p><?php elseif($model==='chair_rent'):?><p class="mb-0 text-secondary">Aluguel mensal: R$ <?=number_format((float)($compensation['monthly_rent']??0),2,',','.')?>.</p><?php elseif($model==='daily_rent'):?><p class="mb-0 text-secondary">Diária: R$ <?=number_format((float)($compensation['daily_rent']??0),2,',','.')?> por dia trabalhado.</p><?php else:?><p class="mb-0 text-secondary">Aluguel mensal: R$ <?=number_format((float)($compensation['monthly_rent']??0),2,',','.')?> + comissão configurada.</p><?php endif;?></div></div></div>
</div>
<?php endif;?>
