<div class="section-heading"><div><div class="eyebrow">Inteligência de retorno</div><h1>Oportunidades de relacionamento</h1><p class="text-secondary mb-0">Transforme padrões de atendimento em retornos, mantendo consentimento e histórico de cada disparo.</p></div></div>
<?php if(isset($_GET['sent'])):?><div class="alert alert-success">Mensagem para <strong><?=htmlspecialchars((string)($_GET['customer']??'o cliente'))?></strong> adicionada à fila de <?=($_GET['channel']??'')==='whatsapp'?'WhatsApp':'e-mail'?>.</div><?php endif;?>
<div class="row g-3 mb-4"><?php foreach([['Oportunidades',$summary['total'],'primary'],['Atrasados',$summary['overdue'],'danger'],['Próximos',$summary['due_soon'],'warning'],['Receita potencial','R$ '.number_format((float)$summary['potential'],2,',','.'),'success']] as [$label,$value,$color]):?><div class="col-6 col-xl-3"><div class="card h-100"><div class="card-body"><div class="metric-label"><?=htmlspecialchars($label)?></div><div class="metric-value fs-4 text-<?=$color?>"><?=htmlspecialchars((string)$value)?></div></div></div></div><?php endforeach;?></div>
<?php if(!$channels['email']&&!$channels['whatsapp']):?><div class="alert alert-warning"><strong>Disparo indisponível.</strong> O Master precisa liberar o disparo manual no plano e configurar ao menos e-mail ou WhatsApp nas integrações.</div><?php endif;?>
<div class="card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Cliente e contato</th><th>Histórico</th><th>Previsão</th><th>Preferência recente</th><th>Confiança</th><th class="text-end">Ações</th></tr></thead><tbody>
<?php foreach($items as $i):$overdue=($i['opportunity_type']??'')==='overdue';$phone=preg_replace('/\D/','',(string)($i['phone']??''));$canContact=!empty($i['consent_marketing'])&&(($channels['email']&&filter_var($i['email']??'',FILTER_VALIDATE_EMAIL))||($channels['whatsapp']&&preg_match('/^\d{10,13}$/',$phone)));?>
<tr><td><strong><?=htmlspecialchars($i['name']??'Cliente')?></strong><small class="d-block text-secondary"><?=htmlspecialchars($i['phone']?:'Sem telefone')?><?=!empty($i['email'])?' · '.htmlspecialchars($i['email']):''?></small><span class="badge <?=$i['consent_marketing']?'text-bg-success':'text-bg-secondary'?> mt-1"><?=$i['consent_marketing']?'Contato autorizado':'Sem consentimento'?></span></td>
<td><strong><?=(int)($i['visits_count']??0)?> visitas</strong><small class="d-block text-secondary">Última: <?=$i['last_visit_at']?date('d/m/Y',strtotime($i['last_visit_at'])):'-'?></small><small class="d-block text-secondary">Média: <?=number_format((float)($i['avg_interval_days']??0),1,',','.')?> dias</small></td>
<td><span class="badge <?=$overdue?'text-bg-danger':'text-bg-warning'?>"><?=$overdue?'Atrasado '.max(0,(int)$i['days_overdue']).' dia(s)':'Retorno próximo'?></span><small class="d-block mt-1">Previsto: <?=$i['next_expected_date']?date('d/m/Y',strtotime($i['next_expected_date'])):'-'?></small></td>
<td><strong><?=htmlspecialchars($i['last_service_name']??'Não identificado')?></strong><small class="d-block text-secondary"><?=htmlspecialchars($i['last_professional_name']??'Sem preferência')?><?php if($i['service_price_snapshot']!==null):?> · R$ <?=number_format((float)$i['service_price_snapshot'],2,',','.')?><?php endif;?></small></td>
<td><div class="progress" style="min-width:90px;height:8px"><div class="progress-bar" style="width:<?=min(100,(int)$i['confidence_score'])?>%"></div></div><small><?=(int)$i['confidence_score']?>%</small></td>
<td class="text-end"><div class="d-flex gap-1 justify-content-end flex-wrap"><a class="btn btn-sm btn-outline-primary" href="/customers/<?=(int)$i['id']?>">Ver detalhes</a><?php if($canContact):?><button class="btn btn-sm btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#message-<?=(int)$i['id']?>">Enviar mensagem</button><?php else:?><button class="btn btn-sm btn-secondary" disabled>Envio indisponível</button><?php endif;?></div></td></tr>
<?php if($canContact):?><tr class="collapse" id="message-<?=(int)$i['id']?>"><td colspan="6" class="bg-body-tertiary"><form method="post" action="/intelligence/<?=(int)$i['id']?>/send" class="row g-2 align-items-end"><?=\App\Core\CSRF::field()?><div class="col-md-2"><label class="form-label">Canal</label><select class="form-select" name="channel"><?php if($channels['whatsapp']&&preg_match('/^\d{10,13}$/',$phone)):?><option value="whatsapp">WhatsApp</option><?php endif;?><?php if($channels['email']&&filter_var($i['email']??'',FILTER_VALIDATE_EMAIL)):?><option value="email">E-mail</option><?php endif;?></select></div><div class="col-md-8"><label class="form-label">Mensagem para <?=htmlspecialchars($i['name'])?></label><textarea class="form-control" name="message" rows="3" minlength="10" maxlength="1500" required>Olá {cliente}, sentimos sua falta na {empresa}! Seu período habitual de retorno chegou. Veja os horários disponíveis e agende: {link}</textarea><small class="text-secondary">Variáveis: {cliente}, {empresa} e {link}.</small></div><div class="col-md-2"><button class="btn btn-primary w-100">Adicionar à fila</button></div></form></td></tr><?php endif;?>
<?php endforeach;?><?php if(!$items):?><tr><td colspan="6" class="text-center py-5 text-secondary">Nenhuma oportunidade agora. Conclua atendimentos para aumentar a precisão do motor.</td></tr><?php endif;?></tbody></table></div></div>
