<?php
namespace App\Services;
use App\Core\{Database,Encryption};
final class GrowthService
{
 public static function sessionKey():string{$key=(string)($_SESSION['growth_session']??'');if(!preg_match('/^[a-f0-9]{40}$/',$key)){$key=bin2hex(random_bytes(20));$_SESSION['growth_session']=$key;}return$key;}
 public static function captureAttribution():array{$keys=['utm_source'=>'source','utm_medium'=>'medium','utm_campaign'=>'campaign','utm_content'=>'content','utm_term'=>'term'];$data=(array)($_SESSION['growth_attribution']??[]);foreach($keys as $query=>$field)if(isset($_GET[$query]))$data[$field]=mb_substr(preg_replace('/[^\pL\pN._-]/u','',(string)$_GET[$query]),0,120);if(isset($_GET['segment']))$data['segment']=self::segment((string)$_GET['segment']);if($data)$_SESSION['growth_attribution']=$data;return$data;}
 public static function record(string $name,array $extra=[],?int $tenantId=null,?int $userId=null,?string $eventId=null,bool $meta=false):string
 {
  $pdo=Database::connection();$attr=self::captureAttribution();$eventId=$eventId&&preg_match('/^[a-zA-Z0-9_-]{8,80}$/',$eventId)?mb_substr($eventId,0,36):self::uuid();$url=mb_substr((string)(($_SERVER['REQUEST_SCHEME']??'https').'://'.($_SERVER['HTTP_HOST']??'').($_SERVER['REQUEST_URI']??'')),0,500);$ip=(string)($_SERVER['REMOTE_ADDR']??'');$ua=(string)($_SERVER['HTTP_USER_AGENT']??'');$consent=($_SESSION['marketing_consent']??false)===true;
  if(!$consent&&$tenantId){$q=$pdo->prepare('SELECT marketing_consent FROM acquisition_events WHERE tenant_id=:t AND marketing_consent=1 ORDER BY id DESC LIMIT 1');$q->execute(['t'=>$tenantId]);$consent=(bool)$q->fetchColumn();}
  $pdo->prepare('INSERT IGNORE INTO acquisition_events(session_key,event_id,event_name,tenant_id,user_id,segment,source,medium,campaign,content,term,event_url,referrer,client_ip_hash,user_agent_hash,marketing_consent,value_amount,currency,created_at)VALUES(:session,:eid,:name,:tenant,:user,:segment,:source,:medium,:campaign,:content,:term,:url,:referrer,:ip,:ua,:consent,:value,:currency,NOW())')->execute(['session'=>self::sessionKey(),'eid'=>$eventId,'name'=>mb_substr($name,0,50),'tenant'=>$tenantId,'user'=>$userId,'segment'=>$extra['segment']??$attr['segment']??null,'source'=>$attr['source']??null,'medium'=>$attr['medium']??null,'campaign'=>$attr['campaign']??null,'content'=>$attr['content']??null,'term'=>$attr['term']??null,'url'=>$url,'referrer'=>mb_substr((string)($_SERVER['HTTP_REFERER']??''),0,500),'ip'=>$ip!==''?hash('sha256',$ip):null,'ua'=>$ua!==''?hash('sha256',$ua):null,'consent'=>$consent?1:0,'value'=>isset($extra['value'])?round((float)$extra['value'],2):null,'currency'=>$extra['currency']??'BRL']);if($meta&&$consent)self::queueMeta($name,$eventId,$extra+['event_url'=>$url,'ip'=>$ip,'user_agent'=>$ua]);return$eventId;
 }
 public static function queueMeta(string $name,string $eventId,array $data):void{$pdo=Database::connection();if(!PlatformSetting::secret('growth.meta_capi'))return;$pdo->prepare("INSERT IGNORE INTO meta_conversion_log(event_id,event_name,status,created_at)VALUES(:id,:name,'queued',NOW())")->execute(['id'=>$eventId,'name'=>$name]);if(!$pdo->lastInsertId())return;$payload=Encryption::encrypt(['event_name'=>$name,'event_id'=>$eventId,'event_time'=>time(),'event_source_url'=>$data['event_url']??null,'client_ip_address'=>$data['ip']??null,'client_user_agent'=>$data['user_agent']??null,'email'=>$data['email']??null,'phone'=>$data['phone']??null,'value'=>$data['value']??null,'currency'=>$data['currency']??'BRL']);$pdo->prepare("INSERT INTO jobs(tenant_id,type,payload_encrypted,status,attempts,available_at,created_at,updated_at)VALUES(NULL,'meta.capi',:p,'queued',0,NOW(),NOW(),NOW())")->execute(['p'=>$payload]);}
 public static function segment(string $value):?string{$value=mb_strtolower(trim($value));return in_array($value,['barber','arena','auto','estetica','saude','salao'],true)?$value:null;}
 private static function uuid():string{$d=random_bytes(16);$d[6]=chr((ord($d[6])&15)|64);$d[8]=chr((ord($d[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4));}
}
