<?php
$pricing=$modulePricing??[];
$cycle=(string)($subscription['billing_cycle']??'monthly');
$cycleLabel=['monthly'=>'Mensal','quarterly'=>'Trimestral','semiannual'=>'Semestral','annual'=>'Anual'][$cycle]??ucfirst($cycle);
?>
<div class="section-heading"><div><div class="eyebrow">Cobrança</div><h1>Minha assinatura</h1><p class="text-secondary mb-0">Acompanhe seu plano, módulos, vencimentos e pagamentos.</p></div><div class="d-flex gap-2"><a class="btn btn-light" href="/billing/modulos">Solicitar módulos</a><a class="btn btn-primary" href="/billing/plans">Ver planos superiores</a></div></div>
<?php if(!empty($_SESSION['billing_notice'])):?><div class="alert alert-warning"><strong>Acesso preservado.</strong> <?=htmlspecialchars($_SESSION['billing_notice'],ENT_QUOTES,'UTF-8')?></div><?php unset($_SESSION['billing_notice']);endif;?>
<?php if($subscription):?>
<div class="card mb-4"><div class="card-body">
<div class="d-flex flex-wrap justify-content-between gap-3"><div><span class="badge text-bg-primary"><?=htmlspecialchars(['trial'=>'Teste grátis','active'=>'Ativa','past_due'=>'Em atraso','suspended'=>'Suspensa','cancelled'=>'Cancelada'][$subscription['status']]??$subscription['status'],ENT_QUOTES,'UTF-8')?></span><h2 class="h3 mt-2 mb-1"><?=htmlspecialchars($subscription['plan_name'],ENT_QUOTES,'UTF-8')?></h2><p class="text-secondary mb-0">Próximo vencimento: <?=$subscription['next_billing_at']?date('d/m/Y',strtotime($subscription['next_billing_at'])):'—'?> · Ciclo: <?=$cycleLabel?></p></div><div class="text-end"><small class="text-secondary">Total contratado</small><div class="display-6">R$ <?=number_format((float)($pricing['total']??$subscription['contracted_price']),2,',','.')?></div></div></div>
<div class="row g-3 mt-3">
<div class="col-md-4"><div class="border rounded p-3 h-100"><small class="text-secondary">Plano/base</small><div class="h5 mb-0">R$ <?=number_format((float)($pricing['base']??$subscription['contracted_price']),2,',','.')?></div></div></div>
<div class="col-md-4"><div class="border rounded p-3 h-100"><small class="text-secondary">Módulos incorporados</small><div class="h5 mb-0">R$ <?=number_format((float)($pricing['addons']??0),2,',','.')?></div><small class="text-secondary">R$ <?=number_format((float)($pricing['monthly_addons']??0),2,',','.')?>/mês</small></div></div>
<div class="col-md-4"><div class="border rounded p-3 h-100"><small class="text-secondary">Assinatura <?=$cycleLabel?></small><div class="h5 mb-0">R$ <?=number_format((float)($pricing['total']??$subscription['contracted_price']),2,',','.')?></div></div></div>
</div>
<?php if(!empty($pricing['items'])):?><div class="mt-3"><strong>Módulos adicionais ativos</strong><div class="d-flex flex-wrap gap-2 mt-2"><?php foreach($pricing['items'] as $item):?><span class="badge <?=($item['billing_mode']??'separate')==='merged_subscription'?'text-bg-primary':'text-bg-warning'?>"><?=htmlspecialchars($item['name'])?> · R$ <?=number_format((float)$item['monthly_price'],2,',','.')?>/mês<?=($item['billing_mode']??'separate')==='merged_subscription'?'':' · cobrança antiga separada'?></span><?php endforeach;?></div></div><?php endif;?>
<?php if((float)($pricing['legacy_monthly']??0)>0):?><div class="alert alert-warning mt-3 mb-0">Há R$ <?=number_format((float)$pricing['legacy_monthly'],2,',','.')?>/mês em módulos antigos ainda cobrados separadamente. Novos módulos já entram na assinatura principal.</div><?php endif;?>
<div class="d-flex flex-wrap gap-2 mt-4"><a class="btn btn-primary" href="/checkout/<?=(int)$subscription['plan_id']?>">Pagar/assinar com cartão</a><?php if(!empty($pixEnabled)&&(\App\Core\Auth::user()['role']??'')==='owner'):?><form method="post" action="/billing/pix"><?php echo \App\Core\CSRF::field();?><button class="btn btn-success">Pagar com Pix<?=$pixDiscount>0?' — '.number_format($pixDiscount,1,',','.').'% de desconto':''?></button></form><?php endif;?><a class="btn btn-outline-primary" href="/billing/modulos">Gerenciar módulos</a></div>
</div></div>
<?php else:?><div class="alert alert-warning">Nenhuma assinatura encontrada. Escolha um plano para continuar.</div><?php endif;?>

<div class="card"><div class="card-header"><strong>Faturas</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Número</th><th>Valor</th><th>Vencimento</th><th>Status</th></tr></thead><tbody><?php foreach($invoices as $i):?><tr><td><?=htmlspecialchars($i['number'],ENT_QUOTES,'UTF-8')?></td><td>R$ <?=number_format((float)$i['amount'],2,',','.')?></td><td><?=date('d/m/Y',strtotime($i['due_at']))?></td><td><span class="badge text-bg-light"><?=htmlspecialchars($i['status'],ENT_QUOTES,'UTF-8')?></span></td></tr><?php endforeach;?><?php if(!$invoices):?><tr><td colspan="4"><div class="empty-state">Nenhuma fatura emitida.</div></td></tr><?php endif;?></tbody></table></div></div>

<?php if((\App\Core\Auth::user()['role']??'')==='owner'):?><div class="row g-4 mt-1"><div class="col-lg-6"><div class="card h-100 border-primary"><div class="card-body"><div class="eyebrow">Documento fiscal</div><h2 class="h5">Solicitar nota fiscal</h2><p class="text-secondary">A solicitação abre um chamado financeiro. Quando o Master anexar e concluir, o PDF ficará disponível aqui.</p><form method="post" action="/billing/solicitar-nota-fiscal"><?php echo \App\Core\CSRF::field();?><label class="form-label">Mês de referência</label><input class="form-control" type="month" name="reference_period" value="<?=date('Y-m')?>" required><button class="btn btn-primary mt-3">Solicitar nota fiscal</button></form></div></div></div><div class="col-lg-6"><div class="card h-100 border-danger"><div class="card-body"><div class="eyebrow">Encerramento</div><h2 class="h5">Solicitar exclusão da conta</h2><p class="text-secondary">A solicitação será analisada em até 5 dias. O Master verificará os pagamentos, cancelará a recorrência e inativará a empresa. Os dados não serão apagados automaticamente.</p><form method="post" action="/billing/solicitar-exclusao" onsubmit="return confirm('Deseja realmente abrir a solicitação de exclusão/inativação da conta?')"><?php echo \App\Core\CSRF::field();?><label class="form-label">Motivo da solicitação</label><textarea class="form-control" name="reason" minlength="10" rows="3" required></textarea><button class="btn btn-outline-danger mt-3">Abrir solicitação</button></form></div></div></div></div><?php endif;?>

<div class="card mt-4"><div class="card-header"><strong>Solicitações financeiras e administrativas</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Protocolo</th><th>Solicitação</th><th>Referência/prazo</th><th>Status</th><th>Arquivo</th></tr></thead><tbody><?php foreach(($billingRequests??[]) as $request):?><tr><td><a href="/support/<?=(int)$request['ticket_id']?>"><?=htmlspecialchars($request['protocol'])?></a></td><td><?=$request['request_type']==='invoice'?'Nota fiscal':'Exclusão/inativação da conta'?></td><td><?php if($request['request_type']==='invoice'):?><?=htmlspecialchars(date('m/Y',strtotime($request['reference_period'].'-01')))?><?php else:?>até <?=date('d/m/Y',strtotime($request['deadline_at']))?><?php endif;?></td><td><span class="badge text-bg-light"><?=htmlspecialchars(['pending'=>'Em análise','completed'=>'Concluída','approved'=>'Aprovada','rejected'=>'Recusada','cancelled'=>'Cancelada'][$request['status']]??$request['status'])?></span></td><td><?php if(!empty($request['attachment_id'])):?><a class="btn btn-sm btn-success" href="/support/attachments/<?=(int)$request['attachment_id']?>">Baixar PDF</a><?php else:?>—<?php endif;?></td></tr><?php endforeach;?><?php if(empty($billingRequests)):?><tr><td colspan="5"><div class="empty-state">Nenhuma solicitação registrada.</div></td></tr><?php endif;?></tbody></table></div></div>

<div class="card mt-4"><div class="card-header"><strong>Pagamentos Pix</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Data</th><th>Valor</th><th>Validade</th><th>Status</th><th></th></tr></thead><tbody><?php foreach(($pixCharges??[]) as $pix):?><tr><td><?=date('d/m/Y H:i',strtotime($pix['created_at']))?></td><td>R$ <?=number_format((float)$pix['amount'],2,',','.')?></td><td><?=date('d/m/Y H:i',strtotime($pix['expires_at']))?></td><td><span class="badge <?=$pix['status']==='paid'?'text-bg-success':'text-bg-light'?>"><?=htmlspecialchars(['pending'=>'Aguardando','paid'=>'Pago','expired'=>'Expirado','cancelled'=>'Cancelado','failed'=>'Falhou'][$pix['status']]??$pix['status'])?></span></td><td><a class="btn btn-sm btn-outline-primary" href="/billing/pix/<?=htmlspecialchars($pix['public_id'])?>">Abrir</a></td></tr><?php endforeach;?><?php if(empty($pixCharges)):?><tr><td colspan="5"><div class="empty-state">Nenhuma cobrança Pix gerada.</div></td></tr><?php endif;?></tbody></table></div></div>
