<?php
use App\Core\CSRF;
$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$a=$settings['amenities']??[];
$amenities=['parking'=>'Estacionamento','locker_room'=>'Vestiário','shower'=>'Chuveiro','bar'=>'Bar','restaurant'=>'Restaurante/Lanchonete','wifi'=>'Wi‑Fi','stands'=>'Arquibancada','bbq'=>'Churrasqueira','equipment_rental'=>'Aluguel de equipamentos','accessibility'=>'Acessibilidade'];
$num=fn($key,$default)=>$e((string)($settings[$key]??$default));
?>
<div class="sports-head"><div><span class="sports-kicker">GESTÃO DA ARENA</span><h1>Configurações</h1><p>Reservas, preço dinâmico, lista de espera e automações da operação esportiva.</p></div><div class="d-flex gap-2 flex-wrap"><a class="btn btn-outline-primary" href="/sports/settings">Reserva pública e modalidades</a><?php if($bankingEnabled):?><a class="btn btn-outline-primary" href="/settings/banking">Bancos e Pagamentos</a><?php endif;?></div></div>
<?php if(isset($_GET['saved'])):?><div class="alert alert-success">Configurações da Arena atualizadas.</div><?php endif;?>
<form method="post" action="/sports/arena-settings"><?=CSRF::field()?>
<div class="row g-4">
  <div class="col-xl-6"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Reserva e pagamentos</h2>
    <label class="form-label">Prazo para pagar sinal (minutos)</label><input class="form-control mb-3" type="number" min="1" max="1440" name="payment_deadline_minutes" value="<?=$num('payment_deadline_minutes',10)?>">
    <label class="form-label">Janela exclusiva da lista de espera (minutos)</label><input class="form-control mb-3" type="number" min="1" max="1440" name="waitlist_offer_minutes" value="<?=$num('waitlist_offer_minutes',10)?>">
    <label class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="allow_waitlist" <?=!empty($settings['allow_waitlist'])?'checked':''?>> <span class="form-check-label">Ativar lista de espera pública</span></label>
    <div class="ms-4 mb-3"><label class="form-check"><input class="form-check-input" type="checkbox" name="waitlist_email_enabled" <?=!empty($settings['waitlist_email_enabled'])?'checked':''?>> E-mail quando houver vaga</label><label class="form-check"><input class="form-check-input" type="checkbox" name="waitlist_whatsapp_enabled" <?=!empty($settings['waitlist_whatsapp_enabled'])?'checked':''?>> WhatsApp quando houver vaga (se integração global estiver configurada)</label></div>
    <label class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="allow_games" <?=!empty($settings['allow_games'])?'checked':''?>> <span class="form-check-label">Permitir Rachas</span></label>
  </div></div></div>

  <div class="col-xl-6"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="d-flex justify-content-between align-items-start gap-3"><div><h2 class="h5 mb-1">Preço dinâmico</h2><p class="text-secondary small">O preço base continua vindo das regras da quadra. O motor abaixo aplica somente ajustes configurados e salva um snapshot na reserva.</p></div><label class="form-check form-switch"><input class="form-check-input" type="checkbox" name="dynamic_pricing_enabled" <?=!empty($settings['dynamic_pricing_enabled'])?'checked':''?>></label></div>
    <div class="row g-2"><div class="col-6"><label class="form-label">Multiplicador mínimo</label><input class="form-control" name="dynamic_min_multiplier" value="<?=$num('dynamic_min_multiplier','0.80')?>" inputmode="decimal"></div><div class="col-6"><label class="form-label">Multiplicador máximo</label><input class="form-control" name="dynamic_max_multiplier" value="<?=$num('dynamic_max_multiplier','1.30')?>" inputmode="decimal"></div>
    <div class="col-6"><label class="form-label">Última hora: até (h)</label><input class="form-control" type="number" min="0" max="168" name="dynamic_last_minute_hours" value="<?=$num('dynamic_last_minute_hours',4)?>"></div><div class="col-6"><label class="form-label">Desconto última hora (%)</label><input class="form-control" name="dynamic_last_minute_discount_percent" value="<?=$num('dynamic_last_minute_discount_percent',10)?>"></div>
    <div class="col-6"><label class="form-label">Alta ocupação a partir de (%)</label><input class="form-control" name="dynamic_high_occupancy_threshold" value="<?=$num('dynamic_high_occupancy_threshold',70)?>"></div><div class="col-6"><label class="form-label">Acréscimo alta ocupação (%)</label><input class="form-control" name="dynamic_high_occupancy_surcharge_percent" value="<?=$num('dynamic_high_occupancy_surcharge_percent',10)?>"></div>
    <div class="col-6"><label class="form-label">Baixa ocupação até (%)</label><input class="form-control" name="dynamic_low_occupancy_threshold" value="<?=$num('dynamic_low_occupancy_threshold',30)?>"></div><div class="col-6"><label class="form-label">Desconto baixa ocupação (%)</label><input class="form-control" name="dynamic_low_occupancy_discount_percent" value="<?=$num('dynamic_low_occupancy_discount_percent',5)?>"></div>
    <div class="col-6"><label class="form-label">Janela baixa procura (h)</label><input class="form-control" type="number" min="0" max="720" name="dynamic_low_demand_window_hours" value="<?=$num('dynamic_low_demand_window_hours',24)?>"></div><div class="col-6"><label class="form-label">Acréscimo fim de semana (%)</label><input class="form-control" name="dynamic_weekend_surcharge_percent" value="<?=$num('dynamic_weekend_surcharge_percent',0)?>"></div>
    <div class="col-6"><label class="form-label">Arredondar preço em</label><select class="form-select" name="dynamic_rounding_step"><?php foreach(['0.01'=>'Centavos','1'=>'R$ 1','5'=>'R$ 5','10'=>'R$ 10'] as $k=>$v):?><option value="<?=$k?>" <?=abs((float)($settings['dynamic_rounding_step']??.01)-(float)$k)<.001?'selected':''?>><?=$v?></option><?php endforeach;?></select></div></div>
    <div class="alert alert-light border small mt-3 mb-0">Ex.: preço base R$ 150. Se a ocupação estiver alta e o acréscimo configurado for 10%, o cliente verá R$ 165. O sistema nunca ultrapassa os multiplicadores mínimo/máximo.</div>
  </div></div></div>

  <div class="col-xl-6"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Automações</h2>
    <label class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="reservation_reminder_enabled" <?=!empty($settings['reservation_reminder_enabled'])?'checked':''?>> Lembrete de reserva</label><label class="form-label">Horas antes</label><input class="form-control mb-3" type="number" min="1" max="336" name="reservation_reminder_hours" value="<?=$num('reservation_reminder_hours',24)?>">
    <label class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="crm_return_enabled" <?=!empty($settings['crm_return_enabled'])?'checked':''?>> Campanha para cliente inativo</label><label class="form-label">Dias sem reservar</label><input class="form-control mb-3" type="number" min="7" max="365" name="crm_return_days" value="<?=$num('crm_return_days',30)?>">
    <label class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="idle_slot_campaign_enabled" <?=!empty($settings['idle_slot_campaign_enabled'])?'checked':''?>> Detectar horários ociosos</label><label class="form-label">Janela de análise (horas)</label><input class="form-control" type="number" min="1" max="336" name="idle_slot_hours_before" value="<?=$num('idle_slot_hours_before',24)?>">
    <div class="form-text">Envios externos passam pela fila de jobs já existente e só são enfileirados quando há destino/canal permitido.</div>
  </div></div></div>

  <div class="col-xl-6"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Comodidades</h2><div class="row g-2"><?php foreach($amenities as $key=>$label):?><div class="col-sm-6"><label class="form-check border rounded-3 p-3 h-100"><input class="form-check-input ms-0 me-2" type="checkbox" name="amenities[]" value="<?=$e($key)?>" <?=in_array($key,$a,true)?'checked':''?>> <span class="form-check-label"><?=$e($label)?></span></label></div><?php endforeach;?></div></div></div></div>
  <div class="col-md-6"><label class="form-label">Regras públicas</label><textarea class="form-control" rows="6" name="public_rules"><?=$e($settings['public_rules']??'')?></textarea></div><div class="col-md-6"><label class="form-label">Política de cancelamento</label><textarea class="form-control" rows="6" name="cancellation_policy"><?=$e($settings['cancellation_policy']??'')?></textarea></div>
</div><button class="btn btn-primary mt-4">Salvar configurações da Arena</button></form>
