# Generated by Django 5.2.17 on 2026-09-21 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_normalize_auth_state'),
        ('billing', '0006_tenant_payment_reconciliation'),
        ('tenants', '0004_normalize_index_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='commercial_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('business_type', models.CharField(max_length=100)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source', models.CharField(default='public_interest_form', max_length=80)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('in_service', 'Em atendimento'), ('contacted', 'Contatado'), ('qualified', 'Qualificado'), ('converted', 'Convertido'), ('lost', 'Perdido')], db_index=True, default='new', max_length=16)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('next_contact_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('contact_deadline_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_transferred_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('loss_reason', models.CharField(blank=True, max_length=255)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('consent_granted', models.BooleanField(default=False)),
                ('consent_version', models.CharField(blank=True, max_length=30)),
                ('consent_purpose', models.CharField(blank=True, max_length=255)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('consent_user_agent', models.CharField(blank=True, max_length=500)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('do_not_contact', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_leads', to=settings.AUTH_USER_MODEL)),
                ('last_transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Criado'), ('claimed', 'Assumido'), ('transferred', 'Transferido'), ('status_changed', 'Status alterado')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_lead_actions', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='commercial.lead')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeadPrivacyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Criado'), ('viewed', 'Visualizado'), ('exported', 'Exportado'), ('consent_updated', 'Consentimento atualizado'), ('do_not_contact', 'Não contatar'), ('anonymized', 'Anonimizado'), ('deleted', 'Excluído')], max_length=24)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_privacy_events', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_events', to='commercial.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('customer_name', models.CharField(blank=True, max_length=160)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('public_token', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviada'), ('viewed', 'Visualizada'), ('converted', 'Convertida'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], db_index=True, default='draft', max_length=16)),
                ('approval_status', models.CharField(choices=[('not_required', 'Não necessária'), ('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], db_index=True, default='not_required', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_ip_hash', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_proposals_approved', to=settings.AUTH_USER_MODEL)),
                ('base_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.plan')),
                ('commercial_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_proposals', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_proposals', to='billing.plan')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_proposals', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_hash', models.CharField(max_length=64)),
                ('proposal_snapshot', models.JSONField()),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('accepted_at', models.DateTimeField()),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance', to='commercial.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('projected', 'Projetada'), ('approved', 'Aprovada'), ('reversed', 'Estornada'), ('paid', 'Paga')], db_index=True, default='projected', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('hold_until', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('commercial_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_commissions', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_commissions', to='billing.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_commissions', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='commercial_commission_idx')],
                'constraints': [models.UniqueConstraint(fields=('commercial_user', 'tenant'), name='uq_commercial_commission_tenant')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'assigned_to', 'created_at'], name='commercial_lead_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='leadhistory',
            index=models.Index(fields=['lead', 'created_at'], name='commercial_lead_hist_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprivacyevent',
            index=models.Index(fields=['lead', 'created_at'], name='commercial_privacy_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['commercial_user', 'status', 'created_at'], name='commercial_prop_owner_idx'),
        ),
    ]
