# Generated by Django 5.2.17 on 2026-09-23 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_autocommanditem_created_at_autosettings_created_at'),
        ('scheduling', '0007_waiting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='auto.vehicle'),
        ),
    ]
