# Generated by Django 5.2.17 on 2026-09-30 01:15

from django.db import migrations, models


def enable_existing_reminders(apps,schema_editor):
    apps.get_model('scheduling','TenantScheduleSettings').objects.filter(reminder_2h_enabled=False).update(reminder_2h_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_appointmentsettlement_appointmentrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('public', 'Público'), ('professional_link', 'Link profissional'), ('internal', 'Interno'), ('whatsapp', 'WhatsApp'), ('campaign', 'Campanha'), ('api', 'API'), ('walk_in', 'Avulso')], default='internal', max_length=24),
        ),
        migrations.AlterField(
            model_name='tenantschedulesettings',
            name='reminder_2h_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(enable_existing_reminders,migrations.RunPython.noop),
    ]
