# Generated by Django 5.2.17 on 2026-09-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_alter_appointment_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_payment',
            field=models.CharField(choices=[('on_site', 'Na unidade'), ('partial', 'Sinal por Pix'), ('full', 'Total por Pix')], default='on_site', max_length=12, verbose_name='Pagamento do agendamento'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='booking_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor solicitado no agendamento'),
        ),
        migrations.AddField(
            model_name='tenantschedulesettings',
            name='allow_full_payment',
            field=models.BooleanField(default=False, verbose_name='Permitir pagamento total por Pix no agendamento'),
        ),
        migrations.AddField(
            model_name='tenantschedulesettings',
            name='allow_partial_payment',
            field=models.BooleanField(default=False, verbose_name='Permitir sinal por Pix no agendamento'),
        ),
        migrations.AddField(
            model_name='tenantschedulesettings',
            name='allow_pay_on_site',
            field=models.BooleanField(default=True, verbose_name='Permitir pagamento na unidade'),
        ),
        migrations.AddField(
            model_name='tenantschedulesettings',
            name='deposit_percent',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Percentual do sinal'),
        ),
    ]
