# Generated by Django 5.2.17 on 2026-09-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_appointment_booking_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantschedulesettings',
            name='online_booking_payments_enabled',
            field=models.BooleanField(default=False, verbose_name='Ativar cobrança online ao agendar'),
        ),
    ]
