# Generated by Django 5.2.17 on 2026-09-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_tenantschedulesettings_online_booking_payments_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='services_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
