# Generated by Django 5.2.17 on 2026-10-03 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_appointment_unit'),
        ('tenants', '0010_unit_public_and_schedule_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='tenants.unit'),
        ),
    ]
