CREATE TABLE IF NOT EXISTS financial_transactions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tenant_id BIGINT UNSIGNED NOT NULL,appointment_id BIGINT UNSIGNED NULL,type ENUM('income','expense') NOT NULL,description VARCHAR(190) NOT NULL,amount DECIMAL(12,2) NOT NULL,status ENUM('pending','paid','cancelled') NOT NULL DEFAULT 'pending',idempotency_key VARCHAR(100) NULL,due_at DATE NULL,paid_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,UNIQUE KEY uq_finance_idempotency(tenant_id,idempotency_key),INDEX idx_finance_period(tenant_id,status,due_at),CONSTRAINT fk_fin_tenant FOREIGN KEY(tenant_id)REFERENCES tenants(id),CONSTRAINT fk_fin_appointment FOREIGN KEY(appointment_id)REFERENCES appointments(id)ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS webhook_events(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,provider VARCHAR(60) NOT NULL,event_id VARCHAR(190) NOT NULL,signature_valid TINYINT(1) NOT NULL,payload_hash CHAR(64) NOT NULL,status ENUM('received','processed','rejected','failed') NOT NULL,received_at DATETIME NOT NULL,processed_at DATETIME NULL,UNIQUE KEY uq_webhook(provider,event_id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS campaigns(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tenant_id BIGINT UNSIGNED NOT NULL,name VARCHAR(150) NOT NULL,type ENUM('return','idle','inactive','birthday','promotion') NOT NULL,channel ENUM('email','whatsapp') NOT NULL,status ENUM('draft','queued','running','completed','cancelled') NOT NULL DEFAULT 'draft',message TEXT NOT NULL,created_by BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_campaign_tenant(tenant_id,status),CONSTRAINT fk_campaign_tenant FOREIGN KEY(tenant_id)REFERENCES tenants(id),CONSTRAINT fk_campaign_user FOREIGN KEY(created_by)REFERENCES users(id)ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS campaign_recipients(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tenant_id BIGINT UNSIGNED NOT NULL,campaign_id BIGINT UNSIGNED NOT NULL,customer_id BIGINT UNSIGNED NOT NULL,status ENUM('queued','sent','delivered','clicked','converted','failed','opted_out') NOT NULL DEFAULT 'queued',sent_at DATETIME NULL,converted_at DATETIME NULL,UNIQUE KEY uq_campaign_customer(campaign_id,customer_id),INDEX idx_recipient_tenant(tenant_id,status),CONSTRAINT fk_cr_campaign FOREIGN KEY(campaign_id)REFERENCES campaigns(id),CONSTRAINT fk_cr_customer FOREIGN KEY(customer_id)REFERENCES customers(id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS revenue_attributions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tenant_id BIGINT UNSIGNED NOT NULL,campaign_recipient_id BIGINT UNSIGNED NOT NULL,appointment_id BIGINT UNSIGNED NOT NULL,amount DECIMAL(12,2) NOT NULL DEFAULT 0,attributed_at DATETIME NOT NULL,UNIQUE KEY uq_attribution_appointment(appointment_id),INDEX idx_attribution_tenant(tenant_id,attributed_at),CONSTRAINT fk_attr_recipient FOREIGN KEY(campaign_recipient_id)REFERENCES campaign_recipients(id),CONSTRAINT fk_attr_appointment FOREIGN KEY(appointment_id)REFERENCES appointments(id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS customer_consents(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tenant_id BIGINT UNSIGNED NOT NULL,customer_id BIGINT UNSIGNED NOT NULL,type VARCHAR(60) NOT NULL,granted TINYINT(1) NOT NULL,version VARCHAR(30) NOT NULL,source VARCHAR(40) NOT NULL,ip_address VARCHAR(64) NULL,created_at DATETIME NOT NULL,INDEX idx_consent_customer(tenant_id,customer_id,type,created_at),CONSTRAINT fk_consent_customer FOREIGN KEY(customer_id)REFERENCES customers(id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS backups(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,type ENUM('database','files','full')NOT NULL,status ENUM('running','completed','failed')NOT NULL,destination VARCHAR(190)NOT NULL,size_bytes BIGINT UNSIGNED NULL,path VARCHAR(500)NULL,started_at DATETIME NOT NULL,completed_at DATETIME NULL,error_message VARCHAR(500)NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT IGNORE INTO permissions(slug,name)VALUES('finance.view','Visualizar financeiro'),('finance.manage','Gerenciar financeiro'),('campaigns.view','Visualizar campanhas'),('campaigns.manage','Gerenciar campanhas'),('settings.manage','Gerenciar integrações'),('privacy.manage','Gerenciar privacidade');
INSERT IGNORE INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.slug IN('owner','manager');
