ALTER TABLE plans ADD COLUMN description VARCHAR(500) NULL AFTER name;
ALTER TABLE plans ADD COLUMN quarterly_price DECIMAL(10,2) NULL AFTER monthly_price;
ALTER TABLE plans ADD COLUMN semiannual_price DECIMAL(10,2) NULL AFTER quarterly_price;
ALTER TABLE plans ADD COLUMN annual_price DECIMAL(10,2) NULL AFTER semiannual_price;
ALTER TABLE plans ADD COLUMN trial_days SMALLINT UNSIGNED NOT NULL DEFAULT 14 AFTER annual_price;
ALTER TABLE plans ADD COLUMN trial_without_card TINYINT(1) NOT NULL DEFAULT 1 AFTER trial_days;
ALTER TABLE plans ADD COLUMN featured TINYINT(1) NOT NULL DEFAULT 0 AFTER active;
ALTER TABLE plans ADD COLUMN sort_order SMALLINT NOT NULL DEFAULT 0 AFTER featured;
ALTER TABLE subscriptions ADD COLUMN billing_cycle ENUM('monthly','quarterly','semiannual','annual') NOT NULL DEFAULT 'monthly' AFTER plan_id;
ALTER TABLE subscriptions ADD COLUMN contracted_price DECIMAL(10,2) NULL AFTER billing_cycle;
ALTER TABLE subscriptions ADD COLUMN trial_ends_at DATETIME NULL AFTER started_at;
ALTER TABLE subscriptions MODIFY status ENUM('trial','active','past_due','suspended','cancelled') NOT NULL DEFAULT 'trial';

CREATE TABLE IF NOT EXISTS tenant_onboarding(tenant_id BIGINT UNSIGNED PRIMARY KEY,company_done TINYINT(1)NOT NULL DEFAULT 0,branding_done TINYINT(1)NOT NULL DEFAULT 0,unit_done TINYINT(1)NOT NULL DEFAULT 0,professional_done TINYINT(1)NOT NULL DEFAULT 0,service_done TINYINT(1)NOT NULL DEFAULT 0,schedule_done TINYINT(1)NOT NULL DEFAULT 0,payment_done TINYINT(1)NOT NULL DEFAULT 0,public_page_done TINYINT(1)NOT NULL DEFAULT 0,completed_at DATETIME NULL,updated_at DATETIME NOT NULL,CONSTRAINT fk_onboarding_tenant FOREIGN KEY(tenant_id)REFERENCES tenants(id)ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS product_events(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tenant_id BIGINT UNSIGNED NULL,user_id BIGINT UNSIGNED NULL,event_type VARCHAR(80)NOT NULL,metadata_json JSON NULL,created_at DATETIME NOT NULL,INDEX idx_product_event(event_type,created_at),INDEX idx_product_tenant(tenant_id,created_at))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS checkout_sessions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(32)NOT NULL UNIQUE,tenant_id BIGINT UNSIGNED NULL,plan_id BIGINT UNSIGNED NOT NULL,billing_cycle ENUM('monthly','quarterly','semiannual','annual')NOT NULL,subtotal DECIMAL(10,2)NOT NULL,discount DECIMAL(10,2)NOT NULL DEFAULT 0,total DECIMAL(10,2)NOT NULL,coupon_code VARCHAR(60)NULL,status ENUM('started','awaiting_payment','paid','expired','abandoned','failed')NOT NULL DEFAULT 'started',idempotency_key CHAR(64)NOT NULL UNIQUE,expires_at DATETIME NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_checkout_status(status,expires_at),CONSTRAINT fk_checkout_plan FOREIGN KEY(plan_id)REFERENCES plans(id),CONSTRAINT fk_checkout_tenant FOREIGN KEY(tenant_id)REFERENCES tenants(id)ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS coupons(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,code VARCHAR(60)NOT NULL UNIQUE,type ENUM('percent','fixed')NOT NULL,value DECIMAL(10,2)NOT NULL,valid_from DATETIME NULL,valid_until DATETIME NULL,max_uses INT UNSIGNED NULL,uses_count INT UNSIGNED NOT NULL DEFAULT 0,active TINYINT(1)NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS invoices(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tenant_id BIGINT UNSIGNED NOT NULL,subscription_id BIGINT UNSIGNED NOT NULL,checkout_session_id BIGINT UNSIGNED NULL,number VARCHAR(60)NOT NULL UNIQUE,amount DECIMAL(10,2)NOT NULL,currency CHAR(3)NOT NULL DEFAULT 'BRL',status ENUM('pending','paid','overdue','cancelled','refunded')NOT NULL DEFAULT 'pending',due_at DATETIME NOT NULL,paid_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_invoice_tenant(tenant_id,status,due_at),CONSTRAINT fk_invoice_tenant FOREIGN KEY(tenant_id)REFERENCES tenants(id),CONSTRAINT fk_invoice_subscription FOREIGN KEY(subscription_id)REFERENCES subscriptions(id),CONSTRAINT fk_invoice_checkout FOREIGN KEY(checkout_session_id)REFERENCES checkout_sessions(id)ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
UPDATE plans SET quarterly_price=monthly_price*3,semiannual_price=monthly_price*6,annual_price=monthly_price*10 WHERE quarterly_price IS NULL;
