-- Corrective commercial architecture: public links, professional portal, POS, support and platform controls.
ALTER TABLE tenants ADD COLUMN public_slug VARCHAR(120) NULL AFTER slug;
ALTER TABLE tenants ADD COLUMN public_short_code VARCHAR(16) NULL AFTER public_slug;
ALTER TABLE tenants ADD COLUMN public_booking_enabled TINYINT(1) NOT NULL DEFAULT 1 AFTER public_short_code;
ALTER TABLE tenants ADD COLUMN category VARCHAR(60) NULL AFTER description;
ALTER TABLE tenants ADD UNIQUE KEY uq_tenant_public_slug(public_slug);
ALTER TABLE tenants ADD UNIQUE KEY uq_tenant_short_code(public_short_code);
UPDATE tenants SET public_slug=slug WHERE public_slug IS NULL;
UPDATE tenants SET public_short_code=UPPER(SUBSTRING(SHA2(CONCAT(id,slug,created_at),256),1,8)) WHERE public_short_code IS NULL;

ALTER TABLE professionals ADD COLUMN public_slug VARCHAR(120) NULL AFTER name;
ALTER TABLE professionals ADD COLUMN email VARCHAR(190) NULL AFTER public_slug;
ALTER TABLE professionals ADD COLUMN phone VARCHAR(32) NULL AFTER email;
ALTER TABLE professionals ADD COLUMN specialty VARCHAR(150) NULL AFTER phone;
ALTER TABLE professionals ADD COLUMN photo_path VARCHAR(255) NULL AFTER specialty;
ALTER TABLE professionals ADD COLUMN commission_percent DECIMAL(5,2) NULL AFTER photo_path;
ALTER TABLE professionals ADD UNIQUE KEY uq_prof_public_slug(tenant_id,public_slug);
CREATE TABLE IF NOT EXISTS professional_services(professional_id BIGINT UNSIGNED NOT NULL,service_id BIGINT UNSIGNED NOT NULL,PRIMARY KEY(professional_id,service_id),CONSTRAINT fk_ps_prof FOREIGN KEY(professional_id) REFERENCES professionals(id) ON DELETE CASCADE,CONSTRAINT fk_ps_service FOREIGN KEY(service_id) REFERENCES services(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE subscriptions ADD COLUMN trial_started_at DATETIME NULL AFTER started_at;
ALTER TABLE subscriptions ADD COLUMN trial_days_snapshot SMALLINT UNSIGNED NULL AFTER trial_ends_at;
ALTER TABLE subscriptions ADD COLUMN provider_customer_id VARCHAR(190) NULL;
ALTER TABLE subscriptions ADD COLUMN provider_subscription_id VARCHAR(190) NULL;
ALTER TABLE subscriptions ADD COLUMN provider_plan_id VARCHAR(190) NULL;
UPDATE subscriptions SET trial_started_at=started_at,trial_days_snapshot=GREATEST(0,DATEDIFF(trial_ends_at,started_at)) WHERE trial_started_at IS NULL;

CREATE TABLE IF NOT EXISTS modules(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(80) NOT NULL UNIQUE,name VARCHAR(120) NOT NULL,active TINYINT(1) NOT NULL DEFAULT 1)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS plan_modules(plan_id BIGINT UNSIGNED NOT NULL,module_id BIGINT UNSIGNED NOT NULL,enabled TINYINT(1) NOT NULL DEFAULT 1,PRIMARY KEY(plan_id,module_id),CONSTRAINT fk_pm_plan FOREIGN KEY(plan_id) REFERENCES plans(id) ON DELETE CASCADE,CONSTRAINT fk_pm_module FOREIGN KEY(module_id) REFERENCES modules(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS tenant_modules(tenant_id BIGINT UNSIGNED NOT NULL,module_id BIGINT UNSIGNED NOT NULL,enabled TINYINT(1) NOT NULL,PRIMARY KEY(tenant_id,module_id),CONSTRAINT fk_tm_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,CONSTRAINT fk_tm_module FOREIGN KEY(module_id) REFERENCES modules(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO modules(slug,name) VALUES ('products','Produtos'),('stock','Estoque'),('finance','Financeiro'),('behavior','Behavior Engine'),('whatsapp','WhatsApp'),('multiunit','Multiunidade'),('medical_records','Prontuário'),('odontology','Odontologia'),('api','API');

CREATE TABLE IF NOT EXISTS products(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tenant_id BIGINT UNSIGNED NOT NULL,unit_id BIGINT UNSIGNED NULL,name VARCHAR(150) NOT NULL,sku VARCHAR(80) NULL,code VARCHAR(80) NULL,category VARCHAR(100) NULL,description TEXT NULL,cost_price DECIMAL(10,2) NOT NULL DEFAULT 0,sale_price DECIMAL(10,2) NOT NULL,stock DECIMAL(12,3) NOT NULL DEFAULT 0,minimum_stock DECIMAL(12,3) NOT NULL DEFAULT 0,unit VARCHAR(20) NOT NULL DEFAULT 'un',commission_type ENUM('none','percent','fixed') NOT NULL DEFAULT 'none',commission_value DECIMAL(10,2) NOT NULL DEFAULT 0,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,UNIQUE KEY uq_product_sku(tenant_id,sku),INDEX idx_product_tenant(tenant_id,active),CONSTRAINT fk_product_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,CONSTRAINT fk_product_unit FOREIGN KEY(unit_id) REFERENCES units(id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sales(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tenant_id BIGINT UNSIGNED NOT NULL,unit_id BIGINT UNSIGNED NULL,professional_id BIGINT UNSIGNED NULL,customer_id BIGINT UNSIGNED NULL,user_id BIGINT UNSIGNED NOT NULL,subtotal DECIMAL(10,2) NOT NULL,discount DECIMAL(10,2) NOT NULL DEFAULT 0,total DECIMAL(10,2) NOT NULL,payment_method VARCHAR(40) NOT NULL,status ENUM('completed','cancelled') NOT NULL DEFAULT 'completed',cancel_reason VARCHAR(500) NULL,cancelled_by BIGINT UNSIGNED NULL,cancelled_at DATETIME NULL,created_at DATETIME NOT NULL,INDEX idx_sale_tenant(tenant_id,created_at),CONSTRAINT fk_sale_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id),CONSTRAINT fk_sale_prof FOREIGN KEY(professional_id) REFERENCES professionals(id) ON DELETE SET NULL,CONSTRAINT fk_sale_customer FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE SET NULL,CONSTRAINT fk_sale_user FOREIGN KEY(user_id) REFERENCES users(id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sale_items(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,sale_id BIGINT UNSIGNED NOT NULL,product_id BIGINT UNSIGNED NOT NULL,quantity DECIMAL(12,3) NOT NULL,unit_price DECIMAL(10,2) NOT NULL,discount DECIMAL(10,2) NOT NULL DEFAULT 0,total DECIMAL(10,2) NOT NULL,cost_snapshot DECIMAL(10,2) NOT NULL,CONSTRAINT fk_si_sale FOREIGN KEY(sale_id) REFERENCES sales(id) ON DELETE CASCADE,CONSTRAINT fk_si_product FOREIGN KEY(product_id) REFERENCES products(id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS product_stock_movements(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tenant_id BIGINT UNSIGNED NOT NULL,product_id BIGINT UNSIGNED NOT NULL,sale_id BIGINT UNSIGNED NULL,type ENUM('sale','sale_reversal','adjustment','entry') NOT NULL,quantity DECIMAL(12,3) NOT NULL,balance_after DECIMAL(12,3) NOT NULL,user_id BIGINT UNSIGNED NOT NULL,reason VARCHAR(500) NULL,created_at DATETIME NOT NULL,INDEX idx_stock_product(product_id,created_at),CONSTRAINT fk_psm_product FOREIGN KEY(product_id) REFERENCES products(id),CONSTRAINT fk_psm_sale FOREIGN KEY(sale_id) REFERENCES sales(id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS support_tickets(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,protocol VARCHAR(30) NOT NULL UNIQUE,tenant_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,category VARCHAR(40) NOT NULL,subject VARCHAR(190) NOT NULL,description TEXT NOT NULL,priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal',status ENUM('open','in_progress','waiting_user','resolved','closed') NOT NULL DEFAULT 'open',assigned_to BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_ticket_tenant(tenant_id,status),CONSTRAINT fk_ticket_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id),CONSTRAINT fk_ticket_user FOREIGN KEY(user_id) REFERENCES users(id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS support_messages(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,ticket_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,message TEXT NOT NULL,attachment_path VARCHAR(255) NULL,created_at DATETIME NOT NULL,CONSTRAINT fk_sm_ticket FOREIGN KEY(ticket_id) REFERENCES support_tickets(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS support_access_sessions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,ticket_id BIGINT UNSIGNED NOT NULL,tenant_id BIGINT UNSIGNED NOT NULL,master_user_id BIGINT UNSIGNED NOT NULL,started_at DATETIME NOT NULL,ended_at DATETIME NULL,ip_address VARCHAR(64) NULL,actions_json JSON NULL,INDEX idx_support_access(tenant_id,started_at))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS user_blocks(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,tenant_id BIGINT UNSIGNED NULL,reason_code VARCHAR(40) NOT NULL,reason_text VARCHAR(500) NULL,blocked_by BIGINT UNSIGNED NULL,blocked_at DATETIME NOT NULL,expires_at DATETIME NULL,unblocked_by BIGINT UNSIGNED NULL,unblocked_at DATETIME NULL,INDEX idx_user_block(user_id,unblocked_at),CONSTRAINT fk_block_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS login_audit(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tenant_id BIGINT UNSIGNED NULL,user_id BIGINT UNSIGNED NULL,email_attempted VARCHAR(190) NOT NULL,event_type VARCHAR(40) NOT NULL,result VARCHAR(20) NOT NULL,ip_address VARCHAR(64) NULL,user_agent VARCHAR(500) NULL,device_info VARCHAR(255) NULL,failure_reason_code VARCHAR(60) NULL,created_at DATETIME NOT NULL,INDEX idx_login_audit(created_at,result),INDEX idx_login_email(email_attempted,created_at))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS tenant_status_history(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tenant_id BIGINT UNSIGNED NOT NULL,from_status VARCHAR(40) NOT NULL,to_status VARCHAR(40) NOT NULL,reason VARCHAR(500) NOT NULL,changed_by BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL,INDEX idx_tsh_tenant(tenant_id,created_at))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS payment_gateways(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,provider VARCHAR(40) NOT NULL UNIQUE,environment ENUM('sandbox','production') NOT NULL DEFAULT 'sandbox',public_key VARCHAR(255) NULL,access_token_encrypted LONGTEXT NULL,webhook_secret_encrypted LONGTEXT NULL,active TINYINT(1) NOT NULL DEFAULT 0,last_tested_at DATETIME NULL,last_test_status VARCHAR(30) NULL,updated_at DATETIME NOT NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS provider_events(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,provider VARCHAR(40) NOT NULL,event_id VARCHAR(190) NOT NULL,event_type VARCHAR(100) NULL,payload_hash CHAR(64) NOT NULL,status ENUM('received','processed','failed') NOT NULL DEFAULT 'received',error_message VARCHAR(500) NULL,received_at DATETIME NOT NULL,processed_at DATETIME NULL,UNIQUE KEY uq_provider_event(provider,event_id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE payments ADD COLUMN provider_status VARCHAR(80) NULL;
ALTER TABLE payments ADD COLUMN provider_payment_id VARCHAR(190) NULL;
ALTER TABLE payments ADD UNIQUE KEY uq_payment_provider_id(provider,provider_payment_id);

INSERT IGNORE INTO permissions(slug,name) VALUES ('products.view','Ver produtos'),('products.create','Criar produtos'),('products.edit','Editar produtos'),('products.stock','Ajustar estoque'),('sales.view','Ver vendas'),('sales.create','Criar vendas'),('sales.cancel','Cancelar vendas'),('sales.discount','Aplicar desconto'),('reports.services','Relatório de serviços'),('reports.products','Relatório de produtos'),('reports.professionals','Relatório profissional'),('professionals.manage','Gerenciar profissionais'),('support.create','Abrir chamado'),('support.view','Ver chamados'),('master.support.manage','Gerenciar suporte'),('master.support.impersonate','Acesso assistido'),('master.plans.manage','Gerenciar planos'),('master.users.manage','Gerenciar usuários'),('master.tenants.manage','Gerenciar tenants'),('master.payments.view','Ver pagamentos'),('master.gateway.manage','Gerenciar gateway'),('master.login_audit.view','Auditoria de login');
INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p WHERE r.slug='owner' AND (p.slug LIKE 'products.%' OR p.slug LIKE 'sales.%' OR p.slug LIKE 'reports.%' OR p.slug='professionals.manage' OR p.slug LIKE 'support.%');
INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p WHERE r.slug='professional' AND p.slug IN('products.view','sales.view','sales.create','support.create','support.view');

-- Safe defaults also protect legacy creation paths that do not yet send the new fields.
CREATE TRIGGER tenants_public_identity_before_insert BEFORE INSERT ON tenants FOR EACH ROW SET NEW.public_slug=COALESCE(NULLIF(NEW.public_slug,''),NEW.slug),NEW.public_short_code=COALESCE(NULLIF(NEW.public_short_code,''),UPPER(SUBSTRING(SHA2(CONCAT(UUID(),NEW.slug),256),1,8)));
CREATE TRIGGER subscriptions_trial_snapshot_before_insert BEFORE INSERT ON subscriptions FOR EACH ROW SET NEW.trial_started_at=COALESCE(NEW.trial_started_at,NEW.started_at),NEW.trial_days_snapshot=COALESCE(NEW.trial_days_snapshot,(SELECT COALESCE(trial_days,14) FROM plans WHERE id=NEW.plan_id)),NEW.trial_ends_at=IF(NEW.status='trial',DATE_ADD(NEW.started_at,INTERVAL COALESCE(NEW.trial_days_snapshot,(SELECT COALESCE(trial_days,14) FROM plans WHERE id=NEW.plan_id)) DAY),NEW.trial_ends_at),NEW.next_billing_at=IF(NEW.status='trial',DATE_ADD(NEW.started_at,INTERVAL COALESCE(NEW.trial_days_snapshot,(SELECT COALESCE(trial_days,14) FROM plans WHERE id=NEW.plan_id)) DAY),NEW.next_billing_at);
