<?php
namespace App\Services;

use App\Core\Database;

final class ArenaTournamentService
{
    public function generateFixtures(int $tenantId,int $tournamentId): array
    {
        $pdo=Database::connection();$t=$this->tournament($tenantId,$tournamentId,true);
        $count=$pdo->prepare('SELECT COUNT(*) FROM sports_tournament_matches WHERE tournament_id=:id AND tenant_id=:tenant');$count->execute(['id'=>$tournamentId,'tenant'=>$tenantId]);if((int)$count->fetchColumn()>0)throw new \DomainException('O torneio já possui partidas.');
        $q=$pdo->prepare('SELECT id,name FROM sports_tournament_teams WHERE tournament_id=:id AND tenant_id=:tenant ORDER BY id');$q->execute(['id'=>$tournamentId,'tenant'=>$tenantId]);$teams=$q->fetchAll()?:[];if(count($teams)<2)throw new \DomainException('Cadastre pelo menos duas equipes.');
        $pdo->beginTransaction();try{$created=0;if(in_array($t['format'],['groups','groups_knockout'],true)){$groups=max(1,(int)ceil(count($teams)/4));$buckets=array_fill(0,$groups,[]);foreach($teams as $i=>$team){$g=$i%$groups;$buckets[$g][]=$team;$pdo->prepare('UPDATE sports_tournament_teams SET group_name=:group WHERE id=:id AND tenant_id=:tenant')->execute(['group'=>'Grupo '.chr(65+$g),'id'=>$team['id'],'tenant'=>$tenantId]);}foreach($buckets as $g=>$bucket){$group='Grupo '.chr(65+$g);for($i=0;$i<count($bucket);$i++)for($j=$i+1;$j<count($bucket);$j++){$this->insertMatch($pdo,$tenantId,$tournamentId,(int)$bucket[$i]['id'],(int)$bucket[$j]['id'],'Grupos',1,$group);$created++;}}}else{$created=$this->createKnockoutRound($pdo,$tenantId,$tournamentId,array_map(fn($x)=>(int)$x['id'],$teams),1);}$pdo->prepare("UPDATE sports_tournaments SET status='running',updated_at=NOW() WHERE id=:id AND tenant_id=:tenant")->execute(['id'=>$tournamentId,'tenant'=>$tenantId]);$this->event($pdo,$tenantId,$tournamentId,'fixtures_generated',$created.' partidas geradas');$pdo->commit();return ['created'=>$created];}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }

    public function standings(int $tenantId,int $tournamentId): array
    {
        $pdo=Database::connection();$teams=$pdo->prepare('SELECT id,name,group_name FROM sports_tournament_teams WHERE tournament_id=:id AND tenant_id=:tenant ORDER BY group_name,name');$teams->execute(['id'=>$tournamentId,'tenant'=>$tenantId]);$rows=[];foreach($teams->fetchAll() as $team)$rows[(int)$team['id']]=['team_id'=>(int)$team['id'],'name'=>$team['name'],'group_name'=>$team['group_name']?:'Geral','played'=>0,'wins'=>0,'draws'=>0,'losses'=>0,'gf'=>0,'ga'=>0,'gd'=>0,'points'=>0];$q=$pdo->prepare("SELECT * FROM sports_tournament_matches WHERE tournament_id=:id AND tenant_id=:tenant AND status='completed' AND phase='Grupos'");$q->execute(['id'=>$tournamentId,'tenant'=>$tenantId]);foreach($q->fetchAll() as $m){$h=(int)$m['home_team_id'];$a=(int)$m['away_team_id'];if(!$h||!$a||!isset($rows[$h],$rows[$a]))continue;$hs=(int)$m['home_score'];$as=(int)$m['away_score'];foreach([$h,$a] as $id)$rows[$id]['played']++;$rows[$h]['gf']+=$hs;$rows[$h]['ga']+=$as;$rows[$a]['gf']+=$as;$rows[$a]['ga']+=$hs;if($hs>$as){$rows[$h]['wins']++;$rows[$h]['points']+=3;$rows[$a]['losses']++;}elseif($as>$hs){$rows[$a]['wins']++;$rows[$a]['points']+=3;$rows[$h]['losses']++;}else{$rows[$h]['draws']++;$rows[$a]['draws']++;$rows[$h]['points']++;$rows[$a]['points']++;}}foreach($rows as &$r)$r['gd']=$r['gf']-$r['ga'];unset($r);usort($rows,fn($a,$b)=>[$b['group_name'],$b['points'],$b['gd'],$b['gf']]<=>[$a['group_name'],$a['points'],$a['gd'],$a['gf']]);return $rows;
    }

    public function advance(int $tenantId,int $tournamentId): array
    {
        $pdo=Database::connection();$t=$this->tournament($tenantId,$tournamentId,true);$pending=$pdo->prepare("SELECT COUNT(*) FROM sports_tournament_matches WHERE tournament_id=:id AND tenant_id=:tenant AND status<>'completed'");$pending->execute(['id'=>$tournamentId,'tenant'=>$tenantId]);if((int)$pending->fetchColumn()>0)throw new \DomainException('Conclua todas as partidas atuais antes de avançar.');
        if($t['format']==='groups'){$stand=$this->standings($tenantId,$tournamentId);if(!$stand)throw new \DomainException('Sem classificação para concluir.');$champ=(int)$stand[0]['team_id'];$this->champion($pdo,$tenantId,$tournamentId,$champ);return ['completed'=>true,'champion'=>$champ];}
        $hasKnock=$pdo->prepare("SELECT COUNT(*) FROM sports_tournament_matches WHERE tournament_id=:id AND tenant_id=:tenant AND phase<>'Grupos'");$hasKnock->execute(['id'=>$tournamentId,'tenant'=>$tenantId]);
        if(!(int)$hasKnock->fetchColumn()&&$t['format']==='groups_knockout'){$stand=$this->standings($tenantId,$tournamentId);$groups=[];foreach($stand as $r)$groups[$r['group_name']][]=$r;$qualified=[];foreach($groups as $rows)foreach(array_slice($rows,0,2) as $r)$qualified[]=(int)$r['team_id'];if(count($qualified)<2)throw new \DomainException('Não há classificados suficientes.');$pdo->beginTransaction();try{$created=$this->createKnockoutRound($pdo,$tenantId,$tournamentId,$qualified,1);$this->event($pdo,$tenantId,$tournamentId,'knockout_started',$created.' partidas de mata-mata geradas');$pdo->commit();return ['created'=>$created,'round'=>1];}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
        $q=$pdo->prepare("SELECT MAX(round_number) FROM sports_tournament_matches WHERE tournament_id=:id AND tenant_id=:tenant AND phase<>'Grupos'");$q->execute(['id'=>$tournamentId,'tenant'=>$tenantId]);$round=max(1,(int)$q->fetchColumn());$m=$pdo->prepare("SELECT * FROM sports_tournament_matches WHERE tournament_id=:id AND tenant_id=:tenant AND round_number=:round AND phase<>'Grupos' ORDER BY id");$m->execute(['id'=>$tournamentId,'tenant'=>$tenantId,'round'=>$round]);$winners=[];foreach($m->fetchAll() as $row){if((int)$row['home_score']===(int)$row['away_score']&&$row['away_team_id'])throw new \DomainException('Mata-mata não pode terminar empatado. Ajuste o placar.');$winners[]=(int)(((int)$row['home_score']>(int)$row['away_score']||!$row['away_team_id'])?$row['home_team_id']:$row['away_team_id']);}$winners=array_values(array_filter($winners));if(count($winners)===1){$this->champion($pdo,$tenantId,$tournamentId,$winners[0]);return ['completed'=>true,'champion'=>$winners[0]];}$pdo->beginTransaction();try{$created=$this->createKnockoutRound($pdo,$tenantId,$tournamentId,$winners,$round+1);$this->event($pdo,$tenantId,$tournamentId,'round_advanced','Rodada '.($round+1).' gerada');$pdo->commit();return ['created'=>$created,'round'=>$round+1];}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }

    public function scheduleMatch(int $tenantId,int $matchId,int $courtId,\DateTimeImmutable $start,int $duration): int
    {
        $pdo=Database::connection();$q=$pdo->prepare("SELECT mt.*,t.modality_id FROM sports_tournament_matches mt JOIN sports_tournaments t ON t.id=mt.tournament_id AND t.tenant_id=mt.tenant_id WHERE mt.id=:id AND mt.tenant_id=:tenant");$q->execute(['id'=>$matchId,'tenant'=>$tenantId]);$m=$q->fetch();if(!$m)throw new \DomainException('Partida não encontrada.');$cq=$pdo->prepare('SELECT 1 FROM sports_courts WHERE id=:court AND tenant_id=:tenant AND active=1');$cq->execute(['court'=>$courtId,'tenant'=>$tenantId]);if(!$cq->fetchColumn())throw new \DomainException('Quadra inválida.');$reservation=(new ArenaReservationService())->create($tenantId,$courtId,(int)($m['modality_id']??0),$start,$duration,['name'=>'Torneio','phone'=>'00000000000','email'=>''],'admin','Partida de torneio #'.$matchId,null,0.0,0.0,'onsite','confirmed');$pdo->prepare('UPDATE sports_reservations SET tournament_match_id=:match WHERE id=:reservation AND tenant_id=:tenant')->execute(['match'=>$matchId,'reservation'=>$reservation['id'],'tenant'=>$tenantId]);$pdo->prepare('UPDATE sports_tournament_matches SET court_id=:court,starts_at=:starts,reservation_id=:reservation,status=\'scheduled\',updated_at=NOW() WHERE id=:id AND tenant_id=:tenant')->execute(['court'=>$courtId,'starts'=>$start->format('Y-m-d H:i:s'),'reservation'=>$reservation['id'],'id'=>$matchId,'tenant'=>$tenantId]);return (int)$reservation['id'];
    }

    public function score(int $tenantId,int $matchId,int $home,int $away): void
    {
        if($home<0||$away<0)throw new \InvalidArgumentException('Placar inválido.');$pdo=Database::connection();$q=$pdo->prepare("UPDATE sports_tournament_matches SET home_score=:home,away_score=:away,status='completed',updated_at=NOW() WHERE id=:id AND tenant_id=:tenant");$q->execute(['home'=>$home,'away'=>$away,'id'=>$matchId,'tenant'=>$tenantId]);if(!$q->rowCount())throw new \DomainException('Partida não encontrada.');
    }

    private function createKnockoutRound(\PDO $pdo,int $tenantId,int $tournamentId,array $teams,int $round): int
    {
        $created=0;$phase=count($teams)<=2?'Final':(count($teams)<=4?'Semifinal':(count($teams)<=8?'Quartas':'Mata-mata'));for($i=0;$i<count($teams);$i+=2){$home=(int)$teams[$i];$away=isset($teams[$i+1])?(int)$teams[$i+1]:null;$this->insertMatch($pdo,$tenantId,$tournamentId,$home,$away,$phase,$round,null,$away===null);$created++;}return $created;
    }
    private function insertMatch(\PDO $pdo,int $tenantId,int $tournamentId,int $home,?int $away,string $phase,int $round,?string $group,bool $bye=false): void{$pdo->prepare("INSERT INTO sports_tournament_matches(tournament_id,tenant_id,home_team_id,away_team_id,phase,round_number,group_name,home_score,away_score,status,created_at,updated_at) VALUES(:tournament,:tenant,:home,:away,:phase,:round,:group,:hs,:as,:status,NOW(),NOW())")->execute(['tournament'=>$tournamentId,'tenant'=>$tenantId,'home'=>$home,'away'=>$away,'phase'=>$phase,'round'=>$round,'group'=>$group,'hs'=>$bye?1:null,'as'=>$bye?0:null,'status'=>$bye?'completed':'scheduled']);}
    private function champion(\PDO $pdo,int $tenantId,int $tournamentId,int $teamId): void{$pdo->prepare("UPDATE sports_tournaments SET champion_team_id=:team,status='completed',updated_at=NOW() WHERE id=:id AND tenant_id=:tenant")->execute(['team'=>$teamId,'id'=>$tournamentId,'tenant'=>$tenantId]);$this->event($pdo,$tenantId,$tournamentId,'champion','Campeão: equipe #'.$teamId);}
    private function tournament(int $tenantId,int $tournamentId,bool $required=false): array{$q=Database::connection()->prepare('SELECT * FROM sports_tournaments WHERE id=:id AND tenant_id=:tenant');$q->execute(['id'=>$tournamentId,'tenant'=>$tenantId]);$r=$q->fetch();if(!$r&&$required)throw new \DomainException('Torneio não encontrado.');return $r?:[];}
    private function event(\PDO $pdo,int $tenantId,int $tournamentId,string $type,string $detail): void{$pdo->prepare('INSERT INTO sports_tournament_events(tenant_id,tournament_id,event_type,detail,created_at) VALUES(:tenant,:tournament,:type,:detail,NOW())')->execute(['tenant'=>$tenantId,'tournament'=>$tournamentId,'type'=>$type,'detail'=>mb_substr($detail,0,500)]);}
}
