<?php use App\Core\CSRF;$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$share=round((float)$game['total_amount']/max(1,(int)$game['max_players']),2);?>
<section class="arena-game-public">
  <div class="arena-hero"><div><span class="sports-kicker">RACHA / PELADA</span><h1><?=$e($game['name'])?></h1><p><?=$e($game['tenant_name'])?> · <?=$e($game['court_name'])?><?php if($game['modality_name']):?> · <?=$e($game['modality_name'])?><?php endif;?></p></div><div class="arena-trust"><strong><?=date('d/m/Y',strtotime($game['starts_at']))?> · <?=date('H:i',strtotime($game['starts_at']))?>–<?=date('H:i',strtotime($game['ends_at']))?></strong><span><?=$confirmed?> confirmado(s) · <?=$available?> vaga(s)</span></div></div>
  <?php if(!empty($_GET['joined'])):?><div class="alert alert-success">Participação confirmada. Guarde este link para consultar seu pagamento.</div><?php endif;?>
  <div class="row g-4">
    <div class="col-lg-7">
      <div class="card border-0 shadow-sm"><div class="card-body"><div class="arena-mini-kpis"><span><strong><?=(int)$game['max_players']?></strong><small>vagas</small></span><span><strong><?=$confirmed?></strong><small>confirmados</small></span><span><strong>R$ <?=number_format((float)$game['total_amount'],2,',','.')?></strong><small>valor do jogo</small></span><?php if($game['split_payment']):?><span><strong>R$ <?=number_format($share,2,',','.')?></strong><small>por jogador</small></span><?php endif;?></div><?php if($game['rules']):?><hr><h2 class="h5">Regras</h2><p class="mb-0"><?=nl2br($e($game['rules']))?></p><?php endif;?></div></div>
      <div class="card border-0 shadow-sm mt-3"><div class="card-body"><h2 class="h5">Participantes</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Jogador</th><th>Participação</th><th>Pagamento</th></tr></thead><tbody><?php foreach($players as $p):?><tr><td><?=$e($p['name'])?></td><td><?=$e(str_replace('_',' ',$p['participation_status']))?></td><td><?=$e(str_replace('_',' ',$p['payment_status']))?></td></tr><?php endforeach;?><?php if(!$players):?><tr><td colspan="3" class="text-secondary">Seja o primeiro a confirmar.</td></tr><?php endif;?></tbody></table></div></div></div>
    </div>
    <div class="col-lg-5">
      <?php if($player):$tx=$player['transaction']??null;?><div class="card border-0 shadow-sm mb-3"><div class="card-body"><span class="sports-kicker">SUA PARTICIPAÇÃO</span><h2 class="h5 mt-2"><?=$e($player['name'])?></h2><p>Valor: <strong>R$ <?=number_format((float)$player['share_amount'],2,',','.')?></strong><br>Status: <strong><?=$e(str_replace('_',' ',$player['payment_status']))?></strong></p><?php if($tx&&$tx['status']!=='paid'):?><div class="arena-pix"><h3 class="h6">Pix do jogador</h3><?php if($tx['pix_qr_code']):?><img class="arena-qr" src="data:image/png;base64,<?=$e($tx['pix_qr_code'])?>" alt="QR Code Pix"><?php endif;?><?php if($tx['pix_copy_paste']):?><label>Pix Copia e Cola</label><textarea class="form-control" rows="3" readonly><?=$e($tx['pix_copy_paste'])?></textarea><?php endif;?><small>O pagamento só será considerado confirmado após validação do provedor.</small></div><?php elseif($tx&&$tx['status']==='paid'):?><div class="alert alert-success mb-0">Pagamento confirmado.</div><?php elseif((float)$player['share_amount']>0):?><div class="alert alert-warning mb-0">Sua participação está confirmada, mas o pagamento ainda precisa ser combinado com a Arena.</div><?php endif;?></div></div><?php endif;?>
      <?php if(!$player && $available>0 && in_array($game['status'],['open','confirmed'],true)):?><form class="card border-0 shadow-sm" method="post" action="/jogo/<?=$e($game['public_token'])?>/participar"><div class="card-body"><?=CSRF::field()?><span class="sports-kicker">ENTRAR NO JOGO</span><h2 class="h5 mt-2">Confirmar participação</h2><input class="form-control mb-2" name="name" required placeholder="Nome completo"><input class="form-control mb-2" name="phone" required placeholder="WhatsApp com DDD"><input class="form-control mb-2" type="email" name="email" placeholder="E-mail para Pix automático (quando disponível)"><label class="form-check small"><input class="form-check-input" type="checkbox" name="terms" required> Confirmo minha participação e aceito as regras do jogo.</label><button class="btn btn-primary w-100 mt-3">Entrar no racha</button></div></form><?php elseif(!$player && $available<=0):?><div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">Vagas preenchidas</h2><p class="mb-0 text-secondary">Entre em contato com a Arena para verificar desistências.</p></div></div><?php endif;?>
    </div>
  </div>
</section>
