<?php
use App\Core\CSRF;
$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$labels=['pending_payment'=>'Aguardando sinal','confirmed'=>'Confirmada','completed'=>'Realizada','cancelled'=>'Cancelada','no_show'=>'Não compareceu'];
$active=in_array($reservation['status'],['pending_payment','confirmed'],true);$tx=$transaction??null;
$isCard=($reservation['payment_method']??'')==='card';
?>
<section class="arena-receipt">
<div class="arena-receipt-check"><?=$reservation['status']==='cancelled'?'×':'✓'?></div><span class="sports-kicker">SUA RESERVA</span><h1><?=$e($labels[$reservation['status']]??$reservation['status'])?></h1><p><?=$e($reservation['tenant_name'])?></p>
<div class="arena-ticket"><div><span>Quadra</span><strong><?=$e($reservation['court_name'])?></strong></div><div><span>Modalidade</span><strong><?=$e($reservation['modality_name']??'')?></strong></div><div><span>Data</span><strong><?=date('d/m/Y',strtotime($reservation['starts_at']))?></strong></div><div><span>Horário</span><strong><?=date('H:i',strtotime($reservation['starts_at']))?>–<?=date('H:i',strtotime($reservation['ends_at']))?></strong></div><div><span>Valor total</span><strong>R$ <?=number_format((float)$reservation['total_amount'],2,',','.')?></strong></div><div><span>Pagamento</span><strong><?=$e(str_replace('_',' ',$finance['payment_state']??$reservation['payment_status']))?></strong></div></div>
<?php if($reservation['status']==='pending_payment'):?>
<div class="arena-pix"><h2>Conclua o sinal da reserva</h2><strong>R$ <?=number_format((float)$reservation['deposit_amount'],2,',','.')?></strong>
<?php if($isCard):?>
  <?php if(!empty($cardConfig)):?><div id="arena-card-payment" class="mt-3" data-public-key="<?=$e($cardConfig['public_key'])?>" data-amount="<?=number_format((float)$reservation['deposit_amount'],2,'.','')?>" data-endpoint="/arena/reserva/<?=$e($token)?>/card-payment"><div id="cardPaymentBrick_container"></div><div class="alert mt-2 d-none" data-card-message></div></div><small>Os dados completos do cartão são tokenizados pelo Mercado Pago e não ficam armazenados no ApPlanner.</small>
  <?php else:?><div class="alert alert-warning mt-2">A Arena escolheu cartão, mas a Public Key do provedor não está configurada. Entre em contato com o estabelecimento.</div><?php endif;?>
<?php elseif($tx&&$tx['status']!=='paid'):?>
  <?php if($tx['pix_qr_code']):?><img class="arena-qr" src="data:image/png;base64,<?=$e($tx['pix_qr_code'])?>" alt="QR Code Pix"><?php endif;?>
  <?php if($tx['pix_copy_paste']):?><label>Pix Copia e Cola</label><textarea class="form-control" rows="3" readonly><?=$e($tx['pix_copy_paste'])?></textarea><?php endif;?>
  <?php if($tx['expires_at']):?><small>Esta cobrança expira em <?=date('d/m/Y H:i',strtotime($tx['expires_at']))?>. A confirmação ocorre somente após validação do provedor.</small><?php endif;?>
<?php elseif(!empty($settings['pix_key'])):?><label>Chave Pix</label><code><?=$e($settings['pix_key'])?></code><small>Titular: <?=$e($settings['pix_holder']??$reservation['tenant_name'])?>. Após pagar, o estabelecimento deve validar o sinal na tela de reservas.</small>
<?php else:?><div class="alert alert-warning mt-2 mb-0">A cobrança automática não pôde ser gerada. Entre em contato com a Arena antes do prazo da reserva.</div><?php endif;?>
</div>
<?php elseif(($tx['status']??'')==='paid'||($finance['payment_state']??'')==='paid'||($finance['payment_state']??'')==='partial'):?><div class="alert alert-success">Pagamento validado. Sua reserva está confirmada.</div><?php endif;?>
<?php if(isset($_GET['rescheduled'])):?><div class="alert alert-success">Reserva remarcada. O novo horário já está bloqueado para você.</div><?php endif;?>
<p class="small text-secondary">Guarde este link privado para acompanhar sua reserva.</p>
<?php if($reservation['status']==='confirmed'):?><details class="arena-manage-box mb-3"><summary class="btn btn-outline-primary">Remarcar reserva</summary><form class="mt-3" method="post" action="/arena/reserva/<?=$e($token)?>/reschedule" data-arena-reschedule data-availability="/arena/reserva/<?=$e($token)?>/availability"><?=CSRF::field()?><div class="row g-2"><div class="col-md-5"><label class="form-label">Nova data</label><input class="form-control" type="date" data-reschedule-date required min="<?=date('Y-m-d')?>"></div><div class="col-md-3"><label class="form-label">Duração</label><input class="form-control" type="number" name="duration_minutes" data-reschedule-duration value="<?=(int)$reservation['duration_minutes']?>" min="15" step="15"></div><div class="col-md-4"><label class="form-label">Horário disponível</label><select class="form-select" name="starts_at" data-reschedule-slot required disabled><option value="">Escolha a data</option></select></div></div><button class="btn btn-primary mt-2">Confirmar remarcação</button></form></details><?php endif;?>
<?php if($active):?><form method="post" action="/arena/reserva/<?=$e($token)?>/cancel" onsubmit="return confirm('Deseja cancelar esta reserva?')"><?=CSRF::field()?><button class="btn btn-outline-danger">Cancelar reserva</button></form><?php endif;?>
<a class="btn btn-link mt-2" href="/arena/<?=$e($reservation['public_slug']?:$reservation['public_short_code'])?>">Fazer outra reserva</a></section>
<?php if($reservation['status']==='pending_payment'&&$isCard&&!empty($cardConfig)):?><script src="https://sdk.mercadopago.com/js/v2"></script><script src="/public/assets/js/arena-card-payment.js?v=1"></script><?php endif;?>
<script>(function(){const form=document.querySelector('[data-arena-reschedule]');if(!form)return;const date=form.querySelector('[data-reschedule-date]'),duration=form.querySelector('[data-reschedule-duration]'),slot=form.querySelector('[data-reschedule-slot]');async function load(){slot.disabled=true;slot.innerHTML='<option value="">Carregando…</option>';if(!date.value){slot.innerHTML='<option value="">Escolha a data</option>';return;}try{const u=form.dataset.availability+'?date='+encodeURIComponent(date.value)+'&duration_minutes='+encodeURIComponent(duration.value||60);const r=await fetch(u,{headers:{'Accept':'application/json'}});const data=await r.json();slot.innerHTML='<option value="">Selecione</option>';for(const s of(data.slots||[])){const o=document.createElement('option');o.value=s.value;o.textContent=s.label+' · '+s.formatted;slot.appendChild(o);}slot.disabled=!data.slots?.length;if(!data.slots?.length)slot.innerHTML='<option value="">Sem horários disponíveis</option>';}catch(e){slot.innerHTML='<option value="">Não foi possível carregar</option>';}}date.addEventListener('change',load);duration.addEventListener('change',load);})();</script>
