# Generated by Django 5.2.17 on 2026-09-23 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_vehicle_package_membership_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocommanditem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='autosettings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
