<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require dirname(__DIR__).'/app/Core/bootstrap.php';
use App\Core\Database;
use App\Services\ModuleService;
$pdo=Database::connection();$rows=$pdo->query("SELECT cm.*,sp.name package_name,c.name customer_name FROM customer_memberships cm JOIN service_packages sp ON sp.id=cm.package_id JOIN customers c ON c.id=cm.customer_id WHERE cm.status='active' AND COALESCE(cm.billing_mode,'manual')='manual' AND cm.next_due_at<=CURDATE() ORDER BY cm.next_due_at LIMIT 500")->fetchAll();$generated=0;
foreach($rows as $m){$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT * FROM customer_memberships WHERE id=:id FOR UPDATE');$q->execute(['id'=>$m['id']]);$locked=$q->fetch();if(!$locked||$locked['status']!=='active'||$locked['next_due_at']>date('Y-m-d')){$pdo->commit();continue;}$key='membership-'.$locked['id'].'-'.$locked['next_due_at'];if(ModuleService::has('finance',(int)$locked['tenant_id'])){$pdo->prepare("INSERT IGNORE INTO financial_transactions(tenant_id,source_type,source_id,type,description,amount,payment_method,status,idempotency_key,competence_at,created_at,updated_at)VALUES(:t,'membership',:sid,'income',:d,:amount,'outro','pending',:key,:due,NOW(),NOW())")->execute(['t'=>$locked['tenant_id'],'sid'=>$locked['id'],'d'=>'Mensalidade '.$m['package_name'].' — '.$m['customer_name'],'amount'=>$locked['recurring_amount'],'key'=>$key,'due'=>$locked['next_due_at']]);}$next=(new DateTimeImmutable($locked['next_due_at']))->modify($locked['cycle']==='quarterly'?'+3 months':'+1 month')->format('Y-m-d');$pdo->prepare('UPDATE customer_memberships SET last_billed_at=:last,next_due_at=:next,updated_at=NOW() WHERE id=:id')->execute(['last'=>$locked['next_due_at'],'next'=>$next,'id'=>$locked['id']]);$pdo->commit();$generated++;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();@file_put_contents(dirname(__DIR__).'/storage/logs/cron.log','['.date('c').'] membership '.(int)$m['id'].' '.substr($e->getMessage(),0,160)."\n",FILE_APPEND|LOCK_EX);}}
echo "Mensalidades processadas: {$generated}\n";
