<?php
$cycle=(string)($pricing['subscription']['billing_cycle']??'monthly');
$months=['monthly'=>1,'quarterly'=>3,'semiannual'=>6,'annual'=>12][$cycle]??1;
$cycleLabel=['monthly'=>'mensal','quarterly'=>'trimestral','semiannual'=>'semestral','annual'=>'anual'][$cycle]??'mensal';
$currentTotal=(float)($pricing['total']??0);
?>
<div class="section-heading"><div><div class="eyebrow">Minha assinatura</div><h1>Módulos adicionais</h1><p class="text-secondary mb-0">Solicite novos recursos. Depois da aprovação, o valor é incorporado à sua assinatura principal — sem criar uma segunda assinatura.</p></div><a class="btn btn-light" href="/billing">Voltar</a></div>
<div class="alert alert-info"><strong>Como funciona:</strong> você solicita o módulo pelo preço mensal exibido → o Master analisa e confirma o valor → o proprietário confirma a alteração → o módulo é ativado e o total da assinatura é atualizado.</div>
<?php if(!empty($pricing['subscription'])):?><div class="card mb-4"><div class="card-body"><div class="row g-3 align-items-center"><div class="col-md-4"><small class="text-secondary">Plano/base do ciclo</small><div class="h4 mb-0">R$ <?=number_format((float)$pricing['base'],2,',','.')?></div></div><div class="col-md-4"><small class="text-secondary">Módulos incorporados</small><div class="h4 mb-0">R$ <?=number_format((float)$pricing['addons'],2,',','.')?></div><small class="text-secondary">R$ <?=number_format((float)$pricing['monthly_addons'],2,',','.')?>/mês em adicionais</small></div><div class="col-md-4"><small class="text-secondary">Total da assinatura <?=$cycleLabel?></small><div class="h3 mb-0">R$ <?=number_format((float)$pricing['total'],2,',','.')?></div></div></div><?php if((float)($pricing['legacy_monthly']??0)>0):?><div class="alert alert-warning mt-3 mb-0">Existem R$ <?=number_format((float)$pricing['legacy_monthly'],2,',','.')?>/mês de módulos antigos ainda cobrados separadamente. Eles não são somados novamente ao total acima.</div><?php endif;?></div></div><?php endif;?>
<div class="row g-3">
<?php foreach($modules as $m):$included=!empty($m['plan_enabled'])||!empty($m['tenant_enabled']);$approvedPrice=(float)($m['quoted_monthly_price']??$m['addon_monthly_price']??0);$projected=round($currentTotal+$approvedPrice*$months,2);?>
<div class="col-lg-4"><div class="card h-100"><div class="card-body d-flex flex-column">
<div class="d-flex justify-content-between gap-2"><h2 class="h5"><?=htmlspecialchars($m['name'])?></h2><?php if($included):?><span class="badge text-bg-success">Disponível</span><?php elseif($m['request_status']):?><span class="badge text-bg-light"><?=htmlspecialchars(['pending'=>'Em análise','approved'=>'Aguardando sua confirmação','awaiting_payment'=>'Cobrança antiga pendente','active'=>'Ativo','payment_failed'=>'Revisar contratação antiga','rejected'=>'Recusado','cancelled'=>'Cancelado'][$m['request_status']]??$m['request_status'])?></span><?php endif;?></div>
<p class="text-secondary"><?=htmlspecialchars($m['description']??'Recurso adicional para ampliar sua operação.')?></p>
<?php if(!$included&&!empty($m['addon_sellable'])&&(float)$m['addon_monthly_price']>0):?><div class="h3">R$ <?=number_format((float)$m['addon_monthly_price'],2,',','.')?><small class="fs-6 text-secondary">/mês</small></div><?php endif;?>
<div class="mt-auto">
<?php if($included):?><p class="text-success mb-0">Este módulo já está incluído no plano ou contratado separadamente.</p><?php if(!empty($m['addon_id'])):?><div class="small mt-2"><?=($m['billing_mode']??'separate')==='merged_subscription'?'<span class="badge text-bg-primary">Incorporado à assinatura</span>':'<span class="badge text-bg-warning">Cobrança separada legada</span>'?></div><?php endif;?>
<?php elseif($m['request_status']==='approved'||$m['request_status']==='payment_failed'):?>
<div class="alert alert-success"><strong>Aprovado:</strong> R$ <?=number_format($approvedPrice,2,',','.')?>/mês.<br>Após confirmar, seu total <?=$cycleLabel?> passa para aproximadamente <strong>R$ <?=number_format($projected,2,',','.')?></strong>.</div>
<?php if((\App\Core\Auth::user()['role']??'')==='owner'):?><form method="post" action="/billing/modulos/solicitacoes/<?=(int)$m['request_id']?>/contratar" onsubmit="return confirm('Confirmar a incorporação deste módulo à sua assinatura principal?')"><?php echo \App\Core\CSRF::field();?><button class="btn btn-primary w-100">Incorporar à assinatura</button></form><?php else:?><div class="alert alert-warning mb-0">O proprietário da conta precisa confirmar a alteração do valor da assinatura.</div><?php endif;?>
<?php elseif($m['request_status']==='awaiting_payment'):?><div class="alert alert-warning mb-0">Existe uma contratação antiga aguardando retorno do provedor. O sistema não criará uma nova cobrança separada.</div>
<?php elseif($m['request_status']==='pending'):?><div class="alert alert-info mb-0">Sua solicitação está em análise pelo Master.</div>
<?php elseif(!empty($m['addon_sellable'])&&(float)$m['addon_monthly_price']>0):?><form method="post" action="/billing/modulos/<?=(int)$m['id']?>/solicitar"><?php echo \App\Core\CSRF::field();?><textarea class="form-control mb-2" name="note" rows="2" placeholder="Explique rapidamente como pretende usar este módulo (opcional)"></textarea><button class="btn btn-outline-primary w-100">Solicitar módulo</button></form>
<?php else:?><div class="text-secondary">Disponível somente por meio de mudança de plano.</div><?php endif;?>
<?php if(!empty($m['addon_id'])&&$m['addon_status']==='active'&&(\App\Core\Auth::user()['role']??'')==='owner'):?><form class="mt-3" method="post" action="/billing/modulos/adicionais/<?=(int)$m['addon_id']?>/cancelar" onsubmit="return confirm('Cancelar este módulo? O valor da assinatura será recalculado quando aplicável.')"><?php echo \App\Core\CSRF::field();?><button class="btn btn-sm btn-outline-danger">Cancelar módulo adicional</button></form><?php endif;?>
<?php if(!empty($m['master_note'])):?><div class="small text-secondary mt-3"><strong>Retorno da administração:</strong> <?=htmlspecialchars($m['master_note'])?></div><?php endif;?>
</div></div></div></div>
<?php endforeach;?>
<?php if(!$modules):?><div class="col-12"><div class="empty-state">Nenhum módulo adicional disponível.</div></div><?php endif;?>
</div>
