<div class="section-heading"><div><div class="eyebrow">Relacionamento</div><h1>Programa de fidelidade</h1><p class="text-secondary mb-0">Pontos, recompensas, indicações e saldo por cliente.</p></div></div>
<div class="row g-4"><div class="col-lg-5"><div class="card"><div class="card-body"><h2 class="h5">Configuração</h2><form method="post" action="/loyalty/settings" class="row g-2"><?=
\App\Core\CSRF::field()?><div class="col-12"><label class="form-check"><input class="form-check-input" type="checkbox" name="enabled" <?=$settings['enabled']?'checked':''?>> Programa ativo</label></div><div class="col-md-3"><label class="form-label">Pontos/R$1</label><input class="form-control" name="points_per_currency" value="<?=htmlspecialchars((string)$settings['points_per_currency'])?>"></div><div class="col-md-3"><label class="form-label">Meta</label><input class="form-control" type="number" name="reward_points" value="<?=(int)$settings['reward_points']?>"></div><div class="col-md-3"><label class="form-label">Benefício R$</label><input class="form-control" name="reward_value" value="<?=htmlspecialchars((string)$settings['reward_value'])?>"></div><div class="col-md-3"><label class="form-label">Pontos indicação</label><input class="form-control" type="number" name="referral_points" value="<?=(int)($settings['referral_points']??50)?>"></div><div class="col-12"><button class="btn btn-primary">Salvar</button></div></form></div></div></div>
<div class="col-lg-7"><div class="card"><div class="card-body"><h2 class="h5">Ações</h2><form method="post" action="/loyalty/adjust" class="row g-2 mb-3"><?=
\App\Core\CSRF::field()?><div class="col-md-5"><select class="form-select" name="customer_id" required><option value="">Cliente</option><?php foreach($customers as $c):?><option value="<?=(int)$c['id']?>"><?=htmlspecialchars($c['name'])?> · <?=(int)$c['points']?> pts</option><?php endforeach;?></select></div><div class="col-md-2"><input class="form-control" type="number" name="points" placeholder="+/-" required></div><div class="col-md-3"><input class="form-control" name="note" placeholder="Motivo" required></div><div class="col-md-2"><button class="btn btn-light w-100">Ajustar</button></div></form><div class="row g-2"><div class="col-md-6"><form method="post" action="/loyalty/redeem" class="d-flex gap-2"><?=
\App\Core\CSRF::field()?><select class="form-select" name="customer_id" required><option value="">Resgatar recompensa para...</option><?php foreach($customers as $c):?><option value="<?=(int)$c['id']?>"><?=htmlspecialchars($c['name'])?> · <?=(int)$c['points']?> pts</option><?php endforeach;?></select><button class="btn btn-outline-primary">Resgatar</button></form></div><div class="col-md-6"><form method="post" action="/loyalty/referrals" class="d-flex gap-2"><?=
\App\Core\CSRF::field()?><select class="form-select" name="referrer_customer_id" required><option value="">Quem indicou</option><?php foreach($customers as $c):?><option value="<?=(int)$c['id']?>"><?=htmlspecialchars($c['name'])?></option><?php endforeach;?></select><select class="form-select" name="referred_customer_id" required><option value="">Indicado</option><?php foreach($customers as $c):?><option value="<?=(int)$c['id']?>"><?=htmlspecialchars($c['name'])?></option><?php endforeach;?></select><button class="btn btn-outline-primary">Registrar</button></form></div></div></div></div></div></div>
<div class="card mt-4"><div class="card-header"><strong>Saldo dos clientes</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Cliente</th><th>Pontos</th><th>Progresso</th></tr></thead><tbody><?php foreach($customers as $c):$pct=min(100,round((int)$c['points']*100/max(1,(int)$settings['reward_points'])));?><tr><td><a href="/customers/<?=(int)$c['id']?>"><?=htmlspecialchars($c['name'])?></a></td><td><strong><?=(int)$c['points']?> pts</strong></td><td style="min-width:180px"><div class="progress"><div class="progress-bar" style="width:<?=$pct?>%"></div></div></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="row g-4 mt-1"><div class="col-lg-6"><div class="card"><div class="card-header"><strong>Recompensas emitidas</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Cliente</th><th>Valor</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rewards as $r):?><tr><td><?=htmlspecialchars($r['customer_name'])?></td><td>R$ <?=number_format((float)$r['reward_value'],2,',','.')?></td><td><?=htmlspecialchars($r['status'])?></td><td><?php if($r['status']==='available'):?><form method="post" action="/loyalty/rewards/<?=(int)$r['id']?>/redeem"><?=
\App\Core\CSRF::field()?><button class="btn btn-sm btn-outline-success">Marcar utilizada</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div></div><div class="col-lg-6"><div class="card"><div class="card-header"><strong>Indicações</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Indicador</th><th>Indicado</th><th>Pontos</th><th>Status</th></tr></thead><tbody><?php foreach($referrals as $r):?><tr><td><?=htmlspecialchars($r['referrer_name'])?></td><td><?=htmlspecialchars($r['referred_name'])?></td><td><?=(int)$r['reward_points']?></td><td><?=htmlspecialchars($r['status'])?></td></tr><?php endforeach;?></tbody></table></div></div></div></div>
