# Generated by Django 5.2.17 on 2026-09-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_merge_onboarding_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantonboarding',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
