# Generated by Django 5.2.17 on 2026-10-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_unit_business_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='cover',
            field=models.ImageField(blank=True, upload_to='unit/cover/'),
        ),
        migrations.AddField(
            model_name='unit',
            name='logo',
            field=models.ImageField(blank=True, upload_to='unit/logo/'),
        ),
        migrations.AddField(
            model_name='unit',
            name='public_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='unit',
            name='schedule_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
