# Generated by Django 5.2.17 on 2026-10-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_unit_public_and_schedule_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='archive_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tenant',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
