# Generated by Django 5.2.18 on 2026-10-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_tenant_archive_snapshot_tenant_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='simple_mode',
            field=models.BooleanField(default=False, editable=False, verbose_name='Modo simples'),
        ),
    ]
