# Generated by Django 5.2.17 on 2026-09-21 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0006_barber_lifecycle'),
        ('tenants', '0004_normalize_index_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('evolution', 'Evolução'), ('anamnesis', 'Anamnese'), ('procedure', 'Procedimento'), ('observation', 'Observação'), ('follow_up', 'Acompanhamento')], default='evolution', max_length=20)),
                ('title', models.CharField(max_length=190)),
                ('content_encrypted', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='scheduling.appointment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='scheduling.customer')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='scheduling.professional')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecordAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Visualização'), ('create', 'Criação'), ('export', 'Exportação')], max_length=12)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record_access', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_record_access', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_log', to='healthcare.medicalrecordentry')),
            ],
        ),
        migrations.AddIndex(
            model_name='medicalrecordentry',
            index=models.Index(fields=['tenant', 'customer', 'created_at'], name='health_record_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecordentry',
            index=models.Index(fields=['tenant', 'professional', 'created_at'], name='health_record_prof_idx'),
        ),
    ]
