# Generated by Django 5.2.17 on 2026-09-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenthub', '0002_public_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformHomepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='platform/')),
                ('hero_title', models.CharField(default='Transforme horários livres em clientes.', max_length=160)),
                ('hero_description', models.CharField(default='Receba agendamentos online, organize sua equipe e acompanhe as vendas no mesmo lugar.', max_length=400)),
                ('closing_title', models.CharField(default='Organize hoje. Escale amanhã.', max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
