# Generated by Django 5.2.18 on 2026-10-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenthub', '0004_faq_medical_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformhomepage',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='platform/'),
        ),
        migrations.AddField(
            model_name='platformhomepage',
            name='logo_dark',
            field=models.ImageField(blank=True, upload_to='platform/'),
        ),
        migrations.AddField(
            model_name='platformhomepage',
            name='logo_light',
            field=models.ImageField(blank=True, upload_to='platform/'),
        ),
    ]
