<?php
namespace App\Controllers;

use App\Core\{Auth,Audit,CSRF,Database,Encryption,HttpException,TenantContext};
use App\Services\{MercadoPagoProvider,NotificationService};

final class BillingSupportController
{
    public function requestDeletion():void
    {
        Auth::requireRole('owner');CSRF::enforce();$t=TenantContext::id();$reason=trim((string)($_POST['reason']??''));if(mb_strlen($reason)<10)HttpException::abort(422,'Explique brevemente o motivo da solicitação.');
        $pdo=Database::connection();$q=$pdo->prepare("SELECT id,ticket_id FROM billing_support_requests WHERE tenant_id=:t AND request_type='account_deletion' AND status='pending' LIMIT 1");$q->execute(['t'=>$t]);if($old=$q->fetch()){header('Location: /support/'.$old['ticket_id']);exit;}
        $protocol=$this->protocol('EXC');$pdo->beginTransaction();try{$pdo->prepare("INSERT INTO support_tickets(protocol,tenant_id,user_id,category,subject,description,source_url,browser_context,app_version,priority,status,remote_access_allowed,created_at,updated_at)VALUES(:p,:t,:u,'billing','Solicitação de exclusão da conta',:d,'/billing',:browser,:version,'high','open',0,NOW(),NOW())")->execute(['p'=>$protocol,'t'=>$t,'u'=>Auth::user()['id'],'d'=>$reason,'browser'=>substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,500),'version'=>(string)((require __DIR__.'/../../config/app.php')['version']??'')]);$ticket=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO billing_support_requests(tenant_id,user_id,ticket_id,request_type,status,deadline_at,created_at,updated_at)VALUES(:t,:u,:ticket,'account_deletion','pending',DATE_ADD(NOW(),INTERVAL 5 DAY),NOW(),NOW())")->execute(['t'=>$t,'u'=>Auth::user()['id'],'ticket'=>$ticket]);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
        Audit::log('ACCOUNT_DELETION_REQUESTED','tenants',$t,null,['ticket_id'=>$ticket]);NotificationService::platformStaff('billing.account_deletion','Exclusão de conta solicitada',$protocol.' — prazo de análise de até 5 dias.','/support/'.$ticket,'warning');header('Location: /support/'.$ticket);exit;
    }

    public function requestInvoice():void
    {
        Auth::requireRole('owner');CSRF::enforce();$t=TenantContext::id();$period=trim((string)($_POST['reference_period']??''));if(!preg_match('/^\d{4}-\d{2}$/',$period))HttpException::abort(422,'Informe o mês de referência.');$pdo=Database::connection();$q=$pdo->prepare("SELECT ticket_id FROM billing_support_requests WHERE tenant_id=:t AND request_type='invoice' AND reference_period=:period AND status='pending' LIMIT 1");$q->execute(['t'=>$t,'period'=>$period]);if($old=$q->fetch()){header('Location: /support/'.$old['ticket_id']);exit;}
        $protocol=$this->protocol('NF');$description='Solicitação de nota fiscal referente a '.date('m/Y',strtotime($period.'-01')).'.';$subject='Solicitação de nota fiscal — '.date('m/Y',strtotime($period.'-01'));$pdo->beginTransaction();try{$pdo->prepare("INSERT INTO support_tickets(protocol,tenant_id,user_id,category,subject,description,source_url,browser_context,app_version,priority,status,remote_access_allowed,created_at,updated_at)VALUES(:p,:t,:u,'billing',:subject,:d,'/billing',:browser,:version,'normal','open',0,NOW(),NOW())")->execute(['p'=>$protocol,'t'=>$t,'u'=>Auth::user()['id'],'subject'=>$subject,'d'=>$description,'browser'=>substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,500),'version'=>(string)((require __DIR__.'/../../config/app.php')['version']??'')]);$ticket=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO billing_support_requests(tenant_id,user_id,ticket_id,request_type,status,reference_period,created_at,updated_at)VALUES(:t,:u,:ticket,'invoice','pending',:period,NOW(),NOW())")->execute(['t'=>$t,'u'=>Auth::user()['id'],'ticket'=>$ticket,'period'=>$period]);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
        Audit::log('INVOICE_REQUESTED','tenants',$t,null,['ticket_id'=>$ticket,'period'=>$period]);NotificationService::platformStaff('billing.invoice_requested','Nota fiscal solicitada',$protocol.' — referência '.$period.'.','/support/'.$ticket,'info');header('Location: /support/'.$ticket);exit;
    }

    public function approveDeletion(string $id):void
    {
        Auth::requireRole('master');CSRF::enforce();if(!isset($_POST['financial_confirmed']))HttpException::abort(422,'Confirme a verificação financeira antes de aprovar.');$requestId=(int)$id;$pdo=Database::connection();$q=$pdo->prepare("SELECT br.*,st.status ticket_status,t.status tenant_status,s.id subscription_id,s.provider_subscription_id FROM billing_support_requests br JOIN support_tickets st ON st.id=br.ticket_id JOIN tenants t ON t.id=br.tenant_id LEFT JOIN subscriptions s ON s.id=(SELECT MAX(s2.id) FROM subscriptions s2 WHERE s2.tenant_id=br.tenant_id) WHERE br.id=:id AND br.request_type='account_deletion' AND br.status='pending'");$q->execute(['id'=>$requestId]);$r=$q->fetch();if(!$r)HttpException::abort(404,'Solicitação pendente não encontrada.');
        $bad=$pdo->prepare("SELECT (SELECT COUNT(*) FROM invoices WHERE tenant_id=:t AND status='overdue')+(SELECT COUNT(*) FROM payments WHERE tenant_id=:t2 AND status='pending')");$bad->execute(['t'=>$r['tenant_id'],'t2'=>$r['tenant_id']]);if((int)$bad->fetchColumn()>0)HttpException::abort(422,'Existem cobranças vencidas ou pagamentos pendentes. Regularize ou analise antes de aprovar.');
        if(!empty($r['provider_subscription_id'])){$gateway=$pdo->query("SELECT access_token_encrypted FROM payment_gateways WHERE provider='mercadopago' AND active=1 AND last_test_status='validated' ORDER BY (environment='production') DESC,last_tested_at DESC LIMIT 1")->fetch();if(!$gateway)HttpException::abort(503,'Mercado Pago não está disponível para cancelar a recorrência.');try{(new MercadoPagoProvider(Encryption::decrypt($gateway['access_token_encrypted'])['value']??''))->cancelSubscription((string)$r['provider_subscription_id']);}catch(\Throwable $e){HttpException::abort(502,'Não foi possível cancelar a recorrência: '.$e->getMessage());}}
        $pdo->beginTransaction();try{$pdo->prepare("UPDATE tenants SET status='cancelled',updated_at=NOW() WHERE id=:t")->execute(['t'=>$r['tenant_id']]);$pdo->prepare("UPDATE subscriptions SET status='cancelled',cancelled_at=COALESCE(cancelled_at,NOW()),updated_at=NOW() WHERE id=:id")->execute(['id'=>$r['subscription_id']]);$pdo->prepare("UPDATE users SET status='inactive',session_version=session_version+1,updated_at=NOW() WHERE tenant_id=:t")->execute(['t'=>$r['tenant_id']]);$pdo->prepare("UPDATE billing_support_requests SET status='completed',reviewed_by=:u,reviewed_at=NOW(),completed_at=NOW(),updated_at=NOW() WHERE id=:id")->execute(['u'=>Auth::user()['id'],'id'=>$requestId]);$pdo->prepare("UPDATE support_tickets SET status='resolved',updated_at=NOW() WHERE id=:id")->execute(['id'=>$r['ticket_id']]);$pdo->prepare("INSERT INTO tenant_status_history(tenant_id,from_status,to_status,reason,changed_by,created_at)VALUES(:t,:from_status,'cancelled','Exclusão/inativação aprovada pelo Master',:u,NOW())")->execute(['t'=>$r['tenant_id'],'from_status'=>$r['tenant_status'],'u'=>Auth::user()['id']]);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}Audit::log('ACCOUNT_DELETION_APPROVED','tenants',(int)$r['tenant_id'],null,['ticket_id'=>$r['ticket_id']]);header('Location: /support/'.$r['ticket_id']);exit;
    }

    public function uploadInvoice(string $id):void
    {
        Auth::requireRole('master');CSRF::enforce();$requestId=(int)$id;$pdo=Database::connection();$q=$pdo->prepare("SELECT br.*,st.user_id FROM billing_support_requests br JOIN support_tickets st ON st.id=br.ticket_id WHERE br.id=:id AND br.request_type='invoice' AND br.status='pending'");$q->execute(['id'=>$requestId]);$r=$q->fetch();if(!$r)HttpException::abort(404,'Solicitação pendente não encontrada.');$f=$_FILES['invoice_pdf']??[];if(($f['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||(int)($f['size']??0)<1||(int)$f['size']>10*1024*1024)HttpException::abort(422,'Envie um PDF de até 10 MB.');$tmp=(string)($f['tmp_name']??'');if(!is_uploaded_file($tmp)||(new \finfo(FILEINFO_MIME_TYPE))->file($tmp)!=='application/pdf')HttpException::abort(422,'O arquivo precisa ser um PDF válido.');$dir=dirname(__DIR__,2).'/storage/private/support/'.(int)$r['tenant_id'];if(!is_dir($dir)&&!mkdir($dir,0750,true)&&!is_dir($dir))throw new \RuntimeException('Não foi possível preparar o armazenamento.');$relative=(int)$r['tenant_id'].'/'.bin2hex(random_bytes(20)).'.pdf';if(!move_uploaded_file($tmp,dirname(__DIR__,2).'/storage/private/support/'.$relative))throw new \RuntimeException('Não foi possível salvar o PDF.');
        $pdo->beginTransaction();try{$pdo->prepare('INSERT INTO support_messages(ticket_id,user_id,message,attachment_path,created_at)VALUES(:t,:u,:m,:a,NOW())')->execute(['t'=>$r['ticket_id'],'u'=>Auth::user()['id'],'m'=>'Nota fiscal disponibilizada. O PDF já pode ser baixado em Minha assinatura.','a'=>$relative]);$message=(int)$pdo->lastInsertId();$pdo->prepare("UPDATE billing_support_requests SET status='completed',attachment_message_id=:message,reviewed_by=:u,reviewed_at=NOW(),completed_at=NOW(),updated_at=NOW() WHERE id=:id")->execute(['message'=>$message,'u'=>Auth::user()['id'],'id'=>$requestId]);$pdo->prepare("UPDATE support_tickets SET status='resolved',updated_at=NOW() WHERE id=:id")->execute(['id'=>$r['ticket_id']]);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();@unlink(dirname(__DIR__,2).'/storage/private/support/'.$relative);throw $e;}Audit::log('INVOICE_PDF_UPLOADED','support_tickets',(int)$r['ticket_id'],null,['request_id'=>$requestId]);NotificationService::user((int)$r['user_id'],(int)$r['tenant_id'],'billing.invoice_ready','Nota fiscal disponível','Sua nota fiscal já está disponível em Minha assinatura.','/billing','success');header('Location: /support/'.$r['ticket_id']);exit;
    }

    private function protocol(string $prefix):string{return $prefix.'-'.date('ymd').'-'.strtoupper(substr(bin2hex(random_bytes(4)),0,6));}
}
