<?php
namespace App\Controllers;
use App\Core\{Auth,Audit,CSRF,Database,HttpException,RateLimiter,View};
final class CommercialLeadController
{
 public function form():void{View::render('commercial/interest',['title'=>'Fale com nosso comercial','publicLayout'=>true,'plans'=>[]]);}
 public function store():void
 {
  CSRF::enforce();$ip=(string)($_SERVER['REMOTE_ADDR']??'unknown');if(!RateLimiter::hit('commercial-lead|'.$ip,4,3600))HttpException::abort(429,'Muitas solicitações. Tente novamente mais tarde.');$name=trim((string)($_POST['name']??''));$phone=preg_replace('/\D/','',(string)($_POST['phone']??''));$email=mb_strtolower(trim((string)($_POST['email']??'')));$type=trim((string)($_POST['business_type']??''));$consent=($_POST['privacy_consent']??'')==='1';$version=(string)($_POST['consent_version']??'');if(mb_strlen($name)<2||strlen($phone)<10||!filter_var($email,FILTER_VALIDATE_EMAIL)||mb_strlen($type)<2||!$consent||$version!=='commercial-lead-v1')HttpException::abort(422,'Preencha os dados e confirme a Política de Privacidade.');$pdo=Database::connection();$days=(int)($pdo->query('SELECT lead_retention_days FROM platform_operation_settings WHERE id=1')->fetchColumn()?:730);$q=$pdo->prepare("INSERT INTO commercial_leads(name,phone,email,business_type,contact_deadline_at,source,status,ip_hash,consent_granted,consent_version,consent_purpose,consent_at,consent_user_agent,retention_until,created_at,updated_at)VALUES(:n,:p,:e,:b,DATE_ADD(NOW(),INTERVAL 30 MINUTE),'public_interest_form','new',:ip,1,:v,'Contato comercial sobre planos, implantação e demonstração',NOW(),:ua,DATE_ADD(NOW(),INTERVAL :days DAY),NOW(),NOW())");$q->execute(['n'=>mb_substr($name,0,160),'p'=>$phone,'e'=>$email,'b'=>mb_substr($type,0,100),'ip'=>hash('sha256',$ip),'v'=>$version,'ua'=>mb_substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,500),'days'=>$days]);$id=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO commercial_lead_history(lead_id,action,notes,created_at)VALUES(:l,'created','Formulário público com consentimento',NOW())")->execute(['l'=>$id]);$pdo->prepare("INSERT INTO lead_privacy_events(lead_id,action,ip_hash,metadata_json,created_at)VALUES(:l,'created',:ip,:m,NOW())")->execute(['l'=>$id,'ip'=>hash('sha256',$ip),'m'=>json_encode(['consent_version'=>$version,'purpose'=>'commercial_contact'],JSON_UNESCAPED_UNICODE)]);View::render('commercial/interest-success',['title'=>'Solicitação recebida','publicLayout'=>true,'plans'=>[]]);
 }
 public function queue():void
 {
  $u=$this->staff();$pdo=Database::connection();$master=($u['role']??'')==='master';$where=$master?'WHERE l.anonymized_at IS NULL':"WHERE l.anonymized_at IS NULL AND (l.assigned_to IS NULL OR l.assigned_to=".(int)$u['id'].")";$sql="SELECT l.*,a.name assigned_name FROM commercial_leads l LEFT JOIN users a ON a.id=l.assigned_to {$where} ORDER BY FIELD(l.status,'new','in_service','contacted','qualified','converted','lost'),l.created_at DESC LIMIT 300";$leads=$pdo->query($sql)->fetchAll();foreach($leads as $lead){$pdo->prepare("INSERT INTO lead_privacy_events(lead_id,action,actor_user_id,ip_hash,created_at)VALUES(:l,'viewed',:u,:ip,NOW())")->execute(['l'=>$lead['id'],'u'=>$u['id'],'ip'=>hash('sha256',(string)($_SERVER['REMOTE_ADDR']??''))]);}$targets=$pdo->query("SELECT DISTINCT u.id,u.name,r.slug role_slug FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id LEFT JOIN commercial_profiles cp ON cp.user_id=u.id WHERE u.tenant_id IS NULL AND u.status='active' AND (r.slug='master' OR (r.slug='commercial' AND cp.active=1)) ORDER BY r.slug,u.name")->fetchAll();View::render('commercial-team/leads',['title'=>'Oportunidades comerciais','leads'=>$leads,'targets'=>$targets,'masterMode'=>$master]);
 }
 public function claim(string $id):void{$u=$this->staff();CSRF::enforce();$q=Database::connection()->prepare("UPDATE commercial_leads SET assigned_to=:u,assigned_at=NOW(),status='in_service',updated_at=NOW() WHERE id=:id AND assigned_to IS NULL AND status='new' AND do_not_contact=0 AND anonymized_at IS NULL");$q->execute(['u'=>$u['id'],'id'=>(int)$id]);if($q->rowCount()!==1)HttpException::abort(409,'Esta oportunidade está indisponível ou já foi atendida.');Audit::log('COMMERCIAL_LEAD_CLAIMED','commercial_leads',(int)$id,null,['assigned_to'=>$u['id']]);header('Location: /comercial/oportunidades');exit;}
 public function transfer(string $id):void{$u=$this->staff();CSRF::enforce();$target=(int)($_POST['target_user_id']??0);$pdo=Database::connection();$valid=$pdo->prepare("SELECT 1 FROM users x JOIN user_roles ur ON ur.user_id=x.id JOIN roles r ON r.id=ur.role_id LEFT JOIN commercial_profiles cp ON cp.user_id=x.id WHERE x.id=:id AND x.tenant_id IS NULL AND x.status='active' AND (r.slug='master' OR (r.slug='commercial' AND cp.active=1)) LIMIT 1");$valid->execute(['id'=>$target]);if(!$target||!$valid->fetchColumn())HttpException::abort(422,'Destino inválido.');$q=$pdo->prepare('UPDATE commercial_leads SET assigned_to=:to,assigned_at=NOW(),last_transferred_by=:actor,last_transferred_at=NOW(),updated_at=NOW() WHERE id=:id AND do_not_contact=0 AND anonymized_at IS NULL');$q->execute(['to'=>$target,'actor'=>$u['id'],'id'=>(int)$id]);if(!$q->rowCount())HttpException::abort(404,'Oportunidade indisponível.');Audit::log('COMMERCIAL_LEAD_TRANSFERRED','commercial_leads',(int)$id,null,['assigned_to'=>$target]);header('Location: /comercial/oportunidades');exit;}
 public function status(string $id):void
 {
  $u=$this->staff();CSRF::enforce();$status=(string)($_POST['status']??'');if(!in_array($status,['in_service','contacted','qualified','converted','lost'],true))HttpException::abort(422,'Status inválido.');
  $next=trim((string)($_POST['next_contact_at']??''));if($next!==''){$dt=\DateTimeImmutable::createFromFormat('Y-m-d\TH:i',$next);if(!$dt)HttpException::abort(422,'Data do próximo contato inválida.');$next=$dt->format('Y-m-d H:i:s');}else $next=null;
  $raw=str_replace(['R$',' ','.'],['','',''],trim((string)($_POST['estimated_value']??'')));$raw=str_replace(',','.',$raw);$estimated=$raw===''?null:(is_numeric($raw)?round((float)$raw,2):false);if($estimated===false||($estimated!==null&&$estimated<0))HttpException::abort(422,'Valor estimado inválido.');
  $notes=mb_substr(trim((string)($_POST['notes']??'')),0,2000)?:null;$loss=$status==='lost'?(mb_substr(trim((string)($_POST['loss_reason']??'')),0,500)?:'Não informado'):null;
  $pdo=Database::connection();$current=$pdo->prepare('SELECT status FROM commercial_leads WHERE id=:id');$current->execute(['id'=>(int)$id]);$from=(string)($current->fetchColumn()?:'');$q=$pdo->prepare('UPDATE commercial_leads SET status=:s,notes=:n,next_contact_at=:next,estimated_value=:value,loss_reason=:loss,updated_at=NOW() WHERE id=:id AND do_not_contact=0 AND anonymized_at IS NULL'.(($u['role']??'')==='master'?'':' AND assigned_to=:u'));$params=['s'=>$status,'n'=>$notes,'next'=>$next,'value'=>$estimated,'loss'=>$loss,'id'=>(int)$id];if(($u['role']??'')!=='master')$params['u']=$u['id'];$q->execute($params);if(!$q->rowCount()&&$from==='')HttpException::abort(403,'Oportunidade indisponível.');
  $pdo->prepare("INSERT INTO commercial_lead_history(lead_id,action,notes,actor_user_id,created_at)VALUES(:l,'status_changed',:n,:u,NOW())")->execute(['l'=>(int)$id,'n'=>mb_substr($from.' → '.$status.($next?' | retorno '.$next:''),0,500),'u'=>$u['id']]);Audit::log('COMMERCIAL_LEAD_UPDATED','commercial_leads',(int)$id,null,['from'=>$from,'to'=>$status,'next_contact_at'=>$next,'estimated_value'=>$estimated]);header('Location: /comercial/oportunidades?salvo=1');exit;
 }
 public function privacy(string $id):void{Auth::requireRole('master');CSRF::enforce();$action=(string)($_POST['action']??'');if(!in_array($action,['do_not_contact','anonymize'],true))HttpException::abort(422,'Ação inválida.');$pdo=Database::connection();if($action==='do_not_contact')$pdo->prepare("UPDATE commercial_leads SET do_not_contact=1,status='lost',updated_at=NOW() WHERE id=:id")->execute(['id'=>(int)$id]);else $pdo->prepare("UPDATE commercial_leads SET name=CONCAT('Lead anonimizado #',id),phone='',email=CONCAT('anon+',id,'@invalid.local'),business_type='Anonimizado',notes=NULL,ip_hash=NULL,consent_user_agent=NULL,do_not_contact=1,anonymized_at=NOW(),updated_at=NOW() WHERE id=:id")->execute(['id'=>(int)$id]);$pdo->prepare("INSERT INTO lead_privacy_events(lead_id,action,actor_user_id,created_at)VALUES(:l,:a,:u,NOW())")->execute(['l'=>(int)$id,'a'=>$action==='anonymize'?'anonymized':'do_not_contact','u'=>Auth::user()['id']]);Audit::log('COMMERCIAL_LEAD_PRIVACY','commercial_leads',(int)$id,null,['action'=>$action]);header('Location: /comercial/oportunidades');exit;}
 public function export(string $id):void{Auth::requireRole('master');$pdo=Database::connection();$q=$pdo->prepare('SELECT id,name,phone,email,business_type,status,source,consent_granted,consent_version,consent_purpose,consent_at,retention_until,created_at FROM commercial_leads WHERE id=:id AND anonymized_at IS NULL');$q->execute(['id'=>(int)$id]);$lead=$q->fetch();if(!$lead)HttpException::abort(404,'Lead não encontrado.');$pdo->prepare("INSERT INTO lead_privacy_events(lead_id,action,actor_user_id,ip_hash,created_at)VALUES(:l,'exported',:u,:ip,NOW())")->execute(['l'=>$lead['id'],'u'=>Auth::user()['id'],'ip'=>hash('sha256',(string)($_SERVER['REMOTE_ADDR']??''))]);Audit::log('COMMERCIAL_LEAD_EXPORTED','commercial_leads',(int)$id);header('Content-Type: application/json');header('Content-Disposition: attachment; filename="lead-'.$id.'.json"');header('Cache-Control: private, no-store');echo json_encode($lead,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE);exit;}
 private function staff():array{Auth::requireRole('master','commercial');return Auth::user();}
}
