<?php
namespace App\Controllers;
use App\Core\{Auth,Audit,CSRF,Database,HttpException,View};
final class CommercialTeamController
{
 private function actor(bool $master=false):array{if($master)Auth::requireRole('master');else Auth::requireRole('commercial');return Auth::user();}
 public function index():void{$this->dashboard(false);}public function masterIndex():void{$this->dashboard(true);}
 private function dashboard(bool $master):void
 {
  $user=$this->actor($master);$pdo=Database::connection();$id=(int)$user['id'];
  if($master){$profile=['commission_percent'=>0,'max_discount_percent'=>100];$code='';}else{$q=$pdo->prepare('SELECT * FROM commercial_profiles WHERE user_id=:u');$q->execute(['u'=>$id]);$profile=$q->fetch();if(!$profile)HttpException::abort(403,'Perfil comercial não configurado pelo Master.');$q=$pdo->prepare('SELECT referral_code FROM marketing_referral_profiles WHERE user_id=:u AND active=1');$q->execute(['u'=>$id]);$code=(string)$q->fetchColumn();}
  $plans=$pdo->query('SELECT id,name,description,monthly_price,trial_days FROM plans WHERE active=1 AND public_visible=1 AND is_custom=0 ORDER BY sort_order,monthly_price')->fetchAll();$modules=$pdo->query('SELECT id,name,description FROM modules WHERE active=1 ORDER BY sort_order,name')->fetchAll();
  if($master){$stats=$pdo->query("SELECT COUNT(*) indications,SUM(status IN('approved','paid')) paid_customers,COALESCE(SUM(IF(status='projected',commission_amount,0)),0) projected,COALESCE(SUM(IF(status IN('approved','paid'),commission_amount,0)),0) approved FROM commercial_commissions")->fetch();$commissions=$pdo->query('SELECT cc.*,t.name tenant_name,u.name commercial_name FROM commercial_commissions cc JOIN tenants t ON t.id=cc.tenant_id JOIN users u ON u.id=cc.commercial_user_id ORDER BY cc.id DESC LIMIT 100')->fetchAll();$proposals=$pdo->query('SELECT cp.*,p.name plan_name,u.name commercial_name FROM commercial_proposals cp JOIN plans p ON p.id=cp.plan_id JOIN users u ON u.id=cp.commercial_user_id ORDER BY cp.id DESC LIMIT 150')->fetchAll();}
  else{$q=$pdo->prepare("SELECT COUNT(*) indications,SUM(status IN('approved','paid')) paid_customers,COALESCE(SUM(IF(status='projected',commission_amount,0)),0) projected,COALESCE(SUM(IF(status IN('approved','paid'),commission_amount,0)),0) approved FROM commercial_commissions WHERE commercial_user_id=:u");$q->execute(['u'=>$id]);$stats=$q->fetch();$q=$pdo->prepare('SELECT cc.*,t.name tenant_name FROM commercial_commissions cc JOIN tenants t ON t.id=cc.tenant_id WHERE cc.commercial_user_id=:u ORDER BY cc.id DESC LIMIT 100');$q->execute(['u'=>$id]);$commissions=$q->fetchAll();$q=$pdo->prepare('SELECT cp.*,p.name plan_name FROM commercial_proposals cp JOIN plans p ON p.id=cp.plan_id WHERE cp.commercial_user_id=:u ORDER BY cp.id DESC LIMIT 100');$q->execute(['u'=>$id]);$proposals=$q->fetchAll();}
  $leadWhere=$master?'l.anonymized_at IS NULL':'l.anonymized_at IS NULL AND l.assigned_to='.(int)$id;
  $leadStats=$this->safeRow($pdo,"SELECT COUNT(*) total,SUM(l.status='new') new_count,SUM(l.status='in_service') in_service,SUM(l.status='contacted') contacted,SUM(l.status='qualified') qualified,SUM(l.status='converted') converted,SUM(l.status='lost') lost,SUM(l.contact_deadline_at<NOW() AND l.status IN('new','in_service')) overdue,COALESCE(SUM(IF(l.status IN('new','in_service','contacted','qualified'),l.estimated_value,0)),0) pipeline FROM commercial_leads l WHERE {$leadWhere}");
  $nextLeads=$this->safeRows($pdo,"SELECT l.id,l.name,l.phone,l.business_type,l.status,l.contact_deadline_at,l.next_contact_at,l.estimated_value,a.name assigned_name FROM commercial_leads l LEFT JOIN users a ON a.id=l.assigned_to WHERE {$leadWhere} AND l.status NOT IN('converted','lost') ORDER BY (l.contact_deadline_at<NOW()) DESC,(l.next_contact_at IS NULL),l.next_contact_at,l.created_at LIMIT 8");
  $app=require __DIR__.'/../../config/app.php';View::render('commercial-team/index',['title'=>$master?'Central comercial Master':'Painel comercial','profile'=>$profile,'plans'=>$plans,'modules'=>$modules,'stats'=>$stats,'leadStats'=>$leadStats,'nextLeads'=>$nextLeads,'commissions'=>$commissions,'proposals'=>$proposals,'referralUrl'=>$code?rtrim($app['url'],'/').'/indicacao/'.$code:'','masterMode'=>$master]);
 }
 public function proposal():void{$this->createProposal(false);}public function masterProposal():void{$this->createProposal(true);}
 private function createProposal(bool $master):void
 {
  $user=$this->actor($master);CSRF::enforce();$pdo=Database::connection();$max=100.0;if(!$master){$q=$pdo->prepare('SELECT max_discount_percent FROM commercial_profiles WHERE user_id=:u AND active=1');$q->execute(['u'=>$user['id']]);$max=(float)$q->fetchColumn();}
  $baseId=(int)($_POST['plan_id']??0);$base=null;if($baseId>0){$q=$pdo->prepare('SELECT * FROM plans WHERE id=:id AND active=1 AND public_visible=1 AND is_custom=0');$q->execute(['id'=>$baseId]);$base=$q->fetch();if(!$base)HttpException::abort(422,'O plano base selecionado está indisponível. Escolha outro ou deixe o campo sem plano base.');}$title=trim((string)($_POST['title']??''));$customName=trim((string)($_POST['custom_plan_name']??$title));$price=$this->money($_POST['custom_price']??null);if(mb_strlen($title)<3||mb_strlen($customName)<2||$price===null||$price<=0)HttpException::abort(422,'Informe nome e valor válido para a proposta.');$minimum=$base?round((float)$base['monthly_price']*(1-$max/100),2):0.0;$needsApproval=!$master&&$base!==null&&$price<$minimum;
  $moduleIds=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['modules']??[])))));if(!$moduleIds)HttpException::abort(422,'Selecione pelo menos um módulo.');$marks=implode(',',array_fill(0,count($moduleIds),'?'));$q=$pdo->prepare("SELECT id,name FROM modules WHERE active=1 AND id IN ($marks)");$q->execute($moduleIds);$validModules=$q->fetchAll();if(count($validModules)!==count($moduleIds))HttpException::abort(422,'Módulo inválido ou inativo.');$features=[];foreach((array)($_POST['included_features']??[]) as $block){foreach(preg_split('/\R/u',(string)$block)?:[] as $f){$f=trim(strip_tags($f));if($f!==''&&mb_strlen($f)<=120&&!in_array($f,$features,true))$features[]=$f;if(count($features)>=30)break 2;}}$trial=max(0,min(90,(int)($_POST['trial_days']??($base['trial_days']??14))));$token=bin2hex(random_bytes(16));$discount=$base&&(float)$base['monthly_price']>0?max(0,round((1-$price/(float)$base['monthly_price'])*100,2)):0.0;
  $pdo->beginTransaction();try{$planFeatures=json_decode((string)($base['features_json']??'{}'),true)?:[];$planFeatures['included_features']=$features;$description=trim((string)($_POST['notes']??''))?:($base['description']??'Plano personalizado conforme proposta comercial.');$pdo->prepare("INSERT INTO plans(name,slug,description,monthly_price,quarterly_price,semiannual_price,annual_price,trial_days,trial_without_card,active,public_visible,is_custom,created_by_user_id,featured,sort_order,features_json,created_at,updated_at)VALUES(:name,:slug,:description,:price,:quarter,:semester,:annual,:trial,1,1,0,1,:creator,0,9999,:features,NOW(),NOW())")->execute(['name'=>$customName,'slug'=>'oferta-'.$token,'description'=>$description,'price'=>$price,'quarter'=>round($price*3,2),'semester'=>round($price*6,2),'annual'=>round($price*12,2),'trial'=>$trial,'creator'=>$user['id'],'features'=>json_encode($planFeatures,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR)]);$planId=(int)$pdo->lastInsertId();$ins=$pdo->prepare('INSERT INTO plan_modules(plan_id,module_id,enabled)VALUES(:p,:m,1)');foreach($moduleIds as $m)$ins->execute(['p'=>$planId,'m'=>$m]);$pdo->prepare("INSERT INTO commercial_proposals(commercial_user_id,plan_id,base_plan_id,title,customer_name,customer_email,discount_percent,final_price,notes,modules_json,features_json,public_token,status,approval_status,expires_at,created_at,updated_at)VALUES(:u,:p,:base,:title,:name,:email,:discount,:price,:notes,:modules,:features,:token,'sent',:approval,DATE_ADD(NOW(),INTERVAL 30 DAY),NOW(),NOW())")->execute(['u'=>$user['id'],'p'=>$planId,'base'=>$baseId?:null,'title'=>$title,'name'=>trim((string)($_POST['customer_name']??''))?:null,'email'=>mb_strtolower(trim((string)($_POST['customer_email']??'')))?:null,'discount'=>$discount,'price'=>$price,'notes'=>trim((string)($_POST['notes']??''))?:null,'modules'=>json_encode(array_column($validModules,'name'),JSON_UNESCAPED_UNICODE),'features'=>json_encode($features,JSON_UNESCAPED_UNICODE),'token'=>$token,'approval'=>$needsApproval?'pending':'not_required']);$proposalId=(int)$pdo->lastInsertId();$pdo->commit();Audit::log($master?'MASTER_CUSTOM_PROPOSAL_CREATED':'COMMERCIAL_PROPOSAL_CREATED','commercial_proposals',$proposalId,null,['custom_plan_id'=>$planId,'base_plan_id'=>$baseId?:null,'price'=>$price]);}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}header('Location: '.($master?'/master/comercial':'/comercial').'?proposta=ok');exit;
 }
 public function publicProposal(string $token):void{if(!preg_match('/^[a-f0-9]{32}$/',$token))HttpException::abort(404,'Proposta inválida.');$pdo=Database::connection();$q=$pdo->prepare("SELECT cp.*,p.name plan_name,p.description,u.name commercial_name,rp.referral_code FROM commercial_proposals cp JOIN plans p ON p.id=cp.plan_id JOIN users u ON u.id=cp.commercial_user_id LEFT JOIN marketing_referral_profiles rp ON rp.user_id=u.id AND rp.active=1 WHERE cp.public_token=:t AND cp.approval_status IN('not_required','approved') AND cp.status NOT IN('expired','cancelled') AND (cp.expires_at IS NULL OR cp.expires_at>NOW())");$q->execute(['t'=>$token]);$proposal=$q->fetch();if(!$proposal)HttpException::abort(404,'Proposta indisponível.');$pdo->prepare("UPDATE commercial_proposals SET status=IF(status='sent','viewed',status),updated_at=NOW() WHERE id=:id")->execute(['id'=>$proposal['id']]);View::render('commercial-team/proposal',['title'=>'Proposta ApPlanner','proposal'=>$proposal,'publicLayout'=>true]);}
 public function acceptProposal(string $token):void{CSRF::enforce();if(!preg_match('/^[a-f0-9]{32}$/',$token))HttpException::abort(404,'Proposta inválida.');$pdo=Database::connection();$q=$pdo->prepare("SELECT cp.*,p.name plan_name,p.description FROM commercial_proposals cp JOIN plans p ON p.id=cp.plan_id WHERE cp.public_token=:t AND cp.approval_status IN('not_required','approved') AND cp.status NOT IN('expired','cancelled','converted') AND (cp.expires_at IS NULL OR cp.expires_at>NOW()) LIMIT 1");$q->execute(['t'=>$token]);$p=$q->fetch();if(!$p)HttpException::abort(404,'Proposta indisponível para aceite.');$snapshot=['proposal_id'=>(int)$p['id'],'plan_id'=>(int)$p['plan_id'],'title'=>$p['title'],'plan_name'=>$p['plan_name'],'description'=>$p['description'],'price'=>(float)$p['final_price'],'modules'=>json_decode((string)($p['modules_json']??'[]'),true)?:[],'features'=>json_decode((string)($p['features_json']??'[]'),true)?:[],'expires_at'=>$p['expires_at']];$json=json_encode($snapshot,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$ip=(string)($_SERVER['REMOTE_ADDR']??'');$ipHash=$ip!==''?hash('sha256',$ip):null;$pdo->prepare('INSERT INTO proposal_acceptances(proposal_id,document_hash,proposal_snapshot_json,ip_hash,user_agent,accepted_at)VALUES(:p,:h,:j,:ip,:ua,NOW()) ON DUPLICATE KEY UPDATE document_hash=VALUES(document_hash),proposal_snapshot_json=VALUES(proposal_snapshot_json),ip_hash=VALUES(ip_hash),user_agent=VALUES(user_agent),accepted_at=NOW()')->execute(['p'=>$p['id'],'h'=>hash('sha256',$json),'j'=>$json,'ip'=>$ipHash,'ua'=>mb_substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,500)]);$pdo->prepare('UPDATE commercial_proposals SET accepted_at=NOW(),accepted_ip_hash=:ip,updated_at=NOW() WHERE id=:id')->execute(['ip'=>$ipHash,'id'=>$p['id']]);header('Location: /cadastro?plan='.(int)$p['plan_id'].'&offer='.$token);exit;}
 private function money(mixed $v):?float{$v=str_replace(['R$',' ','.'],['','',''],trim((string)$v));$v=str_replace(',','.',$v);return is_numeric($v)?round((float)$v,2):null;}
 private function safeRow(\PDO $pdo,string $sql):array{try{return $pdo->query($sql)->fetch()?:[];}catch(\Throwable $e){error_log('[ApPlanner Commercial UX] '.$e->getMessage());return[];}}
 private function safeRows(\PDO $pdo,string $sql):array{try{return $pdo->query($sql)->fetchAll();}catch(\Throwable $e){error_log('[ApPlanner Commercial UX] '.$e->getMessage());return[];}}
}
