<?php
namespace App\Controllers;
use App\Core\{Auth,Audit,CSRF,Database,HttpException,View};
final class DataImportController
{
 public function index():void{Auth::requireRole('master');$pdo=Database::connection();View::render('master/imports',['title'=>'Implantação de bases','tenants'=>$pdo->query("SELECT id,name FROM tenants WHERE deleted_at IS NULL ORDER BY name")->fetchAll(),'jobs'=>$pdo->query('SELECT j.*,t.name tenant_name FROM data_import_jobs j JOIN tenants t ON t.id=j.tenant_id ORDER BY j.id DESC LIMIT 50')->fetchAll()]);}
 public function upload():void{Auth::requireRole('master');CSRF::enforce();$tenant=(int)($_POST['tenant_id']??0);$file=$_FILES['backup']??[];if(!$tenant||($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)HttpException::abort(422,'Selecione o cliente e o arquivo.');if((int)($file['size']??0)>20*1024*1024)HttpException::abort(422,'O backup deve ter no máximo 20 MB.');$name=(string)($file['name']??'backup');$ext=mb_strtolower(pathinfo($name,PATHINFO_EXTENSION));if(!in_array($ext,['json','zip'],true))HttpException::abort(422,'Envie JSON ou ZIP exportado do AppBarber.');$tmp=(string)$file['tmp_name'];$json=$ext==='json'?(string)file_get_contents($tmp):'';if($ext==='zip'){if(!class_exists(\ZipArchive::class))HttpException::abort(500,'Extensão ZIP indisponível.');$zip=new \ZipArchive();if($zip->open($tmp)!==true)HttpException::abort(422,'ZIP inválido.');if($zip->numFiles>30)HttpException::abort(422,'ZIP com arquivos demais.');for($i=0;$i<$zip->numFiles;$i++)if($zip->getNameIndex($i)==='appbarber-export.json'){$json=(string)$zip->getFromIndex($i);break;}$zip->close();}$data=json_decode($json,true);if(!is_array($data)||($data['format']??'')!=='appbarber-export-v1')HttpException::abort(422,'Formato inválido. Use appbarber-export-v1.');$this->import($tenant,$name,$data);}
 private function import(int $tenant,string $name,array $data):never{$pdo=Database::connection();$user=(int)Auth::user()['id'];$pdo->prepare("INSERT INTO data_import_jobs(tenant_id,user_id,original_name,status,created_at)VALUES(:t,:u,:n,'processing',NOW())")->execute(['t'=>$tenant,'u'=>$user,'n'=>mb_substr($name,0,255)]);$job=(int)$pdo->lastInsertId();$counts=['customers'=>0,'services'=>0,'professionals'=>0];$pdo->beginTransaction();try{foreach(array_slice((array)($data['services']??[]),0,5000) as $r){$n=trim((string)($r['name']??''));if($n==='')continue;$pdo->prepare('INSERT INTO services(tenant_id,name,duration_minutes,price,active,created_at,updated_at)VALUES(:t,:n,:d,:p,1,NOW(),NOW())')->execute(['t'=>$tenant,'n'=>mb_substr($n,0,150),'d'=>max(5,(int)($r['duration_minutes']??30)),'p'=>max(0,(float)($r['price']??0))]);$counts['services']++;}foreach(array_slice((array)($data['customers']??[]),0,50000) as $r){$n=trim((string)($r['name']??''));$phone=preg_replace('/\D/','',(string)($r['phone']??''));if($n===''||$phone==='')continue;$pdo->prepare("INSERT INTO customers(tenant_id,name,phone,email,status,created_at,updated_at)VALUES(:t,:n,:p,:e,'active',NOW(),NOW()) ON DUPLICATE KEY UPDATE name=VALUES(name),email=COALESCE(VALUES(email),email),updated_at=NOW()")->execute(['t'=>$tenant,'n'=>mb_substr($n,0,150),'p'=>$phone,'e'=>filter_var($r['email']??'',FILTER_VALIDATE_EMAIL)?:null]);$counts['customers']++;}foreach(array_slice((array)($data['professionals']??[]),0,1000) as $r){$n=trim((string)($r['name']??''));if($n==='')continue;$slug=trim(preg_replace('/-+/','-',preg_replace('/[^a-z0-9]+/','-',iconv('UTF-8','ASCII//TRANSLIT//IGNORE',mb_strtolower($n)))),'-').'-'.bin2hex(random_bytes(3));$pdo->prepare('INSERT INTO professionals(tenant_id,name,public_slug,specialty,active,created_at,updated_at)VALUES(:t,:n,:s,:sp,1,NOW(),NOW())')->execute(['t'=>$tenant,'n'=>mb_substr($n,0,150),'s'=>$slug,'sp'=>mb_substr(trim((string)($r['specialty']??'')),0,150)?:null]);$counts['professionals']++;}$pdo->commit();$pdo->prepare("UPDATE data_import_jobs SET status='completed',summary_json=:s,completed_at=NOW() WHERE id=:id")->execute(['s'=>json_encode($counts),'id'=>$job]);Audit::log('APPBARBER_IMPORT','tenants',$tenant,null,$counts);}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$pdo->prepare("UPDATE data_import_jobs SET status='failed',error_message=:e,completed_at=NOW() WHERE id=:id")->execute(['e'=>mb_substr($e->getMessage(),0,500),'id'=>$job]);throw $e;}header('Location: /master/imports');exit;}
}
