<?php
namespace App\Controllers;
use App\Core\{Authorization,CSRF,Database,TenantContext,View,Audit,HttpException};
use App\Services\ModuleService;
final class DomainController
{
    private function enabled():void{ModuleService::require('custom_domain');}
    public function index():void{$this->enabled();Authorization::require('domains.manage');$t=TenantContext::id();$q=Database::connection()->prepare('SELECT * FROM tenant_domains WHERE tenant_id=:t ORDER BY id DESC');$q->execute(['t'=>$t]);View::render('domains/index',['title'=>'Domínio personalizado','domains'=>$q->fetchAll()]);}
    public function store():void{$this->enabled();Authorization::require('domains.manage');CSRF::enforce();$t=TenantContext::id();$domain=mb_strtolower(trim((string)($_POST['domain']??'')));$domain=preg_replace('#^https?://#','',$domain);$domain=trim($domain,'/');if(!preg_match('/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$/',$domain))HttpException::abort(422,'Domínio inválido.');$token=bin2hex(random_bytes(16));try{Database::connection()->prepare("INSERT INTO tenant_domains(tenant_id,domain,status,verification_token,created_at,updated_at)VALUES(:t,:d,'pending',:v,NOW(),NOW())")->execute(['t'=>$t,'d'=>$domain,'v'=>$token]);}catch(\Throwable){HttpException::abort(422,'Este domínio já está cadastrado.');}Audit::log('domain.created','tenant_domains',(int)Database::connection()->lastInsertId());header('Location: /domains');exit;}

    public function disable(string $id):void{$this->enabled();Authorization::require('domains.manage');CSRF::enforce();$t=TenantContext::id();$q=Database::connection()->prepare("UPDATE tenant_domains SET status='disabled',updated_at=NOW() WHERE id=:id AND tenant_id=:t AND status<>'disabled'");$q->execute(['id'=>(int)$id,'t'=>$t]);if(!$q->rowCount())HttpException::abort(404,'Domínio não encontrado ou já desativado.');Audit::log('domain.disabled','tenant_domains',(int)$id);header('Location: /domains');exit;}
    public function verify(string $id):void{$this->enabled();Authorization::require('domains.manage');CSRF::enforce();$t=TenantContext::id();$q=Database::connection()->prepare('SELECT * FROM tenant_domains WHERE id=:id AND tenant_id=:t');$q->execute(['id'=>(int)$id,'t'=>$t]);$d=$q->fetch();if(!$d)HttpException::abort(404,'Domínio não encontrado.');$records=@dns_get_record('_agenda-verification.'.$d['domain'],DNS_TXT)?:[];$ok=false;foreach($records as $r){if(str_contains((string)($r['txt']??''),$d['verification_token'])){$ok=true;break;}}Database::connection()->prepare("UPDATE tenant_domains SET status=:s,verified_at=IF(:s2='verified',NOW(),NULL),updated_at=NOW() WHERE id=:id AND tenant_id=:t")->execute(['s'=>$ok?'verified':'failed','s2'=>$ok?'verified':'failed','id'=>$d['id'],'t'=>$t]);Audit::log('domain.verified','tenant_domains',(int)$d['id'],null,['success'=>$ok]);header('Location: /domains');exit;}
}
