<?php
namespace App\Controllers;
use App\Core\{Auth,Audit,CSRF,Database,HttpException,View};use App\Services\IncidentMonitorService;
final class IncidentController
{
 public function index():void{Auth::requireRole('master');$pdo=Database::connection();(new IncidentMonitorService())->scan();$status=(string)($_GET['status']??'open');if(!in_array($status,['open','acknowledged','resolved','all'],true))$status='open';$where=$status==='all'?'':' WHERE i.status='.$pdo->quote($status);$rows=$pdo->query("SELECT i.*,a.name acknowledged_name,r.name resolved_name FROM operational_incidents i LEFT JOIN users a ON a.id=i.acknowledged_by LEFT JOIN users r ON r.id=i.resolved_by{$where} ORDER BY FIELD(i.severity,'critical','warning','info'),i.last_seen_at DESC LIMIT 300")->fetchAll();$settings=$pdo->query('SELECT * FROM platform_operation_settings WHERE id=1')->fetch();$summary=['errors24h'=>$this->countLogErrors(),'webhooks'=>$this->safeCount($pdo,"SELECT COUNT(*) FROM webhook_events WHERE status IN('rejected','failed') AND received_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR)"),'jobs'=>$this->safeCount($pdo,"SELECT COUNT(*) FROM jobs WHERE status='failed'"),'emails'=>$this->safeCount($pdo,"SELECT COUNT(*) FROM marketing_deliveries WHERE status='failed' AND updated_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR)"),'whatsapp'=>$this->safeCount($pdo,"SELECT COUNT(*) FROM whatsapp_messages WHERE status='failed' AND created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR)"),'payments'=>$this->safeCount($pdo,"SELECT COUNT(*) FROM payments p LEFT JOIN invoices i ON i.id=p.reference_id AND p.purpose='invoice' WHERE (p.status='paid' AND i.id IS NOT NULL AND i.status<>'paid') OR (p.status='failed' AND i.status='paid')")];View::render('master/incidents',['title'=>'Central de incidentes','rows'=>$rows,'status'=>$status,'settings'=>$settings,'summary'=>$summary]);}
 public function update(string $id):void{Auth::requireRole('master');CSRF::enforce();$status=(string)($_POST['status']??'');if(!in_array($status,['acknowledged','resolved'],true))HttpException::abort(422,'Situação inválida.');$user=(int)Auth::user()['id'];$sql=$status==='acknowledged'?"UPDATE operational_incidents SET status='acknowledged',acknowledged_by=:u,acknowledged_at=NOW(),updated_at=NOW() WHERE id=:id":"UPDATE operational_incidents SET status='resolved',resolved_by=:u,resolved_at=NOW(),updated_at=NOW() WHERE id=:id";$q=Database::connection()->prepare($sql);$q->execute(['u'=>$user,'id'=>(int)$id]);Audit::log('MASTER_INCIDENT_'.strtoupper($status),'operational_incidents',(int)$id);header('Location: /master/incidentes');exit;}
 public function settings():void{Auth::requireRole('master');CSRF::enforce();$email=mb_strtolower(trim((string)($_POST['critical_alert_email']??'')));if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))HttpException::abort(422,'E-mail inválido.');$q=Database::connection()->prepare('UPDATE platform_operation_settings SET backup_retention_days=:r,backup_include_uploads=:up,backup_encrypt=:enc,backup_before_update=:pre,lead_retention_days=:lead,critical_alert_email=:email,critical_alerts_enabled=:alerts,cron_stale_minutes=:cron,disk_min_free_mb=:disk,updated_by=:u,updated_at=NOW() WHERE id=1');$q->execute(['r'=>max(1,min(3650,(int)($_POST['backup_retention_days']??30))),'up'=>isset($_POST['backup_include_uploads'])?1:0,'enc'=>isset($_POST['backup_encrypt'])?1:0,'pre'=>isset($_POST['backup_before_update'])?1:0,'lead'=>max(30,min(3650,(int)($_POST['lead_retention_days']??730))),'email'=>$email?:null,'alerts'=>isset($_POST['critical_alerts_enabled'])?1:0,'cron'=>max(2,min(1440,(int)($_POST['cron_stale_minutes']??15))),'disk'=>max(100,min(102400,(int)($_POST['disk_min_free_mb']??1024))),'u'=>Auth::user()['id']]);Audit::log('MASTER_OPERATION_SETTINGS_UPDATED','platform_operation_settings',1);header('Location: /master/incidentes?settings=1');exit;}
 private function safeCount(\PDO $pdo,string $sql):int{try{return(int)$pdo->query($sql)->fetchColumn();}catch(\Throwable){return 0;}}
 private function countLogErrors():int{$file=dirname(__DIR__,2).'/error_log';if(!is_readable($file))return 0;$since=time()-86400;$n=0;$h=fopen($file,'rb');if(!$h)return 0;while(($line=fgets($h))!==false)if(preg_match('/\[(\d{2}-[A-Za-z]{3}-\d{4} \d{2}:\d{2}:\d{2})/',$line,$m)&&($t=strtotime($m[1]))!==false&&$t>=$since)$n++;fclose($h);return $n;}
}
