<?php
namespace App\Controllers;
use App\Core\{Auth,Audit,CSRF,Database,HttpException,View};
final class OperationsCenterController
{
 public function index():void
 {
  $this->master();$pdo=Database::connection();$schemaError=null;
  try{$checks=$this->checks($pdo);}catch(\Throwable $e){$checks=[['name'=>'Estrutura da central','status'=>'blocked','detail'=>'Execute as migrações do patch V4.']];$schemaError='A estrutura da Central Operacional está incompleta. Execute novamente as migrações do V4.';error_log('[ApPlanner Operations Center] '.$e->getMessage());}
  $last=$this->row($pdo,'SELECT * FROM homologation_runs ORDER BY id DESC LIMIT 1');
  $metrics=['open_leads'=>$this->scalar($pdo,"SELECT COUNT(*) FROM commercial_leads WHERE status NOT IN('converted','lost')"),'overdue_leads'=>$this->scalar($pdo,"SELECT COUNT(*) FROM commercial_leads WHERE contact_deadline_at<NOW() AND status IN('new','in_service')"),'pending_proposals'=>$this->scalar($pdo,"SELECT COUNT(*) FROM commercial_proposals WHERE approval_status='pending'"),'failed_jobs'=>$this->scalar($pdo,"SELECT COUNT(*) FROM jobs WHERE status='failed'"),'projected_commissions'=>(float)$this->scalar($pdo,"SELECT COALESCE(SUM(commission_amount),0) FROM commercial_commissions WHERE status='projected'"),'releasable_commissions'=>(float)$this->scalar($pdo,"SELECT COALESCE(SUM(commission_amount),0) FROM commercial_commissions WHERE status='approved' AND (hold_until IS NULL OR hold_until<=NOW())")];
  $proposals=$this->rows($pdo,"SELECT cp.id,cp.title,cp.final_price,cp.approval_status,cp.created_at,u.name commercial_name FROM commercial_proposals cp JOIN users u ON u.id=cp.commercial_user_id WHERE cp.approval_status='pending' ORDER BY cp.id DESC LIMIT 50");
  $backups=$this->rows($pdo,"SELECT b.*,bv.status verification_status,bv.verified_at FROM backups b LEFT JOIN backup_verifications bv ON bv.id=(SELECT MAX(x.id) FROM backup_verifications x WHERE x.backup_id=b.id) ORDER BY b.id DESC LIMIT 20");
  View::render('master/operations-center',['title'=>'Homologação e operação','checks'=>$checks,'lastRun'=>$last,'metrics'=>$metrics,'pendingProposals'=>$proposals,'backups'=>$backups,'schemaError'=>$schemaError]);
 }
 public function homologate():void
 {
  $this->master();CSRF::enforce();$pdo=Database::connection();try{$checks=$this->checks($pdo);$passed=count(array_filter($checks,fn($x)=>$x['status']==='passed'));$blocked=count(array_filter($checks,fn($x)=>$x['status']==='blocked'));$score=round($passed/max(1,count($checks))*100,2);$status=$blocked?'blocked':($score<100?'warning':'passed');$pdo->prepare('INSERT INTO homologation_runs(status,score,results_json,executed_by,created_at)VALUES(:s,:score,:r,:u,NOW())')->execute(['s'=>$status,'score'=>$score,'r'=>json_encode($checks,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),'u'=>Auth::user()['id']]);Audit::log('MASTER_HOMOLOGATION_RUN','homologation_runs',(int)$pdo->lastInsertId(),null,['status'=>$status,'score'=>$score]);}catch(\Throwable $e){error_log('[ApPlanner Homologation] '.$e->getMessage());HttpException::abort(503,'A homologação ainda não pode ser executada. Reaplique as migrações do V4.');}header('Location: /master/homologacao?executed=1');exit;
 }
 public function proposal(string $id):void{$this->master();CSRF::enforce();$action=(string)($_POST['action']??'');if(!in_array($action,['approve','reject'],true))HttpException::abort(422,'Ação inválida.');$status=$action==='approve'?'approved':'rejected';$q=Database::connection()->prepare("UPDATE commercial_proposals SET approval_status=:s,approved_by=:u,approved_at=NOW(),status=IF(:s2='rejected','cancelled',status),updated_at=NOW() WHERE id=:id AND approval_status='pending'");$q->execute(['s'=>$status,'u'=>Auth::user()['id'],'s2'=>$status,'id'=>(int)$id]);if(!$q->rowCount())HttpException::abort(409,'A proposta já foi processada.');Audit::log('MASTER_PROPOSAL_APPROVAL','commercial_proposals',(int)$id,null,['status'=>$status]);header('Location: /master/homologacao');exit;}
 public function verifyBackup(string $id):void{$this->master();CSRF::enforce();$pdo=Database::connection();$q=$pdo->prepare("SELECT * FROM backups WHERE id=:id AND status='completed'");$q->execute(['id'=>(int)$id]);$b=$q->fetch();if(!$b)HttpException::abort(404,'Backup não encontrado.');$path=realpath((string)$b['path']);$ok=$path&&is_file($path)&&is_readable($path)&&filesize($path)>100;$hash=$ok?hash_file('sha256',$path):null;$details=$ok?'Arquivo legível, não vazio e checksum calculado. Valide uma restauração isolada antes de desastre real.':'Arquivo ausente, vazio ou sem leitura.';$pdo->prepare('INSERT INTO backup_verifications(backup_id,status,checksum_sha256,details,verified_by,verified_at)VALUES(:b,:s,:h,:d,:u,NOW())')->execute(['b'=>$b['id'],'s'=>$ok?'passed':'failed','h'=>$hash,'d'=>$details,'u'=>Auth::user()['id']]);Audit::log('MASTER_BACKUP_VERIFIED','backups',(int)$id,null,['status'=>$ok?'passed':'failed','checksum'=>$hash]);header('Location: /master/homologacao');exit;}
 private function checks(\PDO $pdo):array
 {
  $c=[];$add=function($name,$ok,$detail,$warning=false)use(&$c){$c[]=['name'=>$name,'status'=>$ok?'passed':($warning?'warning':'blocked'),'detail'=>$detail];};$pdo->query('SELECT 1');$add('Banco de dados',true,'Conexão ativa');$add('PHP',version_compare(PHP_VERSION,'8.2','>='),PHP_VERSION);foreach(['curl','openssl','mbstring','pdo_mysql'] as $e)$add('Extensão '.$e,extension_loaded($e),extension_loaded($e)?'Ativa':'Ausente');$plans=(int)$pdo->query("SELECT COUNT(*) FROM plans WHERE active=1")->fetchColumn();$add('Planos',$plans>0,$plans.' plano(s) ativo(s)');$gateway=(int)$pdo->query("SELECT COUNT(*) FROM payment_gateways WHERE active=1 AND last_test_status='validated'")->fetchColumn();$add('Mercado Pago',$gateway>0,$gateway?'Gateway validado':'Gateway não validado');$failed=(int)$pdo->query("SELECT COUNT(*) FROM jobs WHERE status='failed'")->fetchColumn();$add('Fila de tarefas',$failed===0,$failed.' falha(s)',true);
  $backups=(int)$pdo->query("SELECT COUNT(*) FROM backups WHERE status='completed' AND started_at>=DATE_SUB(NOW(),INTERVAL 7 DAY)")->fetchColumn();$add('Backup recente',$backups>0,$backups?'Backup-base limpo disponível':'Sem backup recente',true);
  $tenants=(int)$pdo->query("SELECT COUNT(*) FROM tenants WHERE deleted_at IS NULL AND COALESCE(is_demo,0)=0")->fetchColumn();$cross=(int)$pdo->query("SELECT COUNT(*) FROM appointments a JOIN customers c ON c.id=a.customer_id WHERE a.tenant_id<>c.tenant_id")->fetchColumn();$add('Integridade multiempresa',$tenants>=1&&$cross===0,$tenants.' empresa(s) real(is); '.$cross.' vínculo(s) cruzado(s)');$demo=(int)$pdo->query("SELECT COUNT(*) FROM tenants WHERE deleted_at IS NULL AND COALESCE(is_demo,0)=1")->fetchColumn();$add('Ambiente de homologação',$demo===0,$demo===0?'Sem tenants de demonstração':$demo.' tenant(s) demo ainda instalado(s)');$docs=(int)$pdo->query("SELECT COUNT(*) FROM legal_documents WHERE status='published'")->fetchColumn();$add('Documentos legais',$docs>=2,$docs.' documento(s) publicado(s)');$cron=is_file(__DIR__.'/../../storage/logs/cron.log');$add('Cron',$cron,$cron?'Log localizado':'Log não localizado',true);return $c;
 }
 private function scalar(\PDO $pdo,string $sql):int|float{try{return $pdo->query($sql)->fetchColumn()?:0;}catch(\Throwable $e){error_log('[ApPlanner Operations Metric] '.$e->getMessage());return 0;}}
 private function row(\PDO $pdo,string $sql):array|false{try{return $pdo->query($sql)->fetch();}catch(\Throwable $e){error_log('[ApPlanner Operations Row] '.$e->getMessage());return false;}}
 private function rows(\PDO $pdo,string $sql):array{try{return $pdo->query($sql)->fetchAll();}catch(\Throwable $e){error_log('[ApPlanner Operations Rows] '.$e->getMessage());return [];}}
 private function master():void{Auth::requireRole('master');}
}
