<?php
namespace App\Controllers;
use App\Core\{Authorization,CSRF,Database,TenantContext,View,Audit,HttpException,Auth};
use App\Services\{ModuleService,TenantPaymentService,AutoTenantService};
final class PackageController
{
    private function enabled():void{ModuleService::require('packages');}
    public function index():void
    {
        $this->enabled();Authorization::require('packages.view');$t=TenantContext::id();$pdo=Database::connection();
        $q=$pdo->prepare('SELECT sp.*,(SELECT GROUP_CONCAT(CONCAT(s.name," ×",spi.quantity) SEPARATOR ", ") FROM service_package_items spi JOIN services s ON s.id=spi.service_id WHERE spi.package_id=sp.id) items FROM service_packages sp WHERE sp.tenant_id=:t ORDER BY sp.active DESC,sp.name');$q->execute(['t'=>$t]);$packages=$q->fetchAll();
        $q=$pdo->prepare('SELECT id,name FROM services WHERE tenant_id=:t AND active=1 ORDER BY name');$q->execute(['t'=>$t]);$services=$q->fetchAll();
        $q=$pdo->prepare("SELECT id,name,email FROM customers WHERE tenant_id=:t AND status='active' ORDER BY name LIMIT 1000");$q->execute(['t'=>$t]);$customers=$q->fetchAll();
        $q=$pdo->prepare("SELECT cp.*,c.name customer_name,sp.name package_name,v.model vehicle_model,v.plate vehicle_plate FROM customer_packages cp JOIN customers c ON c.id=cp.customer_id JOIN service_packages sp ON sp.id=cp.package_id LEFT JOIN auto_vehicle_package_links av ON av.customer_package_id=cp.id AND av.tenant_id=cp.tenant_id LEFT JOIN customer_vehicles v ON v.id=av.vehicle_id WHERE cp.tenant_id=:t ORDER BY cp.id DESC LIMIT 200");$q->execute(['t'=>$t]);$customerPackages=$q->fetchAll();
        $q=$pdo->prepare("SELECT cm.*,c.name customer_name,c.email customer_email,sp.name package_name,v.model vehicle_model,v.plate vehicle_plate,rs.status recurring_status,rs.checkout_url recurring_checkout_url,rs.provider_subscription_id recurring_provider_id FROM customer_memberships cm JOIN customers c ON c.id=cm.customer_id JOIN service_packages sp ON sp.id=cm.package_id LEFT JOIN auto_membership_vehicle_links avm ON avm.membership_id=cm.id AND avm.tenant_id=cm.tenant_id LEFT JOIN customer_vehicles v ON v.id=avm.vehicle_id LEFT JOIN tenant_recurring_subscriptions rs ON rs.id=(SELECT rs2.id FROM tenant_recurring_subscriptions rs2 WHERE rs2.tenant_id=cm.tenant_id AND rs2.reference_type='customer_membership' AND rs2.reference_id=cm.id ORDER BY rs2.id DESC LIMIT 1) WHERE cm.tenant_id=:t ORDER BY cm.status,cm.next_due_at LIMIT 200");$q->execute(['t'=>$t]);
        $paymentService=new TenantPaymentService();$automaticAvailable=(bool)$paymentService->connected($t,'mercadopago');$vehicles=[];$autoMode=AutoTenantService::isAutoTenant($t);if($autoMode){$vq=$pdo->prepare("SELECT v.id,v.customer_id,CONCAT(COALESCE(v.make,''),' ',v.model,IF(v.plate IS NULL OR v.plate='','',CONCAT(' • ',v.plate))) label FROM customer_vehicles v WHERE v.tenant_id=:t AND v.active=1 ORDER BY v.model");$vq->execute(['t'=>$t]);$vehicles=$vq->fetchAll();}
        View::render('packages/index',['title'=>'Pacotes e mensalidades','packages'=>$packages,'services'=>$services,'customers'=>$customers,'customerPackages'=>$customerPackages,'memberships'=>$q->fetchAll(),'financeEnabled'=>ModuleService::has('finance',$t),'automaticBillingAvailable'=>$automaticAvailable,'autoMode'=>$autoMode,'vehicles'=>$vehicles]);
    }
    public function store():void
    {
        $this->enabled();Authorization::require('packages.manage');CSRF::enforce();$t=TenantContext::id();$name=trim((string)($_POST['name']??''));$price=$this->money($_POST['price']??null);$service=(int)($_POST['service_id']??0);$qty=max(1,(int)($_POST['quantity']??1));$valid=(int)($_POST['validity_days']??0)?:null;if(strlen($name)<2||$price===null||!$service)HttpException::abort(422,'Pacote inválido.');$pdo=Database::connection();$q=$pdo->prepare('SELECT 1 FROM services WHERE id=:s AND tenant_id=:t AND active=1');$q->execute(['s'=>$service,'t'=>$t]);if(!$q->fetchColumn())HttpException::abort(422,'Serviço inválido.');$pdo->beginTransaction();try{$pdo->prepare('INSERT INTO service_packages(tenant_id,name,price,validity_days,active,created_at,updated_at)VALUES(:t,:n,:price,:valid,1,NOW(),NOW())')->execute(['t'=>$t,'n'=>$name,'price'=>$price,'valid'=>$valid]);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO service_package_items(package_id,service_id,quantity)VALUES(:p,:s,:q)')->execute(['p'=>$id,'s'=>$service,'q'=>$qty]);$pdo->commit();Audit::log('package.created','service_packages',$id);}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}header('Location: /packages');exit;
    }
    public function sell():void
    {
        $this->enabled();Authorization::require('packages.manage');CSRF::enforce();$t=TenantContext::id();$customer=(int)($_POST['customer_id']??0);$package=(int)($_POST['package_id']??0);$recurring=isset($_POST['recurring']);$auto=$recurring&&isset($_POST['automatic_billing']);if($recurring&&!ModuleService::has('finance',$t))HttpException::abort(422,'Mensalidades recorrentes exigem o módulo Financeiro para controlar as cobranças.');$vehicle=(int)($_POST['vehicle_id']??0)?:null;$autoMode=AutoTenantService::isAutoTenant($t);$paymentService=new TenantPaymentService();if($auto&&!$paymentService->connected($t,'mercadopago'))HttpException::abort(422,'Conecte o Mercado Pago da empresa em Bancos e Pagamentos antes de ativar cobrança automática.');
        $pdo=Database::connection();$q=$pdo->prepare('SELECT * FROM service_packages WHERE id=:p AND tenant_id=:t AND active=1');$q->execute(['p'=>$package,'t'=>$t]);$p=$q->fetch();$q=$pdo->prepare("SELECT id,name,email FROM customers WHERE id=:c AND tenant_id=:t AND status='active'");$q->execute(['c'=>$customer,'t'=>$t]);$customerRow=$q->fetch();if(!$p||!$customerRow)HttpException::abort(422,'Cliente ou pacote inválido.');if($vehicle){if(!$autoMode)HttpException::abort(422,'Vínculo de veículo indisponível.');$vv=$pdo->prepare('SELECT 1 FROM customer_vehicles WHERE id=:v AND customer_id=:c AND tenant_id=:t AND active=1');$vv->execute(['v'=>$vehicle,'c'=>$customer,'t'=>$t]);if(!$vv->fetchColumn())HttpException::abort(422,'Veículo inválido para o cliente.');}if($auto&&!filter_var($customerRow['email']??'',FILTER_VALIDATE_EMAIL))HttpException::abort(422,'Para cobrança automática, cadastre um e-mail válido no cliente.');
        $cycle=in_array((string)($_POST['cycle']??'monthly'),['monthly','quarterly'],true)?(string)$_POST['cycle']:'monthly';$months=$cycle==='quarterly'?3:1;$next=$cycle==='quarterly'?date('Y-m-d',strtotime('+3 months')):date('Y-m-d',strtotime('+1 month'));$expires=$p['validity_days']?date('Y-m-d H:i:s',strtotime('+'.(int)$p['validity_days'].' days')):null;$membershipId=null;$cp=null;
        $pdo->beginTransaction();try{
            if($recurring){$pdo->prepare("INSERT INTO customer_memberships(tenant_id,customer_id,package_id,cycle,recurring_amount,billing_mode,provider_status,status,started_at,next_due_at,created_at,updated_at)VALUES(:t,:c,:p,:cycle,:amount,:mode,:provider,'active',CURDATE(),:next,NOW(),NOW())")->execute(['t'=>$t,'c'=>$customer,'p'=>$package,'cycle'=>$cycle,'amount'=>$p['price'],'mode'=>$auto?'provider':'manual','provider'=>$auto?'pending':null,'next'=>$auto?date('Y-m-d'):$next]);$membershipId=(int)$pdo->lastInsertId();if($vehicle)$pdo->prepare('INSERT INTO auto_membership_vehicle_links(membership_id,tenant_id,vehicle_id,created_at)VALUES(:m,:t,:v,NOW())')->execute(['m'=>$membershipId,'t'=>$t,'v'=>$vehicle]);}
            if(!$auto){$pdo->prepare("INSERT INTO customer_packages(tenant_id,customer_id,package_id,purchased_at,expires_at,status,paid_amount,membership_id,created_at)VALUES(:t,:c,:p,NOW(),:e,'active',:amount,:m,NOW())")->execute(['t'=>$t,'c'=>$customer,'p'=>$package,'e'=>$expires,'amount'=>$p['price'],'m'=>$membershipId]);$cp=(int)$pdo->lastInsertId();if($vehicle)$pdo->prepare('INSERT INTO auto_vehicle_package_links(customer_package_id,tenant_id,vehicle_id,created_at)VALUES(:cp,:t,:v,NOW())')->execute(['cp'=>$cp,'t'=>$t,'v'=>$vehicle]);if(ModuleService::has('finance',$t)){$pdo->prepare("INSERT INTO financial_transactions(tenant_id,source_type,source_id,type,description,amount,payment_method,status,idempotency_key,competence_at,paid_at,created_at,updated_at)VALUES(:t,'package',:sid,'income',:d,:amount,'outro','paid',:key,CURDATE(),NOW(),NOW(),NOW())")->execute(['t'=>$t,'sid'=>$cp,'d'=>'Pacote '.$p['name'],'amount'=>$p['price'],'key'=>'package-'.$cp]);$ft=(int)$pdo->lastInsertId();if($ft)$pdo->prepare('UPDATE customer_packages SET financial_transaction_id=:f WHERE id=:id')->execute(['f'=>$ft,'id'=>$cp]);}}
            $pdo->commit();Audit::log('package.sold','customer_packages',$cp,null,['membership_id'=>$membershipId,'automatic'=>$auto]);
        }catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
        if($auto&&$membershipId){try{$sub=$paymentService->createRecurringSubscription($t,'customer_membership',$membershipId,(float)$p['price'],(string)$customerRow['email'],$months);$pdo->prepare("UPDATE customer_memberships SET provider_status=:status,provider_subscription_id=:provider,provider_checkout_url=:url,updated_at=NOW() WHERE id=:id AND tenant_id=:t")->execute(['status'=>$sub['status']??'pending','provider'=>$sub['provider_subscription_id']??null,'url'=>$sub['checkout_url']??null,'id'=>$membershipId,'t'=>$t]);}catch(\Throwable $e){$pdo->prepare("UPDATE customer_memberships SET provider_status='error',updated_at=NOW() WHERE id=:id AND tenant_id=:t")->execute(['id'=>$membershipId,'t'=>$t]);error_log('[ApPlanner Barber] recorrencia membership='.$membershipId.' '.$e->getMessage());HttpException::abort(502,'A mensalidade foi criada, mas o Mercado Pago não gerou o link automático. Você pode tentar novamente na tela de Pacotes.');}}
        header('Location: /packages'.($auto?'?automatic_created=1':''));exit;
    }
    public function activateAutomaticMembership(string $id):void
    {
        $this->enabled();Authorization::require('packages.manage');CSRF::enforce();$t=TenantContext::id();$mid=(int)$id;$pdo=Database::connection();$q=$pdo->prepare("SELECT cm.*,c.email,c.name customer_name,sp.name package_name FROM customer_memberships cm JOIN customers c ON c.id=cm.customer_id JOIN service_packages sp ON sp.id=cm.package_id WHERE cm.id=:id AND cm.tenant_id=:t AND cm.status='active'");$q->execute(['id'=>$mid,'t'=>$t]);$m=$q->fetch();if(!$m)HttpException::abort(404,'Mensalidade não encontrada.');if(!filter_var($m['email']??'',FILTER_VALIDATE_EMAIL))HttpException::abort(422,'Cliente sem e-mail válido.');$months=$m['cycle']==='quarterly'?3:1;try{$sub=(new TenantPaymentService())->createRecurringSubscription($t,'customer_membership',$mid,(float)$m['recurring_amount'],(string)$m['email'],$months);$pdo->prepare("UPDATE customer_memberships SET billing_mode='provider',provider_status=:status,provider_subscription_id=:provider,provider_checkout_url=:url,updated_at=NOW() WHERE id=:id AND tenant_id=:t")->execute(['status'=>$sub['status']??'pending','provider'=>$sub['provider_subscription_id']??null,'url'=>$sub['checkout_url']??null,'id'=>$mid,'t'=>$t]);}catch(\Throwable $e){error_log('[ApPlanner Barber] ativar recorrencia membership='.$mid.' '.mb_substr($e->getMessage(),0,180));HttpException::abort(502,'Não foi possível gerar a assinatura automática. Verifique a integração de pagamentos e tente novamente.');}header('Location: /packages?automatic_created=1');exit;
    }
    public function usePackage(string $id):void
    {
        $this->enabled();Authorization::require('packages.manage');CSRF::enforce();$t=TenantContext::id();$cp=(int)$id;$service=(int)($_POST['service_id']??0);$appointment=(int)($_POST['appointment_id']??0)?:null;$pdo=Database::connection();$q=$pdo->prepare("SELECT cp.*,spi.quantity included,(SELECT COALESCE(SUM(u.quantity),0) FROM customer_package_usage u WHERE u.customer_package_id=cp.id AND u.service_id=:s) used FROM customer_packages cp JOIN service_package_items spi ON spi.package_id=cp.package_id AND spi.service_id=:s2 WHERE cp.id=:id AND cp.tenant_id=:t AND cp.status='active' FOR UPDATE");$pdo->beginTransaction();try{$q->execute(['s'=>$service,'s2'=>$service,'id'=>$cp,'t'=>$t]);$r=$q->fetch();if(!$r||($r['expires_at']&&strtotime($r['expires_at'])<time())||(int)$r['used']>=(int)$r['included'])throw new \DomainException('Pacote sem saldo para este serviço.');$pdo->prepare('INSERT INTO customer_package_usage(customer_package_id,service_id,appointment_id,quantity,created_at)VALUES(:cp,:s,:a,1,NOW())')->execute(['cp'=>$cp,'s'=>$service,'a'=>$appointment]);if((int)$r['used']+1>=(int)$r['included']){$left=$pdo->prepare('SELECT COUNT(*) FROM service_package_items spi WHERE spi.package_id=:p AND (SELECT COALESCE(SUM(u.quantity),0) FROM customer_package_usage u WHERE u.customer_package_id=:cp AND u.service_id=spi.service_id)<spi.quantity');$left->execute(['p'=>$r['package_id'],'cp'=>$cp]);if((int)$left->fetchColumn()===0)$pdo->prepare("UPDATE customer_packages SET status='used' WHERE id=:id AND tenant_id=:t")->execute(['id'=>$cp,'t'=>$t]);}$pdo->commit();Audit::log('package.used','customer_packages',$cp,null,['service_id'=>$service]);}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();HttpException::abort(422,$e->getMessage());}header('Location: /packages');exit;
    }
    public function cancelMembership(string $id):void
    {
        $this->enabled();Authorization::require('packages.manage');CSRF::enforce();$t=TenantContext::id();$mid=(int)$id;$pdo=Database::connection();$q=$pdo->prepare("SELECT billing_mode FROM customer_memberships WHERE id=:id AND tenant_id=:t");$q->execute(['id'=>$mid,'t'=>$t]);$mode=$q->fetchColumn();if($mode===false)HttpException::abort(404,'Mensalidade não encontrada.');if($mode==='provider')(new TenantPaymentService())->cancelRecurringSubscription($t,'customer_membership',$mid);$q=$pdo->prepare("UPDATE customer_memberships SET status='cancelled',provider_status=IF(billing_mode='provider','cancelled',provider_status),updated_at=NOW() WHERE id=:id AND tenant_id=:t AND status<>'cancelled'");$q->execute(['id'=>$mid,'t'=>$t]);Audit::log('membership.cancelled','customer_memberships',$mid);header('Location: /packages');exit;
    }
    private function money(mixed $v):?float{$x=filter_var(str_replace(',','.',(string)$v),FILTER_VALIDATE_FLOAT);return $x===false||$x<0?null:(float)$x;}
}
