<?php
namespace App\Controllers;
use App\Core\{Auth,Audit,CSRF,Database,Encryption,HttpException,TenantContext,View};
use App\Services\{MercadoPagoProvider,PlatformSetting};
final class PixController
{
 public function create():void
 {
  Auth::requireRole('owner');CSRF::enforce();if(!(bool)PlatformSetting::get('mercadopago.pix.enabled',true))HttpException::abort(503,'Pagamento por Pix está temporariamente indisponível.');$t=TenantContext::id();$pdo=Database::connection();$s=$pdo->prepare('SELECT s.*,p.name plan_name FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.tenant_id=:t ORDER BY s.id DESC LIMIT 1');$s->execute(['t'=>$t]);$sub=$s->fetch();if(!$sub||!in_array($sub['status'],['trial','active','past_due','suspended'],true))HttpException::abort(422,'Assinatura indisponível para pagamento.');$gateway=$pdo->query("SELECT * FROM payment_gateways WHERE provider='mercadopago' AND active=1 AND last_test_status='validated' ORDER BY (environment='production') DESC,last_tested_at DESC LIMIT 1")->fetch();if(!$gateway)HttpException::abort(503,'Mercado Pago ainda não está disponível.');
  $discount=max(0,min(50,(float)PlatformSetting::get('mercadopago.pix.discount_percent',0)));$base=round((float)($sub['contracted_price']??0),2);if($base<=0)HttpException::abort(422,'Valor da assinatura inválido.');$total=round($base*(1-$discount/100),2);$hours=max(1,min(720,(int)PlatformSetting::get('mercadopago.pix.expiration_hours',24)));$public=bin2hex(random_bytes(16));$key=hash('sha256','pix|'.$t.'|'.$public);$cycle=(string)($sub['billing_cycle']??'monthly');$pdo->beginTransaction();try{$pdo->prepare("INSERT INTO checkout_sessions(public_id,tenant_id,plan_id,billing_cycle,subtotal,discount,total,status,idempotency_key,expires_at,created_at,updated_at)VALUES(:public,:t,:plan,:cycle,:subtotal,:discount,:total,'awaiting_payment',:key,DATE_ADD(NOW(),INTERVAL :hours HOUR),NOW(),NOW())")->execute(['public'=>$public,'t'=>$t,'plan'=>$sub['plan_id'],'cycle'=>$cycle,'subtotal'=>$base,'discount'=>$base-$total,'total'=>$total,'key'=>$key,'hours'=>$hours]);$checkout=(int)$pdo->lastInsertId();$number='PIX-'.date('Ym').'-'.strtoupper(substr($public,0,8));$pdo->prepare("INSERT INTO invoices(tenant_id,subscription_id,checkout_session_id,number,amount,status,due_at,created_at,updated_at)VALUES(:t,:sub,:checkout,:number,:amount,'pending',DATE_ADD(NOW(),INTERVAL :hours HOUR),NOW(),NOW())")->execute(['t'=>$t,'sub'=>$sub['id'],'checkout'=>$checkout,'number'=>$number,'amount'=>$total,'hours'=>$hours]);$pdo->prepare("INSERT INTO payments(tenant_id,subscription_id,purpose,reference_id,provider,environment,idempotency_key,amount,status,due_at,created_at,updated_at)VALUES(:t,:sub,'subscription',NULL,'mercadopago',:env,:key,:amount,'pending',DATE_ADD(NOW(),INTERVAL :hours HOUR),NOW(),NOW())")->execute(['t'=>$t,'sub'=>$sub['id'],'env'=>$gateway['environment'],'key'=>$key,'amount'=>$total,'hours'=>$hours]);$payment=(int)$pdo->lastInsertId();$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
  try{$remote=(new MercadoPagoProvider(Encryption::decrypt($gateway['access_token_encrypted'])['value']??''))->createPixOrder(['amount'=>$total,'external_reference'=>$public,'payer_email'=>Auth::user()['email'],'expiration_hours'=>$hours,'idempotency_key'=>$key]);$pdo->beginTransaction();$pdo->prepare('UPDATE payments SET provider_reference=:order_id,provider_payment_id=:payment_id,provider_status=:status,updated_at=NOW() WHERE id=:id AND tenant_id=:t')->execute(['order_id'=>$remote['order_id'],'payment_id'=>$remote['payment_id']?:null,'status'=>$remote['status'],'id'=>$payment,'t'=>$t]);$pdo->prepare("INSERT INTO pix_charges(public_id,tenant_id,subscription_id,checkout_session_id,payment_id,provider_order_id,provider_payment_id,amount,qr_code,qr_code_base64,ticket_url,status,expires_at,created_at,updated_at)VALUES(:public,:t,:sub,:checkout,:payment,:order_id,:payment_id,:amount,:qr,:base64,:ticket,'pending',DATE_ADD(NOW(),INTERVAL :hours HOUR),NOW(),NOW())")->execute(['public'=>$public,'t'=>$t,'sub'=>$sub['id'],'checkout'=>$checkout,'payment'=>$payment,'order_id'=>$remote['order_id'],'payment_id'=>$remote['payment_id']?:null,'amount'=>$total,'qr'=>$remote['qr_code'],'base64'=>$remote['qr_code_base64'],'ticket'=>$remote['ticket_url'],'hours'=>$hours]);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$pdo->prepare("UPDATE payments SET status='failed',updated_at=NOW() WHERE id=:id AND tenant_id=:t")->execute(['id'=>$payment,'t'=>$t]);$pdo->prepare("UPDATE checkout_sessions SET status='failed',updated_at=NOW() WHERE id=:id AND tenant_id=:t")->execute(['id'=>$checkout,'t'=>$t]);$pdo->prepare("UPDATE invoices SET status='cancelled',updated_at=NOW() WHERE checkout_session_id=:checkout AND tenant_id=:t")->execute(['checkout'=>$checkout,'t'=>$t]);$safe=mb_substr($e->getMessage(),0,500);error_log('[ApPlanner Pix] tenant='.(int)$t.' error='.$safe);Audit::log('PIX_CHARGE_FAILED','payments',$payment,null,['error'=>$safe]);HttpException::abort(502,'Não foi possível gerar o Pix: '.$safe);}Audit::log('PIX_CHARGE_CREATED','payments',$payment,null,['amount'=>$total,'discount_percent'=>$discount]);header('Location: /billing/pix/'.$public);exit;
 }
 public function show(string $public):void{Auth::requireLogin();$q=Database::connection()->prepare('SELECT pc.*,i.number invoice_number,p.status payment_status FROM pix_charges pc JOIN invoices i ON i.checkout_session_id=pc.checkout_session_id JOIN payments p ON p.id=pc.payment_id WHERE pc.public_id=:public AND pc.tenant_id=:t LIMIT 1');$q->execute(['public'=>$public,'t'=>TenantContext::id()]);$charge=$q->fetch();if(!$charge)HttpException::abort(404,'Cobrança Pix não encontrada.');if($charge['status']==='pending'&&strtotime($charge['expires_at'])<time())Database::connection()->prepare("UPDATE pix_charges SET status='expired',updated_at=NOW() WHERE id=:id")->execute(['id'=>$charge['id']]);View::render('billing/pix',['title'=>'Pagamento por Pix','charge'=>$charge]);}
}
