<?php
namespace App\Controllers;

use App\Core\{CSRF,Database,RateLimiter,View,Encryption,HttpException};
use App\Services\{AvailabilityService,NotificationService,ModuleService};

final class PublicBookingController
{
    private function tenant(string $slug):array|false
    {
        $host=mb_strtolower(preg_replace('/:\d+$/','',(string)($_SERVER['HTTP_HOST']??'')));
        $q=Database::connection()->prepare("SELECT t.* FROM tenants t LEFT JOIN tenant_domains d ON d.tenant_id=t.id AND d.status='verified' WHERE ((t.public_slug=:s OR t.public_short_code=:s2) OR (:host<>'' AND d.domain=:host2)) AND t.public_booking_enabled=1 AND t.public_enabled=1 AND t.status IN('trial','active') AND t.deleted_at IS NULL LIMIT 1");
        $q->execute(['s'=>$slug,'s2'=>$slug,'host'=>$host,'host2'=>$host]);return $q->fetch();
    }
    public function show(string $slug):void{$pdo=Database::connection();$t=$this->tenant($slug);if(!$t){$this->notFound();return;}[$services,$professionals]=$this->catalog($pdo,(int)$t['id'],null);$nextAvailability=$this->nextAvailability((int)$t['id'],$services,$professionals,null);View::render('public/show',array_merge(['title'=>$t['name'],'tenant'=>$t,'routeSlug'=>$slug,'services'=>$services,'professionals'=>$professionals,'selectedProfessional'=>null,'nextAvailability'=>$nextAvailability,'showWaitlist'=>(($_GET['waitlist']??'')==='1'),'publicLayout'=>true,'message'=>$_SESSION['flash_message']??null],$this->publicContent($pdo,(int)$t['id'])));unset($_SESSION['flash_message']);}
    public function professional(string $slug,string $professional):void{$pdo=Database::connection();$t=$this->tenant($slug);if(!$t){$this->notFound();return;}$q=$pdo->prepare('SELECT id,name,public_slug,specialty,photo_path FROM professionals WHERE tenant_id=:t AND public_slug=:p AND active=1');$q->execute(['t'=>$t['id'],'p'=>$professional]);$selected=$q->fetch();if(!$selected){$this->notFound('Profissional não encontrado');return;}[$services,$professionals]=$this->catalog($pdo,(int)$t['id'],(int)$selected['id']);$todayAvailability=null;$engine=new AvailabilityService();$today=new \DateTimeImmutable('today');foreach($services as $service){$slots=$engine->slots((int)$t['id'],(int)$service['id'],(int)$selected['id'],$today);if($slots){$todayAvailability=['service'=>$service,'slot'=>$slots[0],'count'=>count($slots)];break;}}$nextAvailability=$todayAvailability?null:$this->nextAvailability((int)$t['id'],$services,$professionals,(int)$selected['id'],1);View::render('public/show',array_merge(['title'=>$t['name'].' • '.$selected['name'],'tenant'=>$t,'routeSlug'=>$slug,'services'=>$services,'professionals'=>$professionals,'selectedProfessional'=>$selected,'todayAvailability'=>$todayAvailability,'nextAvailability'=>$nextAvailability,'showWaitlist'=>(($_GET['waitlist']??'')==='1'),'publicLayout'=>true,'message'=>$_SESSION['flash_message']??null],$this->publicContent($pdo,(int)$t['id'])));unset($_SESSION['flash_message']);}
    public function availability(string $slug):void{header('Content-Type: application/json; charset=utf-8');$t=$this->tenant($slug);if(!$t){http_response_code(404);echo json_encode(['slots'=>[]]);return;}$service=(int)($_GET['service_id']??0);$professional=(int)($_GET['professional_id']??0);$date=(string)($_GET['date']??'');$random=($_GET['random']??'')==='1';if(!$service||(!$professional&&!$random)||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)){http_response_code(422);echo json_encode(['slots'=>[]]);return;}try{$day=new \DateTimeImmutable($date.' 00:00:00');}catch(\Throwable){http_response_code(422);echo json_encode(['slots'=>[]]);return;}$engine=new AvailabilityService();if($random){$pdo=Database::connection();$q=$pdo->prepare("SELECT p.id,p.name FROM professionals p WHERE p.tenant_id=:t AND p.active=1 AND (NOT EXISTS(SELECT 1 FROM professional_services ps0 WHERE ps0.professional_id=p.id) OR EXISTS(SELECT 1 FROM professional_services ps WHERE ps.professional_id=p.id AND ps.service_id=:s))");$q->execute(['t'=>$t['id'],'s'=>$service]);$choices=[];foreach($q->fetchAll() as $p){foreach($engine->slots((int)$t['id'],$service,(int)$p['id'],$day) as $slot)$choices[]=['professional_id'=>(int)$p['id'],'professional_name'=>$p['name'],'slot'=>$slot];}if(!$choices){echo json_encode(['slots'=>[]],JSON_UNESCAPED_UNICODE);return;}$choice=$choices[array_rand($choices)];echo json_encode(['slots'=>[$choice['slot']],'professional_id'=>$choice['professional_id'],'professional_name'=>$choice['professional_name'],'random'=>true],JSON_UNESCAPED_UNICODE);return;}echo json_encode(['slots'=>$engine->slots((int)$t['id'],$service,$professional,$day)],JSON_UNESCAPED_UNICODE);}
    public function book(string $slug):void
    {
        CSRF::enforce();$ip=$_SERVER['REMOTE_ADDR']??'unknown';if(!RateLimiter::hit('public-book|'.$ip,10,3600))HttpException::abort(429,'Muitas tentativas.');$tenant=$this->tenant($slug);$t=(int)($tenant['id']??0);if(!$t)$this->notFound();
        $name=trim((string)($_POST['name']??''));$phone=preg_replace('/\D/','',(string)($_POST['phone']??''));$email=mb_strtolower(trim((string)($_POST['email']??'')));$service=(int)($_POST['service_id']??0);$professional=(int)($_POST['professional_id']??0);try{$start=new \DateTimeImmutable((string)($_POST['starts_at']??''));}catch(\Throwable){HttpException::abort(422,'Escolha um horário disponível.');}if(strlen($name)<2||strlen($phone)<10||($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))||!$service||!$professional)HttpException::abort(422,'Dados inválidos.');
        $availability=new AvailabilityService();$sv=$availability->service($t,$service);if(!$sv||!$availability->professionalOffers($t,$professional,$service))HttpException::abort(422,'Serviço ou profissional indisponível.');$end=$start->modify('+'.(int)$sv['duration_minutes'].' minutes');if(!$availability->isAvailable($t,$professional,$start,$end,null,true))HttpException::abort(409,'Este horário não está mais disponível.');
        $pdo=Database::connection();$lock="public-book:$t:$professional";$lk=$pdo->prepare('SELECT GET_LOCK(:n,5)');$lk->execute(['n'=>$lock]);if((int)$lk->fetchColumn()!==1)HttpException::abort(409,'Agenda ocupada.');$token=bin2hex(random_bytes(24));
        try{$pdo->beginTransaction();if(!$availability->isAvailable($t,$professional,$start,$end,null,true))throw new \LogicException('Horário já reservado.');$c=$pdo->prepare('SELECT id FROM customers WHERE tenant_id=:t AND phone=:p LIMIT 1');$c->execute(['t'=>$t,'p'=>$phone]);$customer=(int)$c->fetchColumn();if(!$customer){$pdo->prepare("INSERT INTO customers(tenant_id,name,phone,email,status,created_at,updated_at)VALUES(:t,:n,:p,:e,'active',NOW(),NOW())")->execute(['t'=>$t,'n'=>$name,'p'=>$phone,'e'=>$email?:null]);$customer=(int)$pdo->lastInsertId();}else{$pdo->prepare('UPDATE customers SET name=:n,email=COALESCE(NULLIF(:e,\'\'),email),updated_at=NOW() WHERE id=:id AND tenant_id=:t')->execute(['n'=>$name,'e'=>$email,'id'=>$customer,'t'=>$t]);}$source=((string)($_POST['booking_source']??''))==='professional_link'?'professional_link':'public';$pdo->prepare("INSERT INTO appointments(tenant_id,customer_id,professional_id,service_id,service_price_snapshot,starts_at,ends_at,status,source,customer_manage_token_hash,customer_manage_token_encrypted,customer_confirmed_at,created_at,updated_at)VALUES(:t,:c,:p,:sv,:price,:s,:e,'confirmed',:source,:hash,:encrypted,NOW(),NOW(),NOW())")->execute(['t'=>$t,'c'=>$customer,'p'=>$professional,'sv'=>$service,'price'=>$sv['price'],'s'=>$start->format('Y-m-d H:i:s'),'e'=>$end->format('Y-m-d H:i:s'),'source'=>$source,'hash'=>hash('sha256',$token),'encrypted'=>Encryption::encrypt(['token'=>$token])]);$id=(int)$pdo->lastInsertId();$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();HttpException::abort($e instanceof \LogicException?409:422,$e->getMessage());}finally{$pdo->prepare('SELECT RELEASE_LOCK(:n)')->execute(['n'=>$lock]);}
        NotificationService::professional($t,$professional,'appointment.public','Novo agendamento online',$name.' agendou para '.$start->format('d/m H:i'),'/appointments','success');NotificationService::tenantOwners($t,'appointment.public','Novo agendamento online',$name.' agendou para '.$start->format('d/m H:i'),'/appointments','success');header('Location: /booking/'.$token);exit;
    }
    public function joinWaitlist(string $slug):void
    {
        CSRF::enforce();$ip=$_SERVER['REMOTE_ADDR']??'unknown';if(!RateLimiter::hit('public-waitlist|'.$ip,5,3600))HttpException::abort(429,'Muitas tentativas.');$tenant=$this->tenant($slug);$t=(int)($tenant['id']??0);if(!$t)$this->notFound();$pdo=Database::connection();$enabled=$pdo->prepare("SELECT 1 FROM tenant_modules tm JOIN modules m ON m.id=tm.module_id WHERE tm.tenant_id=:t AND tm.enabled=1 AND m.slug='waitlist' AND m.active=1");$enabled->execute(['t'=>$t]);if(!$enabled->fetchColumn())HttpException::abort(403,'A lista de espera não está disponível para este estabelecimento.');$name=trim((string)($_POST['name']??''));$phone=preg_replace('/\D/','',(string)($_POST['phone']??''));$email=mb_strtolower(trim((string)($_POST['email']??'')));$service=(int)($_POST['service_id']??0);$professional=(int)($_POST['professional_id']??0)?:null;$date=trim((string)($_POST['preferred_date']??''))?:date('Y-m-d');if(mb_strlen($name)<2||strlen($phone)<10||($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))||!$service||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))HttpException::abort(422,'Revise os dados da lista de espera.');$valid=$pdo->prepare('SELECT 1 FROM services WHERE id=:s AND tenant_id=:t AND active=1');$valid->execute(['s'=>$service,'t'=>$t]);if(!$valid->fetchColumn())HttpException::abort(422,'Serviço indisponível.');$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT id FROM customers WHERE tenant_id=:t AND phone=:p LIMIT 1');$q->execute(['t'=>$t,'p'=>$phone]);$customer=(int)$q->fetchColumn();if(!$customer){$pdo->prepare("INSERT INTO customers(tenant_id,name,phone,email,status,created_at,updated_at)VALUES(:t,:n,:p,:e,'active',NOW(),NOW())")->execute(['t'=>$t,'n'=>$name,'p'=>$phone,'e'=>$email?:null]);$customer=(int)$pdo->lastInsertId();}$pdo->prepare("INSERT INTO waitlist_entries(tenant_id,customer_id,service_id,professional_id,preferred_date,period,status,notes,created_at,updated_at)VALUES(:t,:c,:s,:p,:d,'any','waiting','Entrada pela página pública',NOW(),NOW())")->execute(['t'=>$t,'c'=>$customer,'s'=>$service,'p'=>$professional,'d'=>$date]);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}NotificationService::tenantOwners($t,'waitlist.public','Nova entrada na lista de espera',$name.' aguarda uma vaga.','/waitlist','info');$_SESSION['flash_message']='Você entrou na lista de espera. O estabelecimento poderá avisar quando surgir uma vaga.';header('Location: /a/'.$slug);exit;
    }
    public function manage(string $token):void{$a=$this->appointmentByToken($token);$settings=(new AvailabilityService())->settings((int)$a['tenant_id']);View::render('public/manage-booking',['title'=>'Gerenciar agendamento','appointment'=>$a,'settings'=>$settings,'token'=>$token,'publicLayout'=>true,'message'=>$_SESSION['flash_message']??null]);unset($_SESSION['flash_message']);}
    public function confirm(string $token):void{CSRF::enforce();$a=$this->appointmentByToken($token);if(in_array($a['status'],['cancelled','completed','no_show'],true))HttpException::abort(409,'Este agendamento não pode mais ser confirmado.');Database::connection()->prepare("UPDATE appointments SET status='confirmed',customer_confirmed_at=NOW(),updated_at=NOW() WHERE id=:id AND tenant_id=:t")->execute(['id'=>$a['id'],'t'=>$a['tenant_id']]);NotificationService::professional((int)$a['tenant_id'],(int)$a['professional_id'],'appointment.confirmed','Cliente confirmou presença',$a['customer_name'].' confirmou o atendimento de '.$a['starts_at'],'/appointments','success');$_SESSION['flash_message']='Presença confirmada com sucesso.';header('Location: /booking/'.$token);exit;}
    public function cancel(string $token):void{CSRF::enforce();$a=$this->appointmentByToken($token);$settings=(new AvailabilityService())->settings((int)$a['tenant_id']);if(empty($settings['customer_can_cancel']))HttpException::abort(403,'Cancelamento pelo link está desativado.');if(new \DateTimeImmutable($a['starts_at'])<(new \DateTimeImmutable())->modify('+'.(int)$settings['cancel_notice_minutes'].' minutes'))HttpException::abort(409,'O prazo para cancelamento online já terminou.');if(in_array($a['status'],['cancelled','completed','no_show'],true))HttpException::abort(409,'Este agendamento não pode ser cancelado.');Database::connection()->prepare("UPDATE appointments SET status='cancelled',updated_at=NOW() WHERE id=:id AND tenant_id=:t")->execute(['id'=>$a['id'],'t'=>$a['tenant_id']]);NotificationService::professional((int)$a['tenant_id'],(int)$a['professional_id'],'appointment.cancelled','Cliente cancelou o horário',$a['customer_name'].' cancelou '.$a['starts_at'],'/appointments','warning');NotificationService::tenantOwners((int)$a['tenant_id'],'appointment.cancelled','Horário liberado por cancelamento',$a['customer_name'].' cancelou '.$a['starts_at'],'/appointments','warning');$_SESSION['flash_message']='Agendamento cancelado. O horário foi liberado.';header('Location: /booking/'.$token);exit;}
    public function reschedule(string $token):void{$a=$this->appointmentByToken($token);$settings=(new AvailabilityService())->settings((int)$a['tenant_id']);if(empty($settings['customer_can_reschedule']))HttpException::abort(403,'Remarcação online está desativada.');View::render('public/reschedule-booking',['title'=>'Remarcar agendamento','appointment'=>$a,'settings'=>$settings,'token'=>$token,'publicLayout'=>true]);}
    public function saveReschedule(string $token):void{CSRF::enforce();$a=$this->appointmentByToken($token);$settings=(new AvailabilityService())->settings((int)$a['tenant_id']);if(empty($settings['customer_can_reschedule']))HttpException::abort(403,'Remarcação online desativada.');try{$start=new \DateTimeImmutable((string)($_POST['starts_at']??''));}catch(\Throwable){HttpException::abort(422,'Escolha um horário disponível.');}$availability=new AvailabilityService();$sv=$availability->service((int)$a['tenant_id'],(int)$a['service_id']);$end=$start->modify('+'.(int)$sv['duration_minutes'].' minutes');if(!$availability->isAvailable((int)$a['tenant_id'],(int)$a['professional_id'],$start,$end,(int)$a['id'],true))HttpException::abort(409,'Horário indisponível.');$pdo=Database::connection();$pdo->beginTransaction();try{$pdo->prepare("INSERT INTO appointment_reschedule_history(tenant_id,appointment_id,old_professional_id,new_professional_id,old_starts_at,old_ends_at,new_starts_at,new_ends_at,reason,actor_type,created_at)VALUES(:t,:a,:op,:np,:os,:oe,:ns,:ne,'Remarcação pelo cliente','customer',NOW())")->execute(['t'=>$a['tenant_id'],'a'=>$a['id'],'op'=>$a['professional_id'],'np'=>$a['professional_id'],'os'=>$a['starts_at'],'oe'=>$a['ends_at'],'ns'=>$start->format('Y-m-d H:i:s'),'ne'=>$end->format('Y-m-d H:i:s')]);$pdo->prepare("UPDATE appointments SET starts_at=:s,ends_at=:e,status='confirmed',reminder_24h_sent_at=NULL,reminder_2h_sent_at=NULL,updated_at=NOW() WHERE id=:id AND tenant_id=:t")->execute(['s'=>$start->format('Y-m-d H:i:s'),'e'=>$end->format('Y-m-d H:i:s'),'id'=>$a['id'],'t'=>$a['tenant_id']]);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}NotificationService::professional((int)$a['tenant_id'],(int)$a['professional_id'],'appointment.rescheduled','Cliente remarcou atendimento',$a['customer_name'].' remarcou para '.$start->format('d/m H:i'),'/appointments','info');$_SESSION['flash_message']='Agendamento remarcado com sucesso.';header('Location: /booking/'.$token);exit;}
    private function appointmentByToken(string $token):array{$token=trim($token);if(!preg_match('/^[a-f0-9]{48}$/',$token))$this->notFound('Link inválido');$q=Database::connection()->prepare("SELECT a.*,c.name customer_name,c.phone customer_phone,c.email customer_email,s.name service_name,p.name professional_name,t.name tenant_name,t.public_slug,t.public_short_code FROM appointments a JOIN customers c ON c.id=a.customer_id JOIN services s ON s.id=a.service_id LEFT JOIN professionals p ON p.id=a.professional_id JOIN tenants t ON t.id=a.tenant_id WHERE a.customer_manage_token_hash=:h AND t.deleted_at IS NULL LIMIT 1");$q->execute(['h'=>hash('sha256',$token)]);$a=$q->fetch();if(!$a)$this->notFound('Agendamento não encontrado');return $a;}
    private function catalog(\PDO $pdo,int $t,?int $p):array{if($p){$s=$pdo->prepare("SELECT s.id,s.name,s.duration_minutes,s.price FROM services s WHERE s.tenant_id=:t AND s.active=1 AND (NOT EXISTS(SELECT 1 FROM professional_services ps0 WHERE ps0.professional_id=:p0) OR EXISTS(SELECT 1 FROM professional_services ps WHERE ps.professional_id=:p AND ps.service_id=s.id)) ORDER BY s.name");$s->execute(['t'=>$t,'p0'=>$p,'p'=>$p]);$pr=$pdo->prepare('SELECT id,name,public_slug,specialty,photo_path FROM professionals WHERE tenant_id=:t AND id=:p AND active=1');$pr->execute(['t'=>$t,'p'=>$p]);return [$s->fetchAll(),$pr->fetchAll()];}$s=$pdo->prepare('SELECT id,name,duration_minutes,price FROM services WHERE tenant_id=:t AND active=1 ORDER BY name');$s->execute(['t'=>$t]);$pr=$pdo->prepare('SELECT id,name,public_slug,specialty,photo_path FROM professionals WHERE tenant_id=:t AND active=1 ORDER BY name');$pr->execute(['t'=>$t]);return [$s->fetchAll(),$pr->fetchAll()];}
    private function publicContent(\PDO $pdo,int $t):array
    {
        $query=function(string $sql)use($pdo,$t){$q=$pdo->prepare($sql);$q->execute(['t'=>$t]);return $q->fetchAll();};
        $units=$query('SELECT * FROM units WHERE tenant_id=:t AND active=1 ORDER BY is_primary DESC,name');
        $products=$query('SELECT id,name,description,sale_price FROM products WHERE tenant_id=:t AND active=1 ORDER BY name LIMIT 12');
        $packages=$query('SELECT id,name,price,validity_days FROM service_packages WHERE tenant_id=:t AND active=1 ORDER BY name LIMIT 12');
        $loyalty=$query('SELECT enabled,points_per_currency,reward_points,reward_value,referral_points FROM tenant_loyalty_settings WHERE tenant_id=:t AND enabled=1');
        $reviews=$query('SELECT customer_name,rating,comment FROM public_reviews WHERE tenant_id=:t AND active=1 ORDER BY created_at DESC LIMIT 12');
        $enabled=$pdo->prepare("SELECT 1 FROM tenant_modules tm JOIN modules m ON m.id=tm.module_id WHERE tm.tenant_id=:t AND tm.enabled=1 AND m.slug='waitlist' AND m.active=1");$enabled->execute(['t'=>$t]);$waitlistEnabled=(bool)$enabled->fetchColumn();
        return compact('units','products','packages','loyalty','reviews','waitlistEnabled');
    }
    private function nextAvailability(int $tenantId,array $services,array $professionals,?int $professionalId=null,int $startOffset=0):?array
    {
        if(!$services||!$professionals)return null;usort($services,fn($a,$b)=>(int)$a['duration_minutes']<=>(int)$b['duration_minutes']);$service=$services[0];$engine=new AvailabilityService();$professionals=$professionalId?array_values(array_filter($professionals,fn($p)=>(int)$p['id']===$professionalId)):array_slice($professionals,0,6);
        for($offset=$startOffset;$offset<15;$offset++){$day=(new \DateTimeImmutable('today'))->modify('+'.$offset.' days');foreach($professionals as $professional){$slots=$engine->slots($tenantId,(int)$service['id'],(int)$professional['id'],$day);if($slots){$days=[1=>'segunda-feira',2=>'terça-feira',3=>'quarta-feira',4=>'quinta-feira',5=>'sexta-feira',6=>'sábado',7=>'domingo'];$label=$offset===0?'Hoje':($offset===1?'Amanhã':ucfirst($days[(int)$day->format('N')]).', '.$day->format('d/m'));return ['date'=>$day->format('Y-m-d'),'date_label'=>$label,'slot'=>$slots[0],'service'=>$service,'professional'=>$professional];}}}return null;
    }
    private function notFound(string $title='Página não encontrada'):never{http_response_code(404);View::render('dashboard/404',['title'=>$title,'publicLayout'=>true]);exit;}
}
