<?php
namespace App\Controllers;
use App\Core\{Auth,Authorization,CSRF,Database,TenantContext,View,Audit,HttpException};
use App\Services\AvailabilityService;
final class ScheduleController
{
    public function settings():void{Authorization::require('agenda.settings.manage');$t=TenantContext::id();$s=(new AvailabilityService())->settings($t);View::render('schedule/settings',['title'=>'Regras da agenda','settings'=>$s]);}
    public function saveSettings():void{Authorization::require('agenda.settings.manage');CSRF::enforce();$t=TenantContext::id();$v=['minimum_notice_minutes'=>max(0,min(10080,(int)($_POST['minimum_notice_minutes']??30))),'maximum_days_ahead'=>max(1,min(365,(int)($_POST['maximum_days_ahead']??90))),'slot_interval_minutes'=>max(5,min(60,(int)($_POST['slot_interval_minutes']??15))),'buffer_minutes'=>max(0,min(120,(int)($_POST['buffer_minutes']??0))),'customer_can_cancel'=>isset($_POST['customer_can_cancel'])?1:0,'customer_can_reschedule'=>isset($_POST['customer_can_reschedule'])?1:0,'cancel_notice_minutes'=>max(0,min(10080,(int)($_POST['cancel_notice_minutes']??120))),'reminder_24h_enabled'=>isset($_POST['reminder_24h_enabled'])?1:0,'reminder_2h_enabled'=>isset($_POST['reminder_2h_enabled'])?1:0];Database::connection()->prepare('INSERT INTO tenant_schedule_settings(tenant_id,minimum_notice_minutes,maximum_days_ahead,slot_interval_minutes,buffer_minutes,customer_can_cancel,customer_can_reschedule,cancel_notice_minutes,reminder_24h_enabled,reminder_2h_enabled,updated_at)VALUES(:t,:min,:max,:slot,:buffer,:cancel,:reschedule,:notice,:r24,:r2,NOW()) ON DUPLICATE KEY UPDATE minimum_notice_minutes=VALUES(minimum_notice_minutes),maximum_days_ahead=VALUES(maximum_days_ahead),slot_interval_minutes=VALUES(slot_interval_minutes),buffer_minutes=VALUES(buffer_minutes),customer_can_cancel=VALUES(customer_can_cancel),customer_can_reschedule=VALUES(customer_can_reschedule),cancel_notice_minutes=VALUES(cancel_notice_minutes),reminder_24h_enabled=VALUES(reminder_24h_enabled),reminder_2h_enabled=VALUES(reminder_2h_enabled),updated_at=NOW()')->execute(['t'=>$t,'min'=>$v['minimum_notice_minutes'],'max'=>$v['maximum_days_ahead'],'slot'=>$v['slot_interval_minutes'],'buffer'=>$v['buffer_minutes'],'cancel'=>$v['customer_can_cancel'],'reschedule'=>$v['customer_can_reschedule'],'notice'=>$v['cancel_notice_minutes'],'r24'=>$v['reminder_24h_enabled'],'r2'=>$v['reminder_2h_enabled']]);Audit::log('agenda.settings.updated','tenant_schedule_settings',$t,null,$v);header('Location: /schedule/settings');exit;}
    public function blocks():void{Authorization::require('agenda.blocks.manage');$t=TenantContext::id();$pdo=Database::connection();$own=$this->ownProfessional();$q=$pdo->prepare('SELECT id,name FROM professionals WHERE tenant_id=:t AND active=1 AND (:own IS NULL OR id=:own2) ORDER BY name');$q->execute(['t'=>$t,'own'=>$own,'own2'=>$own]);$professionals=$q->fetchAll();$q=$pdo->prepare("SELECT o.*,p.name professional_name FROM professional_time_off o JOIN professionals p ON p.id=o.professional_id WHERE o.tenant_id=:t AND o.status='active' AND o.ends_at>=NOW() AND (:own IS NULL OR o.professional_id=:own2) ORDER BY o.starts_at LIMIT 200");$q->execute(['t'=>$t,'own'=>$own,'own2'=>$own]);$timeOff=$q->fetchAll();$q=$pdo->prepare("SELECT b.*,p.name professional_name FROM professional_breaks b JOIN professionals p ON p.id=b.professional_id WHERE b.tenant_id=:t AND b.active=1 AND (:own IS NULL OR b.professional_id=:own2) ORDER BY p.name,b.weekday,b.start_time");$q->execute(['t'=>$t,'own'=>$own,'own2'=>$own]);View::render('schedule/blocks',['title'=>'Folgas, férias e intervalos','professionals'=>$professionals,'timeOff'=>$timeOff,'breaks'=>$q->fetchAll()]);}
    public function addTimeOff():void{Authorization::require('agenda.blocks.manage');CSRF::enforce();$t=TenantContext::id();$p=(int)($_POST['professional_id']??0);$own=$this->ownProfessional();if($own!==null)$p=$own;try{$s=new \DateTimeImmutable((string)($_POST['starts_at']??''));$e=new \DateTimeImmutable((string)($_POST['ends_at']??''));}catch(\Throwable){HttpException::abort(422,'Período inválido.');}if(!$p||$e<=$s)HttpException::abort(422,'Período inválido.');$type=(string)($_POST['type']??'other');if(!in_array($type,['break','day_off','vacation','meeting','personal','other'],true))$type='other';$q=Database::connection()->prepare('SELECT 1 FROM professionals WHERE id=:p AND tenant_id=:t AND active=1');$q->execute(['p'=>$p,'t'=>$t]);if(!$q->fetchColumn())HttpException::abort(422,'Profissional inválido.');Database::connection()->prepare("INSERT INTO professional_time_off(tenant_id,professional_id,type,starts_at,ends_at,reason,status,created_by,created_at,updated_at)VALUES(:t,:p,:type,:s,:e,:r,'active',:u,NOW(),NOW())")->execute(['t'=>$t,'p'=>$p,'type'=>$type,'s'=>$s->format('Y-m-d H:i:s'),'e'=>$e->format('Y-m-d H:i:s'),'r'=>trim((string)($_POST['reason']??''))?:null,'u'=>Auth::user()['id']]);Audit::log('agenda.time_off.created','professional_time_off',(int)Database::connection()->lastInsertId());header('Location: /schedule/blocks');exit;}
    public function addBreak():void{Authorization::require('agenda.blocks.manage');CSRF::enforce();$t=TenantContext::id();$p=(int)($_POST['professional_id']??0);$own=$this->ownProfessional();if($own!==null)$p=$own;$day=(int)($_POST['weekday']??0);$s=(string)($_POST['start_time']??'');$e=(string)($_POST['end_time']??'');if(!$p||$day<1||$day>7||!preg_match('/^\d{2}:\d{2}$/',$s)||!preg_match('/^\d{2}:\d{2}$/',$e)||$s>=$e)HttpException::abort(422,'Intervalo inválido.');Database::connection()->prepare('INSERT INTO professional_breaks(tenant_id,professional_id,weekday,start_time,end_time,label,active,created_at,updated_at)VALUES(:t,:p,:d,:s,:e,:l,1,NOW(),NOW())')->execute(['t'=>$t,'p'=>$p,'d'=>$day,'s'=>$s.':00','e'=>$e.':00','l'=>trim((string)($_POST['label']??'Intervalo'))]);Audit::log('agenda.break.created','professional_breaks',(int)Database::connection()->lastInsertId());header('Location: /schedule/blocks');exit;}
    public function cancelTimeOff(string $id):void{Authorization::require('agenda.blocks.manage');CSRF::enforce();$t=TenantContext::id();$own=$this->ownProfessional();$sql='UPDATE professional_time_off SET status=\'cancelled\',updated_at=NOW() WHERE id=:id AND tenant_id=:t';$p=['id'=>(int)$id,'t'=>$t];if($own!==null){$sql.=' AND professional_id=:p';$p['p']=$own;}Database::connection()->prepare($sql)->execute($p);header('Location: /schedule/blocks');exit;}
    public function deleteBreak(string $id):void{Authorization::require('agenda.blocks.manage');CSRF::enforce();$t=TenantContext::id();$own=$this->ownProfessional();$sql='UPDATE professional_breaks SET active=0,updated_at=NOW() WHERE id=:id AND tenant_id=:t';$p=['id'=>(int)$id,'t'=>$t];if($own!==null){$sql.=' AND professional_id=:p';$p['p']=$own;}Database::connection()->prepare($sql)->execute($p);header('Location: /schedule/blocks');exit;}
    private function ownProfessional():?int{if((Auth::user()['role']??'')!=='professional')return null;$q=Database::connection()->prepare('SELECT id FROM professionals WHERE tenant_id=:t AND user_id=:u AND active=1');$q->execute(['t'=>TenantContext::id(),'u'=>Auth::user()['id']]);$id=$q->fetchColumn();if(!$id)HttpException::abort(403,'Perfil profissional inválido.');return (int)$id;}
}
