<?php
namespace App\Controllers;

use App\Core\{CSRF,Database,Audit,View,Authorization,TenantContext,HttpException};

final class ServiceController
{
    public function index():void{Authorization::require('services.view');$q=Database::connection()->prepare('SELECT * FROM services WHERE tenant_id=:t ORDER BY active DESC,name');$q->execute(['t'=>TenantContext::id()]);View::render('services/index',['title'=>'Serviços','services'=>$q->fetchAll()]);}
    public function create():void{Authorization::require('services.create');TenantContext::id();View::render('services/form',['title'=>'Novo serviço','service'=>null]);}
    public function store():void{Authorization::require('services.create');CSRF::enforce();$d=$this->validated();$pdo=Database::connection();$pdo->prepare("INSERT INTO services(tenant_id,name,description,duration_minutes,price,active,created_at,updated_at)VALUES(:t,:name,:description,:duration,:price,1,NOW(),NOW())")->execute(['t'=>TenantContext::id()]+$d);$id=(int)$pdo->lastInsertId();Audit::log('service.create','services',$id,null,['name'=>$d['name'],'price'=>$d['price']]);header('Location: /services/'.$id.'/edit');exit;}
    public function edit(string $id):void{Authorization::require('services.edit');$q=Database::connection()->prepare('SELECT * FROM services WHERE id=:id AND tenant_id=:t');$q->execute(['id'=>(int)$id,'t'=>TenantContext::id()]);$service=$q->fetch();if(!$service)HttpException::abort(404,'Serviço não encontrado.');View::render('services/form',['title'=>'Editar serviço','service'=>$service]);}
    public function update(string $id):void{Authorization::require('services.edit');CSRF::enforce();$t=TenantContext::id();$sid=(int)$id;$pdo=Database::connection();$q=$pdo->prepare('SELECT * FROM services WHERE id=:id AND tenant_id=:t');$q->execute(['id'=>$sid,'t'=>$t]);$old=$q->fetch();if(!$old)HttpException::abort(404,'Serviço não encontrado.');$d=$this->validated();$active=isset($_POST['active'])?1:0;$pdo->prepare('UPDATE services SET name=:name,description=:description,duration_minutes=:duration,price=:price,active=:active,updated_at=NOW() WHERE id=:id AND tenant_id=:t')->execute($d+['active'=>$active,'id'=>$sid,'t'=>$t]);Audit::log('service.update','services',$sid,$old,['name'=>$d['name'],'active'=>$active]);header('Location: /services/'.$sid.'/edit');exit;}
    public function deactivate(string $id):void{Authorization::require('services.edit');CSRF::enforce();$q=Database::connection()->prepare('UPDATE services SET active=0,updated_at=NOW() WHERE id=:id AND tenant_id=:t');$q->execute(['id'=>(int)$id,'t'=>TenantContext::id()]);if(!$q->rowCount())HttpException::abort(404,'Serviço não encontrado.');Audit::log('service.deactivate','services',(int)$id);header('Location: /services');exit;}
    private function validated():array{$name=trim((string)($_POST['name']??''));$description=trim((string)($_POST['description']??''));$price=filter_var(str_replace(',','.',(string)($_POST['price']??'')),FILTER_VALIDATE_FLOAT);$duration=filter_var($_POST['duration_minutes']??null,FILTER_VALIDATE_INT);if(strlen($name)<2||$price===false||$price<0||$duration===false||$duration<5||$duration>1440)HttpException::abort(422,'Dados do serviço inválidos.');return ['name'=>$name,'description'=>$description?:null,'duration'=>$duration,'price'=>$price];}
}
