<?php
namespace App\Controllers;
use App\Core\{Authorization,CSRF,Database,TenantContext,View,Audit,Auth,HttpException};
use App\Services\ModuleService;
final class StockController
{
    private function enabled():void{ModuleService::require('stock');}
    public function index():void{$this->enabled();Authorization::require('products.stock');$t=TenantContext::id();$pdo=Database::connection();$q=$pdo->prepare('SELECT * FROM products WHERE tenant_id=:t AND active=1 ORDER BY (stock<=minimum_stock) DESC,name');$q->execute(['t'=>$t]);$products=$q->fetchAll();$q=$pdo->prepare('SELECT m.*,p.name product_name,u.name user_name FROM product_stock_movements m JOIN products p ON p.id=m.product_id LEFT JOIN users u ON u.id=m.user_id WHERE m.tenant_id=:t ORDER BY m.id DESC LIMIT 300');$q->execute(['t'=>$t]);View::render('stock/index',['title'=>'Estoque','products'=>$products,'movements'=>$q->fetchAll()]);}
    public function adjust():void{$this->enabled();Authorization::require('stock.adjust');CSRF::enforce();$t=TenantContext::id();$product=(int)($_POST['product_id']??0);$qty=filter_var(str_replace(',','.',(string)($_POST['quantity']??'')),FILTER_VALIDATE_FLOAT);$type=(string)($_POST['type']??'adjustment');$reason=trim((string)($_POST['reason']??''));if(!$product||$qty===false||$qty==0||strlen($reason)<3||!in_array($type,['entry','exit','adjustment'],true))HttpException::abort(422,'Ajuste inválido.');$delta=$type==='exit'?-abs((float)$qty):(float)$qty;$pdo=Database::connection();$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT stock FROM products WHERE id=:p AND tenant_id=:t AND active=1 FOR UPDATE');$q->execute(['p'=>$product,'t'=>$t]);$stock=$q->fetchColumn();if($stock===false)throw new \DomainException('Produto não encontrado.');$balance=(float)$stock+$delta;if($balance<0)throw new \DomainException('O ajuste deixaria o estoque negativo.');$pdo->prepare('UPDATE products SET stock=:b,updated_at=NOW() WHERE id=:p AND tenant_id=:t')->execute(['b'=>$balance,'p'=>$product,'t'=>$t]);$pdo->prepare('INSERT INTO product_stock_movements(tenant_id,product_id,type,quantity,balance_after,user_id,reason,created_at)VALUES(:t,:p,:type,:q,:b,:u,:r,NOW())')->execute(['t'=>$t,'p'=>$product,'type'=>$type,'q'=>$delta,'b'=>$balance,'u'=>Auth::user()['id'],'r'=>$reason]);$pdo->commit();Audit::log('stock.adjusted','products',$product,null,['delta'=>$delta,'balance'=>$balance,'reason'=>$reason]);}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();HttpException::abort(422,$e->getMessage());}header('Location: /stock');exit;}
}
