<?php
namespace App\Controllers;
use App\Core\{Auth,Audit,CSRF,Database,Encryption,HttpException};use App\Services\MercadoPagoProvider;
final class SubscriptionExemptionController
{
 private function master():void{Auth::requireRole('master');}
 public function form(string $id):void{$this->master();$tenant=(int)$id;$pdo=Database::connection();$q=$pdo->prepare("SELECT t.id,t.name,p.name plan_name,s.status subscription_status FROM tenants t LEFT JOIN subscriptions s ON s.id=(SELECT MAX(s2.id) FROM subscriptions s2 WHERE s2.tenant_id=t.id) LEFT JOIN plans p ON p.id=s.plan_id WHERE t.id=:t AND t.deleted_at IS NULL");$q->execute(['t'=>$tenant]);$row=$q->fetch();if(!$row)HttpException::abort(404,'Empresa não encontrada.');$current=\App\Services\SubscriptionExemptionService::current($tenant);$h=$pdo->prepare('SELECT se.*,u.name granted_by_name FROM subscription_exemptions se LEFT JOIN users u ON u.id=se.granted_by WHERE se.tenant_id=:t ORDER BY se.id DESC LIMIT 30');$h->execute(['t'=>$tenant]);\App\Core\View::render('master/subscription-exemption',['title'=>'Isenção de mensalidade','tenant'=>$row,'exemption'=>$current,'history'=>$h->fetchAll()]);}
 public function grant(string $id):void
 {
  $this->master();CSRF::enforce();$tenant=(int)$id;$type=($_POST['exemption_type']??'temporary')==='permanent'?'permanent':'temporary';$reason=trim((string)($_POST['reason']??''));$end=trim((string)($_POST['ends_at']??''));if(mb_strlen($reason)<5)HttpException::abort(422,'Informe um motivo para a isenção.');if($type==='temporary'){if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$end)||strtotime($end.' 23:59:59')<=time())HttpException::abort(422,'Informe uma data futura para o término da isenção.');$ends=$end.' 23:59:59';}else$ends=null;$pdo=Database::connection();$q=$pdo->prepare('SELECT id,provider_subscription_id FROM subscriptions WHERE tenant_id=:t ORDER BY id DESC LIMIT 1');$q->execute(['t'=>$tenant]);$sub=$q->fetch();if(!$sub)HttpException::abort(422,'A empresa não possui assinatura para receber isenção.');$subscription=(int)$sub['id'];if(!empty($sub['provider_subscription_id'])){$g=$pdo->query("SELECT access_token_encrypted FROM payment_gateways WHERE provider='mercadopago' AND active=1 AND last_test_status='validated' ORDER BY (environment='production') DESC,last_tested_at DESC LIMIT 1")->fetch();if(!$g)HttpException::abort(503,'Não foi possível cancelar a recorrência antes da isenção.');try{(new MercadoPagoProvider(Encryption::decrypt($g['access_token_encrypted'])['value']??''))->cancelSubscription((string)$sub['provider_subscription_id']);}catch(\Throwable $e){HttpException::abort(502,'A isenção não foi aplicada porque a recorrência não pôde ser cancelada: ' . $e->getMessage());}}$pdo->beginTransaction();try{$pdo->prepare("UPDATE subscription_exemptions SET status='revoked',revoked_by=:u,revoked_at=NOW(),updated_at=NOW() WHERE tenant_id=:t AND status='active'")->execute(['u'=>Auth::user()['id'],'t'=>$tenant]);$pdo->prepare("INSERT INTO subscription_exemptions(tenant_id,subscription_id,exemption_type,starts_at,ends_at,reason,status,granted_by,created_at,updated_at)VALUES(:t,:s,:type,NOW(),:ends,:reason,'active',:u,NOW(),NOW())")->execute(['t'=>$tenant,'s'=>$subscription,'type'=>$type,'ends'=>$ends,'reason'=>$reason,'u'=>Auth::user()['id']]);$exemption=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE subscriptions SET provider_subscription_id=NULL,updated_at=NOW() WHERE id=:s AND tenant_id=:t')->execute(['s'=>$subscription,'t'=>$tenant]);$pdo->prepare("UPDATE invoices SET status='cancelled',updated_at=NOW() WHERE tenant_id=:t AND status='pending' AND due_at>=CURDATE()")->execute(['t'=>$tenant]);$pdo->prepare("UPDATE payments SET status='cancelled',updated_at=NOW() WHERE tenant_id=:t AND status='pending' AND due_at>=CURDATE()")->execute(['t'=>$tenant]);$pdo->commit();Audit::log('MASTER_SUBSCRIPTION_EXEMPTION_GRANTED','subscription_exemptions',$exemption,null,['tenant_id'=>$tenant,'type'=>$type,'ends_at'=>$ends,'reason'=>$reason]);}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}header('Location: /master/tenants/'.$tenant.'?exemption=granted');exit;
 }
 public function revoke(string $id):void
 {
  $this->master();CSRF::enforce();$tenant=(int)$id;$pdo=Database::connection();$q=$pdo->prepare("UPDATE subscription_exemptions SET status='revoked',revoked_by=:u,revoked_at=NOW(),updated_at=NOW() WHERE tenant_id=:t AND status='active'");$q->execute(['u'=>Auth::user()['id'],'t'=>$tenant]);Audit::log('MASTER_SUBSCRIPTION_EXEMPTION_REVOKED','tenants',$tenant,null,['records'=>$q->rowCount()]);header('Location: /master/tenants/'.$tenant.'?exemption=revoked');exit;
 }
}
