<?php
namespace App\Controllers;
use App\Core\{Authorization,CSRF,Database,TenantContext,View,Audit,HttpException};
use App\Services\AutoTenantService;
final class VehicleController
{
    private function guard(int $t):void{if(!AutoTenantService::isAutoTenant($t))HttpException::abort(403,'Veículos estão disponíveis no ApPlanner Auto.');}
    public function index():void{Authorization::require('vehicles.view');$t=TenantContext::id();$this->guard($t);$pdo=Database::connection();$q=$pdo->prepare("SELECT v.*,c.name customer_name,p.vehicle_type,p.fuel_type,p.current_odometer,p.size_class,p.last_service_at,p.next_recommended_at,(SELECT MAX(a.starts_at) FROM appointments a WHERE a.tenant_id=v.tenant_id AND a.vehicle_id=v.id AND a.status='completed') last_appointment_at FROM customer_vehicles v JOIN customers c ON c.id=v.customer_id LEFT JOIN auto_vehicle_profiles p ON p.vehicle_id=v.id AND p.tenant_id=v.tenant_id WHERE v.tenant_id=:t AND v.active=1 ORDER BY c.name,v.model");$q->execute(['t'=>$t]);$vehicles=$q->fetchAll();$q=$pdo->prepare("SELECT id,name FROM customers WHERE tenant_id=:t AND status='active' ORDER BY name");$q->execute(['t'=>$t]);View::render('vehicles/index',['title'=>'Veículos','vehicles'=>$vehicles,'customers'=>$q->fetchAll()]);}
    public function show(string $id):void{Authorization::require('vehicles.view');$t=TenantContext::id();$this->guard($t);$pdo=Database::connection();$q=$pdo->prepare("SELECT v.*,c.name customer_name,c.phone customer_phone,c.email customer_email,p.* FROM customer_vehicles v JOIN customers c ON c.id=v.customer_id LEFT JOIN auto_vehicle_profiles p ON p.vehicle_id=v.id AND p.tenant_id=v.tenant_id WHERE v.id=:id AND v.tenant_id=:t");$q->execute(['id'=>(int)$id,'t'=>$t]);$vehicle=$q->fetch();if(!$vehicle)HttpException::abort(404,'Veículo não encontrado.');$q=$pdo->prepare("SELECT j.id job_id,j.status,a.starts_at,a.ends_at,s.name service_name,ac.total_amount,ac.status command_status,b.name bay_name FROM auto_jobs j JOIN appointments a ON a.id=j.appointment_id JOIN services s ON s.id=a.service_id LEFT JOIN auto_commands ac ON ac.job_id=j.id LEFT JOIN auto_service_bays b ON b.id=j.bay_id WHERE j.tenant_id=:t AND j.vehicle_id=:v ORDER BY a.starts_at DESC LIMIT 100");$q->execute(['t'=>$t,'v'=>$vehicle['id']]);$history=$q->fetchAll();$m=$pdo->prepare('SELECT * FROM auto_vehicle_maintenance WHERE tenant_id=:t AND vehicle_id=:v ORDER BY performed_at DESC,id DESC');$m->execute(['t'=>$t,'v'=>$vehicle['id']]);$crm=$pdo->prepare("SELECT * FROM auto_crm_events WHERE tenant_id=:t AND vehicle_id=:v ORDER BY due_at DESC LIMIT 50");$crm->execute(['t'=>$t,'v'=>$vehicle['id']]);View::render('vehicles/show',['title'=>$vehicle['model'],'vehicle'=>$vehicle,'history'=>$history,'maintenance'=>$m->fetchAll(),'crm'=>$crm->fetchAll()]);}
    public function store():void{Authorization::require('vehicles.manage');CSRF::enforce();$t=TenantContext::id();$this->guard($t);$d=$this->data();$q=Database::connection()->prepare("SELECT 1 FROM customers WHERE id=:c AND tenant_id=:t AND status='active'");$q->execute(['c'=>$d['customer_id'],'t'=>$t]);if(!$q->fetchColumn())HttpException::abort(422,'Cliente inválido.');$pdo=Database::connection();try{$pdo->beginTransaction();$pdo->prepare('INSERT INTO customer_vehicles(tenant_id,customer_id,plate,make,model,year,color,notes,active,created_at,updated_at)VALUES(:t,:c,:plate,:make,:model,:year,:color,:notes,1,NOW(),NOW())')->execute(['t'=>$t,'c'=>$d['customer_id'],'plate'=>$d['plate'],'make'=>$d['make'],'model'=>$d['model'],'year'=>$d['year'],'color'=>$d['color'],'notes'=>$d['notes']]);$id=(int)$pdo->lastInsertId();$this->profile($pdo,$t,$id,$d);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();HttpException::abort(422,'Não foi possível cadastrar. Verifique se a placa já existe.');}Audit::log('vehicle.created','customer_vehicles',$id);header('Location: /vehicles/'.$id);exit;}
    public function update(string $id):void{Authorization::require('vehicles.manage');CSRF::enforce();$t=TenantContext::id();$this->guard($t);$d=$this->data();$pdo=Database::connection();$cq=$pdo->prepare("SELECT 1 FROM customers WHERE id=:c AND tenant_id=:t AND status='active'");$cq->execute(['c'=>$d['customer_id'],'t'=>$t]);if(!$cq->fetchColumn())HttpException::abort(422,'Cliente inválido.');$pdo->beginTransaction();try{$q=$pdo->prepare('UPDATE customer_vehicles SET customer_id=:c,plate=:plate,make=:make,model=:model,year=:year,color=:color,notes=:notes,updated_at=NOW() WHERE id=:id AND tenant_id=:t');$q->execute(['c'=>$d['customer_id'],'plate'=>$d['plate'],'make'=>$d['make'],'model'=>$d['model'],'year'=>$d['year'],'color'=>$d['color'],'notes'=>$d['notes'],'id'=>(int)$id,'t'=>$t]);$x=$pdo->prepare('SELECT 1 FROM customer_vehicles WHERE id=:id AND tenant_id=:t');$x->execute(['id'=>(int)$id,'t'=>$t]);if(!$x->fetchColumn())throw new \DomainException('Veículo não encontrado.');$this->profile($pdo,$t,(int)$id,$d);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();HttpException::abort(422,$e->getMessage());}Audit::log('vehicle.updated','customer_vehicles',(int)$id);header('Location: /vehicles/'.(int)$id);exit;}
    public function deactivate(string $id):void{Authorization::require('vehicles.manage');CSRF::enforce();$t=TenantContext::id();$this->guard($t);Database::connection()->prepare('UPDATE customer_vehicles SET active=0,updated_at=NOW() WHERE id=:id AND tenant_id=:t')->execute(['id'=>(int)$id,'t'=>$t]);Audit::log('vehicle.deactivated','customer_vehicles',(int)$id);header('Location: /vehicles');exit;}
    private function profile(\PDO $pdo,int $t,int $id,array $d):void{$pdo->prepare("INSERT INTO auto_vehicle_profiles(vehicle_id,tenant_id,vehicle_type,fuel_type,vin,current_odometer,size_class,preferred_notes,updated_at)VALUES(:v,:t,:type,:fuel,:vin,:odo,:size,:notes,NOW()) ON DUPLICATE KEY UPDATE vehicle_type=VALUES(vehicle_type),fuel_type=VALUES(fuel_type),vin=VALUES(vin),current_odometer=COALESCE(VALUES(current_odometer),current_odometer),size_class=VALUES(size_class),preferred_notes=VALUES(preferred_notes),updated_at=NOW()")->execute(['v'=>$id,'t'=>$t,'type'=>$d['vehicle_type'],'fuel'=>$d['fuel_type'],'vin'=>$d['vin'],'odo'=>$d['current_odometer'],'size'=>$d['size_class'],'notes'=>$d['preferred_notes']]);}
    private function data():array{$customer=(int)($_POST['customer_id']??0);$model=trim((string)($_POST['model']??''));$plate=mb_strtoupper(preg_replace('/[^A-Z0-9]/i','',(string)($_POST['plate']??'')));$year=(int)($_POST['year']??0)?:null;$size=(string)($_POST['size_class']??'');if($size!==''&&!in_array($size,['compact','medium','large','pickup','motorcycle','other'],true))$size='';if(!$customer||strlen($model)<2||($plate!==''&&!preg_match('/^[A-Z0-9]{7}$/',$plate)))HttpException::abort(422,'Dados do veículo inválidos.');return ['customer_id'=>$customer,'model'=>$model,'plate'=>$plate?:null,'make'=>trim((string)($_POST['make']??''))?:null,'year'=>$year,'color'=>trim((string)($_POST['color']??''))?:null,'notes'=>trim((string)($_POST['notes']??''))?:null,'vehicle_type'=>trim((string)($_POST['vehicle_type']??''))?:null,'fuel_type'=>trim((string)($_POST['fuel_type']??''))?:null,'vin'=>mb_substr(trim((string)($_POST['vin']??'')),0,40)?:null,'current_odometer'=>max(0,(int)($_POST['current_odometer']??0))?:null,'size_class'=>$size?:null,'preferred_notes'=>trim((string)($_POST['preferred_notes']??''))?:null];}
}
