<?php
namespace App\Controllers;
use App\Core\{Authorization,CSRF,Database,TenantContext,View,Audit,HttpException};
use App\Services\{ModuleService,AvailabilityService};
final class WaitlistController
{
    private function enabled():void{ModuleService::require('waitlist');}
    public function index():void{$this->enabled();Authorization::require('waitlist.view');$t=TenantContext::id();$pdo=Database::connection();$q=$pdo->prepare("SELECT w.*,c.name customer_name,s.name service_name,p.name professional_name FROM waitlist_entries w JOIN customers c ON c.id=w.customer_id JOIN services s ON s.id=w.service_id LEFT JOIN professionals p ON p.id=w.professional_id WHERE w.tenant_id=:t AND w.status='waiting' ORDER BY w.created_at");$q->execute(['t'=>$t]);$entries=$q->fetchAll();$engine=new AvailabilityService();foreach($entries as &$e){$e['suggestions']=[];$professionals=$e['professional_id']?[(int)$e['professional_id']]:$this->professionalsForService($t,(int)$e['service_id']);for($d=0;$d<14&&count($e['suggestions'])<3;$d++){$day=(new \DateTimeImmutable('today'))->modify("+$d days");if($e['preferred_date']&&$day->format('Y-m-d')<$e['preferred_date'])continue;foreach($professionals as $pid){foreach($engine->slots($t,(int)$e['service_id'],$pid,$day) as $slot){$hour=(int)substr($slot['label'],0,2);if($e['period']==='morning'&&$hour>=12)continue;if($e['period']==='afternoon'&&($hour<12||$hour>=18))continue;if($e['period']==='evening'&&$hour<18)continue;$e['suggestions'][]=$slot['label'].' '.$day->format('d/m').' · Prof. #'.$pid;if(count($e['suggestions'])>=3)break 3;}}}}$q=$pdo->prepare("SELECT id,name FROM customers WHERE tenant_id=:t AND status='active' ORDER BY name LIMIT 1000");$q->execute(['t'=>$t]);$customers=$q->fetchAll();$q=$pdo->prepare('SELECT id,name FROM services WHERE tenant_id=:t AND active=1 ORDER BY name');$q->execute(['t'=>$t]);$services=$q->fetchAll();$q=$pdo->prepare('SELECT id,name FROM professionals WHERE tenant_id=:t AND active=1 ORDER BY name');$q->execute(['t'=>$t]);View::render('waitlist/index',['title'=>'Lista de espera','entries'=>$entries,'customers'=>$customers,'services'=>$services,'professionals'=>$q->fetchAll()]);}
    public function store():void{$this->enabled();Authorization::require('waitlist.manage');CSRF::enforce();$t=TenantContext::id();$customer=(int)($_POST['customer_id']??0);$service=(int)($_POST['service_id']??0);$professional=(int)($_POST['professional_id']??0)?:null;$date=trim((string)($_POST['preferred_date']??''))?:null;$period=(string)($_POST['period']??'any');if(!$customer||!$service||($date&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))||!in_array($period,['any','morning','afternoon','evening'],true))HttpException::abort(422,'Dados inválidos.');Database::connection()->prepare("INSERT INTO waitlist_entries(tenant_id,customer_id,service_id,professional_id,preferred_date,period,status,notes,created_at,updated_at)VALUES(:t,:c,:s,:p,:d,:period,'waiting',:n,NOW(),NOW())")->execute(['t'=>$t,'c'=>$customer,'s'=>$service,'p'=>$professional,'d'=>$date,'period'=>$period,'n'=>trim((string)($_POST['notes']??''))?:null]);Audit::log('waitlist.created','waitlist_entries',(int)Database::connection()->lastInsertId());header('Location: /waitlist');exit;}
    public function cancel(string $id):void{$this->enabled();Authorization::require('waitlist.manage');CSRF::enforce();Database::connection()->prepare("UPDATE waitlist_entries SET status='cancelled',updated_at=NOW() WHERE id=:id AND tenant_id=:t")->execute(['id'=>(int)$id,'t'=>TenantContext::id()]);header('Location: /waitlist');exit;}
    private function professionalsForService(int $t,int $service):array{$q=Database::connection()->prepare("SELECT p.id FROM professionals p WHERE p.tenant_id=:t AND p.active=1 AND (NOT EXISTS(SELECT 1 FROM professional_services ps0 WHERE ps0.professional_id=p.id) OR EXISTS(SELECT 1 FROM professional_services ps WHERE ps.professional_id=p.id AND ps.service_id=:s))");$q->execute(['t'=>$t,'s'=>$service]);return array_map('intval',array_column($q->fetchAll(),'id'));}
}
