<?php
declare(strict_types=1);

require __DIR__ . '/app/Core/bootstrap.php';

use App\Core\{Router,Auth};
use App\Services\LegalDocumentService;
use App\Controllers\{AuthController,DashboardController,CustomerController,ServiceController,AppointmentController,OperationsCenterController,IncidentController,MasterCommandController,MasterController,SubscriptionExemptionController,ApiController,PublicBookingController,PublicEntryController,PublicDirectoryController,PublicSportsController,PublicArenaExtrasController,SportsController,SportsReservationsController,ArenaOperationsController,BankingController,MasterBankingController,TenantPaymentWebhookController,FinanceController,PrivacyController,IntegrationController,WebhookController,OnboardingController,CommercialController,CommercialTeamController,CommercialLeadController,BillingController,BillingSupportController,PixController,ProfessionalController,SalesController,SupportController,MercadoPagoController,ReportsController,IntelligenceController,UnitController,MedicalRecordController,ScheduleController,CommissionController,StockController,VehicleController,NotificationController,PackageController,LoyaltyController,WaitlistController,DomainController,LegalController,ModuleController,PlatformFinanceController,BackupController,BrandController,DataImportController,BlogController,LeadMarketingController,WhatsAppController};

$router = new Router();

// Site público e aquisição
$router->get('/', [CommercialController::class, 'landing']);
$router->get('/estabelecimentos', [PublicDirectoryController::class, 'index']);
$router->get('/api/public/company/{slug}/location', [PublicDirectoryController::class, 'companyLocation']);
$router->get('/planos', [CommercialController::class, 'plansPage']);
$router->get('/cadastro', [CommercialController::class, 'signup']);
$router->post('/cadastro', [CommercialController::class, 'register']);
$router->get('/blog', [BlogController::class, 'index']);
$router->get('/blog/{slug}', [BlogController::class, 'show']);
$router->get('/email/descadastrar/{token}', [LeadMarketingController::class, 'unsubscribe']);
$router->get('/indicacao/{code}', [LeadMarketingController::class, 'referral']);
$router->get('/proposta/{token}', [CommercialTeamController::class, 'publicProposal']);
$router->post('/proposta/{token}/aceitar', [CommercialTeamController::class, 'acceptProposal']);
$router->get('/comercial', [CommercialTeamController::class, 'index']);
$router->post('/comercial/propostas', [CommercialTeamController::class, 'proposal']);
$router->get('/interesse-comercial', [CommercialLeadController::class, 'form']);
$router->post('/interesse-comercial', [CommercialLeadController::class, 'store']);
$router->get('/comercial/oportunidades', [CommercialLeadController::class, 'queue']);
$router->post('/comercial/oportunidades/{id}/atender', [CommercialLeadController::class, 'claim']);
$router->post('/comercial/oportunidades/{id}/transferir', [CommercialLeadController::class, 'transfer']);
$router->post('/comercial/oportunidades/{id}/status', [CommercialLeadController::class, 'status']);
$router->get('/termos', [LegalController::class, 'terms']);
$router->get('/privacidade', [LegalController::class, 'privacy']);
$router->get('/aceite-legal', [LegalController::class, 'acceptance']);
$router->post('/aceite-legal', [LegalController::class, 'accept']);

// Autenticação
$router->get('/login', [AuthController::class, 'showLogin']);
$router->post('/login', [AuthController::class, 'login']);
$router->get('/profissional/login', [AuthController::class, 'showProfessionalLogin']);
$router->post('/profissional/login', [AuthController::class, 'professionalLogin']);
$router->post('/logout', [AuthController::class, 'logout']);
$router->get('/forgot-password', [AuthController::class, 'showForgotPassword']);
$router->post('/forgot-password', [AuthController::class, 'requestPasswordReset']);
$router->get('/reset-password', [AuthController::class, 'showResetPassword']);
$router->post('/reset-password', [AuthController::class, 'resetPassword']);
$router->get('/two-factor-challenge', [AuthController::class, 'showTwoFactorChallenge']);
$router->post('/two-factor-challenge', [AuthController::class, 'verifyTwoFactorChallenge']);
$router->get('/security', [AuthController::class, 'security']);
$router->post('/security/password', [AuthController::class, 'changePassword']);
$router->post('/security/2fa/start', [AuthController::class, 'startTwoFactor']);
$router->post('/security/2fa/confirm', [AuthController::class, 'confirmTwoFactor']);
$router->post('/security/email/send', [AuthController::class, 'sendVerification']);
$router->get('/verify-email', [AuthController::class, 'verifyEmail']);

// Cliente SaaS / operação
$router->get('/dashboard', [DashboardController::class, 'index']);
$router->get('/customers', [CustomerController::class, 'index']);
$router->get('/customers/create', [CustomerController::class, 'create']);
$router->post('/customers/store', [CustomerController::class, 'store']);
$router->get('/customers/{id}', [CustomerController::class, 'show']);
$router->get('/customers/{id}/edit', [CustomerController::class, 'edit']);
$router->post('/customers/{id}/update', [CustomerController::class, 'update']);
$router->post('/customers/{id}/deactivate', [CustomerController::class, 'deactivate']);
$router->get('/services', [ServiceController::class, 'index']);
$router->get('/services/create', [ServiceController::class, 'create']);
$router->post('/services/store', [ServiceController::class, 'store']);
$router->get('/services/{id}/edit', [ServiceController::class, 'edit']);
$router->post('/services/{id}/update', [ServiceController::class, 'update']);
$router->post('/services/{id}/deactivate', [ServiceController::class, 'deactivate']);
$router->get('/appointments', [AppointmentController::class, 'index']);
$router->get('/appointments/create', [AppointmentController::class, 'create']);
$router->get('/appointments/availability', [AppointmentController::class, 'availability']);
$router->post('/appointments/store', [AppointmentController::class, 'store']);
$router->post('/appointments/status', [AppointmentController::class, 'updateStatus']);
$router->get('/appointments/{id}/reschedule', [AppointmentController::class, 'reschedule']);
$router->post('/appointments/{id}/reschedule', [AppointmentController::class, 'saveReschedule']);
$router->get('/professionals', [ProfessionalController::class, 'index']);
$router->post('/professionals', [ProfessionalController::class, 'store']);
$router->get('/professionals/{id}/edit', [ProfessionalController::class, 'edit']);
$router->post('/professionals/{id}/update', [ProfessionalController::class, 'update']);
$router->post('/professionals/{id}/delete', [ProfessionalController::class, 'delete']);
$router->post('/professionals/{id}/availability', [ProfessionalController::class, 'saveAvailability']);
$router->post('/professionals/{id}/temporary-password', [ProfessionalController::class, 'temporaryPassword']);
$router->get('/professional/availability', [ProfessionalController::class, 'myAvailability']);
$router->post('/professional/availability', [ProfessionalController::class, 'saveMyAvailability']);
$router->get('/schedule/settings', [ScheduleController::class, 'settings']);
$router->post('/schedule/settings', [ScheduleController::class, 'saveSettings']);
$router->get('/schedule/blocks', [ScheduleController::class, 'blocks']);
$router->post('/schedule/time-off', [ScheduleController::class, 'addTimeOff']);
$router->post('/schedule/time-off/{id}/cancel', [ScheduleController::class, 'cancelTimeOff']);
$router->post('/schedule/breaks', [ScheduleController::class, 'addBreak']);
$router->post('/schedule/breaks/{id}/delete', [ScheduleController::class, 'deleteBreak']);
$router->get('/professional/performance', [ProfessionalController::class, 'performance']);
$router->get('/products', [SalesController::class, 'products']);
$router->post('/products', [SalesController::class, 'storeProduct']);
$router->get('/products/{id}/edit', [SalesController::class, 'editProduct']);
$router->post('/products/{id}/update', [SalesController::class, 'updateProduct']);
$router->post('/products/{id}/deactivate', [SalesController::class, 'deactivateProduct']);
$router->get('/sales', [SalesController::class, 'index']);
$router->post('/sales', [SalesController::class, 'store']);
$router->post('/sales/{id}/cancel', [SalesController::class, 'cancel']);
$router->get('/finance', [FinanceController::class, 'index']);
$router->post('/finance/store', [FinanceController::class, 'store']);
$router->post('/finance/{id}/paid', [FinanceController::class, 'markPaid']);
$router->post('/finance/{id}/cancel', [FinanceController::class, 'cancel']);
$router->post('/finance/categories', [FinanceController::class, 'addCategory']);
$router->post('/finance/cash/open', [FinanceController::class, 'openCash']);
$router->post('/finance/cash/{id}/close', [FinanceController::class, 'closeCash']);
$router->get('/commissions', [CommissionController::class, 'index']);
$router->post('/commissions/{id}/pay', [CommissionController::class, 'pay']);
$router->post('/commissions/pay-period', [CommissionController::class, 'payPeriod']);
$router->get('/stock', [StockController::class, 'index']);
$router->post('/stock/adjust', [StockController::class, 'adjust']);
$router->get('/vehicles', [VehicleController::class, 'index']);
$router->post('/vehicles', [VehicleController::class, 'store']);
$router->post('/vehicles/{id}/update', [VehicleController::class, 'update']);
$router->post('/vehicles/{id}/deactivate', [VehicleController::class, 'deactivate']);
$router->get('/notifications', [NotificationController::class, 'index']);
$router->post('/notifications/read-all', [NotificationController::class, 'readAll']);
$router->post('/notifications/{id}/read', [NotificationController::class, 'read']);
$router->get('/packages', [PackageController::class, 'index']);
$router->post('/packages', [PackageController::class, 'store']);
$router->post('/packages/sell', [PackageController::class, 'sell']);
$router->post('/packages/{id}/use', [PackageController::class, 'usePackage']);
$router->post('/memberships/{id}/cancel', [PackageController::class, 'cancelMembership']);
$router->get('/loyalty', [LoyaltyController::class, 'index']);
$router->post('/loyalty/settings', [LoyaltyController::class, 'settings']);
$router->post('/loyalty/adjust', [LoyaltyController::class, 'adjust']);
$router->post('/loyalty/redeem', [LoyaltyController::class, 'redeem']);
$router->post('/loyalty/rewards/{id}/redeem', [LoyaltyController::class, 'redeemReward']);
$router->post('/loyalty/referrals', [LoyaltyController::class, 'referral']);
$router->get('/waitlist', [WaitlistController::class, 'index']);
$router->post('/waitlist', [WaitlistController::class, 'store']);
$router->post('/waitlist/{id}/cancel', [WaitlistController::class, 'cancel']);
$router->get('/domains', [DomainController::class, 'index']);
$router->post('/domains', [DomainController::class, 'store']);
$router->post('/domains/{id}/verify', [DomainController::class, 'verify']);
$router->post('/domains/{id}/disable', [DomainController::class, 'disable']);
$router->get('/reports', [ReportsController::class, 'index']);
$router->get('/intelligence', [IntelligenceController::class, 'index']);
$router->get('/whatsapp', [WhatsAppController::class, 'inbox']);
$router->get('/whatsapp/conversations/{id}', [WhatsAppController::class, 'show']);
$router->post('/whatsapp/conversations/{id}/reply', [WhatsAppController::class, 'reply']);
$router->post('/whatsapp/conversations/{id}/bot', [WhatsAppController::class, 'bot']);
$router->post('/intelligence/{id}/send', [IntelligenceController::class, 'send']);
$router->get('/units', [UnitController::class, 'index']);
$router->post('/units', [UnitController::class, 'store']);
$router->get('/units/{id}/edit', [UnitController::class, 'edit']);
$router->get('/api/address/cep/{cep}', [UnitController::class, 'lookupPostalCode']);
$router->post('/units/{id}/update', [UnitController::class, 'update']);
$router->post('/units/{id}/deactivate', [UnitController::class, 'deactivate']);
$router->get('/clinical', [MedicalRecordController::class, 'index']);
$router->get('/clinical/patients/{id}', [MedicalRecordController::class, 'show']);
$router->post('/clinical/patients/{id}/records', [MedicalRecordController::class, 'store']);
$router->get('/billing', [BillingController::class, 'index']);
$router->post('/billing/solicitar-exclusao', [BillingSupportController::class, 'requestDeletion']);
$router->post('/billing/solicitar-nota-fiscal', [BillingSupportController::class, 'requestInvoice']);
$router->post('/billing/pix', [PixController::class, 'create']);
$router->get('/billing/pix/{public}', [PixController::class, 'show']);
$router->get('/billing/plans', [BillingController::class, 'plans']);
$router->get('/billing/modulos', [ModuleController::class, 'tenantCatalog']);
$router->post('/billing/modulos/{id}/solicitar', [ModuleController::class, 'requestModule']);
$router->post('/billing/modulos/solicitacoes/{id}/contratar', [ModuleController::class, 'checkout']);
$router->post('/billing/modulos/adicionais/{id}/cancelar', [ModuleController::class, 'cancelAddon']);
$router->get('/checkout/{plan}', [BillingController::class, 'checkout']);
$router->post('/checkout/{plan}', [BillingController::class, 'createCheckout']);
$router->get('/customers/{id}/privacy', [PrivacyController::class, 'show']);
$router->post('/customers/privacy/consent', [PrivacyController::class, 'consent']);
$router->get('/customers/{id}/privacy/export', [PrivacyController::class, 'export']);
$router->get('/onboarding', [OnboardingController::class, 'show']);
$router->post('/onboarding', [OnboardingController::class, 'save']);
$router->get('/settings/branding', [BrandController::class, 'index']);
$router->post('/settings/branding', [BrandController::class, 'update']);
$router->get('/settings/unit', [UnitController::class, 'primaryEdit']);
$router->post('/settings/unit', [UnitController::class, 'primaryUpdate']);

// Quadras, centros esportivos e reservas
$router->get('/sports', [SportsController::class, 'index']);
$router->get('/sports/courts', [SportsController::class, 'courts']);
$router->get('/sports/courts/create', [SportsController::class, 'createCourt']);
$router->post('/sports/courts', [SportsController::class, 'storeCourt']);
$router->get('/sports/courts/{id}/edit', [SportsController::class, 'editCourt']);
$router->post('/sports/courts/{id}/update', [SportsController::class, 'updateCourt']);
$router->post('/sports/courts/{id}/hours', [SportsController::class, 'saveHours']);
$router->post('/sports/courts/{id}/prices', [SportsController::class, 'addPrice']);
$router->post('/sports/prices/{id}/delete', [SportsController::class, 'deletePrice']);
$router->post('/sports/blocks', [SportsController::class, 'addBlock']);
$router->post('/sports/blocks/{id}/cancel', [SportsController::class, 'cancelBlock']);
$router->get('/sports/settings', [SportsController::class, 'settings']);
$router->post('/sports/settings', [SportsController::class, 'saveSettings']);
$router->post('/sports/modalities', [SportsController::class, 'addModality']);
$router->get('/sports/reservations', [SportsReservationsController::class, 'index']);
$router->post('/sports/reservations', [SportsReservationsController::class, 'store']);
$router->post('/sports/reservations/{id}/update', [SportsReservationsController::class, 'update']);
$router->post('/sports/reservations/{id}/reschedule', [SportsReservationsController::class, 'reschedule']);
$router->get('/sports/agenda', [ArenaOperationsController::class, 'agenda']);
$router->get('/sports/memberships', [ArenaOperationsController::class, 'memberships']);
$router->post('/sports/memberships', [ArenaOperationsController::class, 'storeMembership']);
$router->post('/sports/memberships/{id}/generate', [ArenaOperationsController::class, 'generateMembershipNow']);
$router->post('/sports/memberships/{id}/status', [ArenaOperationsController::class, 'membershipStatus']);
$router->get('/sports/games', [ArenaOperationsController::class, 'games']);
$router->post('/sports/games', [ArenaOperationsController::class, 'storeGame']);
$router->get('/sports/waitlist', [ArenaOperationsController::class, 'waitlist']);
$router->post('/sports/waitlist/{id}/status', [ArenaOperationsController::class, 'waitlistStatus']);
$router->get('/sports/commands', [ArenaOperationsController::class, 'commands']);
$router->post('/sports/commands', [ArenaOperationsController::class, 'openCommand']);
$router->post('/sports/commands/{id}/items', [ArenaOperationsController::class, 'addCommandItem']);
$router->post('/sports/commands/{id}/close', [ArenaOperationsController::class, 'closeCommand']);
$router->get('/sports/reports', [ArenaOperationsController::class, 'reports']);
$router->get('/sports/classes', [ArenaOperationsController::class, 'classes']);
$router->post('/sports/classes', [ArenaOperationsController::class, 'storeClass']);
$router->get('/sports/tournaments', [ArenaOperationsController::class, 'tournaments']);
$router->post('/sports/tournaments', [ArenaOperationsController::class, 'storeTournament']);
$router->get('/sports/arena-settings', [ArenaOperationsController::class, 'settings']);
$router->post('/sports/arena-settings', [ArenaOperationsController::class, 'saveSettings']);

// Integrações bancárias são um módulo independente da Arena.
$router->get('/settings/banking', [BankingController::class, 'index']);
$router->post('/settings/banking/connect', [BankingController::class, 'connect']);
$router->post('/settings/banking/connection/{id}/disconnect', [BankingController::class, 'disconnect']);

// Suporte e acesso assistido
$router->get('/support', [SupportController::class, 'index']);
$router->post('/support', [SupportController::class, 'store']);
$router->get('/support/{id}', [SupportController::class, 'show']);
$router->post('/support/{id}/message', [SupportController::class, 'message']);
$router->get('/support/attachments/{id}', [SupportController::class, 'attachment']);
$router->post('/support/{id}/remote-access', [SupportController::class, 'remoteAccess']);
$router->post('/support/{id}/start-access', [SupportController::class, 'startAccess']);
$router->post('/support/{id}/status', [SupportController::class, 'status']);
$router->post('/support/{id}/assign', [SupportController::class, 'assign']);
$router->post('/master/solicitacoes-financeiras/{id}/aprovar-exclusao', [BillingSupportController::class, 'approveDeletion']);
$router->post('/master/solicitacoes-financeiras/{id}/enviar-nota', [BillingSupportController::class, 'uploadInvoice']);
$router->post('/support/end-access', [SupportController::class, 'endAccess']);

// Master SaaS
$router->get('/master', [MasterCommandController::class, 'index']);
$router->get('/master/busca', [MasterCommandController::class, 'search']);
$router->get('/master/tenants', [MasterController::class, 'tenants']);
$router->get('/master/tenants/create', [MasterController::class, 'createTenant']);
$router->post('/master/tenants/store', [MasterController::class, 'storeTenant']);
$router->post('/master/tenants/update', [MasterController::class, 'updateTenant']);
$router->post('/master/tenants/{id}/isencao', [SubscriptionExemptionController::class, 'grant']);
$router->get('/master/tenants/{id}/isencao', [SubscriptionExemptionController::class, 'form']);
$router->post('/master/tenants/{id}/isencao/revogar', [SubscriptionExemptionController::class, 'revoke']);
$router->get('/master/tenants/{id}', [MasterController::class, 'tenantDetail']);
$router->get('/master/plans', [MasterController::class, 'plans']);
$router->get('/master/homologacao', [OperationsCenterController::class, 'index']);
$router->post('/master/homologacao/executar', [OperationsCenterController::class, 'homologate']);
$router->post('/master/homologacao/propostas/{id}', [OperationsCenterController::class, 'proposal']);
$router->post('/master/homologacao/backups/{id}/verificar', [OperationsCenterController::class, 'verifyBackup']);
$router->get('/master/incidentes', [IncidentController::class, 'index']);
$router->post('/master/incidentes/configuracoes', [IncidentController::class, 'settings']);
$router->post('/master/incidentes/{id}', [IncidentController::class, 'update']);
$router->post('/comercial/oportunidades/{id}/privacidade', [CommercialLeadController::class, 'privacy']);
$router->get('/comercial/oportunidades/{id}/exportar', [CommercialLeadController::class, 'export']);
$router->get('/master/comercial', [CommercialTeamController::class, 'masterIndex']);
$router->post('/master/comercial/propostas', [CommercialTeamController::class, 'masterProposal']);
$router->get('/master/plans/create', [MasterController::class, 'createPlan']);
$router->post('/master/plans/store', [MasterController::class, 'storePlan']);
$router->get('/master/plans/{id}/edit', [MasterController::class, 'editPlan']);
$router->post('/master/plans/{id}/update', [MasterController::class, 'updatePlan']);
$router->post('/master/plans/trial-default', [MasterController::class, 'updateTrialDefault']);
$router->post('/master/plans/{id}/automation', [MasterController::class, 'savePlanAutomation']);
$router->get('/master/users', [MasterController::class, 'users']);
$router->post('/master/users/store', [MasterController::class, 'storePlatformUser']);
$router->get('/master/users/{id}/edit', [MasterController::class, 'editUser']);
$router->post('/master/users/{id}/update', [MasterController::class, 'updateUser']);
$router->post('/master/users/{id}/comercial', [MasterController::class, 'saveCommercialProfile']);
$router->post('/master/users/{id}/comercial-suporte', [MasterController::class, 'saveCommercialSupport']);
$router->post('/master/users/{id}/block', [MasterController::class, 'blockUser']);
$router->post('/master/users/{id}/unblock', [MasterController::class, 'unblockUser']);
$router->get('/master/blocked', [MasterController::class, 'blocked']);
$router->get('/master/login-audit', [MasterController::class, 'loginAudit']);
$router->get('/master/payments', [MasterController::class, 'payments']);
$router->get('/master/support', [SupportController::class, 'index']);
$router->get('/master/integrations', [IntegrationController::class, 'index']);
$router->get('/master/whatsapp-chatbot', [WhatsAppController::class, 'master']);
$router->post('/master/whatsapp-chatbot', [WhatsAppController::class, 'save']);
$router->post('/master/whatsapp-chatbot/test', [WhatsAppController::class, 'test']);
$router->post('/master/integrations', [IntegrationController::class, 'save']);
$router->post('/master/integrations/automation/disparar', [IntegrationController::class, 'dispatchAutomation']);
$router->get('/master/system-health', [MasterController::class, 'systemHealth']);
$router->post('/master/mercadopago/pix', [MercadoPagoController::class, 'savePixSettings']);
$router->get('/master/backups', [BackupController::class, 'index']);
$router->post('/master/backups', [BackupController::class, 'create']);
$router->post('/master/backups/{id}/testar-restauracao', [BackupController::class, 'restoreTest']);
$router->get('/master/imports', [DataImportController::class, 'index']);
$router->post('/master/imports', [DataImportController::class, 'upload']);
$router->get('/master/blog', [BlogController::class, 'master']);
$router->get('/master/blog/novo', [BlogController::class, 'create']);
$router->post('/master/blog', [BlogController::class, 'save']);
$router->get('/master/blog/{id}/editar', [BlogController::class, 'edit']);
$router->post('/master/blog/{id}', [BlogController::class, 'save']);
$router->post('/master/blog/{id}/excluir', [BlogController::class, 'delete']);
$router->get('/master/email-marketing', [LeadMarketingController::class, 'index']);
$router->post('/master/email-marketing/smtp', [LeadMarketingController::class, 'saveSmtp']);
$router->post('/master/email-marketing/smtp/testar', [LeadMarketingController::class, 'testSmtp']);
$router->post('/master/email-marketing/contatos', [LeadMarketingController::class, 'addLead']);
$router->post('/master/email-marketing/lista', [LeadMarketingController::class, 'addList']);
$router->post('/master/email-marketing/importar', [LeadMarketingController::class, 'importCsv']);
$router->get('/master/email-marketing/exportar', [LeadMarketingController::class, 'exportCsv']);
$router->post('/master/email-marketing/contatos/{id}', [LeadMarketingController::class, 'updateLead']);
$router->post('/master/email-marketing/enviar', [LeadMarketingController::class, 'send']);
$router->get('/master/backups/{id}/download', [BackupController::class, 'download']);
$router->get('/master/analytics', [MasterController::class, 'analytics']);
$router->get('/master/errors', [MasterController::class, 'errors']);
$router->get('/master/automation-logs', [MasterController::class, 'automationLogs']);
$router->get('/master/modulos', [ModuleController::class, 'masterCatalog']);
$router->post('/master/modulos', [ModuleController::class, 'saveModule']);
$router->get('/master/solicitacoes-modulos', [ModuleController::class, 'requests']);
$router->post('/master/solicitacoes-modulos/{id}/aprovar', [ModuleController::class, 'approve']);
$router->post('/master/solicitacoes-modulos/{id}/recusar', [ModuleController::class, 'reject']);
$router->get('/master/financeiro', [PlatformFinanceController::class, 'index']);
$router->post('/master/financeiro/lancamentos', [PlatformFinanceController::class, 'store']);
$router->post('/master/financeiro/lancamentos/{id}/pagar', [PlatformFinanceController::class, 'markPaid']);
$router->post('/master/financeiro/lancamentos/{id}/cancelar', [PlatformFinanceController::class, 'cancel']);
$router->post('/master/financeiro/categorias', [PlatformFinanceController::class, 'category']);
$router->get('/master/documentos-legais', [LegalController::class, 'masterIndex']);
$router->post('/master/documentos-legais/configuracoes', [LegalController::class, 'saveSettings']);
$router->post('/master/documentos-legais/nova-versao', [LegalController::class, 'newVersion']);
$router->get('/master/documentos-legais/{id}/editar', [LegalController::class, 'edit']);
$router->post('/master/documentos-legais/{id}/atualizar', [LegalController::class, 'update']);
$router->post('/master/documentos-legais/{id}/publicar', [LegalController::class, 'publish']);
$router->get('/master/mercadopago', [MercadoPagoController::class, 'index']);
$router->post('/master/mercadopago', [MercadoPagoController::class, 'save']);
$router->post('/master/mercadopago/validate', [MercadoPagoController::class, 'validateSandbox']);
$router->post('/master/mercadopago/testar-conexao', [MercadoPagoController::class, 'testConnection']);
$router->get('/master/banking-integrations', [MasterBankingController::class, 'index']);

// Inteligência/API interna
$router->post('/api/behavior/recalculate', [ApiController::class, 'recalculateBehavior']);
$router->get('/api/behavior/opportunities', [ApiController::class, 'opportunities']);

// Página pública de cada estabelecimento/profissional
$router->get('/arena/reserva/{token}', [PublicSportsController::class, 'manage']);
$router->post('/arena/reserva/{token}/cancel', [PublicSportsController::class, 'cancel']);
$router->get('/arena/reserva/{token}/availability', [PublicSportsController::class, 'reservationAvailability']);
$router->post('/arena/reserva/{token}/reschedule', [PublicSportsController::class, 'reschedule']);
$router->get('/arena/{slug}/availability', [PublicSportsController::class, 'availability']);
$router->post('/arena/{slug}/reserve', [PublicSportsController::class, 'book']);
$router->post('/arena/{slug}/waitlist', [PublicArenaExtrasController::class, 'waitlist']);
$router->get('/arena/{slug}/quadra/{court}', [PublicArenaExtrasController::class, 'court']);
$router->get('/arena/{slug}', [PublicSportsController::class, 'show']);
$router->get('/jogo/{token}', [PublicArenaExtrasController::class, 'game']);
$router->post('/jogo/{token}/participar', [PublicArenaExtrasController::class, 'joinGame']);
$router->get('/a/{slug}', [PublicEntryController::class, 'show']);
$router->get('/a/{slug}/availability', [PublicBookingController::class, 'availability']);
$router->post('/a/{slug}/book', [PublicBookingController::class, 'book']);
$router->post('/a/{slug}/waitlist', [PublicBookingController::class, 'joinWaitlist']);
$router->get('/a/{slug}/p/{professional}', [PublicBookingController::class, 'professional']);
$router->get('/booking/{token}', [PublicBookingController::class, 'manage']);
$router->post('/booking/{token}/confirm', [PublicBookingController::class, 'confirm']);
$router->post('/booking/{token}/cancel', [PublicBookingController::class, 'cancel']);
$router->get('/booking/{token}/reschedule', [PublicBookingController::class, 'reschedule']);
$router->post('/booking/{token}/reschedule', [PublicBookingController::class, 'saveReschedule']);
$router->get('/{slug}', [PublicBookingController::class, 'show']); // compatibilidade legada

// Webhooks
$router->get('/webhooks/whatsapp', [WebhookController::class, 'whatsappVerify']);
$router->post('/webhooks/whatsapp', [WebhookController::class, 'whatsapp']);
$router->post('/webhooks/payment/{provider}/{tenant}', [WebhookController::class, 'payment']);
$router->post('/webhooks/arena/mercadopago/{tenant}', [TenantPaymentWebhookController::class, 'mercadoPago']);
$router->post('/webhooks/mercadopago', [WebhookController::class, 'mercadoPago']);

$legalPath=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';
$legalExempt=['/aceite-legal','/termos','/privacidade','/logout','/security','/security/password','/security/2fa/start','/security/2fa/confirm'];
if(Auth::user()&&!Auth::isPlatformStaff()&&!Auth::isSupportImpersonating()&&!in_array($legalPath,$legalExempt,true)){
    try{if(LegalDocumentService::pendingForUser((int)Auth::user()['id'])){header('Location: /aceite-legal');exit;}}catch(\Throwable){}
}
if($_SERVER['REQUEST_METHOD']==='POST'&&Auth::user()&&!empty(Auth::user()['tenant_id'])&&(preg_match('#^/checkout/\d+$#',$legalPath)||$legalPath==='/billing/pix')){\App\Services\SubscriptionExemptionService::requireChargeable((int)Auth::user()['tenant_id']);}

$router->dispatch($_SERVER['REQUEST_METHOD'], $_SERVER['REQUEST_URI']);
