from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies=[
        ("billing","0005_payment_integrations"),
        ("tenants","0004_normalize_index_names"),
    ]
    operations=[
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending","Pendente"),("paid","Pago"),("failed","Falhou"),
                    ("expired","Expirado"),("refunded","Estornado"),
                    ("partially_refunded","Estorno parcial"),("cancelled","Cancelado"),
                ],
                db_index=True,default="pending",max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tenantpaymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("created","Criado"),("pending","Pendente"),("paid","Pago"),
                    ("failed","Falhou"),("cancelled","Cancelado"),("expired","Expirado"),
                    ("refunded","Estornado"),("partially_refunded","Estorno parcial"),
                ],
                db_index=True,default="created",max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenantpaymenttransaction",
            name="paid_at",
            field=models.DateTimeField(blank=True,null=True),
        ),
        migrations.AddField(
            model_name="tenantpaymenttransaction",
            name="reconciled_at",
            field=models.DateTimeField(blank=True,null=True),
        ),
        migrations.AddConstraint(
            model_name="tenantpaymenttransaction",
            constraint=models.UniqueConstraint(
                fields=("connection","external_reference"),
                name="uq_tenant_payment_external",
            ),
        ),
        migrations.CreateModel(
            name="TenantPaymentWebhookEvent",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("provider",models.CharField(max_length=40)),
                ("event_id",models.CharField(max_length=190)),
                ("payload_hash",models.CharField(max_length=64)),
                ("signature_valid",models.BooleanField(default=False)),
                ("status",models.CharField(
                    choices=[
                        ("received","Recebido"),("processed","Processado"),
                        ("ignored","Ignorado"),("failed","Falhou"),
                    ],
                    db_index=True,default="received",max_length=16,
                )),
                ("error_code",models.CharField(blank=True,max_length=80)),
                ("received_at",models.DateTimeField(auto_now_add=True)),
                ("processed_at",models.DateTimeField(blank=True,null=True)),
                ("connection",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="webhook_events",
                    to="billing.tenantpaymentconnection",
                )),
                ("tenant",models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="payment_webhook_events",
                    to="tenants.tenant",
                )),
            ],
        ),
        migrations.AddConstraint(
            model_name="tenantpaymentwebhookevent",
            constraint=models.UniqueConstraint(
                fields=("connection","event_id"),
                name="uq_tenant_webhook_event",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantpaymentwebhookevent",
            index=models.Index(fields=["tenant","received_at"],name="billing_tenant_webhook_idx"),
        ),
    ]
