from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies=[
        ("billing","0007_plan_legacy_catalog_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations=[
        migrations.AddField(
            model_name="subscription",name="base_contracted_price",
            field=models.DecimalField(blank=True,decimal_places=2,max_digits=10,null=True),
        ),
        migrations.AddField(
            model_name="subscription",name="addon_contracted_price",
            field=models.DecimalField(decimal_places=2,default=0,max_digits=10),
        ),
        migrations.AddField(
            model_name="checkoutsession",name="base_total",
            field=models.DecimalField(blank=True,decimal_places=2,max_digits=10,null=True),
        ),
        migrations.AddField(
            model_name="checkoutsession",name="addon_total",
            field=models.DecimalField(decimal_places=2,default=0,max_digits=10),
        ),
        migrations.AddField(
            model_name="tenantmoduleaddon",name="billing_mode",
            field=models.CharField(
                choices=[("separate","Separada"),("merged_subscription","Incorporada à assinatura")],
                default="separate",max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionExemption",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("exemption_type",models.CharField(choices=[("temporary","Temporária"),("permanent","Permanente")],default="temporary",max_length=12)),
                ("starts_at",models.DateTimeField()),
                ("ends_at",models.DateTimeField(blank=True,null=True)),
                ("reason",models.CharField(max_length=500)),
                ("status",models.CharField(choices=[("active","Ativa"),("revoked","Revogada"),("expired","Expirada")],db_index=True,default="active",max_length=12)),
                ("revoked_at",models.DateTimeField(blank=True,null=True)),
                ("granted_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="subscription_exemptions_granted",to=settings.AUTH_USER_MODEL)),
                ("revoked_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="subscription_exemptions_revoked",to=settings.AUTH_USER_MODEL)),
                ("subscription",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="exemptions",to="billing.subscription")),
                ("tenant",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="subscription_exemptions",to="tenants.tenant")),
            ],
        ),
        migrations.AddIndex(
            model_name="subscriptionexemption",
            index=models.Index(fields=["tenant","status","starts_at","ends_at"],name="billing_exempt_tenant_idx"),
        ),
        migrations.CreateModel(
            name="SubscriptionModuleAdjustment",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("public_id",models.CharField(max_length=32,unique=True)),
                ("action",models.CharField(choices=[("add","Adicionar"),("remove","Remover"),("consolidate","Consolidar")],max_length=16)),
                ("previous_amount",models.DecimalField(decimal_places=2,max_digits=10)),
                ("new_amount",models.DecimalField(decimal_places=2,max_digits=10)),
                ("addon_monthly_price",models.DecimalField(decimal_places=2,default=0,max_digits=10)),
                ("provider",models.CharField(blank=True,max_length=40)),
                ("provider_reference",models.CharField(blank=True,max_length=190)),
                ("idempotency_key",models.CharField(max_length=64,unique=True)),
                ("status",models.CharField(choices=[("pending","Pendente"),("applied","Aplicado"),("failed","Falhou"),("sync_required","Sincronização necessária")],db_index=True,default="pending",max_length=16)),
                ("error_code",models.CharField(blank=True,max_length=120)),
                ("applied_at",models.DateTimeField(blank=True,null=True)),
                ("created_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="subscription_module_adjustments_created",to=settings.AUTH_USER_MODEL)),
                ("module_addon",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="adjustments",to="billing.tenantmoduleaddon")),
                ("module_request",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="adjustments",to="billing.modulerequest")),
                ("subscription",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="module_adjustments",to="billing.subscription")),
                ("tenant",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="subscription_module_adjustments",to="tenants.tenant")),
            ],
        ),
        migrations.AddIndex(model_name="subscriptionmoduleadjustment",index=models.Index(fields=["tenant","status","created_at"],name="billing_modadj_tenant_idx")),
        migrations.AddIndex(model_name="subscriptionmoduleadjustment",index=models.Index(fields=["subscription","created_at"],name="billing_modadj_sub_idx")),
        migrations.CreateModel(
            name="SubscriptionNoticeLog",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("notice_key",models.CharField(max_length=40)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("subscription",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="notice_logs",to="billing.subscription")),
                ("tenant",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="subscription_notices",to="tenants.tenant")),
            ],
        ),
        migrations.AddConstraint(model_name="subscriptionnoticelog",constraint=models.UniqueConstraint(fields=("subscription","notice_key"),name="uq_subscription_notice")),
        migrations.AddIndex(model_name="subscriptionnoticelog",index=models.Index(fields=["tenant","created_at"],name="billing_notice_tenant_idx")),
        migrations.CreateModel(
            name="ProviderEvent",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("provider",models.CharField(max_length=40)),
                ("event_id",models.CharField(max_length=190)),
                ("event_type",models.CharField(blank=True,max_length=100)),
                ("payload_hash",models.CharField(max_length=64)),
                ("status",models.CharField(db_index=True,default="received",max_length=16)),
                ("error_message",models.CharField(blank=True,max_length=500)),
                ("received_at",models.DateTimeField()),
                ("processed_at",models.DateTimeField(blank=True,null=True)),
            ],
        ),
        migrations.AddConstraint(model_name="providerevent",constraint=models.UniqueConstraint(fields=("provider","event_id"),name="uq_provider_event")),
        migrations.AddIndex(model_name="providerevent",index=models.Index(fields=["provider","status","received_at"],name="billing_provider_evt_idx")),
        migrations.CreateModel(
            name="PixCharge",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("public_id",models.CharField(max_length=32,unique=True)),
                ("provider_order_id",models.CharField(max_length=190)),
                ("provider_payment_id",models.CharField(blank=True,max_length=190)),
                ("amount",models.DecimalField(decimal_places=2,max_digits=10)),
                ("qr_code",models.TextField(blank=True)),
                ("qr_code_base64",models.TextField(blank=True)),
                ("ticket_url",models.URLField(blank=True,max_length=1000)),
                ("status",models.CharField(db_index=True,default="pending",max_length=16)),
                ("expires_at",models.DateTimeField()),
                ("paid_at",models.DateTimeField(blank=True,null=True)),
                ("checkout_session",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="pix_charges",to="billing.checkoutsession")),
                ("payment",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="pix_charges",to="billing.payment")),
                ("subscription",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="pix_charges",to="billing.subscription")),
                ("tenant",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="pix_charges",to="tenants.tenant")),
            ],
        ),
    ]
