# Generated by Django 5.2.17 on 2026-10-04 16:16

from django.db import migrations, models


def backfill_payment_method(apps, schema_editor):
    Subscription = apps.get_model("billing", "Subscription")
    PixCharge = apps.get_model("billing", "PixCharge")
    alias = schema_editor.connection.alias
    subscriptions = Subscription.objects.using(alias)
    subscriptions.exclude(provider_subscription_id="").update(payment_method="card")
    pix_ids = PixCharge.objects.using(alias).values_list("subscription_id", flat=True)
    subscriptions.filter(payment_method="", pk__in=pix_ids).update(payment_method="pix")


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_fiscal_document_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Cartão · assinatura automática'), ('pix', 'Pix · pagamento por ciclo')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_payment_method, migrations.RunPython.noop),
    ]
