# Generated by Django 5.2.17 on 2026-10-05 13:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_subscription_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='annual_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal("99.99"))], verbose_name='Desconto anual (%)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='promotion_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim da oferta para novas contratações'),
        ),
        migrations.AddField(
            model_name='plan',
            name='promotion_months',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Meses da promoção após o teste'),
        ),
        migrations.AddField(
            model_name='plan',
            name='promotion_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço mensal promocional'),
        ),
        migrations.AddField(
            model_name='plan',
            name='promotion_starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início da oferta'),
        ),
        migrations.AddField(
            model_name='plan',
            name='quarterly_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal("99.99"))], verbose_name='Desconto trimestral (%)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='semiannual_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal("99.99"))], verbose_name='Desconto semestral (%)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='commercial_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscription',
            name='promotion_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='regular_base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='SubscriptionPriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Novo valor base por ciclo')),
                ('effective_at', models.DateTimeField(verbose_name='Renovação a partir de')),
                ('reason', models.CharField(choices=[('catalog', 'Reajuste de catálogo'), ('promotion', 'Fim da promoção')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Agendado'), ('applied', 'Aplicado'), ('cancelled', 'Cancelado')], default='pending', max_length=16)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='billing.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
