# Generated by Django 5.2.18 on 2026-10-06 13:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_plan_annual_discount_plan_promotion_ends_at_and_more'),
        ('tenants', '0011_tenant_archive_snapshot_tenant_archived_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFiscalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False, verbose_name='Emitir automaticamente após pagamento')),
                ('auto_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Pagamentos a partir de')),
                ('environment', models.CharField(choices=[('homologation', 'Homologação — sem validade fiscal'), ('production', 'Produção')], default='homologation', max_length=16, verbose_name='Ambiente')),
                ('document', models.CharField(max_length=14, verbose_name='CNPJ do MEI')),
                ('legal_name', models.CharField(max_length=150, verbose_name='Razão social')),
                ('municipality_code', models.CharField(max_length=7, verbose_name='Código IBGE do município emissor')),
                ('service_code', models.CharField(max_length=6, verbose_name='Código nacional de tributação do serviço')),
                ('municipal_service_code', models.CharField(blank=True, max_length=3, verbose_name='Código municipal do serviço (opcional)')),
                ('service_description', models.CharField(max_length=1000, verbose_name='Descrição do serviço')),
                ('series', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(49999)], verbose_name='Série exclusiva da DPS nesta aplicação')),
                ('certificate_encrypted', models.TextField(blank=True)),
                ('certificate_password_encrypted', models.TextField(blank=True)),
                ('certificate_expires_at', models.DateTimeField(blank=True, null=True)),
                ('tax_confirmed', models.BooleanField(default=False, verbose_name='Confirmei com a contabilidade o enquadramento MEI, código e competência do serviço')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fiscaldocumentrequest',
            name='access_key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fiscaldocumentrequest',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fiscaldocumentrequest',
            name='dps_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fiscaldocumentrequest',
            name='emission_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fiscaldocumentrequest',
            name='emission_state',
            field=models.CharField(choices=[('manual', 'Manual'), ('queued', 'Na fila'), ('processing', 'Em processamento'), ('waiting', 'Aguardando consulta'), ('error', 'Precisa de atenção'), ('authorized', 'Autorizada')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='fiscaldocumentrequest',
            name='fiscal_environment',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='fiscaldocumentrequest',
            name='issuer_document',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='fiscaldocumentrequest',
            name='last_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='fiscaldocumentrequest',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscaldocumentrequest',
            name='processing_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscaldocumentrequest',
            name='signed_dps_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TenantFiscalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.CharField(max_length=14, verbose_name='CPF/CNPJ')),
                ('legal_name', models.CharField(max_length=150, verbose_name='Nome / razão social')),
                ('email', models.EmailField(max_length=80, verbose_name='E-mail fiscal')),
                ('municipality_code', models.CharField(max_length=7, verbose_name='Código IBGE do município')),
                ('postal_code', models.CharField(max_length=8, verbose_name='CEP')),
                ('street', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('number', models.CharField(max_length=60, verbose_name='Número')),
                ('district', models.CharField(max_length=60, verbose_name='Bairro')),
                ('complement', models.CharField(blank=True, max_length=156, verbose_name='Complemento')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_profile', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
