# Generated by Django 5.2.18 on 2026-10-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_platformfiscalsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscaldocumentrequest',
            name='notice_queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
