<?php
declare(strict_types=1);
use App\Core\Database;use App\Services\BehaviorEngine;
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}require dirname(__DIR__).'/app/Core/bootstrap.php';
const SPORTS_DEMO_SLUG='arena-applanner-demonstracao';const SPORTS_DEMO_EMAIL='gestor.arena.demo@applanner.local';
$pdo=Database::connection();$action=strtolower((string)($argv[1]??'status'));
function exists(PDO $p,string $t):bool{try{$p->query('SELECT 1 FROM `'.$t.'` LIMIT 1');return true;}catch(Throwable){return false;}}
function cols(PDO $p,string $t):array{static $c=[];return$c[$t]??=$p->query('SHOW COLUMNS FROM `'.$t.'`')->fetchAll(PDO::FETCH_COLUMN);}
function add(PDO $p,string $t,array $d):int{$d=array_intersect_key($d,array_flip(cols($p,$t)));$f=array_keys($d);$p->prepare('INSERT INTO `'.$t.'` (`'.implode('`,`',$f).'`) VALUES (:'.implode(',:',$f).')')->execute($d);return(int)$p->lastInsertId();}
function demo(PDO $p):array|false{$q=$p->prepare('SELECT * FROM tenants WHERE slug=:s');$q->execute(['s'=>SPORTS_DEMO_SLUG]);return$q->fetch();}
function role(PDO $p,string $s):int{$q=$p->prepare('SELECT id FROM roles WHERE slug=:s');$q->execute(['s'=>$s]);return(int)$q->fetchColumn();}
function install(PDO $pdo):array{
 if(demo($pdo))throw new RuntimeException('A Arena ApPlanner demonstração já existe.');foreach(['sports_courts','sports_modalities','sports_reservations','behavior_profiles'] as $t)if(!exists($pdo,$t))throw new RuntimeException('Execute as migrações antes: tabela ausente '.$t);$plan=(int)$pdo->query('SELECT id FROM plans WHERE active=1 ORDER BY monthly_price DESC,id DESC LIMIT 1')->fetchColumn();if(!$plan)throw new RuntimeException('Cadastre um plano ativo.');$now=date('Y-m-d H:i:s');$password='Arena!'.random_int(100000,999999).'Aa';$customers=[];$appointmentCustomers=[];$pdo->beginTransaction();try{
  $tenant=add($pdo,'tenants',['name'=>'Arena ApPlanner — Demonstração','slug'=>SPORTS_DEMO_SLUG,'public_slug'=>'arena-applanner-demo','public_short_code'=>'ARENADEMO','email'=>SPORTS_DEMO_EMAIL,'phone'=>'81999990000','category'=>'centro_esportivo','description'=>'Centro esportivo demonstrativo com cinco quadras, reservas, carteira de clientes e inteligência de retorno.','status'=>'active','primary_color'=>'#16a34a','menu_color'=>'#052e16','menu_text_color'=>'#ffffff','background_color'=>'#f0fdf4','text_color'=>'#102a1b','font_family'=>'Inter','font_size'=>15,'public_enabled'=>1,'public_booking_enabled'=>1,'onboarding_step'=>9,'created_at'=>$now,'updated_at'=>$now]);
  $owner=add($pdo,'users',['tenant_id'=>$tenant,'name'=>'Gestor Arena Demo','email'=>SPORTS_DEMO_EMAIL,'password_hash'=>password_hash($password,PASSWORD_DEFAULT),'must_change_password'=>0,'status'=>'active','email_verified_at'=>$now,'created_at'=>$now,'updated_at'=>$now]);$pdo->prepare('INSERT INTO user_roles(user_id,role_id)VALUES(:u,:r)')->execute(['u'=>$owner,'r'=>role($pdo,'owner')]);add($pdo,'subscriptions',['tenant_id'=>$tenant,'plan_id'=>$plan,'billing_cycle'=>'monthly','contracted_price'=>0,'status'=>'active','started_at'=>date('Y-m-d H:i:s',strtotime('-180 days')),'next_billing_at'=>date('Y-m-d H:i:s',strtotime('+1 year')),'created_at'=>$now,'updated_at'=>$now]);
  $unit=add($pdo,'units',['tenant_id'=>$tenant,'name'=>'Complexo Esportivo Principal','address'=>'Avenida Esportiva','address_number'=>'500','district'=>'Centro','city'=>'Carpina','state'=>'PE','postal_code'=>'55810000','phone'=>'8136210000','whatsapp'=>'81999990000','email'=>'contato.arena@applanner.local','amenities'=>json_encode(['Estacionamento','Vestiários','Chuveiros','Lanchonete','Wi-Fi','Iluminação noturna'],JSON_UNESCAPED_UNICODE),'payment_methods'=>json_encode(['Pix','Crédito','Débito','Dinheiro'],JSON_UNESCAPED_UNICODE),'is_primary'=>1,'active'=>1,'created_at'=>$now,'updated_at'=>$now]);
  $module=(int)$pdo->query("SELECT id FROM modules WHERE slug='sports_courts'")->fetchColumn();$pdo->prepare('INSERT INTO tenant_modules(tenant_id,module_id,enabled)VALUES(:t,:m,1) ON DUPLICATE KEY UPDATE enabled=1')->execute(['t'=>$tenant,'m'=>$module]);
  add($pdo,'sports_settings',['tenant_id'=>$tenant,'public_enabled'=>1,'default_slot_minutes'=>30,'minimum_notice_minutes'=>60,'maximum_days_ahead'=>90,'cancellation_notice_minutes'=>720,'require_deposit'=>1,'deposit_type'=>'percent','deposit_value'=>30,'pix_key'=>'81999990000','pix_holder'=>'Arena ApPlanner Demonstração','booking_terms'=>'Cancelamento gratuito com 12 horas de antecedência.','updated_at'=>$now]);
  $beach=add($pdo,'sports_modalities',['tenant_id'=>$tenant,'name'=>'Beach Tennis e Vôlei de Praia','description'=>'Modalidades praticadas nas quadras de areia.','active'=>1,'sort_order'=>1,'created_at'=>$now,'updated_at'=>$now]);$soccer=add($pdo,'sports_modalities',['tenant_id'=>$tenant,'name'=>'Futebol Society','description'=>'Futebol em gramado sintético.','active'=>1,'sort_order'=>2,'created_at'=>$now,'updated_at'=>$now]);
  $courtSpec=[['Areia 1 — Sol', $beach,'Areia premium',8,90],['Areia 2 — Mar',$beach,'Areia premium',8,90],['Areia 3 — Praia',$beach,'Areia premium',8,80],['Society 1 — Arena',$soccer,'Grama sintética',14,140],['Society 2 — Champions',$soccer,'Grama sintética',14,160]];$courts=[];$professionals=[];$services=[];
  foreach($courtSpec as $i=>[$name,$mod,$surface,$capacity,$price]){$court=add($pdo,'sports_courts',['tenant_id'=>$tenant,'unit_id'=>$unit,'name'=>$name,'slug'=>'quadra-'.($i+1),'description'=>'Quadra demonstrativa equipada e disponível para reserva online.','surface'=>$surface,'indoor'=>0,'lighting'=>1,'capacity'=>$capacity,'minimum_minutes'=>60,'maximum_minutes'=>180,'interval_minutes'=>10,'active'=>1,'sort_order'=>$i+1,'created_at'=>$now,'updated_at'=>$now]);$courts[]=$court;$pdo->prepare('INSERT INTO sports_court_modalities(court_id,modality_id)VALUES(:c,:m)')->execute(['c'=>$court,'m'=>$mod]);for($d=1;$d<=7;$d++)add($pdo,'sports_court_hours',['tenant_id'=>$tenant,'court_id'=>$court,'weekday'=>$d,'start_time'=>$d>=6?'07:00:00':'06:00:00','end_time'=>$d>=6?'23:00:00':'22:30:00','active'=>1,'created_at'=>$now,'updated_at'=>$now]);add($pdo,'sports_price_rules',['tenant_id'=>$tenant,'court_id'=>$court,'modality_id'=>$mod,'price_per_hour'=>$price,'priority'=>1,'active'=>1,'created_at'=>$now,'updated_at'=>$now]);$service=add($pdo,'services',['tenant_id'=>$tenant,'name'=>'Locação '.$name,'description'=>'Reserva de quadra esportiva.','duration_minutes'=>60,'price'=>$price,'active'=>1,'created_at'=>$now,'updated_at'=>$now]);$services[]=$service;$professional=add($pdo,'professionals',['tenant_id'=>$tenant,'unit_id'=>$unit,'name'=>$name,'public_slug'=>'locacao-quadra-'.($i+1),'email'=>'quadra'.($i+1).'@applanner.local','phone'=>'81988880'.str_pad((string)$i,3,'0',STR_PAD_LEFT),'specialty'=>'Espaço esportivo','active'=>1,'created_at'=>$now,'updated_at'=>$now]);$professionals[]=$professional;$pdo->prepare('INSERT INTO professional_services(professional_id,service_id)VALUES(:p,:s)')->execute(['p'=>$professional,'s'=>$service]);}
  $first=['Amanda','André','Beatriz','Bruno','Camila','Carlos','Daniel','Débora','Eduardo','Fernanda','Felipe','Gabriela','Gustavo','Helena','Igor','Isabela','João','Juliana','Larissa','Leandro','Lívia','Lucas','Mariana','Marcelo','Natália','Paulo','Priscila','Rafael','Raquel','Renata','Ricardo','Rodrigo','Sabrina','Samuel','Talita','Thiago','Vanessa','Vinícius','Vitória','Wesley','Alice','Caio','Elisa','Fábio','Márcia','Pedro','Bianca','Diego'];$last=['Alves','Barbosa','Costa','Dantas','Ferreira','Gomes','Lima','Martins'];$revenue=0;$completed=0;
  foreach($first as $i=>$fn){$cid=add($pdo,'customers',['tenant_id'=>$tenant,'name'=>$fn.' '.$last[$i%count($last)],'phone'=>'8197'.str_pad((string)($i+1),7,'0',STR_PAD_LEFT),'email'=>'arena.cliente'.str_pad((string)($i+1),2,'0',STR_PAD_LEFT).'@applanner.local','birth_date'=>(new DateTimeImmutable('today'))->modify('-'.(20+$i%35).' years')->modify('-'.($i*5).' days')->format('Y-m-d'),'consent_marketing'=>$i%6?1:0,'status'=>'active','created_at'=>date('Y-m-d H:i:s',strtotime('-1 year')),'updated_at'=>$now]);$customers[]=$cid;$appointmentCustomers[]=$cid;$visits=3+($i%5);$courtIndex=$i%5;
   for($v=$visits;$v>=1;$v--){$start=(new DateTimeImmutable('today'))->modify('-'.(10+$v*(14+$i%4*7)).' days')->setTime(18+($i%4),0);$total=$courtSpec[$courtIndex][4];add($pdo,'sports_reservations',['public_id'=>bin2hex(random_bytes(16)),'tenant_id'=>$tenant,'court_id'=>$courts[$courtIndex],'modality_id'=>$courtSpec[$courtIndex][1],'customer_id'=>$cid,'customer_name'=>$fn.' '.$last[$i%8],'customer_phone'=>'8197'.str_pad((string)($i+1),7,'0',STR_PAD_LEFT),'customer_email'=>'arena.cliente'.str_pad((string)($i+1),2,'0',STR_PAD_LEFT).'@applanner.local','starts_at'=>$start->format('Y-m-d H:i:s'),'ends_at'=>$start->modify('+60 minutes')->format('Y-m-d H:i:s'),'duration_minutes'=>60,'price_per_hour'=>$total,'total_amount'=>$total,'deposit_amount'=>round($total*.3,2),'status'=>'completed','payment_method'=>'pix','payment_status'=>'paid','manage_token_hash'=>hash('sha256',bin2hex(random_bytes(32))),'source'=>'public','confirmed_at'=>$start->modify('-2 days')->format('Y-m-d H:i:s'),'created_at'=>$start->modify('-3 days')->format('Y-m-d H:i:s'),'updated_at'=>$start->format('Y-m-d H:i:s')]);add($pdo,'appointments',['tenant_id'=>$tenant,'customer_id'=>$cid,'professional_id'=>$professionals[$courtIndex],'service_id'=>$services[$courtIndex],'service_price_snapshot'=>$total,'starts_at'=>$start->format('Y-m-d H:i:s'),'ends_at'=>$start->modify('+60 minutes')->format('Y-m-d H:i:s'),'status'=>'completed','source'=>'public','notes'=>'Locação esportiva realizada — base de inteligência.','created_by'=>$owner,'created_at'=>$start->modify('-3 days')->format('Y-m-d H:i:s'),'updated_at'=>$start->format('Y-m-d H:i:s')]);$revenue+=$total;$completed++;}
  }
  foreach(array_slice($customers,0,18) as $i=>$cid){$c=$i%5;$start=(new DateTimeImmutable('tomorrow'))->modify('+'.intdiv($i,3).' days')->setTime(18+($i%3),0);add($pdo,'sports_reservations',['public_id'=>bin2hex(random_bytes(16)),'tenant_id'=>$tenant,'court_id'=>$courts[$c],'modality_id'=>$courtSpec[$c][1],'customer_id'=>$cid,'customer_name'=>$first[$i].' '.$last[$i%8],'customer_phone'=>'8197'.str_pad((string)($i+1),7,'0',STR_PAD_LEFT),'starts_at'=>$start->format('Y-m-d H:i:s'),'ends_at'=>$start->modify('+60 minutes')->format('Y-m-d H:i:s'),'duration_minutes'=>60,'price_per_hour'=>$courtSpec[$c][4],'total_amount'=>$courtSpec[$c][4],'deposit_amount'=>round($courtSpec[$c][4]*.3,2),'status'=>$i%4?'confirmed':'pending_payment','payment_method'=>'pix','payment_status'=>$i%4?'paid':'pending','manage_token_hash'=>hash('sha256',bin2hex(random_bytes(32))),'source'=>'public','confirmed_at'=>$i%4?$now:null,'created_at'=>$now,'updated_at'=>$now]);}
  $pdo->commit();foreach($appointmentCustomers as $cid)(new BehaviorEngine())->recalculateCustomer($tenant,$cid);return['tenant'=>$tenant,'password'=>$password,'customers'=>count($customers),'completed'=>$completed,'future'=>18,'revenue'=>$revenue];
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
}
try{if($action==='install'){$r=install($pdo);echo "ARENA DEMONSTRAÇÃO CRIADA\nID: {$r['tenant']}\nLogin: ".SPORTS_DEMO_EMAIL."\nSenha: {$r['password']}\nPágina: /arena/arena-applanner-demo\nClientes: {$r['customers']}\nReservas realizadas: {$r['completed']}\nReservas futuras: {$r['future']}\nReceita histórica: R$ ".number_format($r['revenue'],2,',','.')."\n";}elseif($action==='status'){if($d=demo($pdo))echo 'INSTALADA | tenant='.$d['id'].' | /arena/arena-applanner-demo'.PHP_EOL;else echo 'NÃO INSTALADA'.PHP_EOL;}else throw new RuntimeException('Use install ou status.');}catch(Throwable $e){fwrite(STDERR,'ERRO: '.$e->getMessage().PHP_EOL);exit(1);}
