<?php
declare(strict_types=1);if(PHP_SAPI!=='cli'){http_response_code(404);exit;}$root=dirname(__DIR__);$payload=$root.'/patches/applanner-experience-v1/payload';$dry=in_array('--dry-run',$argv,true);
function failExperience(string $m):never{fwrite(STDERR,"[FALHA] {$m}\n");exit(1);}function runExperience(string $file,array $args=[]):array{$cmd=escapeshellarg(PHP_BINARY).' '.escapeshellarg($file);foreach($args as $a)$cmd.=' '.escapeshellarg($a);exec($cmd.' 2>&1',$o,$c);return[$c,implode("\n",$o)];}
function copyExperience(string $src,string $dst,array &$copied):void{$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($src,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::SELF_FIRST);foreach($it as $f){$rel=substr($f->getPathname(),strlen($src)+1);$to=$dst.'/'.$rel;if($f->isDir()){if(!is_dir($to)&&!mkdir($to,0750,true)&&!is_dir($to))failExperience('Não foi possível criar '.$to);continue;}if(!is_dir(dirname($to))&&!mkdir(dirname($to),0750,true)&&!is_dir(dirname($to)))failExperience('Pasta indisponível: '.dirname($to));if(!copy($f->getPathname(),$to))failExperience('Falha ao copiar '.$rel);$copied[]=$rel;}}
if(!is_dir($payload))failExperience('Payload não encontrado. Extraia o patch na raiz do public_html.');[$pc,$po]=runExperience($root.'/tools/preflight-experience-v1.php');echo $po."\n";if($pc!==0)exit($pc);if($dry){echo "[OK] Dry-run: nenhuma alteração realizada.\n";exit;}
require $root.'/app/Core/bootstrap.php';try{$db=(new \App\Services\BackupService())->create('experience-v1');echo '[OK] Backup do banco: '.($db['name']??$db['path']??'criado')."\n";}catch(Throwable $e){failExperience('Backup obrigatório falhou: '.$e->getMessage());}
$manifest=json_decode((string)file_get_contents(dirname($payload).'/manifest.json'),true);if(!is_array($manifest)||empty($manifest['files']))failExperience('Manifesto inválido.');$stamp=date('Ymd-His');$backup=$root.'/storage/update-backups/experience-v1-'.$stamp.'/files';foreach($manifest['files'] as $rel){$src=$root.'/'.$rel;if(!is_file($src))continue;$dst=$backup.'/'.$rel;if(!is_dir(dirname($dst)))mkdir(dirname($dst),0750,true);if(!copy($src,$dst))failExperience('Backup de código falhou: '.$rel);}file_put_contents(dirname($backup).'/MANIFEST.json',json_encode($manifest,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX);
$copied=[];copyExperience($payload,$root,$copied);foreach($copied as $rel)if(str_ends_with($rel,'.php')){exec(escapeshellarg(PHP_BINARY).' -l '.escapeshellarg($root.'/'.$rel).' 2>&1',$lint,$code);if($code!==0)failExperience('Lint falhou em '.$rel.': '.implode(' ',$lint));$lint=[];}
\App\Core\Migrator::run(\App\Core\Database::connection(),$root.'/database/migrations');[$tc,$to]=runExperience($root.'/tests/experience_v1_static.php');echo $to."\n";if($tc!==0)failExperience('Teste do patch falhou.');[$cc,$co]=runExperience($root.'/tools/install-experience-crons.php',['--apply']);echo $co."\n";if($cc!==0)echo "[AVISO] Cadastre os crons pelo cPanel usando cron/run.php.\n";file_put_contents(dirname($backup).'/INSTALLED_AT.txt',date(DATE_ATOM)."\n",LOCK_EX);echo "\n[OK] EXPERIENCE V1 instalado.\nBackup de código: ".dirname($backup)."\nDiagnóstico: php tools/applanner-cron-health.php\n";
