<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
$root=dirname(__DIR__);$payload=$root.'/patches/applanner-auto-v1/payload';$dry=in_array('--dry-run',$argv,true);
$fail=static function(string $m):never{fwrite(STDERR,"[ERRO] {$m}\n");exit(1);};
$run=static function(string $cmd,?array &$out=null):int{$buffer=[];$code=0;exec($cmd.' 2>&1',$buffer,$code);if($out!==null)$out=$buffer;return $code;};
$copy=static function(string $src,string $dst):void{$dir=dirname($dst);if(!is_dir($dir)&&!mkdir($dir,0755,true)&&!is_dir($dir))throw new RuntimeException('Falha ao criar '.$dir);if(!copy($src,$dst))throw new RuntimeException('Falha ao copiar '.$dst);};
$pre=[];$code=$run(escapeshellarg(PHP_BINARY).' '.escapeshellarg($root.'/tools/preflight-auto-v1.php'),$pre);echo implode("\n",$pre)."\n";if($code!==0)$fail('Preflight falhou.');
if(!is_dir($payload))$fail('Payload Auto V1 não encontrado.');$files=[];$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($payload,FilesystemIterator::SKIP_DOTS));foreach($it as $f){if(!$f->isFile())continue;$rel=str_replace('\\','/',substr($f->getPathname(),strlen($payload)+1));$files[$rel]=$f->getPathname();}ksort($files);
if($dry){echo "\n[OK] DRY RUN: preflight e payload validados; banco e arquivos não foram alterados.\nDRY RUN: OK. Execute sem --dry-run para instalar.\n";exit(0);}
$backupDir=$root.'/storage/update-backups/auto-v1-'.date('Ymd-His');if(!is_dir($backupDir)&&!mkdir($backupDir,0750,true)&&!is_dir($backupDir))$fail('Não foi possível criar backup.');$manifest=['patch'=>'PATCH_APPLANNER_AUTO_V1_COMPLETO','created_at'=>date(DATE_ATOM),'backup_dir'=>$backupDir,'files'=>[]];
try{
 foreach($files as $rel=>$src){$dst=$root.'/'.$rel;$exists=is_file($dst);$manifest['files'][]=['path'=>$rel,'existed'=>$exists,'sha256_before'=>$exists?hash_file('sha256',$dst):null,'sha256_payload'=>hash_file('sha256',$src)];if($exists)$copy($dst,$backupDir.'/files/'.$rel);}file_put_contents($backupDir.'/manifest.json',json_encode($manifest,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));echo "[OK] Backup criado: {$backupDir}\n";
 $migrationRels=['database/migrations/039_modules_merged_subscription.sql','database/migrations/040_applanner_barber_v1.sql','database/migrations/041_applanner_auto_v1.sql'];foreach($migrationRels as $rel){if(!isset($files[$rel]))throw new RuntimeException('Migration ausente: '.$rel);$copy($files[$rel],$root.'/'.$rel);}echo "[OK] Migrations 039/040/041 preparadas\n";
 spl_autoload_register(static function(string $class)use($root):void{$prefix='App\\';if(!str_starts_with($class,$prefix))return;$file=$root.'/app/'.str_replace('\\','/',substr($class,strlen($prefix))).'.php';if(is_file($file))require_once $file;});$pdo=\App\Core\Database::connection();\App\Core\Migrator::run($pdo,$root.'/database/migrations');
 $needed=array_map('basename',$migrationRels);$marks=implode(',',array_fill(0,count($needed),'?'));$st=$pdo->prepare("SELECT migration FROM migrations WHERE migration IN ({$marks})");$st->execute($needed);$applied=$st->fetchAll(PDO::FETCH_COLUMN);foreach($needed as $m)if(!in_array($m,$applied,true))throw new RuntimeException('Migration não registrada: '.$m);
 foreach(['auto_settings','auto_vehicle_profiles','auto_service_bays','auto_bay_hours','auto_jobs','auto_job_inspection_items','auto_job_photos','auto_job_material_usage','auto_job_technical_details','auto_estimates','auto_commands','auto_vehicle_maintenance','auto_delivery_terms','auto_crm_events'] as $table){$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$q->execute([$table]);if(!(int)$q->fetchColumn())throw new RuntimeException('Tabela Auto esperada não foi criada: '.$table);}
 $q=$pdo->query("SELECT COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='product_stock_movements' AND COLUMN_NAME='type'");if(!str_contains((string)$q->fetchColumn(),"'command'"))throw new RuntimeException('Enum de estoque não aceita comandas.');echo "[OK] Migrations aplicadas e schema Auto confirmado\n";
 foreach($files as $rel=>$src){if(str_starts_with($rel,'database/migrations/'))continue;$copy($src,$root.'/'.$rel);}echo "[OK] Arquivos da aplicação atualizados\n";
 foreach($files as $rel=>$_){if(!str_ends_with(strtolower($rel),'.php'))continue;$out=[];$c=$run(escapeshellarg(PHP_BINARY).' -l '.escapeshellarg($root.'/'.$rel),$out);if($c!==0)throw new RuntimeException('Lint falhou em '.$rel.': '.implode(' ',$out));}echo "[OK] Lint pós-instalação aprovado\n";
 foreach(['tests/module_subscription_merge_smoke.php','tests/mercadopago_subscription_update_unit.php','tests/barber_v1_smoke.php','tests/barber_recurring_provider_unit.php','tests/auto_v1_smoke.php'] as $test){$out=[];$c=$run(escapeshellarg(PHP_BINARY).' '.escapeshellarg($root.'/'.$test),$out);echo implode("\n",$out)."\n";if($c!==0)throw new RuntimeException('Teste falhou: '.$test);}
 $updates=$root.'/storage/updates';if(!is_dir($updates)&&!mkdir($updates,0750,true)&&!is_dir($updates))throw new RuntimeException('Não foi possível criar storage/updates.');file_put_contents($updates.'/auto-v1.json',json_encode(['patch'=>'PATCH_APPLANNER_AUTO_V1_COMPLETO','installed_at'=>date(DATE_ATOM),'backup_dir'=>$backupDir,'migrations'=>$needed],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));echo "\nPATCH APPLANNER AUTO V1 COMPLETO INSTALADO.\nBackup: {$backupDir}\n";
}catch(Throwable $e){fwrite(STDERR,"[ERRO] Instalação interrompida: {$e->getMessage()}\nRestaurando arquivos a partir de {$backupDir} ...\n");foreach(array_reverse($manifest['files']) as $entry){$rel=(string)$entry['path'];$dst=$root.'/'.$rel;if($entry['existed']){$src=$backupDir.'/files/'.$rel;if(is_file($src))$copy($src,$dst);}elseif(is_file($dst))@unlink($dst);}fwrite(STDERR,"Arquivos restaurados. Migrations incrementais eventualmente aplicadas são preservadas para não apagar dados.\n");exit(1);}
