<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
$root=dirname(__DIR__);$payload=$root.'/patches/applanner-modulos-assinatura-v1/payload';$dry=in_array('--dry-run',$argv,true);
$fail=static function(string $m):never{fwrite(STDERR,"[ERRO] {$m}\n");exit(1);};
$run=static function(string $cmd,array &$out=null):int{$o=[];$c=0;exec($cmd.' 2>&1',$o,$c);if($out!==null)$out=$o;return $c;};
$copy=static function(string $src,string $dst):void{$dir=dirname($dst);if(!is_dir($dir)&&!mkdir($dir,0755,true)&&!is_dir($dir))throw new RuntimeException('Falha ao criar '.$dir);if(!copy($src,$dst))throw new RuntimeException('Falha ao copiar '.$dst);};
$pre=[];$code=$run(escapeshellarg(PHP_BINARY).' '.escapeshellarg($root.'/tools/preflight-modulos-assinatura-v1.php'),$pre);echo implode("\n",$pre)."\n";if($code!==0)$fail('Preflight falhou.');
$files=[];$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($payload,FilesystemIterator::SKIP_DOTS));foreach($it as $f){if(!$f->isFile())continue;$rel=str_replace('\\','/',substr($f->getPathname(),strlen($payload)+1));$files[$rel]=$f->getPathname();}ksort($files);
if($dry){echo "\n[OK] DRY RUN: payload validado; migration não executada; arquivos não alterados.\nDRY RUN: OK.\n";exit(0);}
$backupDir=$root.'/storage/update-backups/modulos-assinatura-v1-'.date('Ymd-His');if(!is_dir($backupDir)&&!mkdir($backupDir,0750,true)&&!is_dir($backupDir))$fail('Não foi possível criar backup.');$manifest=['patch'=>'PATCH_APPLANNER_MODULOS_NA_ASSINATURA_V1','created_at'=>date(DATE_ATOM),'files'=>[]];
try{
 foreach($files as $rel=>$src){$dst=$root.'/'.$rel;$exists=is_file($dst);$manifest['files'][]=['path'=>$rel,'existed'=>$exists,'sha256_before'=>$exists?hash_file('sha256',$dst):null,'sha256_payload'=>hash_file('sha256',$src)];if($exists)$copy($dst,$backupDir.'/files/'.$rel);}file_put_contents($backupDir.'/manifest.json',json_encode($manifest,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));
 // Fase 1: schema primeiro.
 $migration='database/migrations/039_modules_merged_subscription.sql';$copy($files[$migration],$root.'/'.$migration);echo "[OK] Migration 039 preparada\n";
 spl_autoload_register(static function(string $class)use($root):void{$prefix='App\\';if(!str_starts_with($class,$prefix))return;$f=$root.'/app/'.str_replace('\\','/',substr($class,strlen($prefix))).'.php';if(is_file($f))require_once $f;});$pdo=\App\Core\Database::connection();\App\Core\Migrator::run($pdo,$root.'/database/migrations');$q=$pdo->prepare("SELECT COUNT(*) FROM migrations WHERE migration='039_modules_merged_subscription.sql'");$q->execute();if(!(int)$q->fetchColumn())throw new RuntimeException('Migration 039 não foi registrada.');
 foreach([['subscriptions','base_contracted_price'],['subscriptions','addon_contracted_price'],['tenant_module_addons','billing_mode'],['checkout_sessions','base_total'],['checkout_sessions','addon_total']] as [$table,$column]){$c=$pdo->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:t AND COLUMN_NAME=:c');$c->execute(['t'=>$table,'c'=>$column]);if(!(int)$c->fetchColumn())throw new RuntimeException("Coluna {$table}.{$column} não foi criada.");}$tbl=(int)$pdo->query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='subscription_module_adjustments'")->fetchColumn();if(!$tbl)throw new RuntimeException('Tabela subscription_module_adjustments não foi criada.');echo "[OK] Migration 039 aplicada e schema confirmado\n";
 // Fase 2: código novo somente após schema pronto.
 foreach($files as $rel=>$src){if(str_starts_with($rel,'database/migrations/'))continue;$copy($src,$root.'/'.$rel);}echo "[OK] Arquivos atualizados\n";
 foreach($files as $rel=>$src){if(!str_ends_with(strtolower($rel),'.php'))continue;$o=[];$c=$run(escapeshellarg(PHP_BINARY).' -l '.escapeshellarg($root.'/'.$rel),$o);if($c!==0)throw new RuntimeException('Lint falhou em '.$rel.': '.implode(' ',$o));}echo "[OK] Lint pós-instalação aprovado\n";
 foreach(['tests/module_subscription_merge_smoke.php','tests/mercadopago_subscription_update_unit.php'] as $test){$o=[];$c=$run(escapeshellarg(PHP_BINARY).' '.escapeshellarg($root.'/'.$test),$o);echo implode("\n",$o)."\n";if($c!==0)throw new RuntimeException('Teste falhou: '.$test);}
 $updates=$root.'/storage/updates';if(!is_dir($updates))@mkdir($updates,0750,true);file_put_contents($updates.'/modulos-assinatura-v1.json',json_encode(['patch'=>'PATCH_APPLANNER_MODULOS_NA_ASSINATURA_V1','installed_at'=>date(DATE_ATOM),'backup_dir'=>$backupDir],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));
 echo "\nPATCH MÓDULOS NA ASSINATURA V1 INSTALADO.\nBackup: {$backupDir}\n";
}catch(Throwable $e){fwrite(STDERR,"[ERRO] Instalação interrompida: {$e->getMessage()}\nRestaurando arquivos...\n");foreach(array_reverse($manifest['files']) as $entry){$dst=$root.'/'.$entry['path'];if($entry['existed']){$src=$backupDir.'/files/'.$entry['path'];if(is_file($src))$copy($src,$dst);}elseif(is_file($dst))@unlink($dst);}fwrite(STDERR,"Arquivos restaurados. A migration 039 é aditiva e não é removida automaticamente para evitar perda de histórico.\n");exit(1);}
