<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
$root=dirname(__DIR__);$payload=$root.'/patches/applanner-barber-v1/payload';$errors=[];$warnings=[];
$ok=static function(string $m):void{echo "[OK] {$m}\n";};$warn=static function(string $m)use(&$warnings):void{$warnings[]=$m;echo "[AVISO] {$m}\n";};$err=static function(string $m)use(&$errors):void{$errors[]=$m;echo "[ERRO] {$m}\n";};
if(version_compare(PHP_VERSION,'8.1.0','<'))$err('PHP 8.1+ é obrigatório. Atual: '.PHP_VERSION);else$ok('PHP '.PHP_VERSION);
if(!is_file($root.'/storage/installed.lock'))$err('storage/installed.lock não encontrado; execute na raiz ativa do ApPlanner.');else$ok('Instalação ativa reconhecida');
foreach(['037_applanner_arena_v1.sql','038_applanner_arena_v2_complete.sql'] as $m){if(!is_file($root.'/database/migrations/'.$m))$err('Pré-requisito ausente: '.$m);else$ok('Pré-requisito encontrado: '.$m);}
if(!is_dir($payload))$err('Payload Barber V1 não encontrado.');
$files=[];if(is_dir($payload)){$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($payload,FilesystemIterator::SKIP_DOTS));foreach($it as $f){if(!$f->isFile())continue;$rel=str_replace('\\','/',substr($f->getPathname(),strlen($payload)+1));$files[$rel]=$f->getPathname();}ksort($files);if(count($files)<47)$err('Payload incompleto: '.count($files).' arquivos.');else$ok('Payload íntegro: '.count($files).' arquivos');}
foreach(['database/migrations/039_modules_merged_subscription.sql','database/migrations/040_applanner_barber_v1.sql'] as $rel){$f=$payload.'/'.$rel;if(!is_file($f)){$err('Migration ausente: '.$rel);continue;}$sql=(string)file_get_contents($f);if(preg_match('/\b(DROP\s+(DATABASE|TABLE)|TRUNCATE\s+TABLE)\b/i',$sql))$err('Migration destrutiva detectada: '.$rel);else$ok('Migration incremental/não destrutiva: '.$rel);}
// Nomes de FKs do payload não podem colidir entre si.
$constraints=[];$intended=[];foreach(['039_modules_merged_subscription.sql','040_applanner_barber_v1.sql'] as $name){$sql=(string)@file_get_contents($payload.'/database/migrations/'.$name);if(preg_match_all('/CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+`?([A-Za-z0-9_]+)`?\s*\((.*?)\)\s*ENGINE/is',$sql,$blocks,PREG_SET_ORDER)){foreach($blocks as $b){if(preg_match_all('/\bCONSTRAINT\s+([A-Za-z0-9_]+)/i',$b[2],$cm))foreach($cm[1] as $c){$k=strtolower($c);$constraints[$k][]=$name;$intended[$k]=$b[1];}}}}
foreach($constraints as $n=>$where)if(count($where)>1)$err('Foreign key repetida no payload: '.$n.' em '.implode(', ',$where));if(!$errors)$ok('Foreign keys do payload sem colisão interna');
foreach($files as $rel=>$src){if(!str_ends_with(strtolower($rel),'.php'))continue;$out=[];$code=0;exec(escapeshellarg(PHP_BINARY).' -l '.escapeshellarg($src).' 2>&1',$out,$code);if($code!==0){$err('PHP inválido em '.$rel.': '.implode(' ',$out));break;}}if(!$errors)$ok('Lint PHP do payload aprovado');
$index=(string)@file_get_contents($payload.'/index.php');foreach(['/barber/commands','/barber/queue','/barber/goals','/barber/team/{id}','/memberships/{id}/automatic','/webhooks/payments/mercadopago/{tenant}'] as $route)if(!str_contains($index,$route))$err('Rota Barber obrigatória ausente: '.$route);if(!$errors)$ok('Rotas críticas Barber V1 presentes');
$command=(string)@file_get_contents($payload.'/app/Controllers/BarberOperationsController.php');foreach(['PackageService::consumeForAppointment','CommissionService::tip','product_stock_movements','financial_transactions','LoyaltyService::earn'] as $needle)if(!str_contains($command,$needle))$err('Integração do fechamento ausente: '.$needle);if(!$errors)$ok('Comanda integra pacote, comissão, estoque, financeiro e fidelidade');
$webhook=(string)@file_get_contents($payload.'/app/Controllers/TenantPaymentWebhookController.php');if(!str_contains($webhook,'subscription_authorized_payment')||!str_contains($webhook,'BarberMembershipPaymentService'))$err('Tratamento recorrente do Mercado Pago incompleto.');else$ok('Webhook recorrente diferenciado por tópico');
$cron=(string)@file_get_contents($payload.'/cron/barber.php');if(!str_contains($cron,'BarberRecurringReconciliationService'))$err('Reconciliação recorrente não está no cron Barber.');else$ok('Cron Barber contém reconciliação de mensalidades');
if(getenv('APPLANNER_PREFLIGHT_SKIP_DB')==='1'){$warn('Checagem de banco ignorada por APPLANNER_PREFLIGHT_SKIP_DB=1 (somente validação offline).');}
else try{
 spl_autoload_register(static function(string $class)use($root):void{$prefix='App\\';if(!str_starts_with($class,$prefix))return;$f=$root.'/app/'.str_replace('\\','/',substr($class,strlen($prefix))).'.php';if(is_file($f))require_once $f;});
 $pdo=\App\Core\Database::connection();$db=(string)$pdo->query('SELECT DATABASE()')->fetchColumn();$ok('Banco acessível: '.(string)$pdo->query('SELECT VERSION()')->fetchColumn());if($db==='')$err('Nenhum database ativo.');
 // Arena V2 é pré-requisito da infraestrutura bancária por tenant.
 $applied=$pdo->query("SELECT migration FROM migrations WHERE migration IN ('037_applanner_arena_v1.sql','038_applanner_arena_v2_complete.sql')")->fetchAll(PDO::FETCH_COLUMN);foreach(['037_applanner_arena_v1.sql','038_applanner_arena_v2_complete.sql'] as $m)if(!in_array($m,$applied,true))$err('Pré-requisito ainda não aplicado no banco: '.$m);
 foreach(['tenant_payment_connections','tenant_payment_webhook_events','financial_transactions','customer_memberships','customer_packages','professional_commissions','product_stock_movements'] as $table){$st=$pdo->prepare('SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=? AND TABLE_NAME=?');$st->execute([$db,$table]);if(!$st->fetchColumn())$err('Tabela obrigatória ausente: '.$table);}
 if($intended){$names=array_keys($intended);$ph=implode(',',array_fill(0,count($names),'?'));$st=$pdo->prepare("SELECT CONSTRAINT_NAME,TABLE_NAME FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=? AND LOWER(CONSTRAINT_NAME) IN ($ph)");$st->execute(array_merge([$db],$names));foreach($st->fetchAll(PDO::FETCH_ASSOC) as $row){$n=strtolower((string)$row['CONSTRAINT_NAME']);$actual=(string)$row['TABLE_NAME'];$want=$intended[$n]??'';if($want!==''&&strcasecmp($actual,$want)!==0)$err("Colisão de FK: {$row['CONSTRAINT_NAME']} já pertence a {$actual}; patch espera {$want}.");}if(!$errors)$ok('Sem colisão de foreign keys com o schema atual');}
}catch(Throwable $e){$err('Falha na checagem somente-leitura do banco: '.$e->getMessage());}
if($errors){echo "\nPRE-FLIGHT BARBER V1: FALHOU (".count($errors)." erro(s)). Nenhuma alteração foi feita.\n";exit(1);}echo "\nPRE-FLIGHT BARBER V1: OK".($warnings?' com '.count($warnings).' aviso(s)':'').". Nenhuma alteração foi feita.\n";
