<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
$root=dirname(__DIR__);$payload=$root.'/patches/applanner-auto-v1/payload';$errors=[];$warnings=[];
$ok=static function(string $m):void{echo "[OK] {$m}\n";};$warn=static function(string $m)use(&$warnings):void{$warnings[]=$m;echo "[AVISO] {$m}\n";};$err=static function(string $m)use(&$errors):void{$errors[]=$m;echo "[ERRO] {$m}\n";};
if(version_compare(PHP_VERSION,'8.1.0','<'))$err('PHP 8.1+ é obrigatório. Atual: '.PHP_VERSION);else$ok('PHP '.PHP_VERSION);
if(!is_file($root.'/storage/installed.lock'))$err('storage/installed.lock não encontrado; execute na raiz ativa do ApPlanner.');else$ok('Instalação ativa reconhecida');
foreach(['037_applanner_arena_v1.sql','038_applanner_arena_v2_complete.sql'] as $m){if(!is_file($root.'/database/migrations/'.$m))$err('Pré-requisito ausente: '.$m);else$ok('Pré-requisito encontrado: '.$m);}
if(!is_dir($payload))$err('Payload Auto V1 não encontrado.');
$files=[];if(is_dir($payload)){$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($payload,FilesystemIterator::SKIP_DOTS));foreach($it as $f){if(!$f->isFile())continue;$rel=str_replace('\\','/',substr($f->getPathname(),strlen($payload)+1));$files[$rel]=$f->getPathname();}ksort($files);if(count($files)<70)$err('Payload incompleto: '.count($files).' arquivos.');else$ok('Payload íntegro: '.count($files).' arquivos');}
$migrationNames=['039_modules_merged_subscription.sql','040_applanner_barber_v1.sql','041_applanner_auto_v1.sql'];
foreach($migrationNames as $name){$f=$payload.'/database/migrations/'.$name;if(!is_file($f)){$err('Migration ausente: '.$name);continue;}$sql=(string)file_get_contents($f);if(preg_match('/\b(DROP\s+(DATABASE|TABLE)|TRUNCATE\s+TABLE)\b/i',$sql))$err('Migration destrutiva detectada: '.$name);else$ok('Migration incremental/não destrutiva: '.$name);}
$constraints=[];$intended=[];foreach($migrationNames as $name){$sql=(string)@file_get_contents($payload.'/database/migrations/'.$name);if(preg_match_all('/CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+`?([A-Za-z0-9_]+)`?\s*\((.*?)\)\s*ENGINE/is',$sql,$blocks,PREG_SET_ORDER)){foreach($blocks as $b){if(preg_match_all('/\bCONSTRAINT\s+`?([A-Za-z0-9_]+)`?/i',$b[2],$cm))foreach($cm[1] as $c){$k=strtolower($c);$constraints[$k][]=$name;$intended[$k]=$b[1];}}}}
foreach($constraints as $n=>$where)if(count($where)>1)$err('Foreign key repetida no payload: '.$n.' em '.implode(', ',$where));if(!$errors)$ok('Foreign keys do payload sem colisão interna');
foreach($files as $rel=>$src){if(!str_ends_with(strtolower($rel),'.php'))continue;$out=[];$code=0;exec(escapeshellarg(PHP_BINARY).' -l '.escapeshellarg($src).' 2>&1',$out,$code);if($code!==0){$err('PHP inválido em '.$rel.': '.implode(' ',$out));break;}}if(!$errors)$ok('Lint PHP do payload aprovado');
$index=(string)@file_get_contents($payload.'/index.php');foreach(['/auto','/auto/bays','/auto/bookings/create','/auto/jobs/{id}/checkin','/auto/jobs/{id}/inspection','/auto/jobs/{id}/materials','/auto/jobs/{id}/estimates','/auto/commands/{id}/adjust','/auto/crm','/auto/{slug}','/auto/orcamento/{token}','/auto/entrega/{token}'] as $route)if(!str_contains($index,$route))$err('Rota Auto obrigatória ausente: '.$route);if(!$errors)$ok('Rotas críticas Auto V1 presentes');
$ops=(string)@file_get_contents($payload.'/app/Controllers/AutoOperationsController.php');foreach(['PackageService::consumeForAppointment','LoyaltyService::earn','auto_job_material_usage','product_stock_movements','financial_transactions','auto_delivery_terms'] as $needle)if(!str_contains($ops,$needle))$err('Integração Auto ausente: '.$needle);if(!$errors)$ok('Fechamento Auto integra pacote, estoque, financeiro, fidelidade e entrega');
$pub=(string)@file_get_contents($payload.'/app/Controllers/PublicAutoController.php');if(!str_contains($pub,'GET_LOCK')||!str_contains($pub,'customer_can_reschedule')||!str_contains($pub,'NULL,:s'))$err('Reserva pública Auto não possui as proteções esperadas.');else$ok('Reserva pública Auto: sem profissional + lock + autoatendimento protegido');
$cron=(string)@file_get_contents($payload.'/cron/auto.php');if(!str_contains($cron,'auto_crm_events')||!str_contains($cron,'auto_estimates'))$err('Cron Auto incompleto.');else$ok('Cron Auto contém CRM e expiração de orçamentos');
if(getenv('APPLANNER_PREFLIGHT_SKIP_DB')==='1'){$warn('Checagem de banco ignorada por APPLANNER_PREFLIGHT_SKIP_DB=1 (somente validação offline).');}
else try{
 spl_autoload_register(static function(string $class)use($root):void{$prefix='App\\';if(!str_starts_with($class,$prefix))return;$f=$root.'/app/'.str_replace('\\','/',substr($class,strlen($prefix))).'.php';if(is_file($f))require_once $f;});
 $pdo=\App\Core\Database::connection();$db=(string)$pdo->query('SELECT DATABASE()')->fetchColumn();$ok('Banco acessível: '.(string)$pdo->query('SELECT VERSION()')->fetchColumn());if($db==='')$err('Nenhum database ativo.');
 $applied=$pdo->query("SELECT migration FROM migrations WHERE migration IN ('037_applanner_arena_v1.sql','038_applanner_arena_v2_complete.sql')")->fetchAll(PDO::FETCH_COLUMN);foreach(['037_applanner_arena_v1.sql','038_applanner_arena_v2_complete.sql'] as $m)if(!in_array($m,$applied,true))$err('Pré-requisito ainda não aplicado no banco: '.$m);
 foreach(['appointments','customer_vehicles','customers','services','products','product_stock_movements','professional_commissions','financial_transactions','customer_packages','customer_memberships'] as $table){$st=$pdo->prepare('SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=? AND TABLE_NAME=?');$st->execute([$db,$table]);if(!$st->fetchColumn())$err('Tabela obrigatória ausente: '.$table);}
 if($intended){$names=array_keys($intended);$ph=implode(',',array_fill(0,count($names),'?'));$st=$pdo->prepare("SELECT CONSTRAINT_NAME,TABLE_NAME FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=? AND LOWER(CONSTRAINT_NAME) IN ($ph)");$st->execute(array_merge([$db],$names));foreach($st->fetchAll(PDO::FETCH_ASSOC) as $row){$n=strtolower((string)$row['CONSTRAINT_NAME']);$actual=(string)$row['TABLE_NAME'];$want=$intended[$n]??'';if($want!==''&&strcasecmp($actual,$want)!==0)$err("Colisão de FK: {$row['CONSTRAINT_NAME']} já pertence a {$actual}; patch espera {$want}.");}if(!$errors)$ok('Sem colisão de foreign keys com o schema atual');}
}catch(Throwable $e){$err('Falha na checagem somente-leitura do banco: '.$e->getMessage());}
if($errors){echo "\nPRE-FLIGHT AUTO V1: FALHOU (".count($errors)." erro(s)). Nenhuma alteração foi feita.\n";exit(1);}echo "\nPRE-FLIGHT AUTO V1: OK".($warnings?' com '.count($warnings).' aviso(s)':'').". Nenhuma alteração foi feita.\n";
