<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
$root=dirname(__DIR__);$payload=$root.'/patches/applanner-modulos-assinatura-v1/payload';$errors=0;$ok=static function(string $m):void{echo "[OK] {$m}\n";};$warn=static function(string $m):void{echo "[AVISO] {$m}\n";};$err=static function(string $m)use(&$errors):void{$errors++;echo "[ERRO] {$m}\n";};
if(PHP_VERSION_ID<80100)$err('PHP 8.1+ é obrigatório.');else $ok('PHP '.PHP_VERSION);
foreach(['database/migrations/016_v4_commercial_legal_modules_finance.sql','database/migrations/038_applanner_arena_v2_complete.sql','app/Controllers/ModuleController.php','app/Controllers/BillingController.php','app/Services/MercadoPagoProvider.php'] as $f){if(!is_file($root.'/'.$f))$err('Base esperada não encontrada: '.$f);else $ok('Base encontrada: '.$f);}
$required=['database/migrations/039_modules_merged_subscription.sql','app/Services/SubscriptionModuleService.php','app/Services/MercadoPagoProvider.php','app/Controllers/ModuleController.php','app/Controllers/BillingController.php','app/Controllers/WebhookController.php','app/Services/PlatformMetricsService.php','app/Views/billing/modules.php','app/Views/billing/index.php','app/Views/billing/checkout.php','app/Views/master/module-requests.php','tests/module_subscription_merge_smoke.php','tests/mercadopago_subscription_update_unit.php','tools/consolidar-modulos-assinatura.php','tools/diagnosticar-modulos-assinatura.php'];
foreach($required as $f){if(!is_file($payload.'/'.$f))$err('Payload incompleto: '.$f);}
if($errors===0)$ok('Payload obrigatório presente');
$sql=(string)@file_get_contents($payload.'/database/migrations/039_modules_merged_subscription.sql');if(preg_match('/\b(DROP\s+TABLE|DROP\s+DATABASE|TRUNCATE)\b/i',$sql))$err('Migration 039 contém comando destrutivo.');else $ok('Migration 039 é aditiva');
// Colisão de nomes de foreign key com migrations já existentes.
preg_match_all('/CONSTRAINT\s+`?([A-Za-z0-9_]+)`?\s+FOREIGN\s+KEY/i',$sql,$newFk);$newNames=array_unique($newFk[1]??[]);$oldNames=[];foreach(glob($root.'/database/migrations/*.sql')?:[] as $file){if(basename($file)==='039_modules_merged_subscription.sql')continue;$old=(string)@file_get_contents($file);preg_match_all('/CONSTRAINT\s+`?([A-Za-z0-9_]+)`?\s+FOREIGN\s+KEY/i',$old,$m);foreach($m[1]??[] as $name)$oldNames[$name]=basename($file);}foreach($newNames as $name){if(isset($oldNames[$name]))$err("Foreign key {$name} colide com {$oldNames[$name]}");}if($errors===0)$ok('Sem colisões de foreign keys');
// Lint do payload.
$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($payload,FilesystemIterator::SKIP_DOTS));foreach($it as $f){if(!$f->isFile()||strtolower($f->getExtension())!=='php')continue;$out=[];$code=0;exec(escapeshellarg(PHP_BINARY).' -l '.escapeshellarg($f->getPathname()).' 2>&1',$out,$code);if($code!==0)$err('Lint falhou em '.str_replace($payload.'/','',$f->getPathname()).': '.implode(' ',$out));}if($errors===0)$ok('PHP lint do payload aprovado');
// Checagens somente-leitura no banco. Não carrega bootstrap HTTP nem executa migrations.
try{spl_autoload_register(static function(string $class)use($root):void{$prefix='App\\';if(!str_starts_with($class,$prefix))return;$f=$root.'/app/'.str_replace('\\','/',substr($class,strlen($prefix))).'.php';if(is_file($f))require_once $f;});$pdo=\App\Core\Database::connection();$db=(string)$pdo->query('SELECT DATABASE()')->fetchColumn();$ok('Banco conectado: '.$db);$tables=['subscriptions','module_requests','tenant_module_addons','tenant_modules','modules','checkout_sessions','payment_gateways','migrations'];foreach($tables as $table){$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:t');$q->execute(['t'=>$table]);if(!(int)$q->fetchColumn())$err('Tabela obrigatória ausente: '.$table);}if($errors===0)$ok('Tabelas-base disponíveis');$mig=$pdo->prepare("SELECT COUNT(*) FROM migrations WHERE migration='038_applanner_arena_v2_complete.sql'");$mig->execute();if(!(int)$mig->fetchColumn())$err('Arena V2 (migration 038) não consta como aplicada. Instale/regularize o V2 antes deste patch.');else $ok('Migration 038 confirmada');$legacy=(int)$pdo->query("SELECT COUNT(*) FROM tenant_module_addons WHERE status='active'")->fetchColumn();if($legacy>0)$warn("Há {$legacy} módulo(s) adicional(is) ativo(s). Após a migration eles serão classificados inicialmente como cobrança separada; use o consolidar por tenant somente após revisar.");$pending=(int)$pdo->query("SELECT COUNT(*) FROM module_requests WHERE status IN('approved','awaiting_payment','payment_failed')")->fetchColumn();if($pending>0)$warn("Há {$pending} solicitação(ões) antigas em aprovação/cobrança. O novo fluxo permite incorporá-las sem criar nova recorrência separada.");}catch(Throwable $e){$err('Falha na checagem do banco: '.$e->getMessage());}
if($errors){echo "\nPRE-FLIGHT: FALHOU ({$errors} erro(s)). Nenhuma alteração foi feita.\n";exit(1);}echo "\nPRE-FLIGHT: OK. Nenhuma alteração foi feita.\n";
