<?php
namespace App\Controllers;

use App\Core\{CSRF,Database,RateLimiter,View,Encryption,HttpException};
use App\Services\{AutoTenantService,AutoAvailabilityService,NotificationService};

final class PublicAutoController
{
    private function tenant(string $slug):array|false
    {
        $host=mb_strtolower(preg_replace('/:\d+$/','',(string)($_SERVER['HTTP_HOST']??'')));
        $q=Database::connection()->prepare("SELECT t.*,COALESCE(aus.public_enabled,1) auto_public_enabled FROM tenants t LEFT JOIN tenant_domains d ON d.tenant_id=t.id AND d.status='verified' LEFT JOIN auto_settings aus ON aus.tenant_id=t.id WHERE ((t.public_slug=:s OR t.public_short_code=:s2) OR (:host<>'' AND d.domain=:host2)) AND t.public_booking_enabled=1 AND t.public_enabled=1 AND t.status IN('trial','active') AND t.deleted_at IS NULL LIMIT 1");
        $q->execute(['s'=>$slug,'s2'=>$slug,'host'=>$host,'host2'=>$host]);$t=$q->fetch();return $t&&((int)($t['auto_public_enabled']??1)===1)&&AutoTenantService::isAutoCategory($t['category']??'')?$t:false;
    }

    public function show(string $slug):void
    {
        $t=$this->tenant($slug);if(!$t){$this->notFound();return;}$pdo=Database::connection();$q=$pdo->prepare('SELECT id,name,duration_minutes,price,description FROM services WHERE tenant_id=:t AND active=1 ORDER BY name');$q->execute(['t'=>$t['id']]);$services=$q->fetchAll();$q=$pdo->prepare('SELECT * FROM auto_settings WHERE tenant_id=:t');$q->execute(['t'=>$t['id']]);$settings=$q->fetch()?:[];View::render('public/auto',['title'=>$t['name'].' • Reserva automotiva','tenant'=>$t,'routeSlug'=>$slug,'services'=>$services,'settings'=>$settings,'publicLayout'=>true]);
    }

    public function availability(string $slug):void
    {
        header('Content-Type: application/json; charset=utf-8');$t=$this->tenant($slug);if(!$t){http_response_code(404);echo json_encode(['slots'=>[]]);return;}$service=(int)($_GET['service_id']??0);$date=(string)($_GET['date']??'');if(!$service||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)){http_response_code(422);echo json_encode(['slots'=>[]]);return;}try{$day=new \DateTimeImmutable($date.' 00:00:00');}catch(\Throwable){http_response_code(422);echo json_encode(['slots'=>[]]);return;}$slots=(new AutoAvailabilityService())->slots((int)$t['id'],$service,$day);echo json_encode(['slots'=>$slots],JSON_UNESCAPED_UNICODE);
    }

    public function book(string $slug):void
    {
        CSRF::enforce();$ip=$_SERVER['REMOTE_ADDR']??'unknown';if(!RateLimiter::hit('public-auto-book|'.$ip,10,3600))HttpException::abort(429,'Muitas tentativas.');$tenant=$this->tenant($slug);if(!$tenant)$this->notFound();$t=(int)$tenant['id'];
        $name=trim((string)($_POST['name']??''));$phone=preg_replace('/\D/','',(string)($_POST['phone']??''));$email=mb_strtolower(trim((string)($_POST['email']??'')));$service=(int)($_POST['service_id']??0);$bay=(int)($_POST['bay_id']??0);$plate=mb_strtoupper(preg_replace('/[^A-Z0-9]/i','',(string)($_POST['plate']??'')));$make=trim((string)($_POST['make']??''));$model=trim((string)($_POST['model']??''));$year=(int)($_POST['year']??0)?:null;$color=trim((string)($_POST['color']??''))?:null;
        if(mb_strlen($name)<2||strlen($phone)<10||($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))||!$service||!$bay||mb_strlen($model)<2||($plate!==''&&!preg_match('/^[A-Z0-9]{7}$/',$plate)))HttpException::abort(422,'Revise os dados do agendamento e do veículo.');try{$start=new \DateTimeImmutable((string)($_POST['starts_at']??''));}catch(\Throwable){HttpException::abort(422,'Escolha um horário disponível.');}
        $engine=new AutoAvailabilityService();$sv=$engine->service($t,$service);if(!$sv)HttpException::abort(422,'Serviço indisponível.');$end=$start->modify('+'.(int)$sv['duration_minutes'].' minutes');$pdo=Database::connection();$bq=$pdo->prepare("SELECT b.buffer_minutes FROM auto_service_bays b WHERE b.id=:b AND b.tenant_id=:t AND b.active=1 AND (NOT EXISTS(SELECT 1 FROM auto_bay_services x WHERE x.bay_id=b.id) OR EXISTS(SELECT 1 FROM auto_bay_services x WHERE x.bay_id=b.id AND x.service_id=:s AND x.tenant_id=:t2))");$bq->execute(['b'=>$bay,'t'=>$t,'s'=>$service,'t2'=>$t]);$bb=$bq->fetchColumn();if($bb===false)HttpException::abort(422,'Box indisponível para este serviço.');$settings=$engine->settings($t);$buffer=max((int)$bb,(int)($settings['default_buffer_minutes']??0));$offered=false;foreach($engine->slots($t,$service,new \DateTimeImmutable($start->format('Y-m-d').' 00:00:00'),$bay) as $slot){if($slot['starts_at']===$start->format('Y-m-d H:i:s')){$offered=true;break;}}if(!$offered)HttpException::abort(409,'Este horário não está disponível.');if(!$engine->bayAvailable($t,$bay,$start,$end,$buffer,null))HttpException::abort(409,'Este horário acabou de ser ocupado.');
        $lock='auto-public:'.$t.':'.$bay;$lk=$pdo->prepare('SELECT GET_LOCK(:n,5)');$lk->execute(['n'=>$lock]);if((int)$lk->fetchColumn()!==1)HttpException::abort(409,'Agenda ocupada. Tente novamente.');$token=bin2hex(random_bytes(24));
        try{$pdo->beginTransaction();if(!$engine->bayAvailable($t,$bay,$start,$end,$buffer,null))throw new \LogicException('Horário já reservado.');$q=$pdo->prepare('SELECT id FROM customers WHERE tenant_id=:t AND phone=:p LIMIT 1');$q->execute(['t'=>$t,'p'=>$phone]);$customer=(int)$q->fetchColumn();if(!$customer){$pdo->prepare("INSERT INTO customers(tenant_id,name,phone,email,status,created_at,updated_at)VALUES(:t,:n,:p,:e,'active',NOW(),NOW())")->execute(['t'=>$t,'n'=>$name,'p'=>$phone,'e'=>$email?:null]);$customer=(int)$pdo->lastInsertId();}else{$pdo->prepare("UPDATE customers SET name=:n,email=COALESCE(NULLIF(:e,''),email),updated_at=NOW() WHERE id=:c AND tenant_id=:t")->execute(['n'=>$name,'e'=>$email,'c'=>$customer,'t'=>$t]);}
            $vehicle=0;if($plate!==''){$q=$pdo->prepare('SELECT id,customer_id FROM customer_vehicles WHERE tenant_id=:t AND plate=:p LIMIT 1');$q->execute(['t'=>$t,'p'=>$plate]);$existingVehicle=$q->fetch();if($existingVehicle){if((int)$existingVehicle['customer_id']!==$customer)throw new \DomainException('Este veículo já está cadastrado para outro cliente. Entre em contato com o estabelecimento.');$vehicle=(int)$existingVehicle['id'];}}if(!$vehicle){$pdo->prepare('INSERT INTO customer_vehicles(tenant_id,customer_id,plate,make,model,year,color,active,created_at,updated_at)VALUES(:t,:c,:plate,:make,:model,:year,:color,1,NOW(),NOW())')->execute(['t'=>$t,'c'=>$customer,'plate'=>$plate?:null,'make'=>$make?:null,'model'=>$model,'year'=>$year,'color'=>$color]);$vehicle=(int)$pdo->lastInsertId();}else{$pdo->prepare('UPDATE customer_vehicles SET customer_id=:c,make=COALESCE(NULLIF(:make,\'\'),make),model=:model,year=COALESCE(:year,year),color=COALESCE(NULLIF(:color,\'\'),color),updated_at=NOW() WHERE id=:v AND tenant_id=:t')->execute(['c'=>$customer,'make'=>$make,'model'=>$model,'year'=>$year,'color'=>$color??'','v'=>$vehicle,'t'=>$t]);}
            $pdo->prepare("INSERT INTO appointments(tenant_id,customer_id,vehicle_id,professional_id,service_id,service_price_snapshot,starts_at,ends_at,status,source,notes,customer_manage_token_hash,customer_manage_token_encrypted,customer_confirmed_at,created_at,updated_at)VALUES(:t,:c,:v,NULL,:s,:price,:st,:en,'confirmed','public',:notes,:h,:enc,NOW(),NOW(),NOW())")->execute(['t'=>$t,'c'=>$customer,'v'=>$vehicle,'s'=>$service,'price'=>$sv['price'],'st'=>$start->format('Y-m-d H:i:s'),'en'=>$end->format('Y-m-d H:i:s'),'notes'=>trim((string)($_POST['notes']??''))?:null,'h'=>hash('sha256',$token),'enc'=>Encryption::encrypt(['token'=>$token])]);$appointment=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO auto_jobs(tenant_id,appointment_id,vehicle_id,bay_id,status,expected_ready_at,created_at,updated_at)VALUES(:t,:a,:v,:b,'scheduled',:r,NOW(),NOW())")->execute(['t'=>$t,'a'=>$appointment,'v'=>$vehicle,'b'=>$bay,'r'=>$end->format('Y-m-d H:i:s')]);$job=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO auto_job_status_history(tenant_id,job_id,old_status,new_status,notes,created_at)VALUES(:t,:j,NULL,'scheduled','Reserva pública',NOW())")->execute(['t'=>$t,'j'=>$job]);$this->seedSteps($pdo,$t,$job,$service);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();HttpException::abort($e instanceof \LogicException?409:422,$e->getMessage());}finally{$pdo->prepare('SELECT RELEASE_LOCK(:n)')->execute(['n'=>$lock]);}
        NotificationService::tenantOwners($t,'auto.public','Nova reserva automotiva',$name.' reservou '.$model.' para '.$start->format('d/m H:i'),'/auto/jobs/'.$job,'success');header('Location: /auto/booking/'.$token);exit;
    }

    public function manage(string $token):void
    {
        $a=$this->appointment($token);$engine=new AutoAvailabilityService();$settings=$engine->settings((int)$a['tenant_id']);View::render('public/auto-manage',['title'=>'Gerenciar reserva','appointment'=>$a,'settings'=>$settings,'token'=>$token,'publicLayout'=>true,'message'=>$_SESSION['flash_message']??null]);unset($_SESSION['flash_message']);
    }

    public function cancel(string $token):void
    {
        CSRF::enforce();$a=$this->appointment($token);$settings=(new AutoAvailabilityService())->settings((int)$a['tenant_id']);if($a['job_status']!=='scheduled'||!in_array($a['status'],['confirmed','pending_confirmation'],true))HttpException::abort(409,'Esta reserva já entrou em operação e não pode ser cancelada online.');if(empty($settings['customer_can_cancel']))HttpException::abort(403,'Cancelamento online está desativado.');if(new \DateTimeImmutable($a['starts_at'])<(new \DateTimeImmutable())->modify('+'.(int)$settings['cancel_notice_minutes'].' minutes'))HttpException::abort(409,'O prazo para cancelamento online já terminou.');if(in_array($a['status'],['cancelled','completed','no_show'],true))HttpException::abort(409,'Esta reserva não pode ser cancelada.');$pdo=Database::connection();$pdo->beginTransaction();try{$pdo->prepare("UPDATE appointments SET status='cancelled',updated_at=NOW() WHERE id=:a AND tenant_id=:t")->execute(['a'=>$a['id'],'t'=>$a['tenant_id']]);$pdo->prepare("UPDATE auto_jobs SET status='cancelled',updated_at=NOW() WHERE id=:j AND tenant_id=:t")->execute(['j'=>$a['job_id'],'t'=>$a['tenant_id']]);$pdo->prepare("INSERT INTO auto_job_status_history(tenant_id,job_id,old_status,new_status,notes,created_at)VALUES(:t,:j,:o,'cancelled','Cancelamento pelo cliente',NOW())")->execute(['t'=>$a['tenant_id'],'j'=>$a['job_id'],'o'=>$a['job_status']]);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}$_SESSION['flash_message']='Reserva cancelada e horário liberado.';header('Location: /auto/booking/'.$token);exit;
    }

    public function reschedule(string $token):void
    {
        $a=$this->appointment($token);$settings=(new AutoAvailabilityService())->settings((int)$a['tenant_id']);if($a['job_status']!=='scheduled'||!in_array($a['status'],['confirmed','pending_confirmation'],true))HttpException::abort(409,'Esta reserva já entrou em operação e não pode ser remarcada online.');if(empty($settings['customer_can_reschedule']))HttpException::abort(403,'Remarcação online está desativada.');$service=(int)$a['service_id'];$date=(string)($_GET['date']??date('Y-m-d'));try{$day=new \DateTimeImmutable($date.' 00:00:00');}catch(\Throwable){$day=new \DateTimeImmutable('today');}$slots=(new AutoAvailabilityService())->slots((int)$a['tenant_id'],$service,$day,null,(int)$a['job_id']);View::render('public/auto-reschedule',['title'=>'Remarcar reserva','appointment'=>$a,'token'=>$token,'date'=>$day->format('Y-m-d'),'slots'=>$slots,'publicLayout'=>true]);
    }

    public function saveReschedule(string $token):void
    {
        CSRF::enforce();$a=$this->appointment($token);$settings=(new AutoAvailabilityService())->settings((int)$a['tenant_id']);if($a['job_status']!=='scheduled'||!in_array($a['status'],['confirmed','pending_confirmation'],true))HttpException::abort(409,'Esta reserva já entrou em operação e não pode ser remarcada online.');if(empty($settings['customer_can_reschedule']))HttpException::abort(403,'Remarcação online está desativada.');$bay=(int)($_POST['bay_id']??0);try{$start=new \DateTimeImmutable((string)($_POST['starts_at']??''));}catch(\Throwable){HttpException::abort(422,'Escolha um horário disponível.');}$engine=new AutoAvailabilityService();$sv=$engine->service((int)$a['tenant_id'],(int)$a['service_id']);$end=$start->modify('+'.(int)$sv['duration_minutes'].' minutes');$pdo=Database::connection();$bq=$pdo->prepare("SELECT b.buffer_minutes FROM auto_service_bays b WHERE b.id=:b AND b.tenant_id=:t AND b.active=1 AND (NOT EXISTS(SELECT 1 FROM auto_bay_services x WHERE x.bay_id=b.id) OR EXISTS(SELECT 1 FROM auto_bay_services x WHERE x.bay_id=b.id AND x.service_id=:s AND x.tenant_id=:t2))");$bq->execute(['b'=>$bay,'t'=>$a['tenant_id'],'s'=>$a['service_id'],'t2'=>$a['tenant_id']]);$bayBuffer=$bq->fetchColumn();$buffer=max((int)($settings['default_buffer_minutes']??0),(int)($bayBuffer===false?0:$bayBuffer));$offered=false;if($bayBuffer!==false){foreach($engine->slots((int)$a['tenant_id'],(int)$a['service_id'],new \DateTimeImmutable($start->format('Y-m-d').' 00:00:00'),$bay,(int)$a['job_id']) as $slot){if($slot['starts_at']===$start->format('Y-m-d H:i:s')){$offered=true;break;}}}if(!$offered||!$engine->bayAvailable((int)$a['tenant_id'],$bay,$start,$end,$buffer,(int)$a['job_id']))HttpException::abort(409,'Horário indisponível.');$pdo->beginTransaction();try{$pdo->prepare('INSERT INTO appointment_reschedule_history(tenant_id,appointment_id,old_professional_id,new_professional_id,old_starts_at,old_ends_at,new_starts_at,new_ends_at,reason,actor_type,created_at)VALUES(:t,:a,NULL,NULL,:os,:oe,:ns,:ne,\'Remarcação Auto pelo cliente\',\'customer\',NOW())')->execute(['t'=>$a['tenant_id'],'a'=>$a['id'],'os'=>$a['starts_at'],'oe'=>$a['ends_at'],'ns'=>$start->format('Y-m-d H:i:s'),'ne'=>$end->format('Y-m-d H:i:s')]);$pdo->prepare("UPDATE appointments SET starts_at=:s,ends_at=:e,status='confirmed',reminder_24h_sent_at=NULL,reminder_2h_sent_at=NULL,updated_at=NOW() WHERE id=:a AND tenant_id=:t")->execute(['s'=>$start->format('Y-m-d H:i:s'),'e'=>$end->format('Y-m-d H:i:s'),'a'=>$a['id'],'t'=>$a['tenant_id']]);$pdo->prepare("UPDATE auto_jobs SET bay_id=:b,status='scheduled',expected_ready_at=:e,updated_at=NOW() WHERE id=:j AND tenant_id=:t")->execute(['b'=>$bay,'e'=>$end->format('Y-m-d H:i:s'),'j'=>$a['job_id'],'t'=>$a['tenant_id']]);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}$_SESSION['flash_message']='Reserva remarcada com sucesso.';header('Location: /auto/booking/'.$token);exit;
    }

    public function estimate(string $token):void
    {
        $q=Database::connection()->prepare("SELECT e.*,j.id job_id,v.make,v.model,v.plate,c.name customer_name,t.name tenant_name FROM auto_estimates e JOIN auto_jobs j ON j.id=e.job_id JOIN appointments a ON a.id=j.appointment_id JOIN customer_vehicles v ON v.id=j.vehicle_id JOIN customers c ON c.id=a.customer_id JOIN tenants t ON t.id=e.tenant_id WHERE e.public_token_hash=:h LIMIT 1");$q->execute(['h'=>hash('sha256',$token)]);$e=$q->fetch();if(!$e)$this->notFound('Orçamento não encontrado');$i=Database::connection()->prepare('SELECT * FROM auto_estimate_items WHERE estimate_id=:e AND tenant_id=:t ORDER BY id');$i->execute(['e'=>$e['id'],'t'=>$e['tenant_id']]);View::render('public/auto-estimate',['title'=>'Orçamento adicional','estimate'=>$e,'items'=>$i->fetchAll(),'token'=>$token,'publicLayout'=>true]);
    }

    public function respondEstimate(string $token):void
    {
        CSRF::enforce();$decision=(string)($_POST['decision']??'');if(!in_array($decision,['approved','rejected'],true))HttpException::abort(422,'Resposta inválida.');$pdo=Database::connection();$pdo->beginTransaction();try{$q=$pdo->prepare("SELECT * FROM auto_estimates WHERE public_token_hash=:h AND status='sent' AND (expires_at IS NULL OR expires_at>NOW()) FOR UPDATE");$q->execute(['h'=>hash('sha256',$token)]);$e=$q->fetch();if(!$e)throw new \DomainException('Orçamento não está mais disponível.');$pdo->prepare('UPDATE auto_estimates SET status=:s,responded_at=NOW(),customer_note=:n,updated_at=NOW() WHERE id=:id')->execute(['s'=>$decision,'n'=>trim((string)($_POST['customer_note']??''))?:null,'id'=>$e['id']]);$pdo->commit();}catch(\Throwable $x){if($pdo->inTransaction())$pdo->rollBack();if($x instanceof \DomainException)HttpException::abort(409,$x->getMessage());throw $x;}NotificationService::tenantOwners((int)$e['tenant_id'],'auto.estimate.response','Resposta de orçamento','Orçamento #'.$e['id'].' foi '.($decision==='approved'?'aprovado':'recusado').'.','/auto/jobs/'.$e['job_id'],$decision==='approved'?'success':'warning');header('Location: /auto/orcamento/'.$token);exit;
    }

    public function delivery(string $token):void
    {
        $q=Database::connection()->prepare("SELECT d.*,j.status job_status,v.make,v.model,v.plate,t.name tenant_name FROM auto_delivery_terms d JOIN auto_jobs j ON j.id=d.job_id JOIN customer_vehicles v ON v.id=j.vehicle_id JOIN tenants t ON t.id=d.tenant_id WHERE d.public_token_hash=:h LIMIT 1");$q->execute(['h'=>hash('sha256',$token)]);$d=$q->fetch();if(!$d)$this->notFound('Termo não encontrado');View::render('public/auto-delivery',['title'=>'Termo de entrega','delivery'=>$d,'token'=>$token,'publicLayout'=>true]);
    }

    public function acceptDelivery(string $token):void
    {
        CSRF::enforce();$name=trim((string)($_POST['name']??''));if(mb_strlen($name)<2||!isset($_POST['accept']))HttpException::abort(422,'Confirme o aceite e informe seu nome.');$pdo=Database::connection();$q=$pdo->prepare('SELECT * FROM auto_delivery_terms WHERE public_token_hash=:h LIMIT 1');$q->execute(['h'=>hash('sha256',$token)]);$d=$q->fetch();if(!$d)$this->notFound('Termo não encontrado');if(!$d['accepted_at'])$pdo->prepare('UPDATE auto_delivery_terms SET accepted_name=:n,accepted_ip=:ip,accepted_at=NOW() WHERE id=:id')->execute(['n'=>$name,'ip'=>$_SERVER['REMOTE_ADDR']??null,'id'=>$d['id']]);header('Location: /auto/entrega/'.$token);exit;
    }

    private function appointment(string $token):array
    {
        if(!preg_match('/^[a-f0-9]{48}$/',$token))$this->notFound('Link inválido');$q=Database::connection()->prepare("SELECT a.*,j.id job_id,j.status job_status,j.bay_id,b.name bay_name,c.name customer_name,c.phone customer_phone,s.name service_name,v.make,v.model,v.plate,t.name tenant_name,t.public_slug,t.public_short_code FROM appointments a JOIN auto_jobs j ON j.appointment_id=a.id AND j.tenant_id=a.tenant_id JOIN customers c ON c.id=a.customer_id JOIN services s ON s.id=a.service_id JOIN customer_vehicles v ON v.id=j.vehicle_id JOIN tenants t ON t.id=a.tenant_id LEFT JOIN auto_service_bays b ON b.id=j.bay_id WHERE a.customer_manage_token_hash=:h LIMIT 1");$q->execute(['h'=>hash('sha256',$token)]);$a=$q->fetch();if(!$a)$this->notFound('Reserva não encontrada');return $a;
    }
    private function seedSteps(\PDO $pdo,int $t,int $job,int $service):void{$q=$pdo->prepare('SELECT * FROM auto_service_steps WHERE tenant_id=:t AND service_id=:s AND active=1 ORDER BY sort_order,id');$q->execute(['t'=>$t,'s'=>$service]);foreach($q->fetchAll() as $st)$pdo->prepare("INSERT INTO auto_job_steps(tenant_id,job_id,service_step_id,name,status,sort_order)VALUES(:t,:j,:sid,:n,'pending',:o)")->execute(['t'=>$t,'j'=>$job,'sid'=>$st['id'],'n'=>$st['name'],'o'=>$st['sort_order']]);}
    private function notFound(string $title='Página não encontrada'):never{http_response_code(404);View::render('dashboard/404',['title'=>$title,'publicLayout'=>true]);exit;}
}
