<?php
namespace App\Services;
use App\Core\Database;
final class LoyaltyService
{
    public static function earn(int $tenantId,int $customerId,float $amount,string $sourceType,int $sourceId):void
    {
        if(!ModuleService::has('loyalty',$tenantId))return;$pdo=Database::connection();$q=$pdo->prepare('SELECT * FROM tenant_loyalty_settings WHERE tenant_id=:t AND enabled=1');$q->execute(['t'=>$tenantId]);$s=$q->fetch();if(!$s)return;$points=(int)floor($amount*(float)$s['points_per_currency']);if($points<=0)return;
        self::credit($tenantId,$customerId,$points,'earn',$sourceType,$sourceId,'Crédito automático');
    }
    public static function completeReferral(int $tenantId,int $referredCustomerId):void
    {
        if(!ModuleService::has('loyalty',$tenantId))return;$pdo=Database::connection();$q=$pdo->prepare("SELECT lr.*,tls.enabled FROM loyalty_referrals lr JOIN tenant_loyalty_settings tls ON tls.tenant_id=lr.tenant_id WHERE lr.tenant_id=:t AND lr.referred_customer_id=:c AND lr.status='pending' AND tls.enabled=1 LIMIT 1");$q->execute(['t'=>$tenantId,'c'=>$referredCustomerId]);$r=$q->fetch();if(!$r)return;$ownTx=!$pdo->inTransaction();if($ownTx)$pdo->beginTransaction();try{$lock=$pdo->prepare("SELECT status,reward_points,referrer_customer_id FROM loyalty_referrals WHERE id=:id FOR UPDATE");$lock->execute(['id'=>$r['id']]);$x=$lock->fetch();if(!$x||$x['status']!=='pending'){if($ownTx)$pdo->rollBack();return;}$pdo->prepare("UPDATE loyalty_referrals SET status='completed',completed_at=NOW() WHERE id=:id")->execute(['id'=>$r['id']]);$pdo->prepare("INSERT INTO loyalty_accounts(tenant_id,customer_id,points,updated_at)VALUES(:t,:c,:p,NOW()) ON DUPLICATE KEY UPDATE points=points+VALUES(points),updated_at=NOW()")->execute(['t'=>$tenantId,'c'=>$x['referrer_customer_id'],'p'=>$x['reward_points']]);$pdo->prepare("INSERT INTO loyalty_transactions(tenant_id,customer_id,type,points,source_type,source_id,note,created_at)VALUES(:t,:c,'earn',:p,'referral',:sid,'Indicação convertida',NOW())")->execute(['t'=>$tenantId,'c'=>$x['referrer_customer_id'],'p'=>$x['reward_points'],'sid'=>$r['id']]);$ownTx&&$pdo->commit();}catch(\Throwable $e){if($ownTx&&$pdo->inTransaction())$pdo->rollBack();}
    }
    public static function reverse(int $tenantId,int $customerId,string $sourceType,int $sourceId):void
    {
        $pdo=Database::connection();$q=$pdo->prepare("SELECT id,points FROM loyalty_transactions WHERE tenant_id=:t AND customer_id=:c AND source_type=:st AND source_id=:sid AND type='earn' ORDER BY id DESC LIMIT 1");$q->execute(['t'=>$tenantId,'c'=>$customerId,'st'=>$sourceType,'sid'=>$sourceId]);$r=$q->fetch();if(!$r)return;$dup=$pdo->prepare("SELECT 1 FROM loyalty_transactions WHERE tenant_id=:t AND customer_id=:c AND source_type=:st AND source_id=:sid AND type='reverse'");$dup->execute(['t'=>$tenantId,'c'=>$customerId,'st'=>$sourceType,'sid'=>$sourceId]);if($dup->fetchColumn())return;$points=(int)$r['points'];$ownTx=!$pdo->inTransaction();if($ownTx)$pdo->beginTransaction();try{$a=$pdo->prepare('SELECT points FROM loyalty_accounts WHERE tenant_id=:t AND customer_id=:c FOR UPDATE');$a->execute(['t'=>$tenantId,'c'=>$customerId]);$current=(int)($a->fetchColumn()?:0);$new=max(0,$current-$points);$pdo->prepare('UPDATE loyalty_accounts SET points=:p,updated_at=NOW() WHERE tenant_id=:t AND customer_id=:c')->execute(['p'=>$new,'t'=>$tenantId,'c'=>$customerId]);$pdo->prepare("INSERT INTO loyalty_transactions(tenant_id,customer_id,type,points,source_type,source_id,note,created_at)VALUES(:t,:c,'reverse',:p,:st,:sid,'Estorno automático',NOW())")->execute(['t'=>$tenantId,'c'=>$customerId,'p'=>-$points,'st'=>$sourceType,'sid'=>$sourceId]);$ownTx&&$pdo->commit();}catch(\Throwable $e){if($ownTx&&$pdo->inTransaction())$pdo->rollBack();}
    }
    private static function credit(int $t,int $c,int $points,string $type,string $sourceType,int $sourceId,string $note):void{$pdo=Database::connection();$dup=$pdo->prepare('SELECT 1 FROM loyalty_transactions WHERE tenant_id=:t AND customer_id=:c AND source_type=:st AND source_id=:sid AND type=:type');$dup->execute(['t'=>$t,'c'=>$c,'st'=>$sourceType,'sid'=>$sourceId,'type'=>$type]);if($dup->fetchColumn())return;$pdo->prepare("INSERT INTO loyalty_accounts(tenant_id,customer_id,points,updated_at)VALUES(:t,:c,:p,NOW()) ON DUPLICATE KEY UPDATE points=points+VALUES(points),updated_at=NOW()")->execute(['t'=>$t,'c'=>$c,'p'=>$points]);$pdo->prepare('INSERT INTO loyalty_transactions(tenant_id,customer_id,type,points,source_type,source_id,note,created_at)VALUES(:t,:c,:type,:p,:st,:sid,:n,NOW())')->execute(['t'=>$t,'c'=>$c,'type'=>$type,'p'=>$points,'st'=>$sourceType,'sid'=>$sourceId,'n'=>$note]);}
}
