<?php
namespace App\Services;
use App\Contracts\PaymentProviderInterface;
final class MercadoPagoProvider implements PaymentProviderInterface
{
 private string $token;private $transport;
 public function __construct(string $accessToken,?callable $transport=null){if(!preg_match('/^(APP_USR-|TEST-)[A-Za-z0-9_-]{10,}$/',$accessToken))throw new \InvalidArgumentException('Credencial Mercado Pago inválida.');$this->token=$accessToken;$this->transport=$transport;}
 public function createCustomer(array $customer):string{$r=$this->request('POST','/v1/customers',['email'=>$customer['email']??null]);return $this->requiredId($r);}
 public function createSubscription(array $subscription):array{$amount=round((float)($subscription['amount']??0),2);if(!is_finite($amount)||$amount<=0)throw new \InvalidArgumentException('O valor da assinatura deve ser maior que zero e possuir no máximo duas casas decimais.');$body=['reason'=>(string)$subscription['reason'],'external_reference'=>(string)$subscription['external_reference'],'payer_email'=>(string)$subscription['payer_email'],'back_url'=>(string)$subscription['back_url'],'status'=>'pending','auto_recurring'=>['frequency'=>(int)($subscription['frequency']??1),'frequency_type'=>'months','transaction_amount'=>$amount,'currency_id'=>'BRL']];if(!empty($subscription['trial_days']))$body['auto_recurring']['free_trial']=['frequency'=>(int)$subscription['trial_days'],'frequency_type'=>'days'];$r=$this->request('POST','/preapproval',$body,(string)($subscription['idempotency_key']??''));return ['reference'=>$this->requiredId($r),'status'=>(string)($r['status']??'pending'),'init_point'=>$r['init_point']??null];}
 public function createPayment(array $payment):array{throw new \LogicException('Cobrança SaaS recorrente deve usar createSubscription; dados de cartão não passam pelo servidor.');}
 public function createPixOrder(array $payment):array{$amount=number_format(round((float)($payment['amount']??0),2),2,'.','');if((float)$amount<=0)throw new \InvalidArgumentException('Valor Pix inválido.');$hours=max(1,min(720,(int)($payment['expiration_hours']??24)));$body=['type'=>'online','total_amount'=>$amount,'external_reference'=>(string)$payment['external_reference'],'processing_mode'=>'automatic','transactions'=>['payments'=>[['amount'=>$amount,'payment_method'=>['id'=>'pix','type'=>'bank_transfer'],'expiration_time'=>'PT'.$hours.'H']]],'payer'=>['email'=>(string)$payment['payer_email']]];$r=$this->request('POST','/v1/orders',$body,(string)($payment['idempotency_key']??''));$p=$r['transactions']['payments'][0]??[];$method=$p['payment_method']??[];return ['order_id'=>$this->requiredId($r),'payment_id'=>(string)($p['id']??''),'status'=>(string)($p['status']??$r['status']??'action_required'),'ticket_url'=>$method['ticket_url']??null,'qr_code'=>$method['qr_code']??null,'qr_code_base64'=>$method['qr_code_base64']??null];}
 public function getOrder(string $reference):array{return $this->request('GET','/v1/orders/'.rawurlencode($reference));}
 public function createTokenizedCardPayment(array $payment):array
 {
  $amount=round((float)($payment['amount']??0),2);
  if($amount<=0)throw new \InvalidArgumentException('Valor do cartão inválido.');
  $token=trim((string)($payment['token']??''));
  $method=trim((string)($payment['payment_method_id']??''));
  $email=trim((string)($payment['payer_email']??''));
  if($token===''||$method===''||!filter_var($email,FILTER_VALIDATE_EMAIL))throw new \InvalidArgumentException('Dados do cartão incompletos.');
  $installments=max(1,min(24,(int)($payment['installments']??1)));
  $body=['transaction_amount'=>$amount,'token'=>$token,'description'=>(string)($payment['description']??'Reserva ApPlanner Arena'),'installments'=>$installments,'payment_method_id'=>$method,'payer'=>['email'=>$email],'external_reference'=>(string)($payment['external_reference']??'')];
  $issuer=trim((string)($payment['issuer_id']??'')); if($issuer!=='')$body['issuer_id']=$issuer;
  $notification=trim((string)($payment['notification_url']??'')); if($notification!=='')$body['notification_url']=$notification;
  $identification=$payment['identification']??null;
  if(is_array($identification)&&!empty($identification['type'])&&!empty($identification['number']))$body['payer']['identification']=['type'=>(string)$identification['type'],'number'=>(string)$identification['number']];
  $r=$this->request('POST','/v1/payments',$body,(string)($payment['idempotency_key']??''));
  $fee=0.0; foreach(($r['fee_details']??[]) as $detail) if(is_array($detail)&&isset($detail['amount'])&&is_numeric($detail['amount'])) $fee+=(float)$detail['amount'];
  $net=isset($r['transaction_details']['net_received_amount'])&&is_numeric($r['transaction_details']['net_received_amount'])?(float)$r['transaction_details']['net_received_amount']:max(0,$amount-$fee);
  return ['id'=>$this->requiredId($r),'status'=>(string)($r['status']??'pending'),'status_detail'=>(string)($r['status_detail']??''),'payment_method_id'=>(string)($r['payment_method_id']??$method),'payment_type_id'=>(string)($r['payment_type_id']??''),'transaction_amount'=>(float)($r['transaction_amount']??$amount),'fee_amount'=>round($fee,2),'net_received_amount'=>round($net,2)];
 }
 public function getSubscription(string $reference):array{return $this->request('GET','/preapproval/'.rawurlencode($reference));}
 public function getAuthorizedPayment(string $reference):array{return $this->request('GET','/authorized_payments/'.rawurlencode($reference));}
 public function searchPaymentsByExternalReference(string $externalReference,int $days=120):array
 {
  $externalReference=trim($externalReference);if($externalReference==='')return [];$days=max(1,min(364,$days));$end=(new \DateTimeImmutable('now',new \DateTimeZone('UTC')))->format('Y-m-d\TH:i:s.v\Z');$begin=(new \DateTimeImmutable('-'.$days.' days',new \DateTimeZone('UTC')))->format('Y-m-d\TH:i:s.v\Z');$query=http_build_query(['sort'=>'date_created','criteria'=>'desc','external_reference'=>$externalReference,'range'=>'date_created','begin_date'=>$begin,'end_date'=>$end]);$r=$this->request('GET','/v1/payments/search?'.$query);$results=$r['results']??$r;if(!is_array($results))return [];return array_values(array_filter($results,'is_array'));
 }
 public function updateSubscriptionAmount(string $reference,float $amount):array
 {
  $amount=round($amount,2);
  if(!is_finite($amount)||$amount<=0)throw new \InvalidArgumentException('O valor atualizado da assinatura deve ser maior que zero.');
  $r=$this->request('PUT','/preapproval/'.rawurlencode($reference),['auto_recurring'=>['transaction_amount'=>$amount,'currency_id'=>'BRL']]);
  return ['reference'=>(string)($r['id']??$reference),'status'=>(string)($r['status']??''),'amount'=>(float)($r['auto_recurring']['transaction_amount']??$amount),'version'=>(int)($r['version']??0)];
 }
 public function cancelSubscription(string $reference):void{$this->request('PUT','/preapproval/'.rawurlencode($reference),['status'=>'cancelled']);}
 public function getPayment(string $reference):array{return $this->request('GET','/v1/payments/'.rawurlencode($reference));}
 public function handleWebhook(array $headers,string $payload):array{return json_decode($payload,true,512,JSON_THROW_ON_ERROR);}
 public function testConnection():array{return $this->request('GET','/users/me');}
 public static function validWebhookSignature(string $signature,string $requestId,string $dataId,string $secret,?int $now=null):bool{$parts=[];foreach(explode(',',$signature) as $part){[$k,$v]=array_pad(explode('=',trim($part),2),2,'');$parts[$k]=$v;}$ts=(int)($parts['ts']??0);$now??=time();if(!$secret||!$requestId||!$dataId||!$ts||abs($now-(int)floor($ts/($ts>9999999999?1000:1)))>300)return false;$manifest='id:'.strtolower($dataId).';request-id:'.$requestId.';ts:'.$parts['ts'].';';return isset($parts['v1'])&&hash_equals(hash_hmac('sha256',$manifest,$secret),$parts['v1']);}
 private function request(string $method,string $path,array $body=[],string $idempotency=''):array{if($this->transport)return ($this->transport)($method,$path,$body,$idempotency,$this->token);if(!function_exists('curl_init'))throw new \RuntimeException('Extensão cURL obrigatória para Mercado Pago.');$ch=curl_init('https://api.mercadopago.com'.$path);$headers=['Authorization: Bearer '.$this->token,'Content-Type: application/json'];if($idempotency!=='')$headers[]='X-Idempotency-Key: '.$idempotency;curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$headers,CURLOPT_TIMEOUT=>20,CURLOPT_CONNECTTIMEOUT=>5]);if($method!=='GET'){$amountMarker='__APPLANNER_MP_AMOUNT_2_DECIMALS__';$amountLiteral=null;if(isset($body['auto_recurring']['transaction_amount'])){$amountLiteral=number_format(round((float)$body['auto_recurring']['transaction_amount'],2),2,'.','');$body['auto_recurring']['transaction_amount']=$amountMarker;}elseif(isset($body['transaction_amount'])){$amountLiteral=number_format(round((float)$body['transaction_amount'],2),2,'.','');$body['transaction_amount']=$amountMarker;}$oldPrecision=ini_get('serialize_precision');ini_set('serialize_precision','-1');try{$json=json_encode($body,JSON_THROW_ON_ERROR);if($amountLiteral!==null)$json=str_replace(json_encode($amountMarker,JSON_THROW_ON_ERROR),$amountLiteral,$json);}finally{if($oldPrecision!==false)ini_set('serialize_precision',(string)$oldPrecision);}curl_setopt($ch,CURLOPT_POSTFIELDS,$json);}$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$curlError=$raw===false?curl_error($ch):'';curl_close($ch);if($raw===false)throw new \RuntimeException('Mercado Pago indisponível: '.($curlError!==''?$curlError:'falha de conexão').'.');$decoded=json_decode($raw,true);if($status<200||$status>=300){[$message,$cause]=$this->providerError(is_array($decoded)?$decoded:[]);throw new \RuntimeException('Mercado Pago HTTP '.$status.': '.$message.($cause!==''?' ['.$cause.']':''));}if(!is_array($decoded))throw new \RuntimeException('Resposta inválida do Mercado Pago.');return $decoded;}
 private function providerError(array $decoded):array{$message=(string)($decoded['message']??$decoded['error']??'requisição recusada');$cause='';foreach(['errors','cause'] as $field){$item=$decoded[$field][0]??null;if(!is_array($item))continue;$message=(string)($item['message']??$item['description']??$message);$cause=(string)($item['code']??$item['error']??$cause);$details=$item['details']??null;if(is_array($details)&&$details){$detail=json_encode($details,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if(is_string($detail)&&$detail!=='')$message.=' '.$detail;}break;}$clean=static function(string $value,int $limit):string{$value=preg_replace('/[^\pL\pN _.,:;@()\[\]{}\/-]/u',' ',trim($value))??'';$value=preg_replace('/\s+/u',' ',$value)??'';return mb_substr($value,0,$limit);};return [$clean($message?:'requisição recusada',300),$clean($cause,100)];}
 private function requiredId(array $r):string{$id=(string)($r['id']??'');if($id==='')throw new \RuntimeException('Resposta inválida do provider.');return $id;}
}
